### ISSUE TITLE
Interrupt open interpreter model inference without interrupting terminal 

### ISSUE THREAD

**Issue by ngoiyaeric** [KillianLucas/open-interpreter#1005]
### Describe the bug

Sometimes the language model inside open interpreter hallucinates & deviates from what I want it to do. I have to interrupt terminal cmd + c. I have to start the system again this creates additional latency. 

### Reproduce

cmd + c whenever oi is outta pocket 

### Expected behavior

restart system?? I think we can do better

### Open Interpreter version

latest 

### Python version

latest 

### Operating System name and version

mac os

**Comment by Notnaton** [comment]
You can use `%reset` to reset interpreter

**Comment by ngoiyaeric** [comment]
What is %reset? How do you issue this command to the terminal while the terminal is being occupied? Why did you close the ticket and assume issue is resolved?

**Comment by kamil6x** [comment]
FYI: Pressing CTRL-C often kills Open Interpreter and you have to start over. So it's not a good solution.
