### ISSUE TITLE
what is smallest model that know about comp system administration, network admin, etc?

### ISSUE THREAD

**Issue by zinwelzl** [KillianLucas/open-interpreter#1015]
### Describe the solution you'd like

I run ollama locally and need some small model for help with system administration, network administration, etc?

I try few small but are really bad.

**Comment by Notnaton** [comment]
How small do you need it to be?
What hardware do you have?

**Comment by zinwelzl** [comment]
RAM 8 GB

**Comment by jerzydziewierz** [comment]
Try `deepseek-coder` I find it works quite well

There is a 7B, Q4 version that should work well on your ~6GB free VRAM card:
https://ollama.com/library/deepseek-coder:6.7b-instruct-q4_K_S
