### ISSUE TITLE
Error 401: Incorrect API key provided

### ISSUE THREAD

**Issue by evlachos93** [KillianLucas/open-interpreter#1030]
### Describe the bug

I am trying to execute a simple command like "what is the time in Seattle" or "how many folders are in MyDesktop", and I get Error 401. I have followed all the suggest installation steps and have verified via the _echo OPENAI_API_KEY_ command that I am using the correct OpenAI API key. How do I fix this?

### Reproduce

1. Create dedicated conda environment with python==3.11
2. Install open-interpreter using **pip install open-interpreter**
3. Add OPENAI_API_KEY to PATHS from ThisPC->Advanced Properties
4. In anaconda command window, run _interpreter --model gpt-3.5-turbo_
5. Try to ask the interpreter anything

### Expected behavior

I am expecting the interpreter to execute my command.

### Screenshots

![open-interpreter-issue](https://github.com/KillianLucas/open-interpreter/assets/58792226/63828f29-d491-4620-938b-06c56a60fd1c)

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows 11

**Comment by Notnaton** [comment]
Can you wcho the api key in the conda environment?

**Comment by evlachos93** [comment]
I can do that successfully. I actually fixed the issue by editing the configuration file. I am not sure why that fixed it, but it works now.
