### ISSUE TITLE
Migrate from appdirs to platformdirs

### ISSUE THREAD

**Issue by MikeBirdTech** [KillianLucas/open-interpreter#1034]
### Is your feature request related to a problem? Please describe.

Appdirs has been [officially deprecated](https://github.com/ActiveState/appdirs). It is recommended to change to [platformdirs](https://pypi.org/project/platformdirs/). The repo for `platformdirs` can be found here: https://github.com/platformdirs/platformdirs

### Describe the solution you'd like

Appdirs is only used in a couple of files, as can be seen here: https://github.com/search?q=repo:KillianLucas/open-interpreter+appdirs&type=code

Please update to `platformdirs` to ensure we use maintain packages

**Comment by Notnaton** [comment]
> I am currently looking into open-interpreter and would love to help here and there. If OK, I would create a PR right away.

Awesome, this is exactly what these "good first issues" are for.  It's to help new contributors get a foot in on the project and get familiar with the code.

If you need any help you can ping me here or on the Discord 👍
