### ISSUE TITLE
Multi-line Input Support

### ISSUE THREAD

**Issue by Steve235lab** [KillianLucas/open-interpreter#1046]
### Is your feature request related to a problem? Please describe.

OI doesn't support multi-line input from the CLI. It's difficult for user to input code pieces directly from the terminal.

### Describe the solution you'd like

Find a good way to handle multi-line input.

Here are some potential solutions:
* Add some logic when processing user's input, if get line ending like `\n`, search for some specific combo in the line like ` ``` ` , if found then await for more input until get another ` ``` `.
* User write the code into a file and let the OI read the file (this one has been already done).

**Comment by Steve235lab** [comment]
Any good idea? I might try the first solution in the next few days.

**Comment by Notnaton** [comment]
There is a pr draft of future gui using textual, that should handle multi line input.

**Comment by Steve235lab** [comment]
> There is a pr draft of future gui using textual, that should handle multi line input.

Yes, I saw the PR before, it's great and I'll definitely try the GUI app in the future. However it's not exactly the thing I want right here. In my opinion OI is special and powerful largely because it's the only usable CLI Chatbot client out of box, so enhance the CLI user experience is quite important for me. I'll find a good solution later.
