### ISSUE TITLE
Computer API : Will it be open source in the future?

### ISSUE THREAD

**Issue by vaibhavard** [KillianLucas/open-interpreter#1052]
As per my observation , the computer api uses a special api endpoint (https://api.openinterpreter.com/v0/point/) , which returns the coordinates of a described image.
A few Qs regarding the Computer API:

 ● Does the computer api **detect image coordinates through gpt-4-vision**? Or does it use a custom llm?
 
 ● Why to depend on the api ? Why not run the image-coordinate-detection code on the client side only?
 
 ● Is the project **transitioning to a proprietary model / closed source**?
    (Similar to `Open`ai)

**Comment by KillianLucas** [comment]
The project is **not** transitioning to a proprietary model. Will be open-sourcing the point model alongside the release of the [01](https://github.com/KillianLucas/01).

It didn't have great local performance when the [NCU](https://changes.openinterpreter.com/log/the-new-computer-update) update came out in January, so I decided to just host it for free. Now it's been totally revamped for local usage, and will be part of the next OI release. It does not depend on GPT-4V.

**Comment by vaibhavard** [comment]
Oh , now I see the link between 01 and open interpreter.
Excited for the release next week.Looking forward to know if you have optimized this to run on general laptops and pcs.

_Sorry for doubting the open source spirit of this project._

**Comment by vaibhavard** [comment]
Closed as my question is answered.✅
