### ISSUE TITLE
 `go` disabled or not supported.    

### ISSUE THREAD

**Issue by bincooo** [KillianLucas/open-interpreter#1053]
### Describe the bug

 `go` disabled or not supported.    

### Reproduce

.

### Expected behavior

.

### Open Interpreter version

0.2.0

### Python version

Python 3.11.8

### Operating System name and version

MacOS

**Comment by Notnaton** [comment]
Well, yeah. It's not supported by Open-interpreter.

I'll mark this as wontfix and close this issue. 
I don't think we will support go for quite awhile...
