### ISSUE TITLE
Need for Default (GPT-3.5) version

### ISSUE THREAD

**Issue by if1eight0sty** [KillianLucas/open-interpreter#106]
I am using the default 3.5 version of gpt, which seems do not support. Please, make work for the default gpt version.

**Comment by KillianLucas** [comment]
Hi @if1eight0sty! You can run `interpreter --fast` to use it with GPT-3.5. Let me know if that doesn't work!

**Comment by if1eight0sty** [comment]
i did here here what i am getting `You exceeded your current quota, please check your plan and billing details.`

![Screenshot 2023-09-07 151730](https://github.com/KillianLucas/open-interpreter/assets/83457080/f20694e7-1a73-4746-98e9-4726a51ca0a4)

**Comment by sunbinghonter** [comment]
i hava the same error,what can i do?

**Comment by mingmingshiliyu** [comment]
> i hava the same error,what can i do?to

i just bought an abroad bank card binding to my account,all resolved
