### ISSUE TITLE
When refreshing screen it stores each snapshopt to scroll history on the terminal

### ISSUE THREAD

**Issue by Kreijstal** [KillianLucas/open-interpreter#1063]
### Describe the bug

when running anything in the open-interpreter terminal installed from pip in linux, we get a history of EVERY "screen refersh" happened so far, this is annoying for scrolling, let me give you a screenshot

### Reproduce

 instal open interpreter on linux
ask to code something
scroll up

### Expected behavior

when refreshing screen it should overwrite what happened before and not clear screen by scrolling down, if that is not possible, then you can have it work ala vim.

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/2415206/8fb9dc0d-adf0-43a0-8310-e34fb4a5ec4a)

### Open Interpreter version

0.2.0

### Python version

3.10.12

### Operating System name and version

Mint 21.3

**Comment by MikeBirdTech** [comment]
Hi @Kreijstal 
Thanks for raising this. We are currently working on a new terminal interface which will address this issue and many more. Thanks!
