### ISSUE TITLE
use interpreter -l ,get  Attempting to download the Phi-2 language model. This may take a few minutes.

### ISSUE THREAD

**Issue by LMG-arch** [KillianLucas/open-interpreter#1073]
### Describe the bug

use  interpreter --local
get  Attempting to download the Phi-2 language model. This may take a few minutes.

### Reproduce

![1710316233436](https://github.com/KillianLucas/open-interpreter/assets/128892592/742f65fc-33a9-440d-968d-2d332862107b)

### Expected behavior

![1710316233436](https://github.com/KillianLucas/open-interpreter/assets/128892592/cebc62bd-18bb-447e-8906-7b9c624cb0df)

### Screenshots

interpreter --local it is changed?
no  lm studio,
of course.i'm not skilled

### Open Interpreter version

0.2.2

### Python version

3.11.7

### Operating System name and version

win11

**Comment by MikeBirdTech** [comment]
Hi @LMG-arch 
You can use LM Studio by running `interpreter --api_base http://localhost:1234/v1`

We are updating the documentation to reflect this change: https://github.com/KillianLucas/open-interpreter/pull/1074

Sorry for the confusion!
