### ISSUE TITLE
When using LM studio, user is prompted to enter their OpenAI API key when this value isn't needed

### ISSUE THREAD

**Issue by MikeBirdTech** [KillianLucas/open-interpreter#1076]
### Describe the bug

The change in `--local` mode now requires users to launch OI with `interpreter --api_base http://localhost:1234/v1` if they want to use LM Studio. When they run this command, they are prompted to enter their OpenAI API key. Pressing enter without typing any value allows OI to work with LM Studio successfully. However, the user should not be prompted to enter their OpenAI API key when they are using a local model.

### Reproduce

1. Disable `OPENAI_API_KEY` environment variable
2. Run `interpreter --api_base http://localhost:1234/v1`
3. Observe OI asking for OpenAI API key

### Expected behavior

Running `interpreter --api_base http://localhost:1234/v1` should work without prompting user for their OpenAI API key.

### Screenshots

<img width="1246" alt="Screenshot 2024-03-13 at 11 41 50 AM" src="https://github.com/KillianLucas/open-interpreter/assets/63524998/23e4b225-0a75-45e4-b15e-59d35e0cdbb0">

### Open Interpreter version

0.2.2

### Python version

3.11.3

### Operating System name and version

MacOS 14.3

**Comment by lorenzejay** [comment]
I want to take a stab at this

**Comment by MikeBirdTech** [comment]
It's all yours @lorenzejay ! Thanks for stepping up 💪

Let us know if you need a hand with anything

**Comment by lorenzejay** [comment]
So this is my thoughts on this:

if `interpreter.llm.api_base`: 
we can assume this won't need an openAI API, so in validate_llm_settings, we can remove prompting for openai api key

**Comment by lorenzejay** [comment]
expected behavior? @MikeBirdTech 
![open-interpreter](https://github.com/KillianLucas/open-interpreter/assets/63378463/51ce938d-c176-4c14-b65b-5be2b66149cb)

**Comment by lorenzejay** [comment]
even if you do not have a key. 

![open-interpreter-2](https://github.com/KillianLucas/open-interpreter/assets/63378463/4472bbb1-7936-4c20-b3a5-3120f08bea24)
