### ISSUE TITLE
Update Documentation: Remove `--config`

### ISSUE THREAD

**Issue by MikeBirdTech** [KillianLucas/open-interpreter#1080]
### Describe the bug

The 0.2.1 update has moved OI from using a config to a more powerful and robust system using profiles. There are a couple of instances in the docs where this change was missed. Please update the docs so that profiles are referenced instead of config.

### Reproduce

1. Go to the documentation: https://docs.openinterpreter.com/getting-started/introduction
2. Search for 'config'
3. See instances of 'config' - such as https://docs.openinterpreter.com/usage/terminal/arguments#configuration

### Expected behavior

No `--config`, just `--profile`

### Open Interpreter version

0.2.2

### Python version

3.11.3

### Operating System name and version

MacOS 14.3

**Comment by Rishy-09** [comment]
@MikeBirdTech 
Could this issue be assigned to me, please? I'd like to work on it. Thanks!

**Comment by MikeBirdTech** [comment]
All yours @Rishy-09!

Let us know if you need a hand with anything. Thank you for jumping in!

**Comment by Rishy-09** [comment]
I have pull requested the issue as:  Changed --config to --profiles #1082

**Comment by MikeBirdTech** [comment]
Conversation will be moved to the PR. Thanks @Rishy-09
