### ISSUE TITLE
[FEATURE] Using remote inference

### ISSUE THREAD

**Issue by PriNova** [KillianLucas/open-interpreter#109]
Hello Killian,

a feature request to use remote inference through the huggingface.js API will work for users without or low VRAM GPU requirements.
What do you think about?

**Comment by abhinavkulkarni** [comment]
Also, it would be nice to have support for HuggingFace TGI. TGI is probably the most popular framework for LLM serving and it would be good if I could specify a remote TGI server endpoint and run local interpreter locally on my laptop.

**Comment by ericrallen** [comment]
Hey there, @abhinavkulkarni and @PriNova!

Is this functionality available via the current implementation of [LiteLLM](https://github.com/BerriAI/litellm) in Open Interpreter.

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please feel encouraged to reopen if there is more to discuss.
