### ISSUE TITLE
Use a regular message instead of a system message when using llama

### ISSUE THREAD

**Issue by kruemmelbande** [KillianLucas/open-interpreter#110]
In my limited testing, llama pretty much ignores the system message. I have tried to instead use a custimized user message, and the results have been promising. Maybe you could look into it. I put some of my testing into my fork if you want to look at it.

**Comment by KillianLucas** [comment]
I noticed this too. The strongest by far has actually been having it autocomplete this message, which is at the beginning of every message it writes (the user doesn't see this part though):

"Let's explore this. By the way, I can run code on your machine by writing the code in a markdown code block. This works for shell, javascript, python, and applescript. I'm going to try to do this for your task. Anyway, "

lmao. Anyway,

**Comment by KillianLucas** [comment]
but yes it might be beneficial to throw out the system message, put it in a user message. Would be great to test this. Thanks @kruemmelbande!
