### ISSUE TITLE
attempting to download phi (but phi is already downloaded)

### ISSUE THREAD

**Issue by JonMike12341234** [KillianLucas/open-interpreter#1101]
### Describe the bug

attempting to download phi (but phi is already downloaded)

### Reproduce

```interpreter --local```

### Expected behavior

to recognize phi is already downloaded

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/1660310/a89fb8c6-7aad-46e9-ba03-3afd5947ac9d)

### Open Interpreter version

most recent (installed today)

### Python version

Python 3.10.6

### Operating System name and version

windows 10 pro

**Comment by MikeBirdTech** [comment]
Hi @JonMike12341234 
Thanks for reporting this. There is a fix to local mode that has already been merged but not yet deployed to pip. Keep your eyes open for 0.2.3!
