### ISSUE TITLE
Why is Azure based on the GPT-3 model? How can it be changed to GPT-4?

### ISSUE THREAD

**Issue by lz82** [KillianLucas/open-interpreter#111]
![image](https://github.com/KillianLucas/open-interpreter/assets/39956694/3411ec46-4328-430b-bc62-53b3197c06fb)

**Comment by KillianLucas** [comment]
Haha <3 it probably just doesn't know! These things have no self awareness (yet). 

If your deployment is set up to use `gpt-4`, it will use `gpt-4`. As far as I know though, you need to [ask Azure](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart) to use `gpt-4`, so if you haven't done this, it's likely `gpt-3.5-turbo`.

**Comment by lz82** [comment]
> Haha <3 it probably just doesn't know! These things have no self awareness (yet).
> 
> If your deployment is set up to use `gpt-4`, it will use `gpt-4`. As far as I know though, you need to [ask Azure](https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart) to use `gpt-4`, so if you haven't done this, it's likely `gpt-3.5-turbo`.

However, under similar configurations in other scenarios, it indeed possesses self-awareness.
