### ISSUE TITLE
Clarification Regarding Interpreter Chat

### ISSUE THREAD

**Issue by grabani** [KillianLucas/open-interpreter#120]
Hi There,

So to be clear,  if I run Interpreter **without** the "--local" parameter the code is detecting that I have an openai API environment variable setup and uses that to fulfil my chat request? If I want to run all of the Interpreter chat locally (without it utilising my openai API key)  I then have to run Interpreter **with** the  "--local" parameter, is that correct?

Thanks.

**Comment by TanmayDoesAI** [comment]
yes, when you just put `interpreter` in the terminal it would use gpt-4, when you use `interpreter --fast` it would use gpt-3.5-turbo, and as you `interpreter --local` would use the codellama models
