### ISSUE TITLE
I have a GPT4 subscription but receive an error

### ISSUE THREAD

**Issue by you1anna** [KillianLucas/open-interpreter#121]
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.

I have a paid subscription so believe this should allow access, please can anyone help?

Thanks
Robin

**Comment by grabani** [comment]
Do you have an openAI API key? This does NOT work if you have a with ChatGPT Plus subscription.

Obtain a opanai GPT API key. Setup an environment variable with the API details. Alternatively, you can run a "Interpreter --local" to install a loacl LLM and have Interpreter work.

**Comment by joshlopes** [comment]
Same. wondering if it was disabled just now -- I do have a subscription and key valid

**Comment by OneHoopyFrood** [comment]
I have put in a feature request that would make this possible, but it's going to be a serious lift so I don't have high hopes. 😆 

https://github.com/KillianLucas/open-interpreter/issues/123

**Comment by joshlopes** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/3440849/92c48afa-91b6-459f-a003-8e35d7dcc094)

I feel like I should have it? I don't see an option to pre-paid ?

**Comment by OneHoopyFrood** [comment]
https://help.openai.com/en/articles/8264644-what-is-prepaid-billing

**Comment by OneHoopyFrood** [comment]
You'll need to cancel your current plan and start a new one, the last step will be to purchase credit (min $5 USD).

**Comment by jordanbtucker** [comment]
This seems to be an issue this OpenAI rather than Open Interpreter. I'm going to close this issue.

**Comment by joshlopes** [comment]
@jordanbtucker maybe worth to start thinking about some common problems, because in a few minutes two people were facing the same issue 👍

**Comment by jordanbtucker** [comment]
@joshlopes I've added this to the pinned issue #164
