### ISSUE TITLE
Feature Request: ChatGPT Plus sub use

### ISSUE THREAD

**Issue by OneHoopyFrood** [KillianLucas/open-interpreter#123]
This project is wonderful! You're amazing!

I would like to put it on the back burner to consider enabling the use of GPT-4 through a ChatGPT+ subscription via headless chrome scrapping or something like that.

I realize this is a very different direction than API interaction, but it would be so lovely for cost reasons. :)

**Comment by OneHoopyFrood** [comment]
When I get some time I'll start working on this.

**Comment by grexzen** [comment]
Just search github, there's a python wrapper lib already you can easily use instead of the calls to the api.

**Comment by OneHoopyFrood** [comment]
I wondered if there might be something already! Good to know.

Are you saying that this is library is already compatible with
open-interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen if there is movement on it or more to discuss regarding this issue.

**Comment by OneHoopyFrood** [comment]
I haven't had the time to dig into it yet, but I would love an answer if this is already do-able via the library mentioned above?
