### ISSUE TITLE
Feature Request: integration with Whisper STT or other SOTA-like model

### ISSUE THREAD

**Issue by SimplyJuanjo** [KillianLucas/open-interpreter#125]
Input via voice (Whisper-like) would be a nice-to-have feature.
Also adding an extra layer of accessibility for people with disabilities.

@KillianLucas

**Comment by ericrallen** [comment]
Hey there, @SimplyJuanjo!

Like I [mentioned](https://github.com/KillianLucas/open-interpreter/issues/490#issuecomment-1782931344) in #490, while voice is super neat, I don’t think we’re in a place to include in the core yet.

Currently it is possible for individual users to achieve this by wrapping calls to Open Interpreter in a Python script that integrates voice recognition.

That doesn’t mean it won’t ever make it into the roadmap, though.
