### ISSUE TITLE
Saved credentials are not loaded upon startup

### ISSUE THREAD

**Issue by Vybo** [KillianLucas/open-interpreter#129]
I've successfully set up Azure API to use with Open Interpreter, however even while exported to environment variables, new instance of Open Interpreter won't use them and will simply launch the setup "wizard" every time.

I use macOS zsh, echoing the variables mentioned in the after-setup message
`export OPENAI_API_KEY=your_api_key AZURE_API_BASE=your_api_base            
AZURE_API_VERSION=your_api_version AZURE_DEPLOYMENT_NAME=your_gpt_deployment_name`
yields the correct values.

I even added them to ~/.zshenv, sourced it, restarted the Terminal, but it never uses the credentials.

--debug output does not display anything besides the normal output prompting for the credentials.

**Comment by RobP-git** [comment]
I was just playing with this and found it needed to be saved into ~/.zprofile on osx. Working well now.

**Comment by jordanbtucker** [comment]
As @RobP-git mentioned, `~/.zprofile` is the correct file to edit.

For all other shells, see this comment: https://github.com/KillianLucas/open-interpreter/issues/295#issuecomment-1716135343
