### ISSUE TITLE
Distinguishing the built-in "print" from the imported print in interpreter/llama_2.py

### ISSUE THREAD

**Issue by riyanswat** [KillianLucas/open-interpreter#130]
In this file: `interpreter/llama_2.py`, `print` has been imported from `rich`: `from rich import print`. How to distinguish it from the built-in `print` function? Isn't there a naming conflict between the two? 

How about renaming the imported print or just use `rich.print`?

**Comment by ericrallen** [comment]
Closing this one as completed as the latest code imports and aliases the `print` method from `rich`.
