### ISSUE TITLE
Create this as an extension to Oobagooba text generation web ui.

### ISSUE THREAD

**Issue by rombodawg** [KillianLucas/open-interpreter#132]
Text gen web ui already has everything you need to run various ai models locally from the get go. All you need is to port this code into an extension for the web ui and then you will have a fully featured code interpreter that can run any and all ai models out there without having to try to run the models yourself using this program.

**Comment by rombodawg** [comment]
If you dont know what im talking about here it is:

https://github.com/oobabooga/text-generation-webui

**Comment by KewkLW** [comment]
It's a bit easier than that. You can simply use the api and utilize the models. However, you can do the same with HF api and models.

**Comment by twobob** [comment]
hmm dunno about that seems like a local code-llama and this would be a good fit.

**Comment by xb3sox** [comment]
Tried to connect it to the openai-api extension from text-gen-webui with these settings:
api: http://127.0.0.1:5001/v1
api-key: sk-111111...
extension: [https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai](url)


**but i got this issue:**

![image](https://github.com/KillianLucas/open-interpreter/assets/4990091/70d41c4d-b41f-4efd-9971-95f9b536bae7)

**here is the result of the request:**

![image](https://github.com/KillianLucas/open-interpreter/assets/4990091/5eb0f4d0-ecac-4904-ab80-47cb0a843401)


**Any ideas?**

**Comment by Aincvy** [comment]
Same as @xb3sox

**Comment by xb3sox** [comment]
> Same as @xb3sox 
> 
> There is an output in textgen webui console 
> ```
> '{"error": {"message": "functions is not supported.", "code": 400, "type": "InvalidRequestError", "param": "functions"}}
> ```
> 
> Perhaps this is a problem with textgen webui? 
> 

The extension doesn't support functions yet, as mentioned in the extension doc. Let's hope one of the folks here will add it.

**Comment by ericrallen** [comment]
I’m going to close this one for now.

It seems to be an issue in another repo, and hasn’t had any updates in awhile.

Please reopen if I’m wrong or there is more to discuss that is specific to this project.
