### ISSUE TITLE
Feature Request: Custom Instructions.

### ISSUE THREAD

**Issue by DasMonkey** [KillianLucas/open-interpreter#134]
Would love to see Custom instructions capability. Greatly appreciate your work!

**Comment by shubhexists** [comment]
Can you give more details? What exactly in custom Instructions?

**Comment by mak448a** [comment]
You can probably just edit the instructions file. It is stored in `site-packages/interpreter/system_message.txt`. I don't know if it'll work though, so write back if it does! 😁

**Comment by ericrallen** [comment]
In the latest version you can update the `system_prompt` in your `config.yaml` to include whatever custom instructions you'd like.

**Comment by mak448a** [comment]
Yup! Please close this issue.

**Comment by DasMonkey** [comment]
Sorry for the late reply, thank you all.
