### ISSUE TITLE
llama.cpp not using gpu

### ISSUE THREAD

**Issue by iplayfast** [KillianLucas/open-interpreter#139]
I was able to get open-interpreter to run locally by installing 
   pip install llama-cpp-python first 
and then installing
   pip install open-interpreter

It's working (slowly) but when I run nvidia-smi it show that its not using any gpu memory at all.

**Comment by iplayfast** [comment]
The problem was with the llama-cpp-python pip install. Following the instructions at https://github.com/imartinez/privateGPT/issues/885 seems to have resolved the issue.

**Comment by jordanbtucker** [comment]
See [Code-Llama on Windows](https://github.com/jordanbtucker/open-interpreter/blob/windows/WINDOWS.md).

Then if you have an NVIDIA GPU, see [Local Language Models with GPU Support](https://github.com/KillianLucas/open-interpreter/blob/main/GPU.md).

**Comment by jordanbtucker** [comment]
This is now a duplicate of #168. If you still need help, please leave a comment on that issue.
