### ISSUE TITLE
Significant Erroneous Repetition

### ISSUE THREAD

**Issue by AstroJSC12** [KillianLucas/open-interpreter#140]
First, this is amazing. So appreciative that you have built this.

One issue I have run into is massive, erroneous repetition of lines of code, which ended up in huge API usage spikes. See attached file for a sample.

[Repetition.txt](https://github.com/KillianLucas/open-interpreter/files/12553283/Repetition.txt)

[Repetition.rtf.zip](https://github.com/KillianLucas/open-interpreter/files/12553289/Repetition.rtf.zip)

**Comment by jordanbtucker** [comment]
Thanks for reporting. Can you please provide what model you were using?

Unfortunately, running a 7B model is going to be a degraded experience at this early stage. Ensuring you are on the latest version of open-interpreter will help to a degree, but unless you run a 30B model on an RTX 3090 or 4090, you will not likely be able to get anything close to GPT-3.5, at least for now.

We are of course working on improving this.

**Comment by lesong36** [comment]
I reproduced the similar issue.

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the     
model.                                                                                          

[?] Parameter count (smaller is faster, larger is more capable): 34B
   7B
   13B
 > 34B

[?] Quality (lower is faster, higher is more capable): Medium | Size: 20.22 GB, RAM usage: 22.72 GBLow | Size: 14.21 GB, RAM usage: 16.71 GB
   Low | Size: 14.21 GB, RAM usage: 16.71 GB
 > Medium | Size: 20.22 GB, RAM usage: 22.72 GB
   High | Size: 35.79 GB, RAM usage: 38.29 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): y

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA RTX A6000, compute capability 8.6

▌ Model set to Code-Llama                                                                     

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.  

Press CTRL-C to exit.                                                                           

> /home/coty/Documents/SixSigma/datasets/ht1.csv The file is in CSV format, with each row representing an employee and the columns representing their ID, decision (promoted or not), and gender.   
                                                                                                
  I need to know what you want me to do with the CSV file. Please let me know if you want me    
  to read it, write to it, or something else entirely.                                          
                                                                                                
>    1 Analyze the data to see if there are any patterns or trends in the promotion rates by      
                                                                                                
  I need to know what you want me to do with the CSV file. Please let me know if you want me    
  to read it, write to it, or something else entirely.                                          
                                                                                                
> could you please open the file and see 
                                                                                                
  I need to know what you want me to do with the CSV file. Please let me know if you want me    
  to read it, write to it, or something else entirely.

**Comment by ericrallen** [comment]
Hey there, folks!

I'm going to close this one as stale for now, but feel encouraged to reopen it if this is still an issue with the latest version of Open Interpreter.
