### ISSUE TITLE
Feature request: Memory

### ISSUE THREAD

**Issue by scrachatron** [KillianLucas/open-interpreter#144]
Absolutely love the tool already used it a bunch and racked up some open AI charges. 

Im certainly not clever enough to add this feature but was hoping we could get some sort of memory added to the app so as between launches it could remember previous conversations or you could set it up as individual instances 

Something like :
> interpreter user1

This would run the interpreter with the memory profile of user1 

Would allow for multiple different "Bots" on one system to have that object permanence and recall previous tasks they have done and previous context about the system they work in. 

memory could be split into 2 systems short and long term where short term memory is some type of Vector Database (preferably stored locally somewhere) which the AI could manage and long term could be delegated to files elsewhere in a sort of working directory. 

Kind of similar to how Auto-Gpt works but with far more ease of use

**Comment by grexzen** [comment]
Reading the docs it says it does that already, you can wipe it out if you wanna.

**Comment by scrachatron** [comment]
when running under python it seems to yes but more speaking to directly running in terminal

**Comment by scrachatron** [comment]
I can see it has been added to the roadmap so glad the functionality already exists just not part of the CLI version

**Comment by TanmayDoesAI** [comment]
we are working towards making the CLI completely be able to do what is possible in python. It would be available soon!

**Comment by jasonnathan** [comment]
Great, now that its all consolidated! It has been a couple of months now, any updates on this?

**Comment by Notnaton** [comment]
https://docs.openinterpreter.com/usage/examples#save-and-restore-chats
```
interpreter --conversations
```

**Comment by slavakurilyak** [comment]
Any updates on this?

**Comment by Notnaton** [comment]
I think Killian had something for the next update

**Comment by slavakurilyak** [comment]
It would be great to use [RAG to teach Open Interpreter new things](https://github.com/KillianLucas/open-interpreter/releases/tag/v0.1.9) while memory feature is being solved

Related issue https://github.com/KillianLucas/open-interpreter/issues/568

**Comment by slavakurilyak** [comment]
Excited to see [AI File System](https://github.com/KillianLucas/aifs) assist with RAG pipelines when working with local data

**Comment by slavakurilyak** [comment]
Excited to see RAG as this coding model needs access to project-related files (existing source code and docs) to make it more grounded

**Comment by MikeBirdTech** [comment]
Profiles and conversation history are now a part of OI. Thanks!

**Comment by mskogly** [comment]
"In your terminal, Open Interpreter behaves like ChatGPT and will not remember previous conversations." Only possible when wrapping in python?
