### ISSUE TITLE
Rate Limit Error

### ISSUE THREAD

**Issue by HealthSync** [KillianLucas/open-interpreter#145]
I get this error. 

How to fix it please?  Thanks
  

File "/Users/xxxx/.pyenv/versions/3.10.12/lib/python3.10/site-packages/interpreter/interpreter.py", line 401, in respond
    raise openai.error.RateLimitError("RateLimitError: Max retries reached")
openai.error.RateLimitError: RateLimitError: Max retries reached

**Comment by Rainy000** [comment]
I get the same error,  and I check the Rate Limit of gpt-3.5-turbo in below table，feeling confused..
![image](https://github.com/KillianLucas/open-interpreter/assets/10544217/6cf94ab2-5ed8-4f14-bc30-10b45f85473c)

**Comment by superuben** [comment]
this doesnt work for everybody, but you can add a payment method (empty creditcard) in your openai. and watch your usage and set your limits, because the usage ceiling from openai does not work like you expect! there is a 5 min delay in their usage system.

**Comment by jordanbtucker** [comment]
Thanks for reporting. Can you please confirm you are on the latest version of Open Interpreter by running the following command.

```
pip show open-interpreter
```

If the version is 0.1.0 or older, please upgrade.

```
pip install --upgrade open-interpreter
```

**Comment by HealthSync** [comment]
My issues is resolved after increasing my daily usage limit in the Openai subscription

**Comment by AlanZeng423** [comment]
> increasing

I got the same problem
How to increase daily usage limit ?
