### ISSUE TITLE
Error: cannot import name 'cli' from 'interpreter'

### ISSUE THREAD

**Issue by antondkv** [KillianLucas/open-interpreter#15]
```console

╰─$ uname -a
Linux lab 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

╰─$ pip --version                                                           1 ↵
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

╰─$ interpreter                 
Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 5, in <module>
    from interpreter import cli
ImportError: cannot import name 'cli' from 'interpreter' (unknown location)

```

**Comment by KillianLucas** [comment]
This is a weird one. We have an unconventional setup with the CLI to keep things simple for Python users:

When the user starts the CLI, poetry will run `interpreter.cli()`.
`interpreter` is an _instance_ of the `Interpreter` class in interpreter.py, which has a method called `cli`.

What's nice about having the instance as the module, is that when Python users run `import interpreter` they get an _instance_ of interpreter, which is way more intuitive to me.

But this means we risk circular imports and other weird stuff like this.

ChatGPT is telling me that some systems import things in different orders, and this could be causing the problem.

Let me get back to you on this one. Thanks for opening an issue @antondkv.

**Comment by uthpala1000** [comment]
same on windows

**Comment by uthpala1000** [comment]
> This is a weird one. We have an unconventional setup with the CLI to keep things simple for Python users:
> 
> When the user starts the CLI, poetry will run `interpreter.cli()`. `interpreter` is an _instance_ of the `Interpreter` class in interpreter.py, which has a method called `cli`.
> 
> What's nice about having the instance as the module, is that when Python users run `import interpreter` they get an _instance_ of interpreter, which is way more intuitive to me.
> 
> But this means we risk circular imports and other weird stuff like this.
> 
> ChatGPT is telling me that some systems import things in different orders, and this could be causing the problem.
> 
> Let me get back to you on this one. Thanks for opening an issue @antondkv.

I managed solve it just by removing the dot .  from .cli  to from cli

**Comment by uthpala1000** [comment]
> I managed solve it just by removing the dot . from .cli to from cli

 remove dot from interpreter.py  . from .cli to from cli

**Comment by KillianLucas** [comment]
Thanks @uthpala1000 and @antondkv. This is so weird, it's the opposite for me (breaks if I remove the dot). Is there any precedent for doing something like this?

```python
try:
  from .cli import cli
except:
  from cli import cli
```

Have either of you seen something like this before / know what's going on?
