### ISSUE TITLE
How does it know my username?

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#151]
It's kinda creepy. I asked it to send an email, and it wrote `Sincerely, mak448a`. So where did it get that from?

**Comment by mak448a** [comment]
Well, found it! But this should be said up front. Isn't this a privacy concern if running on openai's servers? https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/interpreter.py#L118

**Comment by bmc84** [comment]
You need to stop raising "issues" that aren't really issues/defects.
All your "issues" are questions. Raise them elsewhere.

**Comment by mak448a** [comment]
Okay.
