### ISSUE TITLE
interpreter local: llama_tokenize_with_model: too many tokens

### ISSUE THREAD

**Issue by ramonck** [KillianLucas/open-interpreter#158]
I am using local llama with 7B.

I am having issue to read excel file and output search result.

I just did 2 prompts, the excel file has 1.15MB with 15076 rows and 8 columns.

![image](https://github.com/KillianLucas/open-interpreter/assets/5229948/6fab942c-d559-4d93-bb1e-412345c0e610)

**Comment by jordanbtucker** [comment]
Thanks for reporting. Closing this as a duplicate of #126
