### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx

### ISSUE THREAD

**Issue by roggrat** [KillianLucas/open-interpreter#16]
When trying to use the interpreter -y --local 

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.                                               

[?] Parameter count (smaller is faster, larger is more capable): 7B
 > 7B
   16B
   34B

[?] Quality (lower is faster, higher is more capable): High | Size: 7.16 GB, RAM usage: 9.66 GB
   Low | Size: 3.01 GB, RAM usage: 5.51 GB
   Medium | Size: 4.24 GB, RAM usage: 6.74 GB
 > High | Size: 7.16 GB, RAM usage: 9.66 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): n

[?] This instance of `Code-Llama` was not found. Would you like to download it? (Y/n): y

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1145  100  1145    0     0   9656      0 --:--:-- --:--:-- --:--:--  9703
100 6829M  100 6829M    0     0  46.0M      0  0:02:28  0:02:28 --:--:-- 52.1M

 Finished downloading `Code-Llama`. 

llama.cpp: loading model from /Users/dwayne/Library/Application Support/Open Interpreter/models/codellama-7b.Q8_0.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000001; is this really a GGML file?
llama_load_model_from_file: failed to load model
Traceback (most recent call last):

AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by KillianLucas** [comment]
Hi @roggrat! It looks like it didn't actually download the file, or perhaps `llama-cpp-python` is an old version. I'd try a few things:

1) Upgrade `llama-cpp-python` with `pip install --upgrade --force-reinstall llama-cpp-python`. Then try using Open Interpreter in local mode as you did before— selecting the high quality 7B model.

2) **If that doesn't work,** try [manually downloading the 8 bit 7B CodeLlama from here](https://huggingface.co/TheBloke/CodeLlama-7B-GGUF/resolve/main/codellama-7b.Q8_0.gguf). Move it to `/Users/dwayne/Library/Application Support/Open Interpreter/models/` (overwrite the old file that's there with the same name). Then try again to run that same model in Open Interpreter.

3) If that doesn't work, let me know more information about your system.

**Comment by mihnin** [comment]
How can I transition from using CodeLlama models to Python CodeLlama models? I've noticed that Python-based models tend to produce superior code quality compared to the standard CodeLlama models

**Comment by KillianLucas** [comment]
@mihnin I think this is very important to get right.

We should make it easy for folks to use open source models, but I'm not sure about the right approach to that yet. Mainly because I don't know if `llama-cpp-python` is the best approach. There might be [better options](https://github.com/hyperonym/basaran) for [running](https://github.com/huggingface/text-generation-inference) LLMs [locally](https://github.com/nomic-ai/gpt4all).

If you have any experience running LLMs locally, I'd love it if you [dropped by the discord](https://discord.gg/YG7APUyJ5) #general channel and let me know how you like doing it. Trying to make something that detects the users system and installs the right stuff is hard.

**Comment by japanvik** [comment]
Hi @KillianLucas 

There is a server implementation in llama.cpp available [here](https://github.com/ggerganov/llama.cpp/tree/master/examples/server) which might be interesting to leverage. This implementation allows you to run an OpenAI-compatible API endpoint locally by utilizing the provided Python script as a compatibility layer (named `api_like_OAI.py`). To access it, simply set the `OPENAI_API_BASE` environment variable to point to this local endpoint. You can then access it using the GPT-4 mode within open-interpreter.

In my initial testing, I observed that connectivity works as expected, although the generated output is pretty bad. I've had decent success with my own langchain code, so while I haven't delved deeply into your code yet, it's possible that there are prompt differences between GPT-4 and the llama models that could be influencing the output.

While a bit of an unofficial llamma.cpp use case, it does decouple the LLM backend to the front end so it may be worth exploring.

**Comment by roggrat** [comment]
Hi @KillianLucas looks like you are correct, there were some dependencies that were either old or conflicting and creating a new environment and re-installing open-interpreter solved the issue.
