### ISSUE TITLE
MAC OS Installation error again，help~

### ISSUE THREAD

**Issue by DawnMelody** [KillianLucas/open-interpreter#162]
ERROR: Cannot install open-interpreter because these package versions have conflicting dependencies.

The conflict is caused by:
    openai 0.27.10 depends on aiohttp
    openai 0.27.9 depends on aiohttp
    openai 0.27.8 depends on aiohttp

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by jordanbtucker** [comment]
It seems like you might have some other pip packages that have dependency conflicts. You could trying installing open-interpreter using [pipx](https://pypa.github.io/pipx/) instead.

**Comment by DawnMelody** [comment]
thank you!
