### ISSUE TITLE
Bash code doesn't run correctly

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#163]
Sometimes, it writes bash code (e.g. echo test) and tries to run it, and it executes in python and errors out.

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```

Are you using GPT-3.5 or GPt-4?

Unfortunately, running a 7B model is going to be a degraded experience at this early stage. Ensuring you are on the latest version of open-interpreter will help to a degree, but unless you run a 30B model on an RTX 3090 or 4090, you will not likely be able to get anything close to GPT-3.5, at least for now.

We are of course working on improving this.

**Comment by markharley12** [comment]
I encountered a similar issue yesterday. Would it be possible to implement a regex check for shebangs in the code as an override for the code language?

**Comment by mak448a** [comment]
I'm using Llama 7b

**Comment by mak448a** [comment]
Suggestion: Maybe ask the ai language model to include what language it is and parse its output?

**Comment by mak448a** [comment]
Update: I've looked the source code. It looks like it uses code blocks to see what language to run it in. So if we prompt it to always use code blocks properly, then maybe it'll work?

**Comment by mak448a** [comment]
I've found a workaround. Go to line 181 of interpreter.py and replace it with `      info += "\n\nTo run code, write a fenced code block (i.e ```python, R or ```shell) in markdown. Whenever you are using bash, use ```shell. When you close it with ```, it will be run. You'll then be given its output."`

**Comment by mak448a** [comment]
I'm gonna open a pull request

**Comment by ericrallen** [comment]
I'm going to close this one as stale for now.

Please reopen the issue if there's anything more to discuss about it or the issue still exists in the latest version of Open Interpreter.
