### ISSUE TITLE
Surpport for the thirdparty API？

### ISSUE THREAD

**Issue by Hezhexi2002** [KillianLucas/open-interpreter#165]
As the title described,is there any plan to surpport the thirdparty api？

**Comment by xnpeter** [comment]
You can change the API Base yourself at "python<version>/site-packages/openai/__init__.py"

**Comment by Hezhexi2002** [comment]
> You can change the API Base yourself at "python/site-packages/openai/**init**.py"

I see,but what I want is the official surpport for the thirdparty API like adding a argument specifically for it

**Comment by michael19960921** [comment]
Does it support the execution of Java now? @xnpeter

**Comment by Nolan-zhong** [comment]
v0.12不支持第三方版本了吗？

**Comment by rishabhjain** [comment]
Since litellm supports many third party apis, this is now possible.
