### ISSUE TITLE
problem with Code Llama prompt.

### ISSUE THREAD

**Issue by lesong36** [KillianLucas/open-interpreter#166]
![image](https://github.com/KillianLucas/open-interpreter/assets/85875665/d5c39382-b40f-4bc1-a9b4-27626938267c)

Ubuntu 22.04, A6000 GPU, 34B medium quality.

**Comment by jackfood** [comment]
Did you change any of the py files?

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```

Once upgraded, let us know if you are still seeing the issue.

**Comment by lesong36** [comment]
@jordanbtucker Thanks for your feedback, I upgrade the open-interpreter, but still have the same issue. BTW, gpt3.5 work fine for me. 
![image](https://github.com/KillianLucas/open-interpreter/assets/85875665/18a16214-7de3-45be-8a2b-68fb16fbcadb)

**Comment by lesong36** [comment]
It is 0.1.1 now

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jordan Tucker ***@***.***>
发送时间: Saturday, September 9, 2023 1:12:31 AM
收件人: KillianLucas/open-interpreter ***@***.***>
抄送: LEI SONG ***@***.***>; Author ***@***.***>
主题: Re: [KillianLucas/open-interpreter] problem with Code Llama prompt. (Issue #166)


Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

pip install --upgrade open-interpreter


Once upgraded, let us know if you are still seeing the issue.

―

**Comment by jordanbtucker** [comment]
Thank you for the feedback. For now, the best experience will be through GPT-4, but we will take this feedback and review it to enhance the performance of the local language models.

**Comment by noneabove1182** [comment]
any chance that hosting an openai-compatible endpoint (say, with text-gen-webui or just llama.cpp server) would work better than the wrapper you have?

To that point as well, it may be worth investigating if a BNF in llama.cpp would be helpful so you can guarantee specific formatting

**Comment by ericrallen** [comment]
Hey there, folks!

I'm going to close this one as stale for now, but feel encouraged to reopen it if this is still an issue with the latest version of Open Interpreter.
