### ISSUE TITLE
WinError 10106 when installing or running Code-Llama

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#167]
When running Open Interpreter on Windows with Code-Llama (either because you did not enter an OpenAI API key or you ran interpreter --local) you may encounter an error similar to the following.

```
OSError: [WinError 10106] The requested service provider could not be loaded or
initialized
Error during installation with OpenBLAS: Command '['C:\\Users\\Jane\\AppData\\
Local\\Microsoft\\WindowsApps\\python.exe', '-m', 'pip', 'install',
'llama-cpp-python']' returned non-zero exit status 1.
```

To resolve this issue, please follow the steps in [Code-Llama on Windows](https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md). If you still run into problems, please leave comment here or ask on [the Discord server](https://discord.gg/YG7APUyJ5).

**Comment by superuben** [comment]
this bug still remains. ive tried these commands;

pip install llama-cpp-python
pip install --upgrade llama-cpp-python
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
pip install -U open-interpreter

but didnt work. also installed all the VS C modules and packages.
i can run models on my pc using other software, but this just does not work somehow
