### ISSUE TITLE
Configuring Code-Llama to use an NVIDIA GPU on Windows

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#168]
Open Interpreter can be used with local language models, however these can be rather taxing on your computer's resources. If you have an NVIDIA GPU, you may benefit from offloading some of the work to your GPU.

The set this up, follow the steps in [Local Language Models with GPU Support](https://github.com/KillianLucas/open-interpreter/blob/main/docs/GPU.md).

If you still run into problems, leave a comment here or ask on [the Discord server](https://discord.gg/YG7APUyJ5).

**Comment by mathpopo** [comment]
@jordanbtucker thanks first, i use CUDA_PATH=/usr/local/cuda FORCE_CMAKE=1 CMAKE_ARGS='-DLLAMA_CUBLAS=on' pip3 install llama-cpp-python --force-reinstall --upgrade --no-cache-dir -vv  ---> Removed build tracker: '/tmp/pip-build-tracker-2tvw_2hj'  there is no error ,but python3 -c "from llama_cpp import GGML_USE_CUBLAS; print(GGML_USE_CUBLAS)"--->  False

**Comment by mathpopo** [comment]
(open-interpreter) chenxin@chenxin-Nitro-AN515-52:~$ nvidia-smi
Fri Sep  8 16:02:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8     3W /  N/A |     11MiB /  6078MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1185      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2157      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by gnivler** [comment]
Hi - thanks for all your work on this, very exciting!

The link in your OP is 404 - I think it should go to here maybe (missing docs path)?  [https://github.com/KillianLucas/open-interpreter/blob/main/docs/GPU.md](url)

**Comment by jordanbtucker** [comment]
@raptor-bot Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```

Unfortunately, running a local model is going to be a degraded experience at this early stage. Ensuring you are on the latest version of open-interpreter will help to a degree, but unless you run a 30B model on an RTX 3090 or 4090, you will not likely be able to get anything close to GPT-3.5, at least for now.

We are of course working on improving this.

**Comment by jordanbtucker** [comment]
@raptor-bot It will likely be the same or slower based on your mac's GPU.

**Comment by hvacjava** [comment]
@raptor-bot you are constrained by your GPUs memory. If the model is larger than the onboard memory (keeping at least 1gb of headroom for stability) it will be shifted to CPU and RAM.

Your best bet is probably to use smaller, heavily quantized models. Of course this has direct negative implications for performance but that's the cost of being on the bleeding edge of tech. Financially probably better off subbing to OpenAi and utilizing the API if you are looking for performance. Otherwise you are looking at dropping a couple stacks on a new rig.

Honestly with the pace of things the best bet for most is probably a combo of gpu rental (Llamba, vast etc) and OpenAi api. Gives the best performance with very little upfront buy-in cost.
