### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#170]
When installing Open Interpreter via `pip install open-interpreter`, you may see an error similar to the following.

```
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
```

This is likely because you are using an unsupported version of Python. Please install Python 3.10 or later.

To check your Python version, run the following command.

```
python -V
```

If you still run into problems, leave a comment here or ask on [the Discord server](https://discord.gg/YG7APUyJ5).

**Comment by Raclez** [comment]
zsh: command not found: interpreter

**Comment by TanmayDoesAI** [comment]
@Raclez please refer to https://github.com/KillianLucas/open-interpreter/issues/169

**Comment by roprice** [comment]
Hey guys - I have 3.11.4 but still have the same issue. Anyone seens this or have ideas?

```
% pip install open-interpeter
ERROR: Could not find a version that satisfies the requirement open-interpeter (from versions: none)
ERROR: No matching distribution found for open-interpeter

% python3 --version
Python 3.11.4
```

**Comment by TanmayDoesAI** [comment]
@roprice Kindly try using `pip3 install open-interpreter` or try checking your path variables

**Comment by Hussseinkizz** [comment]
> @roprice Kindly try using `pip3 install open-interpreter` or try checking your path variables

This worked for me, on python 3.11, I was still getting the error!

**Comment by afanjul** [comment]
For those who are getting the error, this is the correct answer for me in MacOs Sonoma:
` pip3.10 install open-interpreter`

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks

**Comment by sam1am** [comment]
> For those who are getting the error, this is the correct answer for me in MacOs Sonoma:
> ` pip3.10 install open-interpreter`

This worked for me in userland on android after installing python 3.10 and pip3.
