### ISSUE TITLE
Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by afiqnazir** [KillianLucas/open-interpreter#173]
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

**Comment by Mustafagrbz** [comment]
I solved it by upgrading pip

**Comment by artificeryy** [comment]
I solved it by following the fixes people proposed here: https://github.com/oobabooga/text-generation-webui/issues/1534
