### ISSUE TITLE
 Function call could not be parsed.

### ISSUE THREAD

**Issue by lk1ngaa7** [KillianLucas/open-interpreter#178]
> Function call could not be parsed.

Please open an issue on Github (openinterpreter.com, click Github) and paste the
following:

<OpenAIObject at 0x1102389b0> JSON: {
  "name": "python",
  "arguments": "import subprocess\n\n# Download the video using
yt-dlp\nvideo_url =
\"https://www.bilibili.com/video/BV1DN4y1R7xB/?spm_id_from=333.1007.tianma.2-1-4
.click\"\ncommand = f\"yt-dlp {video_url}\"\noutput =
subprocess.check_output(command, shell=True, text=True)\n\noutput"
}

**Comment by lk1ngaa7** [comment]
using gpt3.5 
it becomes good after i use gpt4

**Comment by ericrallen** [comment]
Hey there, @lk1ngaa7!

Is this still an issue for you with the most recent version of Open Interpreter?

**Comment by ericrallen** [comment]
I think this might have been fixed by a Pull Request that was merged recently that handles GPT-3.5 Turbo hallucinating a `Python` function.

I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
