### ISSUE TITLE
Error in URL for the 7B high quality CodeLlama model

### ISSUE THREAD

**Issue by merlinfrombelgium** [KillianLucas/open-interpreter#179]
**Describe the bug**
The download link to the 7B High quality model, is wrong, resulting in a 401: Unauthorized access error upon download.

**To Reproduce**
1. run 'interpreter --local' or its Python equivalent 'get_llama_2_instance()'
2. Choose '7B' for parameter count, then 'High' for quality
3. Use of GPU is irrelevant to reproduce the issue
4. [?] This instance of `Code-Llama` was not found. Would you like to download it? (Y/n): Y
5. See error:
`
▌ Failed to install Code-LLama.

We have likely not built the proper Code-Llama support for your system.

( Running language models locally is a difficult task! If you have insight into the best way to implement this across
platforms/architectures, please join the Open Interpreter community Discord and consider contributing the project's
development. )

Please press enter to switch to GPT-4 (recommended).
nTraceback (most recent call last):
  File "D:\envs\conda\oi\Lib\site-packages\interpreter\interpreter.py", line 177, in chat
    self.llama_instance = get_llama_2_instance()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\site-packages\interpreter\llama_2.py", line 86, in get_llama_2_instance
    wget.download(url, download_path)
  File "D:\envs\conda\oi\Lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\envs\conda\oi\Lib\urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
`

**Expected behavior**
The 7B high quality model should be downloaded successfully.

**Screenshots**
![image](https://github.com/KillianLucas/open-interpreter/assets/26247323/c5e64158-5b63-4104-abe2-06cdc5d8e33f)

**System (please complete the following information):**
 - OS: Windows 11
 - Python 3.11.4

**Additional context**

**Fix**
The download URL for this model is wrong in the code:
![image](https://github.com/KillianLucas/open-interpreter/assets/26247323/e3a2a77a-7ec8-4410-9fa6-3f1e3edebbfb)
The correct URL is 'https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-GGUF/resolve/main/codellama-7b-instruct.Q8_0.gguf'

**Comment by twobob** [comment]
doh yeah this
