### ISSUE TITLE
Instruction clarifications

### ISSUE THREAD

**Issue by iplayfast** [KillianLucas/open-interpreter#18]
If I have llama.cpp installed and running as a string (ie http://0.0.0.0:8080), how would I instruct open-interpreter to use it.

**Comment by iplayfast** [comment]
As an enhancement / suggestion

I was able to setup llama.cpp by linking my version's subdirectory. 
Maybe mention in the readme that it expects to find llama.cpp in the directory and will set it up if not there. 

It doesn't ask me what model I would like to use.  I like the arrow key to select, but the buffer should be cleared before waiting for a keypress. 

I have many models downloaded it would be nice to use the arrow key to select which one. 

Or If I'm running it as a server it would be nice to just specify that on the command line. for example --host 127.0.0.1 --port 8080

or pass llama parameters to llama from the command line, something like

interpreter --local ../llama.cpp/server -t 16 --host 127.0.0.1 --port 8080 -m ../llama.cpp/AllModels/TheBloke_CodeLlama-13B-
oasst-sft-v10-GGUF/codellama-13b-oasst-sft-v10.Q8_0.gguf

That way the other questions about gpu etc are all handed by llama.cpp/server or llama.cpp/main 

Very interesting project.

**Comment by KillianLucas** [comment]
I'm very interested in how you got that to work. Any way you could [come to the discord](https://discord.gg/YG7APUyJ5) (#general channel) and we could talk about it?

To me this is very important to get right. I think specifying `--model` from the command line is brilliant.
