### ISSUE TITLE
Interpreter not able to run python code, run_code issue?

### ISSUE THREAD

**Issue by vinay235** [KillianLucas/open-interpreter#180]
Please find the interpreter chat below where I am trying to verify the running of python code. I have uninstalled all older versions of python as well. Appreciate the response and feedback.
Windows 11 64-bit. 

    Let's start by checking the Python version.
      python --version
      y
    ```
      python --version


      Microsoft Windows [Version 10.0.22621.2134]
      (c) Microsoft Corporation. All rights reserved.
      C:\Users\Vinay Datta>echo "ACTIVE_LINE:1"
      "ACTIVE_LINE:1"
      C:\Users\Vinay Datta>python --version
      Python 3.11.5
      C:\Users\Vinay Datta>
    ```

      The Python version installed on your machine is 3.11.5, which is a valid version.

    Next, let's verify the Python installation by running a simple Python command. We'll try to print a simple message
      using Python.

      python -c "print('Hello, World!')"

      Would you like to run this code? (y/n)

      y

    ```
      python -c "print('Hello, World!')"

      C:\Users\Vinay Datta>echo "ACTIVE_LINE:1"
      "ACTIVE_LINE:1"
      C:\Users\Vinay Datta>python -c "print('Hello, World!')"
      Hello, World!
      C:\Users\Vinay Datta>

    ```
      The Python command executed successfully and printed the message "Hello, World!". This indicates that your Python
      installation is working correctly when accessed directly from the shell.

      The issue might be with the way the Python environment is being accessed by the run_code function. Let's try running
      a Python script using the run_code function again to see if the issue persists.

      print('Hello, World!')

      Would you like to run this code? (y/n)

      y

    ```
      print('Hello, World!')

        File "C:\Users\Vinay
      Datta\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 133, in run
          self.start_process()
        File "C:\Users\Vinay
      Datta\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 81, in
      start_process
          self.proc = subprocess.Popen(start_cmd.split(),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Vinay Datta\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Vinay Datta\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in
      _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      OSError: [WinError 193] %1 is not a valid Win32 application
    ```

      The issue persists when trying to run Python code using the run_code function. This suggests that the problem might
      be with the way the run_code function is trying to access the Python environment.

      Unfortunately, as an AI, I don't have the ability to fix issues with the underlying system or the run_code function.
      I would recommend reaching out to a system administrator or a software engineer who can help troubleshoot this issue
      further. They might need to look into the configuration of the run_code function or the Python environment on your
      machine.

      In the meantime, you can continue to run Python code directly from the shell as we did earlier.

**Comment by jordanbtucker** [comment]
Thanks for reporting. This is likely due to the same issue described in #82.

I'm going to close this issue in favor of that one for now.

**Comment by vinay235** [comment]
@jordanbtucker I managed to fix it by splitting the parameters explicitly in code_interpreter.py line 32 : 
` "start_cmd": [sys.executable, "-i" ,"-q" ,"-u"] ` 
and removing the .split() from line 82 in the same file. Its working for me now.
