### ISSUE TITLE
Token size limit. I hit by a token limit of 1024 after two to three rounds of python run. How to increase it to 2048?

### ISSUE THREAD

**Issue by jackfood** [KillianLucas/open-interpreter#184]
I am using local llama gguf, an d I tried edit the py local llama to ctx 2048, but it still remain 1048

**Comment by merlinfrombelgium** [comment]
#126
[#2](https://github.com/KillianLucas/tokentrim/pull/2)

**Comment by jackfood** [comment]
Thanks @merlinfrombelgium 
i tried 
**llama_2.py** -` n_ctx=4096`
**tokentrim.py** -` 'code-llama': 4096,`
**interpreter.py** - ```
 if self.local:
      messages = tt.trim(self.messages, max_tokens=4096, system_message=system_message)
```

**but still encountered** - ValueError: Requested tokens (1066) exceed context window of 1048

Thanks for your help, hope this can be increased to 4096.
