### ISSUE TITLE
Planning to implement OpenSource models ?

### ISSUE THREAD

**Issue by PedzacyKapec** [KillianLucas/open-interpreter#19]
Hi,
Are you planning to implement OpenSource models ?
Especially knowing that a lot of the recent models are even better in many tasks than gpt4 itself .
Thanks !

**Comment by KillianLucas** [comment]
Hey @PedzacyKapec! **1000%.**

Open Interpreter already supports `Code Llama` (run `interpreter --local` to install and use it) and there seems to be demand for more models too.

Would it be the same to you if we supported running open source models in the cloud, like on RunPod.io or HuggingFace? Or is it the _local_ aspect that you're looking for (no connection to the internet)?

**Comment by ericrallen** [comment]
I haven't started hacking on this yet, but integrating with [`ollama`](https://github.com/jmorganca/ollama) could be an interesting approach.

The [ollama API](https://github.com/jmorganca/ollama/blob/main/docs/api.md) lets you [list local models](https://github.com/jmorganca/ollama/blob/main/docs/api.md#list-local-models) and [generate chat completions](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion). Ollama should support Windows and Linux soon.

**Comment by PedzacyKapec** [comment]
> Hey @PedzacyKapec!
> 
> **100%.**
> 
> Open Interpreter already supports `CodeLlama` (run `interpreter --local` to install and use it) and there seems to be demand for other open-source models like `WizardCoder`.
> 
> Would it be the same to you if we simply supported running open source models in the cloud, like on RunPod.io or HuggingFace? Or is it specifically the _local_ aspect that you're looking for (no connection to the internet)?

Personally i would prefer to run it offline.
