### ISSUE TITLE
Open Interpreter Exits After Choosing GPU Option

### ISSUE THREAD

**Issue by search620** [KillianLucas/open-interpreter#193]
Hello everyone,

I'm trying to run Open Interpreter with local language models and GPU support on my Windows machine. However, the program exits as soon as I choose the GPU option.

Here are the details:

Operating System: Windows 10
GPU: NVIDIA GeForce RTX 3060 Ti
CUDA Version: 12.2
Driver Version: 531.61
Command Run: interpreter --local
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2

The program exits after displaying:
```
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060 Ti, compute capability 8.6
```

I've tried running the Command Prompt as an administrator and ensuring all software is up-to-date, but the issue persists.
Has anyone encountered this issue before or have any suggestions on how to resolve it?
Thank you in advance for your help!

**Comment by darkacorn** [comment]
did you pass in the model with -v ?

**Comment by darkacorn** [comment]
what model did you load ? 
can you can nvidia-smi during that so see how your vram is allocated ?

**Comment by search620** [comment]
> what model did you load ? can you can nvidia-smi during that so see how your vram is allocated ?

I am using code lama 13b and large ram 16g
About the usage of the vram I am using real time monitoring and didn't see any peak ov vram or any use on vram... so.. maybe it is not related to vram.

**Comment by search620** [comment]
CUDA error 222 at C:\Users\Home\AppData\Local\Temp\pip-install-okablop9\llama-cpp-python_7c577c2675f64ee393e5de5ff792263f\vendor\llama.cpp\ggml-cuda.cu:6046: the provided PTX was compiled with an unsupported toolchain.

**Comment by search620** [comment]
OK after updating my drive GPU to the latest driver now it seems to work (very slow) but work
