### ISSUE TITLE
Issue while using Azure OpenAI api

### ISSUE THREAD

**Issue by Duggempudi-BC** [KillianLucas/open-interpreter#194]
Your issue may have already been reported. Please check the following link for common issues and solutions.

[Commonly faced issues and their solutions](https://github.com/KillianLucas/open-interpreter/issues/164)

**Describe the bug**

raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

This error is encountered while using Azure OpenAI API key

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Python version [e.g. 3.10]
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 

**Additional context**

**Comment by jordanbtucker** [comment]
Thanks for reporting. I've updated your issue with a template. Can you please fill out the template. Thanks!

**Comment by OlegRakovitch** [comment]
I am having the same issue. This is the output I am seeing

```
S:\>interpreter --use-azure

Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▌ Azure OpenAI Service API info not found

To use GPT-4 (recommended) please provide an Azure OpenAI API key, a API base, a deployment name and a API version.

To use Code-Llama (free but less capable) press enter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Azure OpenAI API key: [redacted]
Azure OpenAI API base: [redacted]
Azure OpenAI deployment name of GPT: gpt-4-32k
Azure OpenAI API version: 2023-03-15-preview

Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key AZURE_API_BASE=your_api_base
AZURE_API_VERSION=your_api_version AZURE_DEPLOYMENT_NAME=your_gpt_deployment_name on Mac/Linux or setx OPENAI_API_KEY
your_api_key AZURE_API_BASE your_api_base AZURE_API_VERSION your_api_version AZURE_DEPLOYMENT_NAME
your_gpt_deployment_name on Windows.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▌ Model set to GPT-4

Tip: To run locally, use interpreter --local

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> List 5 most critical security vulnerabilities in the source code located at https://github.com/KillianLucas/open-interpreter
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\interpreter\interpreter.py", line 104, in cli
    cli(self)
  File "C:\Python\Lib\site-packages\interpreter\cli.py", line 46, in cli
    interpreter.chat()
  File "C:\Python\Lib\site-packages\interpreter\interpreter.py", line 256, in chat
    self.respond()
  File "C:\Python\Lib\site-packages\interpreter\interpreter.py", line 380, in respond
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Python\Lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions
```

**Comment by jordanbtucker** [comment]
@OlegRakovitch Thanks for reporting. If you could fill out the template above, or create your own issue [using the template](https://github.com/KillianLucas/open-interpreter/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=), that would be helpful. Getting all the information up front will help troubleshoot issues quicker.

**Comment by OlegRakovitch** [comment]
**Describe the bug**
interpreter crashes with exception when used with `--use-azure` flag

**To Reproduce**
Steps to reproduce the behavior:
1. Install interpreter for Windows by following instructions on this page https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md
2. Open cmd
3. Run `interpreter --use-azure`
4. Provide Azure OpenAI API key
5. Provide Azure OpenAI API base
6. Provide Azure OpenAI deployment name of GPT
7. Provide Azure OpenAI API version
8. Provide any prompt
9. See `openai.error.InvalidRequestError` exception

**Expected behavior**
interpreter to come up with a plan and execute it in multiple steps

**Screenshots**
![image](https://github.com/KillianLucas/open-interpreter/assets/16016624/faef834c-2697-48f7-8d01-cc78596cfd34)

**System (please complete the following information):**
 - OS: Windows 10
 - Python version Python 3.11.5
 - Open Interpreter version (`pip show open-interpreter`):  0.1.1

**Comment by mikeplavsky** [comment]
@OlegRakovitch This fixes the problem: 
```
Azure OpenAI API version: 2023-07-01-preview 
```

**Comment by OlegRakovitch** [comment]
That totally works, thank you @mikeplavsky !

**Comment by warjiang** [comment]
> That totally works, thank you @mikeplavsky !

0315 is too old

**Comment by demon869** [comment]
@mikeplavsky I encountered the same problem when using Azure openai gpt-4-32k. The problem was solved after using api_versio: 2023-07-01-preview, thank you
