### ISSUE TITLE
Explain how to set up access to GPT-4 in README

### ISSUE THREAD

**Issue by cherkavi** [KillianLucas/open-interpreter#200]
after installation not so clear how to setup GPT-4

**Steps to reproduce the behavior:**
1. `pip install open-interpreter`
2. error in the console
```
python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**System:**
 - OS: Ubuntu 22.04
 - Python version 3.10
 - Open Interpreter version: 0.1.1

**Additional context**
maybe it is luck of the description in README.md ?

**Comment by jordanbtucker** [comment]
Yes, we should explain how to set up GPT-4 access in the README.

**Comment by pratss10** [comment]
Is this issue still unresolved? I would like to contribute if its open

**Comment by ericrallen** [comment]
Hey there, @pratss10!

There’s a brief mention in the pinned common issues issue, but that’s pretty much all that’s out there.

I think this one would be good for a separate Markdown file in the `docs` directory.

Thanks for picking this up!

I’ll assign it to you.

**Comment by pratss10** [comment]
I am new to open source contributing and would like to know how do i verify and find the detailed setup for gpt-4 since i do not have chatgpt plus
