### ISSUE TITLE
Incomplete response

### ISSUE THREAD

**Issue by padamshrestha** [KillianLucas/open-interpreter#205]
**Describe the bug**
Response generated by llama model doesn't completes.

**To Reproduce**
Run interpreter --local

**Expected behavior**
It should either complete the response or allow to continue to remaining parts

**Screenshots**
![image](https://github.com/KillianLucas/open-interpreter/assets/6394404/b6ad1139-a7aa-4cbf-bd82-d3f8d742b89f)

**System (please complete the following information):**
 - OS: Ubuntu container on Mac M1
 - Python version 3.10.12
 - Open Interpreter version 0.1.1

**Comment by oalvay** [comment]
actually, you can input something like "please continue to complete your code", it will then generate the remaining part.

**Comment by newlxj** [comment]
> **Describe the bug** Response generated by llama model doesn't completes.
> 
> **To Reproduce** Steps to reproduce the behavior: Run interpreter --local
> 
> **Expected behavior** It should either complete the response or allow to continue to remaining parts
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/6394404/266753958-b6ad1139-a7aa-4cbf-bd82-d3f8d742b89f.png)
> 
> **System (please complete the following information):**
> 
> * OS: Ubuntu container on Mac M1
> * Python version 3.10.12
> * Open Interpreter version 0.1.1

Me Too

**Comment by newlxj** [comment]
> actually, you can input something like "please continue to complete your code", it will then generate the following part.

This plan is not feasible, he will continue to start over until it is interrupted

**Comment by ericrallen** [comment]
Hey there!

I'm going to close this one as stale for now, but please feel encouraged to reopen it if it's still an issue with the latest version of Open Interpreter.
