### ISSUE TITLE
[Feature] Code Llama Implementation in Google Colab

### ISSUE THREAD

**Issue by DevDeepakBhattarai** [KillianLucas/open-interpreter#207]
**Is your feature request related to a problem? Please describe.**
Code Llama is not working in Google Colab when I install it.

**Describe the solution you'd like**
Proper documentation on how to run Code Llama in google colab should be given or code should be provided

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. This doesn't really support Jupyter Notebooks right now because of its reliance of terminal/tty. But it's definitely something to look into.

**Comment by amida47** [comment]
@jordanbtucker https://github.com/InfuseAI/colab-xterm might be a solution
