### ISSUE TITLE
  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by fzfz666** [KillianLucas/open-interpreter#211]
How to solve?(>:-:<)

Building wheels for collected packages: llama-cpp-python
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by TanmayDoesAI** [comment]
@fzfz666 Kindly go through #164 if this still is a problem feel free to reopen this issue
