### ISSUE TITLE
Large files in git history

### ISSUE THREAD

**Issue by joshuavial** [KillianLucas/open-interpreter#214]
**Describe the bug**
Cloning down the repo takes ~89MB due to large files that were committed in the past and removed from the current code base, but not from the git history.

**To Reproduce**
`du -hs .git`

**Expected behavior**
The repo should be under 2MB when the unnecessary large files (venv folder and .whl files) are removed from git history

**Additional context**
[BFG](https://rtyley.github.io/bfg-repo-cleaner/) can clean them up, though it will involve rewriting git history and require a rebase from all open PRs. My view is it is better to wear the pain once while the project is still young than just ignore it.

You could actually do this with open interpreter if you wanted to - here is one way of doing it https://youtu.be/SIVDUDfKcJo?si=4COYdCxb8_CAaclP&t=425

**Comment by jordanbtucker** [comment]
Thanks for the suggestion! I've noticed this too. I will need to discuss with the other contributors. @KillianLucas @TanmayDoesAI

**Comment by joshuavial** [comment]
A viewer asked me for a clean version of the git history so I made them one at https://github.com/joshuavial/open-interpreter/tree/clean-git-history
It only has the venv folder and *.whl files removed but gets it down to 1.5M

**Comment by AHB102** [comment]
So is this issue up for grabs ?

**Comment by ericrallen** [comment]
Hey there, @AHB102!

It is available.

I can assign it to you if you want it.

**Comment by XoL1507** [comment]
what i mean is, we cannot stop them to control my data.

**Comment by ericrallen** [comment]
Actually, I might have mistakenly marked this one as a `good first issue`.

I’m not sure how complicated it will be to rewrite all the history and submit that PR.

Feel encouraged to look into it, and let us know if it seems feasible.

Now is a good time to handle it, though. We mostly have outdated PRs open right now.

**Comment by AHB102** [comment]
@ericrallen As a newcomer to open source, I'm wondering if it's appropriate for me to tackle issues like this. Although it seemed straightforward, I have quite a few questions. Are there any groups or chats where I can seek guidance?

**Comment by ericrallen** [comment]
@AHB102 There's an [Open Interpreter Discord](https://discord.gg/6p3fD6rBVm).

There are also some other Issues I tagged as [`good-first-issue`](https://github.com/KillianLucas/open-interpreter/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) that might be worth looking into.

**Comment by AHB102** [comment]
@ericrallen I think I can and will solve this issue. Can you please assign this to me? It might require some time as I'm getting acquainted with everything.

**Comment by AHB102** [comment]
@ericrallen I've looked into rewriting Git history. It's a powerful tool, but it also has the potential to ruin a project. As a first-time contributor, I feel it would be a bit too much to take on. However, I'd be happy to stay in the loop and learn more about it

**Comment by joshuavial** [comment]
FYI @AHB102

I checked out a mirror of the git repo with 
```
git clone --mirror https://github.com/KillianLucas/open-interpreter 
```
then removed everything in the venv folder and *.whl files using [bfg](https://rtyley.github.io/bfg-repo-cleaner/)

```
cd open-interpreter.git
java -jar ../bfg-1.14.0.jar -D '*.whl' .
java -jar ../bfg-1.14.0.jar --delete-folders venv --no-blob-protection .
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

then force pushed it up to my repo
```
git remote add jv https://github.com/joshuavial/open-interpreter
git push --force jv main
```

then I can check that it has made no change on the current main with
```
git clone https://github.com/joshuavial/open-interpreter
git remote add upstream https://github.com/KillianLucas/open-interpreter
git diff origin/main upstream/main
```

**Comment by jordanbtucker** [comment]
@joshuavial While the files may not be different, the vast majority of the git history, including the commit hashes, will not be identical. This can wreak havoc on all PRs, clones, and forks that have been created before this change. By that I mean it will be troublesome to reconcile the 16 open PRs and the commits and feature branches on any clones/forks. Basically everything will need to be rebased.

There are already almost 3,000 forks, and I don't know how many local clones. I'm not saying it shouldn't be done. But the cost/benefit needs to be carefully weighed.

**Comment by joshuavial** [comment]
@jordanbtucker absolutely, that's for the project maintainers to make a call on. I figure since the help wanted tag went up on the issue it is what they want.

If it does get merged there will need to be some decent comms about rebasing as I would expect a bunch of people to be unfamiliar with it.

**Comment by ericrallen** [comment]
Honestly, the `help wanted` tag was a mistake on my end while triaging 250+ issues and not wanting to think about this one.

I don’t actually care about any of the open PRs - they are all basically stale at this point and I just haven’t had a chance to close them all - or the forks (if you fork a project, you gotta worry about what happens upstream).

I actually just think this is not an important problem to deal with.

Most users install via `pip` and move on.

I can count the active contributors on one hand - maybe two if I stretch it - and this has not prevented any of them from contributing.

Is it ideal? No. Is it important? Probably not.

I’m going to leave this open for a few days in case anyone coma convince me this is important, but otherwise it will just be closed soon and we’ll just circle back if it becomes a big deal at some point.

**Comment by ericrallen** [comment]
It seems I missed the open PR when I wrote my knee jerk reaction to this Issue suddenly getting so much attention.

I’ll review it tomorrow and double-check that the guy blame still seems accurate so people know who to ping with questions.

Thanks for tackling this issue thst we’ve been putting off dealing with.

I’m sorry if I was dismissive, just got so many pings on this Issue today and should have managed it better.
