### ISSUE TITLE
Please add how to properly delete Open-interpreter

### ISSUE THREAD

**Issue by altruistminute** [KillianLucas/open-interpreter#218]
No GPT-Key is requested after pip install and interpreter commands
Add guide to manually do it or fix it plz.
Add guide to uninstall Open-interpreter properly because pip uninstall wont do it.
Thanks.

**Comment by altruistminute** [comment]
Precise also to use cmd prompt and not git bash as it is not supported on it.

**Comment by jordanbtucker** [comment]
I think what you are asking is how to remove residual files and environment variables, right? Like the `OPENAI_API_KEY` env and the models that were downloaded?

**Comment by ericrallen** [comment]
I’m going to close this one as stale.

Please reopen the issue if you still need help or have suggestions on how we can better explain this one.

**Comment by RisingTM** [comment]
i do have the same problem i downloaded oi and then for some reason it didnt work and i tried gpt and the other option and it didnt work ... now it just took up like 5 gb of my storage and i done know how to free it
