### ISSUE TITLE
not use gpt4

### ISSUE THREAD

**Issue by Raclez** [KillianLucas/open-interpreter#224]
**Describe the bug**
use chatgpt3.5  
`openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x110521340>: Failed to establish a new connection: [Errno 60] Operation timed out'))`

**To Reproduce**
i want to use chatgpt4

**Screenshots**
![image](https://github.com/KillianLucas/open-interpreter/assets/82217572/46ad2f94-8d05-4aa0-b926-8d839d2c08b9)

**System (please complete the following information):**
 - OS: [e.g. mac]
 - Python version [e.g. 3.9.0]
 - Open Interpreter version (0.1）

**Comment by warjiang** [comment]
can you use gpt3.5 api local? it report network probelm

**Comment by jusanz** [comment]
In my case, I can't use gpt-4 too because I have not paid for OpenAI API yet. Though I'm using open-interpreter on gpt-3.5-turbo, it's still great.

**Comment by Raclez** [comment]
I can't use gpt3.5 either

**Comment by jusanz** [comment]
Have you ever tried -f option? This let open-interpreter use gpt-3.5-turbo instead of gpt-4.

**Comment by okisdev** [comment]
Hi please see https://github.com/KillianLucas/open-interpreter/issues/238#issuecomment-1713006188.

**Comment by jordanbtucker** [comment]
Thanks @okisdev ! Closing.
