### ISSUE TITLE
Having the possibility to set LMStudio Local Inference Server Endpoint as the OpenAI URL to run quantized models like CodeLlama

### ISSUE THREAD

**Issue by sgaseretto** [KillianLucas/open-interpreter#225]
LMStudio offers the feature to launch a Local Inference Server that resembles the OpenAI API:
<img width="642" alt="Captura de pantalla 2023-09-09 a la(s) 20 30 50" src="https://github.com/KillianLucas/open-interpreter/assets/6946040/8d4e0cec-3bf2-4e14-821e-c95d486e7dd6">
Having the possibility to use that server to leverage the power from CodeLlama based models (and possibly others like WizardCoder) would be great! It will also allow the users to use quantized models on Windows and MacOS with minimal setup, since LMStudio already uses llama.cpp and other solutions to run quantized models

**Comment by PaulConyngham** [comment]
have you seen this pull request by any chance?

https://github.com/KillianLucas/open-interpreter/pull/311

**Comment by PaulConyngham** [comment]
Waiting on Yags to add function calling & the whole thing should work

**Comment by ericrallen** [comment]
Hey there!

Is this still an Issue?

**Comment by ericrallen** [comment]
I'm going to close this one as LM Studio is now the default provider for local models in Open Interpreter.
