### ISSUE TITLE
open-interpreter fails to install

### ISSUE THREAD

**Issue by manuelzo** [KillianLucas/open-interpreter#233]
**Describe the bug**
When I try to install open-intepreter the installation fails

**To Reproduce**
1. Open the terminal (zsh)
2. Write 'pip install open-interpreter'
3. I receive the message:
4. ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

**Expected behavior**
The installation works.

**Screenshots**
<img width="729" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/24671558/41201cf7-b02e-4cc9-a53b-5dabc3e9273e">

**System (please complete the following information):**
 - Macos Ventura 13.5.1
 - Python 3.11.1
 - WARNING: Package(s) not found: open-interpreter

**Comment by ihgalis** [comment]
It seems you are on an Macbook Air. Try this including miniconda as a virtual environment for open-interpreter:

https://github.com/KillianLucas/open-interpreter/blob/main/docs/MACOS.md

**Comment by Everminds** [comment]
I get the same error. Working on windows

**Comment by Everminds** [comment]
Also, I tried using Conda, still doesn't work

**Comment by Everminds** [comment]
Solved it, seems like my python version was set to 3.9

**Comment by cpeisert** [comment]
I found that I had multiple versions of pip installed:

```sh
$ which -a pip
/home/\<username>/.local/bin/pip
/home/\<username>/miniconda3/envs/py10/bin/pip
```

The simplest solution was to use the command:

```sh
python -m pip install open-interpreter
```

This ensures that the pip version associated with the active python version will be used.

**Comment by jordanbtucker** [comment]
Please see https://github.com/KillianLucas/open-interpreter/blob/main/docs/MACOS.md

**Comment by fengwuyun** [comment]
I got the same error on win10, while my python version is 3.10.6
`Python 版本信息:
3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]`

The full error msg is:
`
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Pytuires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python 
>=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python 
>=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter`

**Comment by fengwuyun** [comment]
I got the same error on win10, while my python version is 3.10.6
`Python Version:
3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]`

The full error msg is:
![image](https://github.com/KillianLucas/open-interpreter/assets/36253054/d860bac1-8839-46b4-953d-17381cd9a8db)

**Comment by jordanbtucker** [comment]
@fengwuyun Please try @cpeisert's solution or confirm that you've tried it.

https://github.com/KillianLucas/open-interpreter/issues/233#issuecomment-1712908300

**Comment by fengwuyun** [comment]
> 
Still doesn't work
![image](https://github.com/KillianLucas/open-interpreter/assets/36253054/35ca94fa-f954-47c0-b1b3-ab0e4d409f29)

**Comment by fengwuyun** [comment]
Still not work @jordanbtucker 
![image](https://github.com/KillianLucas/open-interpreter/assets/36253054/78e23cf7-8e8d-457a-842e-a4e313246e9a)

**Comment by ihgalis** [comment]
> Still not work @jordanbtucker ![image](https://user-images.githubusercontent.com/36253054/266912920-78e23cf7-8e8d-457a-842e-a4e313246e9a.png)

You could try it with python3 instead of python and see which python version is used:

`python --version`

If it is not at least 3.10 it will not work as stated in your error message.

I would recommend using a virtualenvironment. Miniconda is my favorite, since it is easy to use on all platforms including Windows: https://docs.conda.io/projects/miniconda/en/latest/

`conda create -n openinterpret python=3.11.4`
`conda activate openinterpret`
`pip install open-interpreter`

**Comment by Metnt** [comment]
![blob](https://github.com/KillianLucas/open-interpreter/assets/145179725/108edfd5-57f8-4e80-994e-5a19495105d2)

**Comment by Metnt** [comment]
![blob](https://github.com/KillianLucas/open-interpreter/assets/145179725/41b952fd-17bb-4fd4-8db3-21c7f775e05e)
