### ISSUE TITLE
400 Bad Request when trying to get Open Procedures recommendation

### ISSUE THREAD

**Issue by ifsheldon** [KillianLucas/open-interpreter#236]
**Describe the bug**

The code in this line seems not to function correctly. https://github.com/KillianLucas/open-interpreter/blob/4404c4baa4f0abe6325a50b82acfbc6226cd540c/interpreter/interpreter.py#L144

It always gets 400 from the Open Procedures server. I guess you have made the request in a wrong HTTP format? since the your example to query open procedures is 

```
import requests
query = 'How to reverse a string in Python?'
response = requests.get('https://open-procedures.replit.app/search/', params={'query': query})
print(response.json())
```

**To Reproduce**

You can modify the code as below and try to debug locally to see what's going on. 

<img width="1190" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/39153080/3cd09301-32b3-4524-8f3e-bfed6337a03c">

```python
      try:
        relevant_procedures = requests.get(url, data=json.dumps(query))
        relevant_procedures = relevant_procedures.json()["procedures"]
        info += "\n\n# Recommended Procedures\n" + "\n---\n".join(relevant_procedures) + "\nIn your plan, include steps and, if present, **EXACT CODE SNIPPETS** (especially for depracation notices, **WRITE THEM INTO YOUR PLAN -- underneath each numbered step** as they will VANISH once you execute your first line of code, so WRITE THEM DOWN NOW if you need them) from the above procedures if they are relevant to the task. Again, include **VERBATIM CODE SNIPPETS** from the procedures above if they are relevent to the task **directly in your plan.**"
      except Exception as e:
        # For someone, this failed for a super secure SSL reason.
        # Since it's not stricly necessary, let's worry about that another day. Should probably log this somehow though.
        print("Ooops, failed to fetch procedures.")
        print(e)
        pass
```

**Expected behavior**
Correctly fetch code snippet recommendations.

**Screenshots**
The error is JSON parsing error but it's due to 400 Bad Request essentially.
<img width="737" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/39153080/552b38e8-5f88-4794-9fd8-ccacd8c03442">

**System (please complete the following information):**
 - OS: MacOS
 - Python version 3.10
 - Open Interpreter version (`pip show open-interpreter`): master/HEAD

**Additional context**

**Comment by kazuhiro4949** [comment]
I found the same issue. RAG with embedding is not working at all...

**Comment by ericrallen** [comment]
Hey there!

Do you see the same issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Hey there, @ifsheldon and @kazuhiro4949!

I'm going to close this one as the call to `https://open-procedures.replit.app/` was removed in more recent versions of Open Interpreter.
