### ISSUE TITLE
Failed. Are you sure there are GGUF files in `tiiuae/falcon-180B`?

### ISSUE THREAD

**Issue by DanWahlin** [KillianLucas/open-interpreter#246]
**Issue**

I'm trying to run:

- `interpreter --model tiiuae/falcon-180B` on my MacBook Pro (Intel chip)

That gave an error but I realized I wasn't logged into huggingface so did the following:

- Go to https://huggingface.co/tiiuae/falcon-180B, login, and click the button to accept the gated model.
- `pip install transformers`
- `huggingface-cli <your-hf-token>`

Ran `interpreter --model tiiuae/falcon-180B` again but now get:

```
Open Interpreter will use tiiuae/falcon-180B for local execution. Use your arrow keys to set up the model.              

Failed. Are you sure there are GGUF files in `tiiuae/falcon-180B`?
```

**To Reproduce**
1. Login using the huggingface-cli
2. Run `interpreter --model tiiuae/falcon-180B`

**Expected behavior**
Expected the model to be retrieved and then run locally. However, since no additional instructions about using the model are in the readme I might be missing something simple (I hope :-)).

**System (please complete the following information):**
 - OS: MacOS Ventura (Intel chip)
 - Python 3.11.5
 - Open Interpreter version: 0.1.2

**Comment by jadedgnome** [comment]
GGUF files can be found here https://huggingface.co/TheBloke/Falcon-180B-Chat-GGUF

**Comment by DanWahlin** [comment]
Thanks. Since this error is occurring when running Open Interpreter, is there something else I need to do to get it to use these?

**Comment by gleicon** [comment]
Try running $ interpreter --model TheBloke/falcon-180B-Chat-GGUF instead of the model at tiiuae/falcon-180B - The last one has the ggml files already

**Comment by DanWahlin** [comment]
That fixes it - thanks @gleicon!

**Comment by gleicon** [comment]
You are welcome. I've created a [short gist with all steps I took in case someone needs](https://gist.github.com/gleicon/535add68e7d4c9d25c4081474b20bf14 )

**Comment by DanWahlin** [comment]
Nice - great idea! I saw a few people on X that ran into issues that these steps will help them solve.
