### ISSUE TITLE
Problems with java development

### ISSUE THREAD

**Issue by jwlioahd** [KillianLucas/open-interpreter#250]
I have seen this project written in Python, JavaScript, and shell. Are there any examples written in java?

**Comment by jordanbtucker** [comment]
If you're asking whether Open Interpreter should be able to provide you with Java code, then yes. If you're asking about this project being implemented in Java, the only official version of this project is currently written in Python and hosted in this repo.

**Comment by ericrallen** [comment]
Going to close this as Java isn't a currently supported language in Open Interpreter.

Feel encouraged to reopen it if you'd like to explore adding Java as a supported language.

As @jordanbtucker mentioned, you should be able to generate Java code, but Open Interpreter will be unable to execute it until someone creates a [code interpreter language configuration](https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/code_interpreters/language_map.py) for it.
