### ISSUE TITLE
Any plans on saving the generated scripts to files ?

### ISSUE THREAD

**Issue by KitoKotowa** [KillianLucas/open-interpreter#26]
It can be pretty convenient to watch the code saved on a file, rather than seeing the generated code in the terminal

**Comment by KillianLucas** [comment]
Hey @KitoKotowa. For sure! The [desktop app](https://openinterpreter.com/) will let you export all the non-erroring code blocks in a chat session as a `.py` or `.ipynb`.

Perhaps we can implement this in the CLI first if enough folks want it. We're thinking of making some magic commands that control the interpreter from within the chat. Commands would start with `%`. 

We could make it so `%export` or `%export script.py` exports all the non-erroring code blocks into the current directory. What do you think?

**Comment by KitoKotowa** [comment]
That seems to be a good one, @KillianLucas.  Although if you want to export to ipynb, the interpreter needs to be able to seperate markdown and python codes, so export to .py files only is a good start

**Comment by djmango** [comment]
> Hey @KitoKotowa. For sure! The [desktop app](https://openinterpreter.com/) will let you export all the non-erroring code blocks in a chat session as a `.py` or `.ipynb`.
> 
> Perhaps we can implement this in the CLI first if enough folks want it. We're thinking of making some magic commands that control the interpreter from within the chat. Commands would start with `%`.
> 
> We could make it so `%export` or `%export script.py` exports all the non-erroring code blocks into the current directory. What do you think?

Any word on that desktop app? Would love the ability to pick up and resume data analysis sessions (currently working with Jupyter + Interpreter + saving sessions, a bit archaic!)

**Comment by jacksongoode** [comment]
I think saving the code snippets in the CLI would be a very good feature!
