### ISSUE TITLE
Can I set up a network proxy？

### ISSUE THREAD

**Issue by xggz** [KillianLucas/open-interpreter#261]
My network cannot directly access openai.

**Comment by ishaan-jaff** [comment]
yes, you set litellm.api_base or os.environ['OPENAI_API_BASE'] and all your requests will be sent to the proxy :

https://docs.litellm.ai/docs/providers/openai#using-openai-proxy-with-litellm

**Comment by ishaan-jaff** [comment]
@xggz let me know if that worked for you

**Comment by jordanbtucker** [comment]
Thanks for the workaround @ishaan-jaff !

Although I think Open Interpreter should probably honor the system proxy settings if set.

**Comment by codeacme17** [comment]
I think open interpreter can make a --proxy param @jordanbtucker

**Comment by xggz** [comment]
I added the environment variable OPENAI_ API_ BASE has no effect, but OPENAI_ API_ KEY can take effect.

**Comment by xggz** [comment]
> @xggz let me know if that worked for you

I added the environment variable OPENAI_API_BASE has no effect, but OPENAI_API_KEY can take effect.

**Comment by ericrallen** [comment]
Going to close this one as I believe it’s been implemented via LiteLLM.

Feel free to reopen if that isn’t the case and the issue is still present in the latest version.
