### ISSUE TITLE
About run pip install something by interpreter

### ISSUE THREAD

**Issue by Hanochhu** [KillianLucas/open-interpreter#272]
### Describe the bug

**the interpreter can't run instruction like pip install ...** but I have seen others did that

### Reproduce

1.tpye "analyze temp.xlsx and draw picture "
2.when it run "pip install matplotlib"

### Expected behavior

interpreter run "pip install something" directly without my typing

### Screenshots

<img width="1050" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/52187558/49ec8d2a-3f29-4952-8d7b-25c1f1e3cc64">

### Open Interpreter version

0.1.1

### Python version

3.11.4

### Operating System name and version

macOS13

**Comment by TanmayDoesAI** [comment]
please update to the newer version, using `pip install -U open-interpreter` the prompt file was changed in the update, it should be fixed by that!

**Comment by cppong1117** [comment]
i try to update   but still can  not auto setup the pip

**Comment by Hanochhu** [comment]
> please update to the newer version, using `pip install -U open-interpreter` the prompt file was changed in the update, it should be fixed by that!

have upadated to 0.1.3 but still can't

**Comment by movitecc** [comment]
I alse met this issue, manjaro linux, OI 0.1.3 version.

**Comment by jordanbtucker** [comment]
Seems like the model thinks you're in a Jupyter Notebook because of the `!`. You can try telling it you're not in one and see how it responds. Unfortunately, the local models aren't as smart as GPT yet.

**Comment by Hanochhu** [comment]
> Seems like the model thinks you're in a Jupyter Notebook because of the `!`. You can try telling it you're not in one and see how it responds. Unfortunately, the local models aren't as smart as GPT yet.

I'm using gpt3.5 api as the base model of interpreter, I think it's most accessible and powerful api for most people. And it should have capacity to give right instructions, I tried in chatgpt web. 

 And I noticed that you had put a sentence in system_message  **Never use (!) when running commands.**
Why did't work by the way

**Comment by jordanbtucker** [comment]
I don't think that message is clear enough. Probably it needs a negative example, like:

Do not prefix commands with "!". For example, don't provide the command `!pip install`, instead provide the command `pip install`.

**Comment by ericrallen** [comment]
I'm going to close this one as completed as I believe the current code has extra safeguards to strip the `!` from the `!pip install` command in case the model tries to call pip like it's in a Jupyter notebook.

Please reopen if you still experience the issue.
