### ISSUE TITLE
Ability to Send Chars to the Underlying Shell

### ISSUE THREAD

**Issue by totalhack** [KillianLucas/open-interpreter#274]
### Is your feature request related to a problem? Please describe.

If the AI runs a command (like `npm init astro`) that has some prompts for configuring the project, open-interpreter currently hangs and has no way to send an answer to the underlying shell. You can press Ctrl+C which gives you an opportunity to retry or pass params to skip prompts but that's not always an option.

### Describe the solution you'd like

Some way to answer prompts in underlying shells would be great.

### Describe alternatives you've considered

Ctrl+C and adjusting the prompt as described above, which would be a valid workaround in some cases but happens to not be in mine.

**Comment by totalhack** [comment]
On a related note, one thing open-interpreter tries to recommend in these situations if you Ctrl+C and tell it what's going wrong is to pipe characters into the command, such as piping "yes" into the command. This somehow seems to have caused an infinite loop of retries which I had to keyboard interrupt to get out of. You may want to add at least a small delay between any command retries as a safety net.

**Comment by moming2k** [comment]
I faced the same problem when the OI created a react project for me, but during the initialization, npm asked me for some additional information, and I could not pass it to the shell, so I got stuck there.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
