### ISSUE TITLE
Interpreter Can't Execute Pip Running Under Windows/Anaconda Desktop

### ISSUE THREAD

**Issue by bakertn** [KillianLucas/open-interpreter#276]
### Describe the bug

This happens for any request I make that requires any package installation.
Windows, Anaconda Desktop, Dedicated Environment created within Anaconda
Running Anaconda Desktop as Admin
I checked and the python appears to be running as "me" the admin as you would expect.
I have run out of ideas.  Any suggestions as to how to enable the Interpreter to execute pip on Window/Anaconda Desktop/Env?

**Interaction that demonstrates the problem.** 

Request:
C:/Users/lbake/Downloads/sample_invoice.png  look at this file and tell me what kind of document this is. 

import magic

mime = magic.Magic(mime=True)
mime.from_file('C:/Users/lbake/Downloads/sample_invoice.png')

Would you like to run this code? (y/n)

y

File "<stdin>", line 4, in <module>
ModuleNotFoundError: No module named 'magic'

It seems that the magic module is not installed on your machine. This module is used to determine the file type based on its
content.

To proceed, I will need to install the python-magic package. May I proceed with the installation?

To proceed, I will need to install the python-magic package. May I proceed with the installation?

y

!pip install python-magic

Would you like to run this code? (y/n)

y

  !pip install python-magic

  Traceback (most recent call last):
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 177, in run
      code = self.add_active_line_prints(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 268, in
  add_active_line_prints
      return add_active_line_prints_to_python(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 430, in
  add_active_line_prints_to_python
      tree = ast.parse(code)
             ^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\ast.py", line 50, in parse
      return compile(source, filename, mode, flags,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<unknown>", line 1
      !pip install python-magic
      ^
  SyntaxError: invalid syntax

  I apologize for the inconvenience. It seems that I cannot directly install packages using the !pip command in this environment.

  To proceed, please manually install the python-magic package by running the following command in your terminal or command prompt:

   pip install python-magic

  Once the package is installed, please let me know so that I can continue with the file analysis.

>

### Reproduce

Ask the interpreter to do anything that requires a pip install.
interpreter will attempt and then fail.

### Expected behavior

Expect it to install the files and not quit. 

### Open Interpreter version

0.1.3

### Python version

3.11.3

### Operating System name and version

Windows  - Version	10.0.19045 Build 19045

### Additional context

Anaconda Desktop, dedicated environment created for Interpreter.

**Comment by TheWhiteWord** [comment]
From what I gathered from this video that just come out from 1littlecoder ( https://youtu.be/01tQLn_RRcE ), dependencies are a bit of an issue if they are all not set correctly, and also he mentions that pip3 should be the correct command. But I may be wrong. Worthe the wath anyhow IMO, its 5mn

**Comment by jordanbtucker** [comment]
This is a problem with how the model is responding. It thinks you're in a Jupyter Notebook, which is why it's adding the `!` to the command. Try telling it you're not in a notebook and see if it can fix it.

**Comment by bakertn** [comment]
I don't recall seeing a flag of that nature.  So you are suggesting I fork the code and fix it.  Or is there some extended configuration settings I am not aware of.

**Comment by bakertn** [comment]
I also went over to a new Mac I have and installed Anaconda Navigator, created a new environment and set it up again.  Same general result, only worse.  It does not apologize and ask you to install it yourself, it just quits.  

So it appears that this would qualify as a bug to be fixed as it's across at least 2 platforms.

**Comment by bakertn** [comment]
I tried Jordan's suggestion and informed the interpreter where is was.  This was the result.  Amusing.  Ended up in the same place but a good try.   Still used !pip regardless of it's awareness and my warning. 


> look at this file and tell me what kind of document you think it is.   I am running you in Anaconda Navigator, in a dedicated enviroment.  You are NOT in a notebook so be careful you execute your command properly with the correct syntax according to this environment.     File: C:/Users/lbake/Downloads/sample_invoice.png

  To determine the type of document, we can use an image recognition model to analyze the contents of the file. I will use the Python programming language to execute the necessary code.
  Please give me a moment to write the code and execute it in your Anaconda Navigator environment.



  import cv2
  import pytesseract

  # Load the image
  image_path = 'C:/Users/lbake/Downloads/sample_invoice.png'
  image = cv2.imread(image_path)

  # Convert the image to grayscale
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Use Tesseract OCR to extract text from the image
  text = pytesseract.image_to_string(gray_image)

  # Print the extracted text
  print(text)


  Would you like to run this code? (y/n)

  y


  import cv2
  import pytesseract

  # Load the image
  image_path = 'C:/Users/lbake/Downloads/sample_invoice.png'
  image = cv2.imread(image_path)

  # Convert the image to grayscale
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Use Tesseract OCR to extract text from the image
  text = pytesseract.image_to_string(gray_image)

  # Print the extracted text
  print(text)


  File "<stdin>", line 4, in <module>
  ModuleNotFoundError: No module named 'cv2'


  It seems that the OpenCV library (cv2) is not installed in your Anaconda Navigator environment. To proceed with the image analysis, we need to install the necessary packages. Please
  give me a moment to install the required packages.



  !pip install opencv-python pytesseract


  Would you like to run this code? (y/n)

  y


  !pip install opencv-python pytesseract


  Traceback (most recent call last):
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 177, in run
      code = self.add_active_line_prints(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 268, in add_active_line_prints
      return add_active_line_prints_to_python(code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\site-packages\interpreter\code_interpreter.py", line 430, in add_active_line_prints_to_python
      tree = ast.parse(code)
             ^^^^^^^^^^^^^^^
    File "C:\Users\lbake\anaconda3\envs\CodeInterpreter\Lib\ast.py", line 50, in parse
      return compile(source, filename, mode, flags,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<unknown>", line 1
      !pip install opencv-python pytesseract
      ^
  SyntaxError: invalid syntax



  I apologize for the inconvenience. It seems that I cannot directly execute the installation command in this environment. However, you can manually install the required packages by
  following these steps:

   1 Open the Anaconda Navigator.
   2 Select your dedicated environment.
   3 Click on the "Environments" tab.
   4 Search for "opencv-python" and "pytesseract" in the package list.
   5 Check the boxes next to the packages.
   6 Click on the "Apply" button to install the packages.

  Once the packages are installed, please let me know, and I will provide you with the code to analyze the image and determine the document type.

**Comment by jordanbtucker** [comment]
Unfortunately, I'm not sure there's a way we can fix this right now. The local models are no where near as powerful as GPT-3.5/4.

We could try adding something to the "system message", but if you telling it directly that's not in a notebook didn't work, then I'm not sure if changing the system message will really help.

**Comment by bakertn** [comment]
I don’t understand your reply.  My implementation is interpreter –fast which is using GPT-3.5/4 as the LLM.  The issue, that I described in great detail, is when you ask the interpreter to do anything which requires any kind of install it blows up.  The other note is that running under Anaconda is the preferred, best practices methodology of running python as it keeps the myriad installs, libraries and such neatly compartmentalized as separate from one another, each in its own pristine environment.  So the fact that interpreter, running in fast mode, cannot execute PIP basically kneecaps the entire project as currently it is useless in its present form.   As I tried it on both Window Anaconda Navigator and Mac Anaconda Navigator and got basically the same results, the question is, what platform does this run unattended on currently.  Linux?   If so you are 1 of three on major platforms. 

So again, not sure where the local model comments is sourcing from as running a local LLM is problematic at best due to computing restrictions on a local machine.   For the record I have a very powerful gaming PC with a recent Nvidia card.  Running a LLM on that (I tried several) is a pretty underwhelming experience.  Just not enough horsepower.  😊   So for this Bug Report that (running local LLMs) was never part to the experiment/use case to begin with.

**Comment by jordanbtucker** [comment]
Probably the system message needs to be clearer with a negative example, like:

Do not prefix commands with "!". For example, don't provide the command `!pip install`, instead provide the command `pip install`.

I will look into testing and creating a PR for that.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
