### ISSUE TITLE
Fix for this in certain cases https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md

### ISSUE THREAD

**Issue by iller75** [KillianLucas/open-interpreter#285]
### Describe the bug

I tried this https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md but it didn't work. However i did some googling and found that you can use this instead x64 Native Tools Command Prompt for VS 2022 and that fixed it for me. 

### Reproduce

N/A

### Expected behavior

for it to work :D

### Open Interpreter version

0.1.3

### Python version

3.10

### Operating System name and version

windows 11

**Comment by jordanbtucker** [comment]
Nice find!

**Comment by jordanbtucker** [comment]
Fixed by #287
