### ISSUE TITLE
I have Python 3.11 but can not install

### ISSUE THREAD

**Issue by tinteth** [KillianLucas/open-interpreter#286]
### Describe the bug

Error getting that I can not install because I do not have correct python version (Requires-Python >=3.10,<4.0;)

Which I have python 3.11 but still says I can not download

### Reproduce

-Updated python to appropriate version and add it to path
-Run terminal command to install interpreter
-Get error

### Expected behavior

download intepreter

### Open Interpreter version

N/A

### Python version

3.11.5

### Operating System name and version

MacOS

**Comment by jordanbtucker** [comment]
Without the actual error, it's very hard to troubleshoot this issue. Can you please post the error message you are getting.

**Comment by tinteth** [comment]
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Python >=3.10,<4.0; 0.0.223 Requires-Python >=3.10,<4.0; 0.0.224 Requires-Python >=3.10,<4.0; 0.0.225 Requires-Python >=3.10,<4.0; 0.0.226 Requires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python >=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

**Comment by jordanbtucker** [comment]
Thanks. Please run the following commands, and report what they return.

```
which python
which pip
```

**Comment by smytjf11** [comment]
This is mine:

```
me@ubuntu:~/Documents/open-interpreter$ which pip
/home/me/.local/bin/pip
me@ubuntu:~/Documents/open-interpreter$ which python
/usr/bin/python
```
I resolved that error by making sure I had python3 installed. Make sure you use pip3 instead of pip if your setup is anything like mine.

**Comment by tinteth** [comment]
Thanks @smytjf11 I had to use pip3.

**Comment by JJery-web** [comment]
I have

***
3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0)

where python=3.11.1. But I get the same error information like 'Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0'

**Comment by JJery-web** [comment]
> 

ERROR: Could not find a version that satisfies the requirement interpreter (from versions: none)
ERROR: No matching distribution found for interpreter

**Comment by tinteth** [comment]
make sure to use pip3 instead of pip
