### ISSUE TITLE
How to interact with local dataset?

### ISSUE THREAD

**Issue by ltzmaxwell** [KillianLucas/open-interpreter#29]
Hi, 
    Will that be any tutorial on how to use this to interact with local datasets, xls, database, etc? 
    Thank you!

**Comment by KillianLucas** [comment]
Hey @eltociear! We should make a tutorial, you're right. I'll film some next weekend.

In the meantime, you should be able to run `interpreter` and just ask it to use that data / where to find it. I usually use my desktop:

**Step 1:** Drag `dataset.csv` onto your desktop

**Step 2:** Open Terminal and type:

```
$: interpreter -y
> Hey, can you plot dataset.csv (it's on my desktop) and run some basic analysis on it?
Sure, first we'll open `dataset.csv` on your Desktop...
```

Something like that.
