### ISSUE TITLE
No matching distribution found for open-interpreter

### ISSUE THREAD

**Issue by zhenhuamo** [KillianLucas/open-interpreter#290]
### Describe the bug

pip install  open-interpreter
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

### Reproduce

pip install  open-interpreter

ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

### Expected behavior

I want to successfully install

### Open Interpreter version

pip open-interpreter

### Python version

python 3.8

### Operating System name and version

window 11

**Comment by mak448a** [comment]
Try upgrading your python version to 3.11.

**Comment by eliasrob** [comment]
i upgraded my python to 3.11 and still got the same error actually

**Comment by mak448a** [comment]
I have no idea what's causing it then. Can you post the error?

**Comment by nlake44** [comment]
I get the same problem:
nchohan open-interpreter % sudo pip install open-interpreter
WARNING: The directory '/Users/nchohan/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Python >=3.10,<4.0; 0.0.223 Requires-Python >=3.10,<4.0; 0.0.224 Requires-Python >=3.10,<4.0; 0.0.225 Requires-Python >=3.10,<4.0; 0.0.226 Requires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python >=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0; 0.1.4 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
nchohan open-interpreter % python --version
Python 3.11.5

**Comment by eliasrob** [comment]
Actually, I was trying to pip install open interpreter on my venv,
if I install it directly without any virtual environment setup , it works.

**Comment by tranhoangnguyen03** [comment]
I'm having the same issue when trying to deploy my streamlit app on streamlit cloud
![image](https://github.com/KillianLucas/open-interpreter/assets/31383641/2b29c703-8bfc-4bcf-adb2-31935eeac946)

**Comment by ericrallen** [comment]
@tranhoangnguyen03 Is your Streamlit app using Python 3.10 or 3.11?
