### ISSUE TITLE
Configurable model directory

### ISSUE THREAD

**Issue by JJery-web** [KillianLucas/open-interpreter#294]
### Is your feature request related to a problem? Please describe.

How can I change the path to the model download, please? My C disk has no more space :(?

### Describe the solution you'd like

Maybe I can use other paths to save the model?

**Comment by JJery-web** [comment]
> I have same issue on linux. Models will be downloaded into `~/.local/share/Open Interpreter/models/`. My workaround is to mv this models dir to my storage disk, and create a symlink back.

May I ask if you downloaded the model before using it? Because the disk space was already full halfway through my download.

**Comment by JJery-web** [comment]
It asks me whether I want to download it to 'c:\Users\85415\AppData\Local\Open Interpreter\Open Interpreter models'?"
I reply with 'n', and the download process ends.

I believe there might be other ways to deal with this.

**Comment by tonypius** [comment]
Another work around that worked for me is to add more paths to "directories_to_check" variable in the "/interpreter/get_hf_llm.py" file.

**Comment by 7415647** [comment]
> Another work around that worked for me is to add more paths to "directories_to_check" variable in the "/interpreter/get_hf_llm.py" file.

I have the same proplem. Could you show me screenshot about your variable "directories_to_check" in get_hf_llm.py. I have tried but not successed. Hope you can show me the correct variable. Thanks a lot.

**Comment by mferris77** [comment]
I was able to make the change pretty easily.  Find the 'get_hf_llm.py' file, edit it, and you'll find 'default_path' somewhere around line 92.  In my screenshot I commented out the original line which is pointing to my user data directory (c:\users\user\AppData... on Windows).  The '#' comments out that line. Be mindful that there should be 4 spaces starting each line.  Then I added a new line pointing to where I want the default folder to point to - in my case a folder I've created specifically for open interpreter.
![image](https://github.com/KillianLucas/open-interpreter/assets/16640236/66f1bc82-412e-4b19-aa38-381bb87fdc7f)

FYI I used conda to install open interpreter, so it took some digging to find the files, which were in (anaconda install location)\envs\open_interpreter\Lib\site-packages\interpreter.  Note that I named the conda environment 'open_interpreter', so whatever environment name you used will be the folder name in the 'envs' folder.

**Comment by 7415647** [comment]
i have tried but not work.

> I was able to make the change pretty easily. Find the 'get_hf_llm.py' file, edit it, and you'll find 'default_path' somewhere around line 92. In my screenshot I commented out the original line which is pointing to my user data directory (c:\users\user\AppData... on Windows). The '#' comments out that line. Be mindful that there should be 4 spaces starting each line. Then I added a new line pointing to where I want the default folder to point to - in my case a folder I've created specifically for open interpreter. ![image](https://user-images.githubusercontent.com/16640236/267367837-66f1bc82-412e-4b19-aa38-381bb87fdc7f.png)
> 
> FYI I used conda to install open interpreter, so it took some digging to find the files, which were in (anaconda install location)\envs\open_interpreter\Lib\site-packages\interpreter. Note that I named the conda environment 'open_interpreter', so whatever environment name you used will be the folder name in the 'envs' folder.
> 
> Note: Came back to add a note that I also had to modify a couple more lines - around line 125 you'll see two calls to a function named 'hf_hub_download'. One of the arguments is 'local_dir=default_path', which is fine as you will have updated that path in the steps above. However it seems this function first downloads to a temporary folder, which again defaults to your user directory. I added 'cache_dir=default_path' as an additional argument to this function and now I can download the models to my custom file location without issue.

i have tried but not work. I have reinstalled the open interpreter and then modified the file and saved. Totally i have just modified two codes in file "get_hf_llm.py".
1. 
![图片](https://github.com/KillianLucas/open-interpreter/assets/6607700/0e5d883c-760e-46a8-b3b2-d045de85a525)
2.
![图片](https://github.com/KillianLucas/open-interpreter/assets/6607700/92239dcc-647f-40a9-acc5-1b54ce586868)
Finally when i tried to download the model the path is not changed as before.
![图片](https://github.com/KillianLucas/open-interpreter/assets/6607700/b9125a20-a339-458f-85f9-a97af7388384)

I have no idea and hope somebody can help.

**Comment by ReddZhu** [comment]
@7415647 it works for me. If you don't mind, may I ask if you have saved the changes successfully?  Permission for writing is required for changing the file.

BTW here is my file:
![image](https://github.com/KillianLucas/open-interpreter/assets/20872011/36a4c280-31d0-4267-acf2-18df10217e6d)

**Comment by tonypius** [comment]
> Another work around that worked for me is to add more paths to "directories_to_check" variable in the "/interpreter/get_hf_llm.py" file.

This is the screenshot of the place where I added the new directories with the models.
<img width="694" alt="Screenshot 2023-09-13 at 12 37 55 PM" src="https://github.com/KillianLucas/open-interpreter/assets/3880829/65fa0f65-0973-4b2d-b122-db417c549844">

**Comment by 7415647** [comment]
> 

Finally i successed. 

Previously I modified the another file with same file name. I used Python to install open-interpreter. When i git clone the open-interpreter from github then there are two files with file name "get_hf_llm.py" in my PC. One is in file "open-interpreter\interpreter" ane the other is in "Python3.11.5\Lib\site-packages\interpreter". The correct file to modify is the latter one. And as [mferris77] said i modified the code and successed. Here is the screenshot if anyone else has the same issue.

![1694595352610](https://github.com/KillianLucas/open-interpreter/assets/6607700/ac843822-9b61-442f-a1d8-4a7b3da3e936)
![1694595392224](https://github.com/KillianLucas/open-interpreter/assets/6607700/b10a3a36-6b40-4b61-a5d3-7e0e75ba2c8d)

**Comment by jordanbtucker** [comment]
There is no built-in way to accomplish this yet, but you can use symlinks to make Open Interpreter download to the path of your choosing.

**Comment by jpontanares** [comment]
Edit this file too =>  <python installation direcotry>\Lib\site-packages\interpreter\llm\setup_local_text_llm.py

change  the following lines accordingly

    # Get user data directory
    user_data_dir = appdirs.user_data_dir("Open Interpreter")
    #default_path = os.path.join(user_data_dir, "models")
    default_path = os.path.join( "D:/openai/", "models")


----

    # Define the directories to check
    directories_to_check = [
        "D:/openai/models",
        default_path,
        "llama.cpp/models/",
        os.path.expanduser("~") + "/llama.cpp/models/",
        "/"
    ]
![modelsdownload](https://github.com/KillianLucas/open-interpreter/assets/46335925/dc48d18d-e2e4-45ef-a163-7e92f85e060a)

**Comment by ericrallen** [comment]
I’m going to close this one for now as I believe LM Studio allows you to do this.

Please reopen it if I’m wrong.

**Comment by iopenet** [comment]
This is the main reason I moved the app to the trash-bin!
Many other apps allow you to place models in another driver/location.

**Comment by fl0wm0ti0n** [comment]
"There is no built-in way to accomplish this yet, but you can use symlinks to make Open Interpreter download to the path of your choosing."

sorry saying this, but choosing path for large files is a feature which is default to have in any modern app... this is insane...

"I’m going to close this one for now as I believe LM Studio allows you to do this."

you need to change code to make it possible.. sorry no thats not an "allows to do this"... -.-

**Comment by endolith** [comment]
> "I’m going to close this one for now as I believe LM Studio allows you to do this."
> 
> you need to change code to make it possible.. sorry no thats not an "allows to do this"... -.-

I've not verified this myself but AI says:

**No, LM Studio does allow changing the models directory.**

From its official docs and user reports: In the app, go to the "My Models" tab (often shown with a folder icon), where you can directly set or change the custom directory for downloaded models. This applies to where new models are saved when you download them via the built-in downloader.

The commenter is correct that Open Interpreter itself lacks a built-in configurable path (hence the symlink suggestion in issue #294), but when using models already in LM Studio (via its local server), you avoid OI's downloader entirely—no need to download via OI or hack its paths.

If you're running OI → LM Studio server, the storage choice is handled by LM Studio, which supports custom paths natively.

**Comment by endolith** [comment]
> "I’m going to close this one for now as I believe LM Studio allows you to do this."
> 
> you need to change code to make it possible.. sorry no thats not an "allows to do this"... -.-

I've not verified this myself but AI says:

**No, LM Studio does allow changing the models directory.**

From its official docs and user reports: In the app, go to the "My Models" tab (often shown with a folder icon), where you can directly set or change the custom directory for downloaded models. This applies to where new models are saved when you download them via the built-in downloader.

The commenter is correct that Open Interpreter itself lacks a built-in configurable path (hence the symlink suggestion in issue #294), but when using models already in LM Studio (via its local server), you avoid OI's downloader entirely—no need to download via OI or hack its paths.

If you're running OI → LM Studio server, the storage choice is handled by LM Studio, which supports custom paths natively.

**Comment by fl0wm0ti0n** [comment]
> > "I’m going to close this one for now as I believe LM Studio allows you to do this."
> > you need to change code to make it possible.. sorry no thats not an "allows to do this"... -.-
> 
> I've not verified this myself but AI says:
> 
> **No, LM Studio does allow changing the models directory.**
> 
> From its official docs and user reports: In the app, go to the "My Models" tab (often shown with a folder icon), where you can directly set or change the custom directory for downloaded models. This applies to where new models are saved when you download them via the built-in downloader.
> 
> The commenter is correct that Open Interpreter itself lacks a built-in configurable path (hence the symlink suggestion in issue [#294](https://github.com/openinterpreter/open-interpreter/issues/294)), but when using models already in LM Studio (via its local server), you avoid OI's downloader entirely—no need to download via OI or hack its paths.
> 
> If you're running OI → LM Studio server, the storage choice is handled by LM Studio, which supports custom paths natively.

thank you very much was searching a lot and didnt find it...
