### ISSUE TITLE
Failed to save openai api key by using "r setx OPENAI_API_KEY your_api_key" on win10

### ISSUE THREAD

**Issue by fengwuyun** [KillianLucas/open-interpreter#295]
### Describe the bug

I used `setx` to save my key succefully. However it said OpenAI api key was not found  when I restarted the interpreter.

### Reproduce

1 setx OPENAI_API_KEY my_openai_api_key
2 interpreter

### Expected behavior

OPENAI_API_KEY  should be found

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/36253054/f175a929-cc23-47d5-a63b-66acbb05f68c)

### Open Interpreter version

0.1.3

### Python version

3.11.4

### Operating System name and version

Windows10

**Comment by khakhasshi** [comment]
试试 interpreter -d

**Comment by RedwindA** [comment]
试试powershell

**Comment by jordanbtucker** [comment]
The command will be different based on what shell you are using.

**Windows Command Prompt**
```cmd
setx OPENAI_API_KEY your_api_key
```

**Windows PowerShell**
```powershell
[Environment]::SetEnvironmentVariable('OPENAI_API_KEY', 'your_api_key', 'User')
```

Windows environment variables can also be set by searching for **Edit environment variables for your account** in the Start menu.

For macOS, Linux, and other Unix-based shells, see https://unix.stackexchange.com/a/117470/88458
