### ISSUE TITLE
Can we consider adding a customized API

### ISSUE THREAD

**Issue by shenmadouyaowen** [KillianLucas/open-interpreter#296]
### Is your feature request related to a problem? Please describe.

Some models have different input formats, can we add custom API functionality

### Describe the solution you'd like

I use other API interfaces, but I cannot have them run the code

**Comment by Joackk** [comment]
Yes, I usually use third-party APIs, but it seems that I cannot customize the interface and can only use the official API interface. Can I add custom interface calls?

**Comment by Niche-Apps** [comment]
I would like to use other APIs as well, especially Poe since I already paid for it.

**Comment by ishaan-jaff** [comment]
I'm the maintainer of LiteLLM, o-i uses litellm for the LLM API calls. You can start calling your custom api endpoints like this:

## OpenAI ChatCompletion proxy:
```python
import os 
import litellm
from litellm import completion

os.environ["OPENAI_API_KEY"] = ""

# set custom api base to your proxy
# either set .env or litellm.api_base
# os.environ["OPENAI_API_BASE"] = ""
litellm.api_base = "https://openai-proxy.berriai.repl.co"


messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion("gpt-3.5-turbo", messages)
```
Docs: https://docs.litellm.ai/docs/providers/openai

## Custom LLM API endpoint: 
```python
from litellm import completion
response = completion(
    model="custom/meta-llama/Llama-2-13b-hf", 
    messages= [{"content": "what is custom llama?", "role": "user"}],
    temperature=0.2,
    max_tokens=10,
    api_base="https://api.autoai.dev/inference",
    request_timeout=300,
)
print("got response\n", response)
```
Docs: https://docs.litellm.ai/docs/providers/custom

**Comment by RedwindA** [comment]
> @shenmadouyaowen @Joackk @Niche-Apps please let me know if anything is missing from our support for this

Thanks for your support, but I'm a rookie, could you teach me directly how to set up the custom api_base and key in the windows command line to use o-i?

**Comment by ishaan-jaff** [comment]
i'm not sure if o-i allows you to set custom api_base, you might need to make the change in interpreter.py and then run it 

Happy to help on a discord chat if you'd like!

**Comment by Sagners** [comment]
It seem that we need do something in the  sourcecode, it seems simple

**Comment by Sagners** [comment]
<img width="485" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/53614951/4e165d73-24ed-4e59-8d13-2bea6c123038">

It seems that the groundwork was done

**Comment by RedwindA** [comment]
But it seems that it still cannot work on the API endpoint I created myself, possibly because my endpoint only provides chat completion

> <img alt="image" width="485" src="https://user-images.githubusercontent.com/53614951/267400461-4e165d73-24ed-4e59-8d13-2bea6c123038.png">
> It seems that the groundwork was done

**Comment by Joackk** [comment]
> I'm the maintainer of LiteLLM, o-i uses litellm for the LLM API calls. You can start calling your custom api endpoints like this:
> 
> ## OpenAI ChatCompletion proxy:
> ```python
> import os 
> import litellm
> from litellm import completion
> 
> os.environ["OPENAI_API_KEY"] = ""
> 
> # set custom api base to your proxy
> # either set .env or litellm.api_base
> # os.environ["OPENAI_API_BASE"] = ""
> litellm.api_base = "https://openai-proxy.berriai.repl.co"
> 
> 
> messages = [{ "content": "Hello, how are you?","role": "user"}]
> 
> # openai call
> response = completion("gpt-3.5-turbo", messages)
> ```
> 
> Docs: https://docs.litellm.ai/docs/providers/openai
> 
> ## Custom LLM API endpoint:
> ```python
> from litellm import completion
> response = completion(
>     model="custom/meta-llama/Llama-2-13b-hf", 
>     messages= [{"content": "what is custom llama?", "role": "user"}],
>     temperature=0.2,
>     max_tokens=10,
>     api_base="https://api.autoai.dev/inference",
>     request_timeout=300,
> )
> print("got response\n", response)
> ```
> 
> Docs: https://docs.litellm.ai/docs/providers/custom

 Do you want to modify the source code? Or create a new py script and write this content to call it yourself? Isn't the start of the interpreter called directly from the command line?

**Comment by Joackk** [comment]
> <img alt="image" width="485" src="https://user-images.githubusercontent.com/53614951/267400461-4e165d73-24ed-4e59-8d13-2bea6c123038.png">
> It seems that the groundwork was done

Are you ready to use the custom API?

**Comment by shenmadouyaowen** [comment]
@ishaan-jaff @Sagners Thank you. If the data returned by the custom API does not meet this judgment, the code will not be interpreted
![image](https://github.com/KillianLucas/open-interpreter/assets/12426724/89596571-9960-4b1c-b43d-aa6bb8075d81)

**Comment by ericrallen** [comment]
I’m going to close this one as it seems like it is covered by the LiteLLM integration.

Please reopen this issue if there’s still a problem.
