### ISSUE TITLE
Unable to run the interpreter on mac

### ISSUE THREAD

**Issue by saridsa1** [KillianLucas/open-interpreter#300]
### Describe the bug

Trying to run the interpreter on my local machine, but it gets stuck 

(gptinterviewer) satyasumansaridae@Satyas-MacBook-Pro GPTInterviewer % python
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import interpreter
>>> 

Nothing happens after this. 

### Reproduce

(gptinterviewer) satyasumansaridae@Satyas-MacBook-Pro GPTInterviewer % python
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import interpreter
>>> 

### Expected behavior

The interpreter should start

### Open Interpreter version

0.1.3

### Python version

Python 3.11.1

### Operating System name and version

MacOS 14.0 Beta (23A5337a)

### Additional context

Name: open-interpreter
Version: 0.1.3
Summary: Let language models run code locally.
Home-page:
Author: Killian Lucas
Author-email: killian@drinkwater.ai
License:
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: appdirs, astor, git-python, huggingface-hub, inquirer, litellm, openai, python-dotenv, rich, six, tiktoken, tokentrim, wget
Required-by:

**Comment by jordanbtucker** [comment]
Thanks for reporting. Did you run the following command to install interpreter:

```
python -m pip install open-interpreter
```

**Comment by ericrallen** [comment]
I’m going to close this one as stale.

It looks like you’re running Open Interpreter in the Python interpreter so you’ll need to invoke it following the [Python examples](https://github.com/KillianLucas/open-interpreter#python).

If you want to run it interactively, you’ll want to run `interpreter` in your terminal after installing `open-interpreter` via `pip`.
