### ISSUE TITLE
The code it generated repeated the same function call 20-30 times and used up $5 in a matter of minutes

### ISSUE THREAD

**Issue by nayan924** [KillianLucas/open-interpreter#303]
### Describe the bug

same line was written multiple times, I was pressing y and enter and didnt realise i executed a code with 20-30 calls to a gpt-4 summary of long text and it ate $5.

### Reproduce

I am not sure, but i did paste a code snippet along with instruction to guide it because it was making same mistake multiple times.

### Expected behavior

i wanted to recreate this https://platform.openai.com/docs/tutorials/meeting-minutes/creating-an-automated-meeting-minutes-generator-with-whisper-and-gpt-4

### Open Interpreter version

0.1.3

### Python version

3.11.4

### Operating System name and version

mac 12.5

**Comment by transcendr** [comment]
Not sure about your specific issue but just a tip, instead of pasting stuff to, just tell it to run `pbpaste` and get the text from your clipboard (or whatever the windows equivalent is if on windows)

**Comment by grexzen** [comment]
Where do you set the token limit per call?

**Comment by Videoteq** [comment]
> Where do you set the token limit per call?

Good ideas, but ideally OpenAI should have an enhanced useage limit settings per API key - so that one could set a limit on each API key generated. This would take the heat off OpenInterpreter and also would benefit all OpenAI users. Right now their udeage limits are pretty basic. Using interpreter I clocked up a couple of $ in seconds as it was so exiting! Now I use --fast to use the *much* cheaper GPT3.5-Turbo.

**Comment by jouky2** [comment]
umm, why are you paying?
[**https://github.com/xtekky/gpt4free**](https://github.com/xtekky/gpt4free)

**Comment by tbels89** [comment]
> umm, why are you paying? [**https://github.com/xtekky/gpt4free**](https://github.com/xtekky/gpt4free)

have you implemented this as a local model for use?

**Comment by ericrallen** [comment]
Hey there, @nayan924!

Can you clarify what you’re asking for from Open Interpeter here or can we close this Issue?

**Comment by ericrallen** [comment]
Going to close this one as stale.

Please feel encouraged to reopen it if you’d like to explain the ask here a bit and when we dig into it.
