### ISSUE TITLE
Gui / App interface like Incognito Pilot

### ISSUE THREAD

**Issue by menelic** [KillianLucas/open-interpreter#306]
### Is your feature request related to a problem? Please describe.

I am aware of #1  but would like to ask you to please have a look at https://github.com/silvanmelchior/IncognitoPilot as this seems to a great interface for the purposes and capabilities of open interpreter. 

### Describe the solution you'd like

Please consider adapting a similar UI - or even an Ui based on - https://github.com/silvanmelchior/IncognitoPilot. This would make it accessible to a broader user base

**Comment by ericrallen** [comment]
Thanks for the suggestion, @menelic!

We'll take this into consideration as we think about the desktop app.

I'm going to close this one for now to help reduce the noise in the repos Issues.
