### ISSUE TITLE
How to prompt

### ISSUE THREAD

**Issue by dantodor** [KillianLucas/open-interpreter#31]
Probably I'm doing something wrong, but this is the kind of dialogue I get at the moment:
```
Finished downloading `Code-Llama`.


▌ Model set to Code-Llama

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> please generate a plot of the evolution of S&P 500 over the last month

  please generate a plot of the evolution of S&P 500 over the last month

> write a Python program to analyze the performance of the S&P500 index over the last month

  write a Python program to analyze the performance of the S&P500 index over the last month

> what is 2**3 + 4**2 ?

  what is 23 + 42 ?
``` 

NB, running on Mac M2, with local CodeLLama.

Any hints where I'm wrong?

**Comment by fanweiya** [comment]
You can use codellama-7b.Q4_K_M.gguf to get a good result.

**Comment by multiade** [comment]
I agree, I have tried different codellama 7b and 13b models, they all do very poorly and nothing much can be done with the result :(
![Screenshot_20230904_135622](https://github.com/KillianLucas/open-interpreter/assets/138007899/34b626d3-713a-4652-a63c-02a3c87acdcf)

![Screenshot_20230904_140144](https://github.com/KillianLucas/open-interpreter/assets/138007899/089fde55-a8cd-4a40-94be-1b5009975178)

![Screenshot_20230904_140642](https://github.com/KillianLucas/open-interpreter/assets/138007899/98c7e43c-bab1-41d4-b320-891261782293)

**Comment by HexHands** [comment]
Is there anyway of specifically telling it to use code? Like when I ask it to use Python code it doesn't even make any for some reason.

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```

Unfortunately, running a 7B model is going to be a degraded experience at this early stage. Ensuring you are on the latest version of open-interpreter will help to a degree, but unless you run a 30B model on an RTX 3090 or 4090, you will not likely be able to get anything close to GPT-3.5, at least for now.

We are of course working on improving this.

**Comment by CorentinWicht** [comment]
Same issue here, I am trying the `codellama-7b-instruct.Q8_0.gguf` model (TheBloke) and the prompt keeps repeating itself, that's very weird and makes it completely unusable:

![image](https://github.com/KillianLucas/open-interpreter/assets/52161904/84a49e39-ca3d-4fdd-8596-6bfcff53133f)

Installation went smoothly and I ran `interpreter -y` when prompted so (i.e., _Open Interpreter will require approval before running code. Use interpreter -y to bypass this._).

@jordanbtucker any idea what's happening? 
Interpreter looks like a great tool by the way, thanks for your hard work.

**Comment by jordanbtucker** [comment]
@CorentinWicht Thanks for reporting. I've noticed the same thing with the 13B medium model. It's definitely something we're investigating.
