### ISSUE TITLE
Log of code created

### ISSUE THREAD

**Issue by iplayfast** [KillianLucas/open-interpreter#315]
### Is your feature request related to a problem? Please describe.

I did some work where it wrote code to scrape websites etc etc, and that worked fine. However, I wanted the code that it created to scrape the websites to be saved. When I requested that it saved the code it instead it saved only the last operation

### Describe the solution you'd like

I think it would be useful as an interim step to just have an option to log the whole session. Then at least you can review the code generated. 

The optimal solution would be to somehow trigger it to alway save the generated code with meaningful names.

**Comment by moming2k** [comment]
Would [interactive-mode-commands](https://github.com/KillianLucas/open-interpreter#interactive-mode-commands) partially help you review the conversation once the messages are exported in JSON?

**Comment by feherg** [comment]
> Would [interactive-mode-commands](https://github.com/KillianLucas/open-interpreter#interactive-mode-commands) partially help you review the conversation once the messages are exported in JSON?

Not OP, but I ran into the same issue. For me, open-interpreter froze shortly after I asked it to write the code to disk, so debugging was not an option. I think that writing a log file by default would be useful.

**Comment by MikeBirdTech** [comment]
Should be available in conversation history. Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
