### ISSUE TITLE
It Got Stuck After Pressing the Enter Key to Confirm the Execution of the Command

### ISSUE THREAD

**Issue by HoshiMeisa** [KillianLucas/open-interpreter#317]
### Describe the bug

It got stuck after pressing the Enter key. Unable to execute the generated command.

### Reproduce

It got stuck after pressing the Enter key. The issue persists even after switching to the GPT-4 model. 

![image](https://github.com/KillianLucas/open-interpreter/assets/116141481/6e06ca00-d705-46d8-8d99-3175b2489d2e)

---
And if it's started with `interpreter -y`, it will get stuck right there after generating the command.

![image](https://github.com/KillianLucas/open-interpreter/assets/116141481/340b0ee4-009e-4d15-aa03-5e33a02cbfae)

### Expected behavior

The generated command will be executed.

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

Linux Arch 6.1.52-1-lts

**Comment by dorianherle** [comment]
Same issue on Windows.

**Comment by davebrouwer1** [comment]
Same on debian based linux as well

**Comment by Ananderz** [comment]
I have the same issue unfortunately and it goes into a loop when it starts iterating the creation of a folder.

Might be the 7B model that is causing issues

**Comment by dorianherle** [comment]
I saw that if you use "Ctrl+c" often it deblocks the state and continues. (but sometimes also not, I have not yet recognized a pattern)

**Comment by ericrallen** [comment]
I’m going to close this one as stale, as I think some recent changes to how we handle token trimming might have fixed this issue.

Please reopen it or ping me if that’s not the case.

**Comment by endolith** [comment]
This started happening to me on Linux when installed using pipx.  I'm pretty sure commands worked in the past.  Running Python code still works.
