### ISSUE TITLE
How to disable SSL certificate verification in open-interpreter? 

### ISSUE THREAD

**Issue by sanjuadlakha** [KillianLucas/open-interpreter#318]
### Describe the bug

Getting SSL error CERTIFICATE_VERIFY_FAILED : unable to get local issuer certificate. How can one disable SSL certification verification in open-intepreter? I am running on windows 11 and behind corporate security. Just want to try out open-interpreter so asking. I understand its not safe. But there should be a way to disable the certification verification. 

### Reproduce

Asked interpreter to open a new chrome window

### Expected behavior

a new chrome window opens

### Open Interpreter version

0.1.3

### Python version

3.11.3

### Operating System name and version

Windows 11

**Comment by astelmach01** [comment]
Could try this (lasts until command prompt is closed)

```
set PYTHONHTTPSVERIFY=0
```

**Comment by sanjuadlakha** [comment]
Thankyou Andrew. It worked.
