### ISSUE TITLE
Azure service request denied

### ISSUE THREAD

**Issue by catundchat** [KillianLucas/open-interpreter#319]
### Describe the bug

After I provide valid key, endpoint(base), version and deployment name of azure openai service, it doesn't work.
```
openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.    
```

### Reproduce

1. input "interpreter --use-azure"
2. input azure api key, base, version and deployment name.
3. it says that "Model set to GPT-4"
4. then ask something the error occured.

### Expected behavior

it could return correct reply.

### Open Interpreter version

0.1.3

### Python version

3.10.6

### Operating System name and version

windows 10

**Comment by ericrallen** [comment]
Hey there, @catundchat!

Is thus still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or you expert the issue with the latest version of Open Interpreter.
