### ISSUE TITLE
Download starts without checking the free disk space

### ISSUE THREAD

**Issue by astares** [KillianLucas/open-interpreter#321]
### Describe the bug

If you run

```
$ pip install open-interpreter
$ interpreter
```
and request the download of the large Llama model the disk size is not checked
(I tried on an old Linux installation which had only 12 GB left, but model size is around 34 GB)

### Reproduce

- use a Linux system that has not much disk space left, one can check with "df -h")
- instruct open-interpreter to use the large parameter model (34B model) with 35.9 GB download

### Expected behavior

- check the remaining disk size **before** the download and warn the user

### Screenshots

-

### Open Interpreter version

0.1.3

### Python version

3.11.4

### Operating System name and version

Linux

### Additional context

-

**Comment by michaelzdrav** [comment]
[This](https://github.com/KillianLucas/open-interpreter/pull/323) should fix the issue. Feel free to clone and test locally with the steps in https://github.com/KillianLucas/open-interpreter/blob/main/docs/contributing.md

Worked for me.

**Comment by jordanbtucker** [comment]
Fix merged and will be in next release!
