### ISSUE TITLE
Fix hyperlinks to docs in 'Commonly faced issues and their solutions #164'

### ISSUE THREAD

**Issue by merlinfrombelgium** [KillianLucas/open-interpreter#328]
### Describe the bug

In #164 , there are two links to docs that have since been moved to the /docs folder. Links need to be updated.

### Reproduce

1. Go to #164 
2. Click on any of these 2 links:
> Instructions can be found in [Code-Llama on Windows](https://github.com/KillianLucas/open-interpreter/blob/main/WINDOWS.md)

> ... then kindly go through [Local Language Models with GPU Support](https://github.com/KillianLucas/open-interpreter/blob/main/GPU.md)
3. Cringe over the 404 😖

### Expected behavior

End up on the actual documentation pages.

- [docs/WINDOWS.md](https://github.com/KillianLucas/open-interpreter/blob/main/docs/WINDOWS.md)
- [docs/GPU.md](https://github.com/KillianLucas/open-interpreter/blob/main/docs/GPU.md)

### Open Interpreter version

n/a

### Python version

n/a

### Operating System name and version

n/a

**Comment by jordanbtucker** [comment]
I thought those already got fixed. Thanks for reporting!
