### ISSUE TITLE
Trid to run jupyter notebook with --model parameter for a local GGUF model.

### ISSUE THREAD

**Issue by tonypius** [KillianLucas/open-interpreter#329]
### Describe the bug

I tried to run a jupyter notebook and start interpreter.chat() with interpreter.model defined. This is the same as  --model parameter from the console. But i'm still getting the OPEN_AI key missing error since its looking for GPT-4 key.

### Reproduce

1. In a notebook. Run import interpreter
2. Then define interpreter.model=modelpath
3. Finally interpreter.chat() fails with api key error. 

### Expected behavior

Its supposed to spin up the local gguf model up and running right ?

### Open Interpreter version

0.1.2

### Python version

3.10

### Operating System name and version

Ubuntu 22

**Comment by ericrallen** [comment]
Hey there, @tonypius!

Is this still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
If this is a local model, you might also need to set local to true.

I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
