### ISSUE TITLE
Function call could not be parsed

### ISSUE THREAD

**Issue by marcocastignoli** [KillianLucas/open-interpreter#33]
<OpenAIObject at 0x1038e76b0> JSON: {
  "name": "python",
  "arguments": "import os\nimport requests\n\n# Create the \"cat\" folder in the
\"Downloads\" directory\ndownloads_path = 
os.path.expanduser(\"~/Downloads\")\ncat_folder_path = 
os.path.join(downloads_path, \"cat\")\nos.makedirs(cat_folder_path, 
exist_ok=True)\n\n# Download the image of a cat from a URL\nurl = 
\"https://images.unsplash.com/photo-1560807707-9b4f6b1f6bcb\"\nresponse = 
requests.get(url)\n\n# Save the image in the \"cat\" folder\nimage_path = 
os.path.join(cat_folder_path, \"cat_image.jpg\")\nwith open(image_path, \"wb\") 
as file:\n    file.write(response.content)\n\nimage_path"
}

**Comment by KillianLucas** [comment]
Hey @marcocastignoli, looks like it tried using "name" instead of "language" in the function call. Thanks for letting me know! If this tends to be how it fails / other folks report this, we could consider parsing "name" as "language" so this doesn't happen again.

Was it able to self-correct after this?

**Comment by dillfrescott** [comment]
Im having this issue with every command

**Comment by highkay** [comment]
I have the same issue

```
  Let's execute this plan step by step.



  Would you like to run this code? (y/n)

  y

> Function call could not be parsed.

Please open an issue on Github (openinterpreter.com, click Github) and paste the following:


<OpenAIObject at 0x10594b4d0> JSON: {
  "name": "python",
  "arguments": "# Step 1: Install the Elasticsearch Python client library\n!pip install elasticsearch"
}

```

**Comment by dillfrescott** [comment]
@highkay try the git version! `pip install git+https://github.com/KillianLucas/open-interpreter` you of course need git installed for it to work

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please make sure you are on the latest version of open-interpreter by running the following.

```
pip install --upgrade open-interpreter
```
