### ISSUE TITLE
The read operation timed out while downloading the models.

### ISSUE THREAD

**Issue by 7415647** [KillianLucas/open-interpreter#332]
### Describe the bug

When i downloading the models the issue will occur on 3% or 7% or other pecent. Then if i delete the cache file and redownload the models it will start at the begining 0%. Btw my download speed is about 100-500kb/s. Here is the diolog

### Reproduce

1.use windows powershell 
2.input "interpreter" and start the diolog as screenshot
3.begin download the code-llama
4.a few dozen minutes later the error will show

### Expected behavior

Hope the Code-Llama will be downloaded successly

### Screenshots

Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▌ OpenAI API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.

To use Code-Llama (free but less capable) press enter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OpenAI API key:

▌ Switching to Code-Llama...

Tip: Run interpreter --local to automatically use Code-Llama.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 34B
   7B
   13B
 > 34B

[?] Quality (smaller is faster, larger is more capable): Large | Size: 33.4 GB, Estimated RAM usage: 35.9 GB
   Small | Size: 13.2 GB, Estimated RAM usage: 15.7 GB
   Medium | Size: 18.8 GB, Estimated RAM usage: 21.3 GB
 > Large | Size: 33.4 GB, Estimated RAM usage: 35.9 GB
   See More

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): y

This language model was not found on your system.

Download to `D:/Open_Interpreter/models`?
[?]  (Y/n): y

Downloading (…)b-instruct.Q8_0.gguf:   3%|▉                                    | 954M/35.9G [1:35:04<69:37:43, 139kB/s]Traceback (most recent call last):
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 710, in _error_catcher
    yield
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 814, in _raw_read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 799, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\ssl.py", line 1311, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\ssl.py", line 1167, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 940, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 879, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 813, in _raw_read
    with self._error_catcher():
  File "D:\Chatgpt\Python3.11.5\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\urllib3\response.py", line 715, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\interpreter\interpreter.py", line 203, in chat
    self.llama_instance = get_hf_llm(self.model, self.debug_mode, self.context_window)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\interpreter\get_hf_llm.py", line 130, in get_hf_llm
fault_path)
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\huggingface_hub\file_download.py", line 1364, in hf_hub_download
    http_get(
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\huggingface_hub\file_download.py", line 541, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "D:\Chatgpt\Python3.11.5\Lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

▌ Failed to install TheBloke/CodeLlama-34B-Instruct-GGUF.

Common Fixes: You can follow our simple setup docs at the link below to resolve common errors.

 https://github.com/KillianLucas/open-interpreter/tree/main/docs

If you've tried that and you're still getting an error, we have likely not built the proper
TheBloke/CodeLlama-34B-Instruct-GGUF support for your system.

( Running language models locally is a difficult task! If you have insight into the best way to implement this across
platforms/architectures, please join the Open Interpreter community Discord and consider contributing the project's
development. )

Press enter to switch to GPT-4 (recommended).

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

Windows 11

### Additional context

My download speed is slow about 100-500kb/s. Whether i can improve the speed with VPN and which notional node will be faster?

**Comment by ericrallen** [comment]
Hey there, @7415647!

Is this still an issue with the most recent version of Open Interpreter?

You might also want to consider any other download methods that might be more successful for you given the network speed constraints you mentioned and use the [underlying integration with LiteLLM](https://docs.litellm.ai/docs/providers) to connect to your local model.

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Please reopen it if the issue still exists in the latest version of Open Interpreter or you feel like there’s more to discuss.
