### ISSUE TITLE
Running interpreter command opens interpreter directory

### ISSUE THREAD

**Issue by dadcancode** [KillianLucas/open-interpreter#334]
### Describe the bug

I am using WSL2 running Ubuntu 22.04 on Windows 10 machine

After running `pip install open-interpreter`

when I try to run `interpreter` from the `open-interpreter` directory, my terminal cd's into `open-interpreter/interpreter` instead of running the command.

When I run `interpreter` from the `open-interpreter/interpreter` directory, I get the message
`zsh: command not found: interpreter`

Also, when I run `python -V` i get `command not found: python` I seem to have Python3 installed because when I run `python3 -V` it prints `Python 3.10.12`

Am I missing a step?

### Reproduce

1. clone `open-interpreter` from github repo
2. cd into `open-interpreter`
3. run `pip install open-interpreter`
4. run `interpreter`

### Expected behavior

Interpreter interface should appear

### Open Interpreter version

0.1.3

### Python version

3.10.12

### Operating System name and version

Windows 10

### Additional context

Ubuntu 22.04 on WSL2 on Windows 10

**Comment by astelmach01** [comment]
I personally alias python to python3 and pip to pip3, might be a fix

**Comment by guoqiao** [comment]
On Debian/Ubuntu Linux, `python` normally refers to Python 2.x, and `python3` refers to Python 3.x.

Just consider python2 and python3 as different languages and ecosystems.
Also, you may have multiple python3 versions installed.

When use `pip install`,  it's unclear which python or  python3 installation it is installing for.

To ensure you install the pkg for expected python3, run this instead:
```
python3 -m pip install open-interpreter
```

**Comment by jordanbtucker** [comment]
The Ubuntu way to fix the `python` vs `python3` issue is to install the package `python-is-python3`.

```
sudo apt install python-is-python3
```

If you just want to install open-interpreter, I recommend using pipx so it stays in its own virtual environment and doesn't interfere with any system packages.

```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```

Then you can install open-interpreter with pipx.

```
pipx install open-interpreter
```

Once installed, you should be able to run interpreter in the terminal from any directory.

```
interpreter
```

---

If you're contributing or investigating the source code, you'll want to set up a virtual environment and use poetry.

```
git clone https://github.com/KillianLucas/open-interpreter.git
cd open-interpreter
python3 -m venv venv
./venv/Scripts/activate
pip install poetry
poetry install
```

When you want to run interpreter from source, do that through poetry.

```
poetry run interpreter
```

**Comment by haseeb-heaven** [comment]
Better watch this Video : [Code interpreter Setup](https://www.youtube.com/watch?v=J-H2un1Adr0)
