### ISSUE TITLE
interpreter should display what language the code block is in

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#340]
### Is your feature request related to a problem? Please describe.

I asked interpreter how many files are on my desktop and it wanted to run the following code:

```python
ls ~/Desktop
```

That code should have worked, except that interpreter tried to run it as Python.

### Describe the solution you'd like

interpreter should be explicit about the language the code it's displaying is written in.

Examples:

\> What is my OS?

**Python**
```python
import os
print(os.name)
```

Would you like to run this code? (y/n)

\> How many files are on my desktop?

**Bash**
```bash
ls ~/Desktop
```

Would you like to run this code? (y/n)

**Comment by bitsnaps** [comment]
I guess a better way to start by gathering some user's info (os, username, PATH...), like it won't run `ls` if you're in windows and uses `dir` instead, and check if python is installed and which version... but of course this has to be with user consent...

**Comment by kreynolds** [comment]
I wouldn't call this an enhancement, I would call it a bug that things are trying to execute using the wrong language. What appears to be happening is that the language is missing from the code block and the default is python. I am unable to consistently get it to specify the language by modifying the question, its possible a different prompt will do better.

For example:
"How many files are in the current directory?"
```
{
    'content': "\n\nLet's start with finding out how many files are in the current directory. To do this, we can use the
`ls` command in the terminal. This will list all the files in the current directory. We can then count the number of 
files listed by using a variable and incrementing it each time a file is listed.\n```\nls | wc -l\n```"
```

**Comment by ericrallen** [comment]
Is this still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
