### ISSUE TITLE
Accumulate commented code files to preserve state 

### ISSUE THREAD

**Issue by adbutler007** [KillianLucas/open-interpreter#341]
### Is your feature request related to a problem? Please describe.

First off - open-interpreter is absolutely incredible. Thank you!

I'm running open-interpreter on a 2022 Macbook Air M1 with 16GB. 

When I run the code directly in terminal (ie not in a python session) the session always freezes after 10-15 minutes. I'm not sure if this is because I run out of context window (using GPT-4) or there is something else going on. Perhaps there is a network error. Either way, interpreter works brilliantly up to that point.

When the session freezes, it can sometimes be "coaxed" to continue with CTRL-C. But eventually it stops and I have to terminate the session, at which point I lose all my work.

### Describe the solution you'd like

I'm considering a user hack where I instruct interpreter to write fully commented code to a named script file whenever I prompt with a certain instruction code. The initial prompt might be: "When I say "summarize all to file" your task is to write a parsimonious summary and meticulously commented code to the following path <path/file>. The summary and code should reference only the final decisions and working code for each step of our chat session so far.  Ignore unproductive lines of inquiry, code errors, debugging steps, etc. The summary should describe the objective of the session; the steps we plan to take; paths to any files that are read, written, or sourced and packages that must be installed for the code to run. The summary should be as concise as possible, but contain all the context necessary to reproduce the productive parts of the session. The code should follow with concise but meticulous comments, and references to all external objects and paths. Always include code that we have validated as correct and that is consistent with our most up-to-date objectives and plan. Never include code from unproductive lines of inquiry. Always overwrite the previous contents of the file."

The goal is to have all the information I need in permanent storage to restart the session as near as possible to the point where the session breaks.

Ideally, this process would run in the background on a regular basis, and perhaps after every interaction using a more efficient model. It shouldn't be necessary to use GPT-4 to produce the summary. At any point the user can choose to abandon the current session and "reboot" the session with the concise summary as the only context in the chat. Aside from preserving state along the way, this would extend the context length of an interaction with interpreter dramatically.

**Comment by moming2k** [comment]
Not a prefect solution yet, but this MR will enable the start of the script to load with the stored conversation. 

https://github.com/KillianLucas/open-interpreter/pull/359

**Comment by moming2k** [comment]
https://github.com/KillianLucas/open-interpreter/pull/359 released with the published 0.1.4. You can have a try.
