### ISSUE TITLE
A feature for Reverse Proxy users

### ISSUE THREAD

**Issue by TheProfessionalDumbass** [KillianLucas/open-interpreter#342]
### Describe the solution you'd like

For Open Ai reverse proxy users to use this interpreter

**Comment by ericrallen** [comment]
Have you tried using the [`--api_base` functionality that works with the LiteLLM integration](https://docs.litellm.ai/docs/set_keys#litellmapi_base) to allow you to specify a URL for your API?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if there is more to discuss.
