### ISSUE TITLE
How to change the domain name of an API?

### ISSUE THREAD

**Issue by Cheng5696** [KillianLucas/open-interpreter#348]
### Is your feature request related to a problem? Please describe.

I am using a translation model called GPT-3.5-turb as an intermediary. Therefore, I cannot directly perform the requested action.

### Describe the solution you'd like

I am using a translation model called GPT-3.5-turb as an intermediary. Therefore, I cannot directly perform the requested action.

### Describe alternatives you've considered

I am using a translation model called GPT-3.5-turb as an intermediary. Therefore, I cannot directly perform the requested action.

### Additional context

I am using a translation model called GPT-3.5-turb as an intermediary. Therefore, I cannot directly perform the requested action.

**Comment by Joackk** [comment]
me too

**Comment by bitsnaps** [comment]
I think this can be handy as well for any one using alternative API (e.g. [NovaAI](https://nova-oss.com/)...), I think gpt-aider implement this option in command line argument by setting custom `openai.api_base`.

**Comment by CiaranYoung** [comment]
yeah, i think so

**Comment by bitsnaps** [comment]
Think it's already [there](https://github.com/KillianLucas/open-interpreter/blob/5d8a0e1afa3d658142fc2c2b9a441008a441451a/interpreter/archive/cli.py#L106) with `--api_base`.

**Comment by Joackk** [comment]
> I think it's already [there](https://github.com/KillianLucas/open-interpreter/blob/5d8a0e1afa3d658142fc2c2b9a441008a441451a/interpreter/archive/cli.py#L106) with `--api_base`.

Has this option been added? Well done
