### ISSUE TITLE
openai.error.AuthenticationError

### ISSUE THREAD

**Issue by weiwill88** [KillianLucas/open-interpreter#349]
### Describe the bug

Hi there， when I "pip install open-interpreter", there appears a bunch of "DEPRECATION" hints, and when I type "interpreter", It shows the error message: "openai.error. AuthenticationError: Incorrect API key provided: your_api_key. You can find your API key at https://platform.openai.com/account/api-keys." The question is, I don‘t know where to modify the API key. Help me out, please!

### Reproduce

1、pip install open-interpreter
2、interpreter

### Expected behavior

Please show me where to modify the API key.

### Screenshots

![微信截图_20230914140129](https://github.com/KillianLucas/open-interpreter/assets/130907725/f036e4bf-ac9c-4931-b369-4e1a5051ebbe)
![微信截图_20230914140111](https://github.com/KillianLucas/open-interpreter/assets/130907725/e968cd5e-8191-4aca-89f2-d9ca551a959b)
![微信截图_20230914140026](https://github.com/KillianLucas/open-interpreter/assets/130907725/225e04d8-5de8-4f1b-a859-d01e24da5c38)

### Open Interpreter version

Version: 0.1.3

### Python version

Python 3.11.4

### Operating System name and version

Windows 11

**Comment by codeacme17** [comment]
Hi @weiwill88 , You can use `setx OPENAI_API_KEY <the modify key>` to modify your existing Openai api key."

**Comment by jordanbtucker** [comment]
Please upgrade to the latest version of Open Interpreter.

```
pip install --upgrade open-interpreter
```

**Comment by ericrallen** [comment]
I’m going to close this one, but please feel free to reopen if the issue still exists.
