### ISSUE TITLE
Product video

### ISSUE THREAD

**Issue by paulpierre** [KillianLucas/open-interpreter#35]
What tool, service, etc. did you use to make the demo video?

**Comment by DrCool** [comment]
Yes, I came here to ask the same thing! The video is amazing. What software is it?

**Comment by KillianLucas** [comment]
Thanks @paulpierre and @DrCool! I used [Rotato](https://rotato.app/), couldn't recommend it highly enough! The song does most of the work IMO, and that's [Pnau - Baby (Breakbot remix)](https://www.youtube.com/watch?v=GhuGMK18Bss&ab_channel=MartynasLajauskas).

**Comment by paulpierre** [comment]
🙏 ty.
