### ISSUE TITLE
Add support for Vertex AI

### ISSUE THREAD

**Issue by haseeb-heaven** [KillianLucas/open-interpreter#352]
### Describe the solution you'd like

**_If you are looking for a powerful and affordable platform for text generation, I highly recommend Vertex AI._**

Vertex AI offers a variety of generative models, such as Text Bison, Chat Bison, Code Generation, Code Chat, and Code Completion. These models are fine-tuned for code generation, code chat, and code completion.

The pricing for Vertex AI generative models is very reasonable compared to OpenAI. You only pay for the input and output characters that you use, and the price per 1,000 characters is $0.0005 for most models.[Vertex AI Pricing](https://cloud.google.com/vertex-ai/pricing)

[Vertex AI Code Models](https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-models-overview)

### Describe alternatives you've considered

I have tried with OpenAI API and Vertex AI are pretty cheap for code generations

**Comment by jordanbtucker** [comment]
@krrishdholakia Is this something LiteLLM already supports?

**Comment by krrishdholakia** [comment]
Yep - https://docs.litellm.ai/docs/providers/vertex

@haseeb-heaven any specific models you were trying to use?

Here's what we currently support: 
```
vertex_chat_models = ["chat-bison", "chat-bison@001"]


vertex_text_models = ["text-bison", "text-bison@001"]
```

Let me know if there's any we're missing

**Comment by haseeb-heaven** [comment]
> Yep - https://docs.litellm.ai/docs/providers/vertex
> 
> @haseeb-heaven any specific models you were trying to use?
> 
> Here's what we currently support:
> 
> ```
> vertex_chat_models = ["chat-bison", "chat-bison@001"]
> 
> 
> vertex_text_models = ["text-bison", "text-bison@001"]
> ```
> 
> Let me know if there's any we're missing

Thats great i wanted to use them for code generation Bison model is good for code generation and Gecko is good for code completion. 

But which one is supported here in OpenInterpreter ?

**Comment by krrishdholakia** [comment]
I believe this PR - https://github.com/KillianLucas/open-interpreter/pull/288, would enable open-interpreter users to easily go cross-provider 

cc: @ishaan-jaff @jordanbtucker

**Comment by ishaan-jaff** [comment]
@haseeb-heaven I can take care of this: 

- [ ] We need to add code-bison, code-chat-bison, code-gecko to litellm
- [ ] Make a PR to O-I to add the following VertexAI LLMs

**Comment by ishaan-jaff** [comment]
tracking LiteLLM change here: https://github.com/BerriAI/litellm/issues/377

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven I can take care of this:
> 
> * [x]  We need to add code-bison, code-chat-bison, code-gecko to litellm
> * [ ]  Make a PR to O-I to add the following VertexAI LLMs

Great so are we going to use litellm package then here in open-interpreter ?

**Comment by ishaan-jaff** [comment]
@haseeb-heaven open-interpreter  already uses litellm :)

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven open-interpreter already uses litellm :)

okay then its great 👍

**Comment by ishaan-jaff** [comment]
@haseeb-heaven litellm now supports all the LLMs you've requested above: https://docs.litellm.ai/docs/providers/vertex 

if you'd like you can already using vertex on open interpreter 

Going to make a PR to natively support vertex ai on open interpreter

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven litellm now supports all the LLMs you've requested above: https://docs.litellm.ai/docs/providers/vertex
> 
> if you'd like you can already using vertex on open interpreter
> 
> Going to make a PR to natively support vertex ai on open interpreter

Thats great thanks for adding it.

But i have tested your litellm i cannot use Coding LLM models there are giving me this error

Code :
```cpp
        user_prompt = "Write factorial of number"
        vertex_model = "code-bison"
        response = completion(model=vertex_model, messages=[{"role": "user", "content": user_prompt}])
```
Error:
An unexpected error occurred: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/code-bison',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by ishaan-jaff** [comment]
looks like it's on an older version, can you retry this after running:

`pip install litellm 0.1.643`

**Comment by haseeb-heaven** [comment]
> looks like it's on an older version, can you retry this after running:
> 
> `pip install litellm 0.1.643`

Great thats working now

**Comment by ishaan-jaff** [comment]
awesome - you can also try running vertext ai llms with o-i locally - here's roughly the changes you'd need https://github.com/KillianLucas/open-interpreter/pull/288

**Comment by haseeb-heaven** [comment]
> awesome - you can also try running vertext ai llms with o-i locally - here's roughly the changes you'd need #288

Yes, i got it thanks.
But for Vertex LLM we need to have special section with README for `credentials.json` and how to set it up for Vertex AI.

Pre-requisites

- pip install google-cloud-aiplatform
- Authentication:
- run gcloud auth application-default login See [Google Cloud Docs](https://cloud.google.com/docs/authentication/external/set-up-adc)
- Alternatively you can set application_default_credentials.json

**Comment by haseeb-heaven** [comment]
I am getting error even after running Claude 2 and Vertex AI Code Bison.

```cpp
haseeb-mir@Haseebs-MacBook-Pro open-interpreter % python3.11 -m poetry run interpreter --model code-bison
A new version is available. Please run 'pip install --upgrade open-interpreter'.

▌ Model set to CODE-BISON                                                                                                                                             

Tip: To run locally, use interpreter --local                                                                                                                            

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.                                                                          

Press CTRL-C to exit.                                                                                                                                                   

> Write factorial of number in python and save it to file called fact_num.py and then try to run the program.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/haseeb-mir/Documents/Code/Python/open-interpreter/interpreter/interpreter.py", line 131, in cli
    cli(self)
  File "/Users/haseeb-mir/Documents/Code/Python/open-interpreter/interpreter/cli.py", line 207, in cli
    interpreter.chat()
  File "/Users/haseeb-mir/Documents/Code/Python/open-interpreter/interpreter/interpreter.py", line 412, in chat
    self.respond()
  File "/Users/haseeb-mir/Documents/Code/Python/open-interpreter/interpreter/interpreter.py", line 584, in respond
    messages = tt.trim(self.messages, self.model, system_message=system_message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haseeb-mir/Library/Caches/pypoetry/virtualenvs/open-interpreter-hpQxQ_Bl-py3.11/lib/python3.11/site-packages/tokentrim/tokentrim.py", line 133, in trim
    raise ValueError(f"Invalid model: {model}. Specify max_tokens instead")
ValueError: Invalid model: code-bison. Specify max_tokens instead
```

**Comment by ishaan-jaff** [comment]
@haseeb-heaven can you try/except that. in the except branch you can `pass` 


It's because token trimmer does not support code bison

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven can you try/except that. in the except branch you can `pass`
> 
> It's because token trimmer does not support code bison

I tried this code
```cpp
    messages = self.messages
    system_message = self.system_message + "\n\n" + info
    try:
      if self.local:
        messages = tt.trim(self.messages, max_tokens=(self.context_window-self.max_tokens-25), system_message=system_message)
      else:
        messages = tt.trim(self.messages, self.model, system_message=system_message)
    except:
      pass
```

But i am not getting any response back.

**Comment by ericrallen** [comment]
Can we confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Please reopen it if the issue still exists with the latest version.
