### ISSUE TITLE
Issue in user interface while downloading the model.

### ISSUE THREAD

**Issue by VinylBinary** [KillianLucas/open-interpreter#353]
### Describe the bug

While I was installing the latest version on PopOS (linux distribution), I encountered an issue that when the model was being downloaded it seemed like that the model was being downloaded multiple times, but it was being downloaded only once. 

### Reproduce

Download 13b medium model in a linux distro. 

### Expected behavior

The progress bar should be visible once and the progress should not stop. 

### Screenshots

![issue](https://github.com/KillianLucas/open-interpreter/assets/128230190/e8260da9-1f1e-4a09-9e24-60bfe609bfd1)

### Open Interpreter version

v0.1.3

### Python version

3.10.6

### Operating System name and version

Linux(PopOS)

**Comment by merlinfrombelgium** [comment]
At first look (without reproducing the issue), looks like the path has a syntax error where \` should be `'`

**Comment by merlinfrombelgium** [comment]
Will try to reproduce in WSL2...

**Comment by merlinfrombelgium** [comment]
My bad. I failed to read your issue description properly.
I didn't insinuate you made a syntax error. I thought something might be up with the code. Disregard.

Back to your issue. A progress bar in a terminal, in my experience, may get iterated over multiple lines depending on terminal behaviour. But I'll leave to one of the devs to rule out this can or can't be fixed.

**Comment by jordanbtucker** [comment]
I'll see if I can set up a Pop!_OS instance to test this.

**Comment by ericrallen** [comment]
Hey there, folks!

I'm going to close this one as stale for now, but please feel encouraged to reopen it if you still experience the issue in the latest version of Open Interpreter.
