### ISSUE TITLE
Integration of Enhanced hf model performance

### ISSUE THREAD

**Issue by SeungyounShin** [KillianLucas/open-interpreter#354]
### Is your feature request related to a problem? Please describe.

I've observed that certain challenges you've faced might not be solely attributed to the open-interpreter as referenced in:

[Issue 308](https://github.com/KillianLucas/open-interpreter/issues/308)
[Issue 166](https://github.com/KillianLucas/open-interpreter/issues/166)

Moreover, I noticed potential alignment issues in the Llama model's approach to code interpretation.

### Describe the solution you'd like

I suggest a collaboration to integrate the model I've developed on[Llama2-Code-Interpreter](https://github.com/SeungyounShin/Llama2-Code-Interpreter),  [HuggingFace](https://huggingface.co/Seungyoun/codellama-7b-instruct-pad), tailored uniquely for tasks like code generation, execution, and debugging trajectories. This model, finetuned from GPT4, integrates specialized tokens to guide its behavior. Here are some essential insights to consider:

1. Purely prompting the model will not yield the desired level of accuracy and precision.
2. Similar to projects like alpaca, which transition from a language prior to instruction-following, the naive use of code-llama would be akin to conversing with GPT-3 and not the specialized Chat-GPT. **To harness its full potential, there's a need to ensure alignment with a code-interpreter, transitioning from code-llama's innate abilities to focused code generation, execution, and trajectory management.**
3. To reiterate, a direct or simplistic use of the HuggingFace model may not provide the desired outcomes.

### Describe alternatives you've considered

I tried a lot but prefix, prompting , etc... method without finetuning the weight doesn't work

### Additional context

I'm eager to discuss potential avenues of collaboration. If this proposal aligns with the project's vision, perhaps we could arrange a Zoom meeting to delve deeper into the specifics.

**Comment by ericrallen** [comment]
Hey there, @SeungyounShin!

Have you tried loading your model into Open Interpreter to see how it performs?

Since Open Interpreter now integrates LiteLLM, you can use the `--model` argument to set the model to yours and play around with it.

**Example:**

`interpreter -—model “ Seungyoun/codellama-7b-instruct-pad”`

Always looking for capable models to recommend to folks.

**Comment by ericrallen** [comment]
Going to close this one for now, but please feel encouraged to reopen it if you want to test it out and discuss this further.
