### ISSUE TITLE
The gpt4.0 api keys have been entered, if you modify this keys，how to modify this keys?

### ISSUE THREAD

**Issue by LoveDurian** [KillianLucas/open-interpreter#357]
### Describe the bug

The gpt4.0 api keys have been entered, if you modify this keys

### Reproduce

The gpt4.0 api keys have been entered, if you modify this keys

### Expected behavior

The gpt4.0 api keys have been entered, if you modify this keys

### Screenshots

The gpt4.0 api keys have been entered, if you modify this keys

### Open Interpreter version

0.1.1

### Python version

3.11

### Operating System name and version

win11

### Additional context

The gpt4.0 api keys have been entered, if you modify this keys

**Comment by codeacme17** [comment]
Hi @LoveDurian, You can use `setx OPENAI_API_KEY <the modify key>` to modify your existing Openai api key."

**Comment by LoveDurian** [comment]
Yeah, that's it. I couldn't find it. Thank you so much.
The key was changed, but there were other errors：
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
![QQ截图20230915102121](https://github.com/KillianLucas/open-interpreter/assets/21336306/37659841-57c5-431d-ac4d-419873c2f16c)

**Comment by codeacme17** [comment]
This likely means that your current key doesn't have access to GPT-4. Please check with OpenAI to see if you have permissions to use GPT-4.

**Comment by jordanbtucker** [comment]
This issue is fixed in the latest version of Open Interpreter. Please run

```
pip install --upgrade open-interpreter
```
