### ISSUE TITLE
Model Selection prompt bug  🐞 (Code LLaMa)

### ISSUE THREAD

**Issue by haseeb-heaven** [KillianLucas/open-interpreter#358]
### Describe the bug

Model selection prompt still comes even you select the model via command line arguements.
While selecting model from `--model` flag it still asks us to select the model.

### Reproduce

1. Go to terminal.
2. Type `interpreter --local --model TheBloke/CodeLlama-7B-Instruct-GGUF`
3. See model prompt is still asking to choose paramter for CodeLlama.

### Expected behavior

It should directly set the model without prompting us again and again because we already mentioned in arguments.

### Screenshots

<img width="1116" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/11544739/4ca4e229-35df-43df-858f-03ae290076db">

### Open Interpreter version

0.1.4

### Python version

3.11.1

### Operating System name and version

Mac OS 13.5 (Ventura)

**Comment by haseeb-heaven** [comment]
> What I think the issue is that you have added "--local" as a flag. I think removing it would solve the problem [Readme](https://github.com/KillianLucas/open-interpreter#running-open-interpreter-locally)

<img width="1338" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/11544739/d296a27e-2cad-4d8d-92e2-78044d453f28">
It's still giving me prompt of selecting the model size which should be set through flag as well. This bug is only for models which are not GPT.

**Comment by jordanbtucker** [comment]
@haseeb-heaven This is because the `--model` are accepts a Hugging Face model name, which is a repository of files.

For example, if you visit https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-GGUF/tree/main you'll see there are many different gguf files in that repository. Open Interpreter doesn't know which one you want to use, so it prompts you.

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven This is because the `--model` are accepts a Hugging Face model name, which is a repository of files.
> 
> For example, if you visit https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-GGUF/tree/main you'll see there are many different gguf files in that repository. Open Interpreter doesn't know which one you want to use, so it prompts you.

Yes i know that but is there any option to make this interpreter remember which model i have set like in config file because i already downloaded medium size model but it still asking me to choose the model again and again which is annoying?

**Comment by jordanbtucker** [comment]
> is there any option to make this interpreter remember which model i have set

Not at this time, but you're welcome to create a feature request.
