### ISSUE TITLE
How to add BASE_URL

### ISSUE THREAD

**Issue by tibbar213** [KillianLucas/open-interpreter#36]
I want to use my own API

**Comment by KillianLucas** [comment]
This is a great idea. If you do this regularly, how do you like to do this? Can we just set `BASE_URL` on the `openai` package object..? This could be really simple to implement if so.

**Comment by liaozhangsheng** [comment]
It's easy to just add it to your code

**Comment by tibbar213** [comment]
Maybe like this ?
```
import interpreter
import openai

openai.api_base = my_api_base

interpreter.chat()
```
