### ISSUE TITLE
【 Building wheel for llama-cpp-python (pyproject.toml) did not run successfully】【Cannot unpack non-iterable NoneType Object】 

### ISSUE THREAD

**Issue by 7415647** [KillianLucas/open-interpreter#360]
### Describe the bug

I have read the doc "use x64 in WINDOWS.md and GPU.md " and follow step by step. But the error occur

### Reproduce

1.Download and install the latest version of [Visual Studio 2022 Community]

 2. choose Desktop development for C++ workload
     C++ CMake tools for Windows

3. open the Start menu, search for x64 Native Tools Command Prompt for VS 2022, and open it.

4. Run the following command.
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir

### Expected behavior

Build wheel for llama-cpp-python (pyproject.toml)  run successfully

### Screenshots

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

D:\Microsoft Visual Studio>pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.2.4.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Obtaining dependency information for typing-extensions>=4.5.0 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Obtaining dependency information for numpy>=1.20.0 from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Obtaining dependency information for diskcache>=5.6.1 from https://files.pythonhosted.org/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl.metadata
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.4 MB/s eta 0:00:00
Downloading numpy-1.25.2-cp311-cp311-win_amd64.whl (15.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 6.7 MB/s eta 0:00:00
Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      *** scikit-build-core 0.5.0 using CMake 3.27.4 (wheel)
      *** Configuring CMake...
      2023-09-14 22:00:40,453 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\鍖呮尟涓淺AppData\Local\Temp\tmpczivqzvp\build\CMakeInit.txt
      -- Building for: Visual Studio 17 2022
      -- The C compiler identification is MSVC 19.37.32824.0
      -- The CXX compiler identification is MSVC 19.37.32824.0

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects

D:\Microsoft Visual Studio>

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

Windows 11

**Comment by DaveChini** [comment]
I had this same issue, solved it by uninstalling visual studio and all extras and reinstalling with default options and MSVC v142, windows 10 sdk and c++ make tools for windows selected. Then i was able to install llama-cpp-python myself and open-interpreter was able to use it. also make sure you are building/compiling in the vs developer console. This helped guide me to a fix for my system https://github.com/imartinez/privateGPT/issues/18

**Comment by 7415647** [comment]
> https://blog.csdn.net/jxyk2007/article/details/132901316 解决办法
Thank you for your help. But after that when i run interpreter this error occur. Do you meet same issue?

![图片](https://github.com/KillianLucas/open-interpreter/assets/6607700/e65c45c6-a672-4fcc-8be1-15504b70dfa5)

**Comment by yipulerina** [comment]
I'm also getting the same error. I've followed the guidelines step by step. 
The only issue left is this. The error keeps popping up endlessly.
![1](https://github.com/KillianLucas/open-interpreter/assets/88201911/3d9d5d5d-0134-4161-ab5a-aa63aeedbf9b)
![2](https://github.com/KillianLucas/open-interpreter/assets/88201911/84f119c4-7b2d-48ee-b16e-1da5fab242bc)

**Comment by jxyk2007** [comment]
> > https://blog.csdn.net/jxyk2007/article/details/132901316 解决办法
> > Thank you for your help. But after that when i run interpreter this error occur. Do you meet same issue?
> 
> ![图片](https://user-images.githubusercontent.com/6607700/268246014-e65c45c6-a672-4fcc-8be1-15504b70dfa5.png)
> 
> About few minutes later. Some steps appear but one letter by one letter. The time between two letters show is about 2-3minutes. The screenshot is following: ![图片](https://user-images.githubusercontent.com/6607700/268256173-c2895e7f-0fc3-4dc7-8799-e60fd8ac445d.png)

你应该使用GPU把

**Comment by jxyk2007** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/44092526/f15c1c52-8ae5-4999-91af-1c1e72cafcf0)

**Comment by jxyk2007** [comment]
> > https://blog.csdn.net/jxyk2007/article/details/132901316 解决办法
> > Thank you for your help. But after that when i run interpreter this error occur. Do you meet same issue?
> 
> ![图片](https://user-images.githubusercontent.com/6607700/268246014-e65c45c6-a672-4fcc-8be1-15504b70dfa5.png)
> 
> About few minutes later. Some steps appear but one letter by one letter. The time between two letters show is about 2-3minutes. The screenshot is following: ![图片](https://user-images.githubusercontent.com/6607700/268256173-c2895e7f-0fc3-4dc7-8799-e60fd8ac445d.png)

是不是.gguf文件路径写错了？

**Comment by wyf00747** [comment]
后来解决了么？按照帖子手动安装了llama-cpp-python 还是无法调用GPU

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now, but please reopen it if you still experience the same issue with the latest version of Open Interpreter.
