### ISSUE TITLE
Handle errors during code execution to avoid restarting from step zero

### ISSUE THREAD

**Issue by thedoctorjtd** [KillianLucas/open-interpreter#362]
### Is your feature request related to a problem? Please describe.

If there is an error during code execution the code-interpreter exits entirely leaving you to restart from the first step. Depending on where in the process you are, this could be costly (time and API) to get back to. 

### Describe the solution you'd like

Have all errors during code execution handled. If there is an error, pass the error to GPT to give it the opportunity to fix the issue or to allow the user to suggest an alternative. 

### Additional context

Note - I am not suggesting that open-interpreter should be able to automatically handle every error; I know that is far out. I simply would like the ability to not have to restart the script if there was an error during code execution. Allowing gpt the ability to correct the code usually works well.

**Comment by jordanbtucker** [comment]
This doesn't normally happen. You're probably running into an issue where the language isn't support.

See this example:

\> write some python code that will raise an exception

```python
raise Exception('This is a custom exception')
```

Would you like to run this code? (y/n)

y

```python
raise Exception('This is a custom exception')
```
```
File "<stdin>", line 3, in <module>
Exception: This is a custom exception
```

As expected, the Python code raised an exception with the message "This is a custom exception".

Open Interpreter didn't crash. However, if it tried to write code in a language that isn't yet supported, like C++, Open Interpreter will crash. There is a feature request for this. #376

**Comment by ericrallen** [comment]
I believe this might be fixed in the current `main` branch.

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
