### ISSUE TITLE
Windows: OpenInterpreter not using OPENAI_API_KEY environment variable as suggested to set

### ISSUE THREAD

**Issue by thedoctorjtd** [KillianLucas/open-interpreter#363]
### Describe the bug

When running `interpreter` for the first time you are prompted to set your OpenAI API key. After setting your key you are told 
```
OpenAI API key: REDACTED

Tip: To save this key for later, run export OPENAI_API_KEY=your_api_key on Mac/Linux or setx OPENAI_API_KEY your_api_key
on Windows.
```

Running `setx` as suggested works as intended
```
(.venv) PS D:\Windows Locations\Documents\Code\OpenInterpreter> setx OPENAI_API_KEY REDACTED

SUCCESS: Specified value was saved.
```

However when re-running interpreter, the key is not found from the variable.
```
(.venv) PS D:\Windows Locations\Documents\Code\OpenInterpreter> setx OPENAI_API_KEY REDACTED

SUCCESS: Specified value was saved.
(.venv) PS D:\Windows Locations\Documents\Code\OpenInterpreter> interpreter

Welcome to Open Interpreter.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

▌ OpenAI API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.
```

### Reproduce

See above. This is running in a python venv, not sure if that could be the cause.

### Expected behavior

OpenInterpreter should pull the environment variable as suggested to save the key to. If it expects a different variable then the in-program hint should be updated.

### Open Interpreter version

0.1.4

### Python version

Python 3.10.11

### Operating System name and version

Windows 10

**Comment by gbombardi** [comment]
you have to close cmd and re-open it in order to consider the new env variable

**Comment by codeacme17** [comment]
Hi @thedoctorjtd, Please try closing the current terminal and opening a new one after you've finished setting it up. This should activate the changes.

**Comment by jordanbtucker** [comment]
While `setx` will set the environment variable, it will not actually activate in PowerShell under you close and re-open the terminal. To make it work in PowerShell run both of these commands:

```
setx OPENAI_API_KEY your_api_key
$env:OPENAI_API_KEY='your_api_key'
```
