### ISSUE TITLE
Integrate OpenRouter Support for GPT-4-32k with LiteLLM

### ISSUE THREAD

**Issue by nickvarterian** [KillianLucas/open-interpreter#364]
### Is your feature request related to a problem? Please describe.

OpenAI has limited the access to GPT-4-32k. However, there is a potential workaround to this limitation through the use of OpenRouter, as highlighted in the [LiteLLM documentation](https://litellm.vercel.app/docs/providers/openrouter).

### Describe the solution you'd like

I suggest integrating OpenRouter support to allow users to utilize GPT-4-32k in open-interpreter. This would potentially allow more users to take advantage of the advanced capabilities of GPT-4-32k, even if they don't have direct access from OpenAI.

**Comment by ishaan-jaff** [comment]
@nickvarterian sounds good - we can add openrouter pretty easily through litellm

**Comment by ishaan-jaff** [comment]
I will make a PR for this

**Comment by semikolon** [comment]
Any update? :)

**Comment by arjanflac** [comment]
I was also hoping to use openrouter since I don't yet have access to gpt-4 api from OI

**Comment by jordantgh** [comment]
OI now uses litellm, which supports openrouter by default so should be easy enough to implement. You would just plug in `completion(model = 'openrouter/openai/gpt-4-32k', ...)` wherever the relevant calls are.

**Comment by jordantgh** [comment]
The only thing to watch for is in what format exactly OI is expecting the endpoint to be specified, e.g. if it is already building the endpoint piecewise under the hood or if you can just specify the full endpoint.

**Comment by ericrallen** [comment]
Hey there, folks!

I’m going to close this one as I believe this can be achieved with the existing LiteLLM integration.

Feel free to reopen it if I’m wrong.
