### ISSUE TITLE
Error : Running C++ code | Code LLaMa

### ISSUE THREAD

**Issue by haseeb-heaven** [KillianLucas/open-interpreter#367]
### Describe the bug

It cannot run the C++ code generated using LLama. Gives error only for this model

### Reproduce

1. Select Code LLaMa model.
2.Ask it to write code in C++ language.
3.Then ask it to run this code using C++ compiler.
4.See the error in output.

### Expected behavior

The code should run properly even check for C++ compiler installed.

### Screenshots

<img width="1398" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/11544739/e0b39f39-52a1-4675-aabf-4f84a0e4ca78">

### Open Interpreter version

0.1.4

### Python version

3.11.1

### Operating System name and version

Mac OS 13.5 (Ventura)

**Comment by haseeb-heaven** [comment]
I see Open interpreter only supports some languages so C/C++,Java,C# and others are not supported yet.

**Comment by jordanbtucker** [comment]
Closing this since C++ is not a supported language yet. You're welcome to create a feature request for it.
