### ISSUE TITLE
cant install code llama ccp python 

### ISSUE THREAD

**Issue by nassab13** [KillianLucas/open-interpreter#37]
hey

i cant install it 

heres the error message

>Failed to install Code-LLama.

**We have likely not built the proper `Code-Llama` support for your system.**

heres my system : macbook pro 2015 mac os monterey  i7 16go ram 

please help me

**Comment by KillianLucas** [comment]
Hi @nassab13! We're working hard on supporting more systems, but I think your Mac might not work yet as the error message suggests. Soon we'll have a more contained Code-Llama system that runs on many more systems, so stay tuned. 

In the meantime I'd suggest getting an OpenAI API key and using Open Interpreter with `gpt-4` (or with `gpt-3.5-turbo` by running `interpreter --fast`.

**Comment by mberman84** [comment]
I'm getting the same issue. I tried on my Macbook Pro M2 AND my Windows PC with RTX 4090. Neither work, both the same error as above.
