### ISSUE TITLE
Timeout for running code

### ISSUE THREAD

**Issue by kevin666aa** [KillianLucas/open-interpreter#370]
### Is your feature request related to a problem? Please describe.

I couldn't find a place to add timeout for code. Sometimes the Python code is running for a long time.

### Describe the solution you'd like

Allow user to pass in timeout time for code running. Possibly for different languages.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
