### ISSUE TITLE
I'm using the latest version .4. Drag - drop file from desktop issue

### ISSUE THREAD

**Issue by AcumenNations** [KillianLucas/open-interpreter#371]
### Describe the bug

I just updated to the latest version and now when I drag and drop a file from my desktop into the terminal, I get the new command features and an unknown error 

### Reproduce

check the screen shot

### Expected behavior

I would expect it to read It like version 0.1.2

### Screenshots

<img width="566" alt="Screenshot 2023-09-14 at 7 35 35 PM" src="https://github.com/KillianLucas/open-interpreter/assets/88368180/246ca147-97cd-4fef-a7e9-33b536e5bd7b">

### Open Interpreter version

0.1.4

### Python version

3.11

### Operating System name and version

venture 13

**Comment by jordanbtucker** [comment]
@KillianLucas or @TanmayDoesAI Can you please take a look.

**Comment by gggthatch** [comment]
Can confirm I am getting the same error on Mac after the update this morning :( 

Awesome work on everything BTW team!

**Comment by moming2k** [comment]
I can have a look on it.

**Comment by moming2k** [comment]
@jordanbtucker @TanmayDoesAI @KillianLucas I have created a fix, it would be resolve this issue.

**Comment by TanmayDoesAI** [comment]
@AcumenNations this should be fixed now, Thanks to @moming2k But this hasn't been pushed to pip yet, would be soon, but till then you could either try using a previous version, or install by cloning the repository.

**Comment by AcumenNations** [comment]
Nice work everyone! @TanmayDoesAI I'll try cloning the repo this weekend if the update hasn't been pushed to pip yet.

Have a great weekend everyone!
