### ISSUE TITLE
Switch from environment variables to a config file

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#372]
### Is your feature request related to a problem? Please describe.

Environment variables are not very user-friendly. They are great for server deployments, but rarely are casual users expected to deal with them, which has caused a lot of confusion.

### Describe the solution you'd like

Open Interpreter should switch to a configuration file that is automatically managed by Open Interpreter, for example with a package like [Trapdoor](https://github.com/claymcleod/trapdoor/).

For example, when the user sets their OpenAI API Key, Open Interpreter can ask if they would like to save it.

**Comment by ishaan-jaff** [comment]
are you suggesting using a config.json file? 

something like this:
```json
{
    "gpt-4": {
      "prompt": "hello i am a coding assistant",
      "temperature": 0.7,
      "max_tokens": 10
    },
    "claude-instant-1.2": {
      "prompt": "hello i am a coding assistant",
      "temperature": 0.7,
      "max_tokens": 10
    }
}
```

**Comment by krrishdholakia** [comment]
hey @jordanbtucker we also just added config files - https://docs.litellm.ai/docs/completion/config#usage

Would love to see if there's an overlap / way we can create a simplified UX here.

**Comment by ericrallen** [comment]
Just to add to this one, the `confit.yaml` file provides a lot of flexibility for this now, but we should probably be looking into something like [keyring](https://pypi.org/project/keyring/) for the user’s API keys instead of writing them out to a plaintext config file.

**Comment by ericrallen** [comment]
Going to close this one as I think the `--config` and `--config_file` options address it.

Feel free to reopen or start a new thread if that isn’t the case.
