### ISSUE TITLE
Gracefully fail when a language is not supported

### ISSUE THREAD

**Issue by jordanbtucker** [KillianLucas/open-interpreter#376]
### Is your feature request related to a problem? Please describe.

Currently when a model returns code for a language that Open Interpreter doesn't support, it crashes.

### Describe the solution you'd like

Open Interpreter should gracefully inform the user and the model that the selected language is not supported and tell the model which languages are supported.

**Comment by TanmayDoesAI** [comment]
@jordanbtucker nice idea, what do you think the user should just be informed and then interpreter exits, or would it be like interpreter informs to both the user and the llm that this code can't be run, and the conversation goes on?

**Comment by vipulcvyas** [comment]
it crashes while running php code. and also crashes for windows system commands , too like adding an item to task scheduler

**Comment by ericrallen** [comment]
I believe #680 fixes this and it should be solved in the `main` branch.

**Comment by ericrallen** [comment]
I'm going to close this one because I _think_ it has been solved in a recent release.

Please reopen it if I'm wrong.
