### ISSUE TITLE
是否可以支持revChatGPT

### ISSUE THREAD

**Issue by jxyk2007** [KillianLucas/open-interpreter#379]
### Is your feature request related to a problem? Please describe.

revChatGPT 无需openai api 的token 就可以实现 对接chatgpt3.5

### Describe the solution you'd like

{
  "conversation_id": "UUID...",
  "parent_id": "UUID...",
  "proxy": "...",
  "model": "gpt-4", // gpt-4-browsing, text-davinci-002-render-sha, gpt-4, gpt-4-plugins
  "plugin_ids": ["plugin-d1d6eb04-3375-40aa-940a-c2fc57ce0f51"], // Wolfram Alpha example
  "disable_history": true,
  "PUID": "<_puid cookie for plus accounts>", // Only if you have a plus account and use GPT-4
  "unverified_plugin_domains":["showme.redstarplugin.com"] // Unverfied plugins to install
}

**Comment by jxyk2007** [comment]
``from revChatGPT.V1 import Chatbot
import calendar

chatbot = Chatbot(config={
  "access_token": "***************************************",
  "model": "gpt-3"
})
def askai():
    print("Chatbot: ")
    prev_text = ""
    for data in chatbot.ask(
        "你的模型？",
       # conversation_id='4469b92d-0cbf-45ee-ad71-285*******e25'
    ):
        message = data["message"][len(prev_text) :]
        print(message, end="", flush=True)
        prev_text = data["message"]
    print()
    print(data['conversation_id'])

askai()

prompt = "你的模型？"
response = ""
for data in chatbot.ask(
  prompt
):
    response = data["message"]
print(response)

**Comment by ericrallen** [comment]
Hey there, @jxyk2007!

Could you provide some more context around what you're asking for here?

**Comment by jxyk2007** [comment]
The API for OpenAI comes at a cost. Revchatgpt is free of charge 。
Reverse engineered ChatGPT **API**
https://github.com/acheong08/ChatGPT

**Comment by ericrallen** [comment]
I believe you can run that yourself and then use the `api_base` functionality in LiteLLM to point to your proxy.

It’s worth noting that at some points in the past there were a number of accounts banned for using these kinds of tools.

**Comment by ericrallen** [comment]
Going to close this one for now as I believe the underlying LiteLLM integration provides the functionality you’re looking for.
