### ISSUE TITLE
Usage with "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by mboremski** [KillianLucas/open-interpreter#380]
### Is your feature request related to a problem? Please describe.

In my company-enviroment I have self-hosted certifiates in the chain since our firewall neetds to look into traffic.

This situation leads to an error like this:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
```

### Describe the solution you'd like

Description on how to deactivate the certificate-ferify (unsave) or on how to promote our company-ca to interpreter.

### Describe alternatives you've considered

#318 did not solve my issue.

**Comment by sebrk** [comment]
Got the same issue

**Comment by zachfarrell** [comment]
same

**Comment by ericrallen** [comment]
Hey there, folks!

I’m going to close this one as environment issues related to your network are out of our scope.

You might need to configure the appropriate certificate environment variables to allow Python packages that make requests to work with your restricted networks.

https://stackoverflow.com/a/43935319/656011
