### ISSUE TITLE
SyntaxError: (unicode error)

### ISSUE THREAD

**Issue by Danielnara24** [KillianLucas/open-interpreter#392]
### Describe the bug

When asking it to open a python script, it gives an error. This was the conversation:

Microsoft Windows [Versión 10.0.19045.3448]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Windows\system32>interpreter

▌ Model set to GPT-4

Tip: To run locally, use interpreter --local

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> Open this file and tell me what it does C:\Users\danle\OneDrive\Documentos\Python\WebhookJSON.py

  with open('C:\Users\danle\OneDrive\Documentos\Python\WebhookJSON.py', 'r') as file:
      data = file.read()
  data

  Would you like to run this code? (y/n)

  y

  with open('C:\Users\danle\OneDrive\Documentos\Python\WebhookJSON.py', 'r') as file:
      data = file.read()
  data

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Python311\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    with open('C:\Users\danle\OneDrive\Documentos\Python\WebhookJSON.py', 'r') as file:
                                                                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

My python version: 3.11.5
I've update open interpreter to the latest version, i've tried opening the command prompt as admin, tried it on a conda enviroment, tried to open a text file too and it also gives the same error.

### Reproduce

1. Open the CMD
2. run "interpreter" or "interpreter --fast"
3. Give the interpreter a file to open
4. The interpreter gives a code to run
5. Tell it to run it
6. Error

### Expected behavior

I expect it to open the file and tell me what it contains

### Open Interpreter version

0.1.4

### Python version

3.11.5

### Operating System name and version

Windows 10

**Comment by ElCuboNegro** [comment]
same for GPT-4 and Win 11.

**Comment by ray2021** [comment]
It seems interpret writes and run code to open files using exactly the path provided. I changed path to forward slash and it worked.

**Comment by ericrallen** [comment]
Hey there, folks!

Going to try to consolidate the conversation around UnicodeDecodeError and UnicodeEncodeError into #93

Please feel encouraged to continue the discussion in that thread so we’ve got everything in one spot.
