### ISSUE TITLE
Customize the domain for open API requests.

### ISSUE THREAD

**Issue by c469591** [KillianLucas/open-interpreter#398]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I hope to be able to customize the domain name for API requests through any means, such as using the command "interpreter --api=xxx.com"

### Describe alternatives you've considered

no

### Additional context

Please tell me, in the current version of the interpreter, which file should I modify to change the domain name for accessing the open API? I am a user who installed the interpreter using pip.
thanks

**Comment by ericrallen** [comment]
Hey there, @c469591!

I believe this is handled by LiteLLM’s API Base setting now.

**Comment by ericrallen** [comment]
Going to close this one as it should be available.

Feel free to reopen if you update and there’s still an Issue.

**Comment by c469591** [comment]
Please tell me the methods and steps to change the address of the openai.com for API requests to another address. Thank you!

**Comment by ericrallen** [comment]
You can use the `--api_base` flag while invoking interpreter, set the `api_base` property in your `config.yaml`, or use `interpreter.api_base` if you’re using Open Interpreter via Python.

**Comment by c469591** [comment]
thank you
