### ISSUE TITLE
Adding Support for Cohere and Hugging Face Hub API Keys

### ISSUE THREAD

**Issue by mlibre** [KillianLucas/open-interpreter#400]
### Describe the solution you'd like

- Implement a configuration option to input Cohere API key
- Implement a configuration option to input Hugging Face Hub API key

**Comment by haseeb-heaven** [comment]
Also for [Inference](https://huggingface.co/docs/api-inference/quicktour) API as well so we can use any model from Hugging face.

**Comment by ericrallen** [comment]
Hey there @mlibre and @haseeb-heaven!

I believe this is already handled by Open Interpreter's integration with LiteLLM.

There are some docs that might help:

- [Cohere Setup](https://docs.openinterpreter.com/language-model-setup/hosted-models/cohere)
- [Hugging Face Setup](https://docs.openinterpreter.com/language-model-setup/local-models/getting-models)
- [LiteLLM Hugging Face Docs](https://docs.litellm.ai/docs/providers/huggingface)
- [LiteLLM Cohere Docs](https://docs.litellm.ai/docs/providers/cohere)

I'm going to close this one as I think it should work, but please feel encouraged to reopen this issue if I'm wrong or if you run into any errors.
