### ISSUE TITLE
No output when running programs in chat mode on mac

### ISSUE THREAD

**Issue by newlegendmedia** [KillianLucas/open-interpreter#403]
### Describe the bug

I can run the interpreter and chat with it, but when it tries to do anything, I only get a blank line printed to the terminal, never any code or results. Here is the debug from a couple simple requests...

  {'role': 'user', 'content': 'Use python to print hello world'},
    {
        'role': 'assistant',
        'content': None,
        'function_call': <OpenAIObject at 0x104a77e30> JSON: {
  "name": "run_code",
  "arguments": ""
}
    },
    {'role': 'user', 'content': 'Use python to print hello world'},
    {
        'role': 'assistant',
        'content': None,
        'function_call': <OpenAIObject at 0x104a76e10> JSON: {
  "name": "run_code",
  "arguments": ""
}
    },
    {'role': 'user', 'content': 'print the first 10 fibonnaci numbers'},
    {
        'role': 'assistant',
        'content': 'Plan:\n1. Define a function to generate the Fibonacci sequence.\n2. Call this function to 
generate the first 10 numbers in the Fibonacci sequence.\n3. Print these numbers.'
    },
    {'role': 'user', 'content': 'execute'},
    {
        'role': 'assistant',
        'content': None,
        'function_call': <OpenAIObject at 0x104a76b10> JSON: {
  "name": "run_code",
  "arguments": ""
}
    },
    {'role': 'user', 'content': 'interpreter.model = "gpt-3.5-turbo"'}
]

### Reproduce

just run interpreter -y 

### Expected behavior

I would expect to see some code printed to the screen and some kind of results fromm execution.

### Open Interpreter version

Open Interpreter 0.1.4

### Python version

Python 3.11.5

### Operating System name and version

MacOS Ventura 13.5.2

**Comment by seshakiran** [comment]
Same for me. Could not get it to run.

**Comment by davidmoshal** [comment]
I think this is the same issue I opened a few hours prior:
https://github.com/KillianLucas/open-interpreter/issues/393

I explain how I got this project to work in that issue.

**Comment by ericrallen** [comment]
Hey there, @newlegendmedia 

I’m going to close this one as it’s for an older version of Open Interpreter.

Please reopen the issue if you upgrade to the latest version and still experience the issue.

**Comment by chymian** [comment]
@ericrallen 
pls. don't close bugs just because there is a new release, when the same bug is still persistend.
like here and in [393](https://github.com/KillianLucas/open-interpreter/issues/393)
IMHO: closing bugs on assumptions, without beeing really solved degrades the product quality massivly.

**Comment by Notnaton** [comment]
https://github.com/KillianLucas/open-interpreter/issues/393#issuecomment-1827374006
