### ISSUE TITLE
AWS integration

### ISSUE THREAD

**Issue by deanbushmiller** [KillianLucas/open-interpreter#406]
### Describe the solution you'd like

Parity with the Azure connection solution. Since Amazon Web services is three times more popular than Azure. I think it would benefit the community as a whole.

**Comment by TanmayDoesAI** [comment]
@deanbushmiller I think Amazon does not support OpenAI models, could you elaborate on what models are you suggesting through AWS?

**Comment by rperdiga** [comment]
AWS Bedrock supports Claude 2.0

**Comment by ericrallen** [comment]
Hey there!

Since LiteLLM is integrated under the hood, I _think_ you could [use AWS Bedrock models via LiteLLM](https://docs.litellm.ai/docs/providers/bedrock) if you provide the correct model name and make sure your Environment variables are set up properly.

**Comment by ishaan-jaff** [comment]
LiteLLM has full support for bedrock - you should be able to call them already. let me know if it does not work
