### ISSUE TITLE
Advice on which local model to use

### ISSUE THREAD

**Issue by davidmoshal** [KillianLucas/open-interpreter#407]
### Is your feature request related to a problem? Please describe.

Given an M1 mac with 16Gb memory, is it better to use
- a smaller model with better quality, 
  - eg : 13B with large memory, or
- a bigger model with smaller quality, 
  - eg: 34B with small memory
 
both claim to use around 15-16Gb RAM.
  
  

### Describe the solution you'd like

I'd like to see documentation on this.

**Comment by haseeb-heaven** [comment]
Are you suggesting an automatic method to detect local model to use depending upon the RAM available ?
Your issue is not clear please write and explain properly.
Thanks

**Comment by davidmoshal** [comment]
sorry, no, I'm asking how one would decide which model to use?

**Comment by mak448a** [comment]
Try both and see which you like better.

**Comment by mak448a** [comment]
I think 7b is fastest, and 34b is slowest. So pick one based on how fast you want the model to generate responses.

**Comment by haseeb-heaven** [comment]
> I think 7b is fastest, and 34b is slowest. So you can pick whichever one based on how fast you want the model to generate responses. 34b should be better for writing good code and responses though, at the expense of time.

i chooser medium one still not good than Gpt 3.5 i recommend Gpt but its not local

**Comment by fredrik-hansen** [comment]
Usually a bigger model with smaller quality is preferred - in your example 34B with small memory.

**Comment by davidmoshal** [comment]
Thank you

**Comment by ericrallen** [comment]
Going to close this one for now as it seems resolved and isn’t really in the scope of Open Interpreter.

Choosing a local model can be a very personal decision depending on your hardware and how much you understand about the relevant settings and prompting strategies for that model.

Please reopen this issue if you feel like there’s more to discuss.
