### ISSUE TITLE
Output disappears when I use the open-interpreter in Jupyter Notebook

### ISSUE THREAD

**Issue by choies1** [KillianLucas/open-interpreter#411]
### Is your feature request related to a problem? Please describe.

When I use the open-interpreter in Terminal, the output does not disappear.
But when I use it in Jupyter Notebook, the output is visible for a while and then disappears. 
Is there any way to make the output not disappear?

### Describe the solution you'd like

I'd like to be able to see all of my output in Jupyter Notebook without it disappearing, just like when I use open-interpreter in Terminal.

**Comment by DecaiJin** [comment]
I found the same question!!!

**Comment by hoshins** [comment]
I faced same situation. I updated python version from 3.10 to 3.11 but there is nothing changed

**Comment by ericrallen** [comment]
Hey there, folks!

I'm going to close this one as a duplicate of #52 

Let's keep any Jupyter discussion there.

Thanks!
