### ISSUE TITLE
Undo and Redo Capabilities

### ISSUE THREAD

**Issue by AdamSobieski** [KillianLucas/open-interpreter#413]
### Is your feature request related to a problem? Please describe.

Hello. I would like to request an enhancement: **undo** and, perhaps, **redo** capabilities for Open Interpreter. In my opinion, end-users would very much enjoy these features.

Which new features, if any, might systems like Open Interpreter require from other software applications, tools, and operating systems to best deliver these capabilities for end-users?

### Describe the solution you'd like

I look forward to any possible brainstorming and discussion of these ideas with others here. In my opinion, application developers, library developers, and operating system teams would all be interested in proposals regarding how best to deliver undo and, perhaps, redo capabilities for end-users using systems like Open Interpreter.

### Describe alternatives you've considered

1. Session and transaction scopes provided by the operating system and/or a shared library
2. An `undo` command which receives a previously executed command line as its argument: `undo "othercommand /arg"`

### Additional context

[Undo](https://en.wikipedia.org/wiki/Undo), [Transaction processing](https://en.wikipedia.org/wiki/Transaction_processing), [Database transaction](https://en.wikipedia.org/wiki/Database_transaction), [Nested transaction](https://en.wikipedia.org/wiki/Nested_transaction), [Savepoint](https://en.wikipedia.org/wiki/Savepoint), [Rollback](https://en.wikipedia.org/wiki/Rollback_(data_management)), [Commit](https://en.wikipedia.org/wiki/Commit_(data_management)).

**Comment by MikeBirdTech** [comment]
`%undo` has been implemented. Thanks!
