### ISSUE TITLE
Custom Instructions

### ISSUE THREAD

**Issue by yonaka43** [KillianLucas/open-interpreter#414]
### Is your feature request related to a problem? Please describe.

Sometimes the code generated by Open Interpreter is deprecated. I understand that Open Procedures is doing a very good job, but what about the idea of allowing users to give custom instructions to Open Interpreter?

### Describe the solution you'd like

Enter **Custom Instruction Mode** with the `--instructions` flag. Users have prepared custom instructions in `.md` format in the `instructions` folder. When generating system messages, it will include relevant instructions from this folder.

### Additional context

If you're interested, I'm ready to submit a pull request. I would be honored to help make this great project even greater.

**Comment by FrancyJGLisboa** [comment]
That's a must-have feature

**Comment by jfischburg-us** [comment]
I've been rather amazed by Gorilla when it comes to determining API's to access: https://gorilla.cs.berkeley.edu/
This might be a really solid integration/plugin to consider incorporating.

**Comment by MikeBirdTech** [comment]
`custom_instructions` can be set in profiles. Thanks!
