### ISSUE TITLE
There is no way to give openai api key please help

### ISSUE THREAD

**Issue by politas180** [KillianLucas/open-interpreter#418]
### Describe the bug

So when I type "interpreter" It then shows this:

▌ Model set to GPT-4

Tip: To run locally, use interpreter --local

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

>

But I use it for the first time and don't know where to put my API key.

### Reproduce

.

### Expected behavior

I would type my openai api key

### Screenshots

.

### Open Interpreter version

0.1.4

### Python version

3.11.3

### Operating System name and version

windows 11

### Additional context

.

**Comment by Cdaprod** [comment]
run `export OPENAI_API_KEY=sk-therestofyourkey` from your terminal

**Comment by Joshuahupp1** [comment]
To check if your Open API key has been saved properly open up another command line interface ( I hit the windows key and type CMD then hit enter) dont try to use interpreter to check it. 

`echo %OPENAI_API_KEY%`

--You should see an output that looks like this--
sk-blahblahblah <----your key

If you see this than everything should be working fine.

I hope this helps someone.

**Comment by LinkReincarnate** [comment]
I'm having the same issue, for some reason set OPENAI_API_KEY = (mykey) isn't updating the variable and it's stuck on a key I've revoked

**Comment by torealise** [comment]
I had same issue. The problem is that I had old OpenAI API KEY in my Environment Variables. This is why interpreter didn't ask for API KEY. So you need to remove the old OpenAI API KEY in Environment Variables

**Comment by politas180** [comment]
Than you everyone I checked my environment variables and yes there was a key and when I changed to the new it worked thanks again.

**Comment by TONGlong520** [comment]
> 我检查过我的环境指标的每个人都有一个钥匙，当我将其更改为新的时候，它就工作了，再次表示感谢。

How to change key
