### ISSUE TITLE
How to hook into the Text Stream

### ISSUE THREAD

**Issue by fire17** [KillianLucas/open-interpreter#419]
Hi there,
I cant believe I'm the first to ask this.....
but how can we hook into the text stream?

I'm building a UI for open-interpreter,
and I want to display the text stream in my UI, how do i access the text before it is printed?
Also I wish to send it to Elevenlabs Text2Voice (which supports streaming now)

Any help getting the live text will be helpfull
Thanks a lot and all the best!

 

### Reproduce

1. Add function hook, to interpreter, that will recieve all the text the interpreter genererates
interpreter.chat(user_msg, text_stream_hook=myFunc)

### Expected behavior

Text stream should be sent to myFunc

### Open Interpreter version

0.1.4

### Python version

3.11.5

### Operating System name and version

Windows 10

### Additional context

I would love the hook to exist, but i'll also take where i need to intercept in the code as an answer for now... since i can continue from there...

**Comment by fire17** [comment]
I got elevenlabs to play the final output :)
but i need help getting to all the rest of the output
anyone?

**Comment by MrJarnould** [comment]
@fire17 This seems more like a "_Feature request – Suggest an idea for this project_" than a "_Bug – Create a report to help us improve_". Perhaps you'll receive more interest from the community if you label this issue as such and follow the _Feature request_ issue [template](https://github.com/KillianLucas/open-interpreter/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml).

**Comment by fire17** [comment]
@MrJarnould I've marked it as bug since this text should be treated as first class citizen
And be fully accessible from interpreter object
So either it's available and should be better documented or it's a missing piece and not so much of a feature. 

Got any suggestions ?

**Comment by TheApeMachine** [comment]
"a missing piece" also known as a "feature"? First-class citizen notwithstanding, things can only be a bug if they were a feature first right? Or in another way, things have to exist before they can be broken.

**Comment by fire17** [comment]
Well.... you guys let me know if you want a PR for streaming the text out 

Meanwhile, sneak peak
<a href="https://github.com/fire17/MagicLLight">
![image](https://github.com/KillianLucas/open-interpreter/assets/9356048/a6509c58-c26b-48aa-bff2-06ee7fb5e1ce)
</a>
All the best :)

**Comment by ericrallen** [comment]
Hey there, @fire17!

There are some docs about how to [programmatically handle streaming responses from Open Interpreter](https://docs.openinterpreter.com/usage/python/streaming-response).

**Comment by ericrallen** [comment]
Going to close this for now due to the requested functionality being documented now.

Feel free to reopen if there’s still an Issue.
