### ISSUE TITLE
Support for OpenAI Base API Integration 

### ISSUE THREAD

**Issue by haseeb-heaven** [KillianLucas/open-interpreter#420]
## Feature description
**Support for OpenAI Base API Integration:**  
This feature introduces the capability for users to integrate their own **OpenAI Base API**. Currently, our system is reliant on the OpenAI's primary API Base. Given the associated costs and the availability of different models such as _GPT 3.5 and GPT 4_, it's imperative to provide an alternative. By allowing users to supply their own base API, we can potentially offer more cost-effective or even complimentary access to **GPT** models. This can be configured through a dedicated settings file, enabling users to utilize the **Open-Interpreter** with their preferred version of **GPT**.

## Motivation/Application
**Cost Efficiency and Flexibility:**  
The primary motivation behind this feature is to offer users greater flexibility and cost efficiency. With the rising costs associated with using OpenAI's primary API, providing an alternative where users can integrate their own API can lead to significant savings. Additionally, this feature can attract a broader user base, especially those looking for reduced costs or free access to GPT models. Furthermore, by allowing users to use their preferred version of GPT, we can cater to a wider range of user preferences and needs.

### Additional context

**PS**: I have created a new free **API** that supports _GPT 3.5, 3.5 Turbo, and 4_ versions using the repo below, and I will also give it for free once I test it properly in my development. This is just to give people an idea of how to use their own custom API base for OpenAI and not to use it commercially for their application.

**Comment by Masterlovsky** [comment]
Yes, this is a great suggestion. Currently, the only way to modify the API base is by making changes in the source code. Hopefully, the author can provide this interface to users, just like how the API key can be set as an environment variable.

**Comment by haseeb-heaven** [comment]
> Yes, this is a great suggestion. Currently, the only way to modify the API base is by making changes in the source code. Hopefully, the author can provide this interface to users, just like how the API key can be set as an environment variable.

Yes there is no option to set base API easily we can have it set from config file

**Comment by efed151** [comment]
I strongly agree that the author provides simple and clear options to use third-party APIs. Due to some other reasons, I had to use a third-party API to call the API; about a week ago, I was able to use the third-party API by modifying the source files of the openai library. But after I updated all libraries, this method no longer works. I tried to search for the cause, but there was no solution; the option of a third-party API has been present in the community for a long time, and I very much hope that our request will be resolved soon. Thanks to the development team!

**Comment by haseeb-heaven** [comment]
> I strongly agree that the author provides simple and clear options to use third-party APIs. Due to some other reasons, I had to use a third-party API to call the API; about a week ago, I was able to use the third-party API by modifying the source files of the openai library. But after I updated all libraries, this method no longer works. I tried to search for the cause, but there was no solution; the option of a third-party API has been present in the community for a long time, and I very much hope that our request will be resolved soon. Thanks to the development team!

If we will get more votes then we can create PR to simple use our own API rather than OpenAI's API simply in the JSON or Config file.

**Comment by zhuifeng7000** [comment]
I also have to use a third-party API, so I especially hope that the team can provide a configuration method

**Comment by efed151** [comment]
> 我还得使用第三方API，所以特别希望团队能提供一个配置方法
I think this problem should have been solved. You can find the source file interpreter.py under the two paths of ~/site-packages/interpreter or ~/dist-packages/interpreter, and modify the parameters of self.api_base&self.api_key. This is a solution; the second is that you can get help in intreterpre -h, the specific command is "interpreter --api_base <you use the base provided by the api>"; both methods support you to use third parties api, I have tried it and succeeded; it is worth noting that your base path is consistent with the base path that directly calls the official openai. Usually their path ends with v1.

**Comment by ericrallen** [comment]
Hey there, @haseeb-heaven!

I think this is covered by LiteLLM’s API Base now, right?

**Comment by haseeb-heaven** [comment]
> `OPENAI_API_BASE`: https://docs.litellm.ai/docs/set_keys
> 
> You can set it with the `--api_base` argument.

Yes LiteLLM supports this change now.

**Comment by haseeb-heaven** [comment]
But still LiteLLM needs to work with this issue for this Tokenizer
https://github.com/BerriAI/litellm/issues/587
