### ISSUE TITLE
example of how to use main.embedding

### ISSUE THREAD

**Issue by johntday** [KillianLucas/open-interpreter#427]
### Describe the solution you'd like

Explanation for using embedding vector database

**Comment by ericrallen** [comment]
Hey there, @johntday!

Can you clarify what you’re asking for here?

**Comment by johntday** [comment]
Plugin or extension to add additional vector database of embeddings

**Comment by ericrallen** [comment]
I'm going to close this one as a `duplicate` so we can consolidate all of the Vector, Memory, RAG, storage, etc. discussions into the first issue that brought them up (#144) and reduce the overall noise in the projects' Issues.
