### ISSUE TITLE
Interpreter under windows doesn't work. 

### ISSUE THREAD

**Issue by iplayfast** [KillianLucas/open-interpreter#428]
### Describe the bug

After installing python and pip install open-interpreter as the readme specifies, I've found that running interpreter does not work, However running from within python does work. 

I've been able to work successfully in Linux so this is a windows only problem. 

### Reproduce

Install python, and open-interpreter according to the readme.

### Expected behavior

interpreter should start open-interpreter

### Open Interpreter version

0.1.4

### Python version

3.11.5

### Operating System name and version

Windows 10

**Comment by ElCuboNegro** [comment]
I think is about your python configuration. try to install it from pipx.
in other side, when try to acomplish certain tasks (read my emails or so) the system don't do anything.

**Comment by ericrallen** [comment]
Hey there, @iplayfast!

There’s not a lot of info to go on here, so I’m going g to close this one as stale, but feel encouraged to reopen it and give us some more context if you experience the same issue with the latest version of Open Interpreter.
