### ISSUE TITLE
Consistency check failed Large 13b (large) Llama model

### ISSUE THREAD

**Issue by ChrisWan** [KillianLucas/open-interpreter#429]
### Describe the bug

Consistency check failed: file should be of size 13831494016 but has size 5464519 ((…)b-instruct.Q8_0.gguf)

### Reproduce

Download 13b "large" Llama variant:
Large | Size: 12.9 GB, Estimated RAM usage: 15.4 GB

### Expected behavior

successful download

### Open Interpreter version

0.1.3

### Python version

Python 3.11.5

### Operating System name and version

Linux

**Comment by ericrallen** [comment]
Hey there, @ChrisWan!

Can you confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Please reopen it if the issue still exists in the latest version of Open Interpreter or you feel like there’s more to discuss.
