### ISSUE TITLE
collection of use cases

### ISSUE THREAD

**Issue by guruk** [KillianLucas/open-interpreter#430]
### Is your feature request related to a problem? Please describe.

i love open-interpreter and even more i love what we can make out of it. 
i trust sharing such ideas will help us all a lot to grow faster together.

i see in the description: 
Create and edit photos, videos, PDFs, etc.
Control a Chrome browser to perform research
Plot, clean, and analyze large datasets
...etc.

### Describe the solution you'd like

i was able to prompt: (i am on macOs)

> open a new tab in my chrome browser and open news.google.com
(love that)

>  create a simple pomodoro app in html
(worked)

> can u list what is in my calendar 
(worked, while i would not need all the infos about what script it does create, or at least not after it came created once)
Here a reminder "would u like i create a new script or use the previous once created)

> go find finder into a folder and open there with right click menu a terminal session in that folder
useful for commands like "convert word docs to pdfs" or summarize the context of this documents"

>and so on. 

i think it could be useful to share prompts what we can do with openinterpreter as examples
please share what and how u do with codeinterpreter.

**Comment by iamwavecut** [comment]
In terms of creating a software, I was persuasive enough to make the interpreter review its work and fix the TODO's and stubs on its own, run lints and go back to fix bugs until everything runs smooth.

However, that works for GPT-4, and in its case it works hard enough to bill GPT-4 at the comparable SWE's level hourly rates. Just spent $80 in a couple of hours. :)

Can't share the exact prompt, but you should figure out how to instruct it to go in back-and-forth style.

**Comment by MikeBirdTech** [comment]
The community has been aggregating examples of what OI can do. A single place for this is a good idea. Will add it to the roadmap. Thanks!
