### ISSUE TITLE
Can't run interpreter on PC

### ISSUE THREAD

**Issue by RichardCCampbell** [KillianLucas/open-interpreter#432]
### Describe the bug

After installing interpreter I get two errors. The first is a warning after installing and the second is when I try to run interpter. 

### Reproduce

Installed python from Microsoft Store
installed interpreter 

### Expected behavior

Interpreter should run. 

### Screenshots

![Error](https://github.com/KillianLucas/open-interpreter/assets/131579837/4c7ea9b7-79ed-4d0d-b3c1-fed5c77e85b6)
![Warning](https://github.com/KillianLucas/open-interpreter/assets/131579837/0097af24-e573-4b2d-901d-71fdc71ef413)

### Open Interpreter version

1

### Python version

3.11.5

### Operating System name and version

Windows 11

**Comment by ElCuboNegro** [comment]
This is not a problem with the package, just add the python packages into your PATH, or install trough pipx instead of pip @RichardCCampbell RichardCCampbell

**Comment by ericrallen** [comment]
Closing as this is a local environment configuration issue with the PATH.

more information ca  be found in [#164 
](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711044334).
