### ISSUE TITLE
Readline Error v0.1.4, after published fix, Still got issue, 9.18.23

### ISSUE THREAD

**Issue by DarickBrokaw** [KillianLucas/open-interpreter#433]
### Describe the bug

Readline Error v0.1.4

I keep getting the following error on all models and setting combinations. I have uninstalled and reinstalled the tool 3 times today. Below is my system info. If I have missed something obvious my apologies. Thank you for this work! I look forward to seeing it grow.

### Reproduce

C:\Users\User>interpreter --local -y

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 7B

7B
13B
34B

[?] Quality (smaller is faster, larger is more capable): Small | Size: 2.6 GB, Estimated RAM usage: 5.1 GB

Small | Size: 2.6 GB, Estimated RAM usage: 5.1 GB
Medium | Size: 3.8 GB, Estimated RAM usage: 6.3 GB
Large | Size: 6.7 GB, Estimated RAM usage: 9.2 GB
See More

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): Y

Model found at C:\Users\User\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-7b-instruct.Q2_K.gguf

▌ Model set to TheBloke/CodeLlama-7B-Instruct-GGUF

Readline internal error
Traceback (most recent call last):
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 804, in hook_wrapper_23
res = ensure_str(readline_hook(prompt))
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darick\AppData\Local\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 587, in readline
self.readline_setup(prompt)
File "C:\Users\Darick\AppData\Local\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 583, in readline_setup
self._print_prompt()
File "C:\Users\Darick\AppData\Local\anaconda3\Lib\site-packages\pyreadline3\rlmain.py", line 487, in _print_prompt
n = c.write_scrolling(self.prompt, self.prompt_color)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\pyreadline3\console\console.py", line 332, in write_scrolling
w, h = self.size()
^^^^
TypeError: cannot unpack non-iterable NoneType object

Let's start with the first step of the plan: "Create a new folder called 'My Project'".

mkdir MyProject

Microsoft Windows [Version 10.0.22621.2134]
(c) Microsoft Corporation. All rights reserved.
C:\Users\User>mkdir MyProject
C:\Users\User>

it appears that the "My Project" folder was created successfully in the current directory. Now, let's move on to the
next step of the plan: "Create a new file called 'main.py'".

touch main.py

Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Users\User\AppData\Local\anaconda3\Scripts\interpreter.exe_main.py", line 7, in
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
cli(self)
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\cli.py", line 207, in cli
interpreter.chat()
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
self.respond()
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 938, in respond
self.respond()
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
code_interpreter.run()
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
code = wrap_in_try_except(code)
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\User\AppData\Local\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
parsed_code = ast.parse(code)
^^^^^^^^^^^^^^^
File "C:\Users\User\AppData\Local\anaconda3\Lib\ast.py", line 50, in parse
return compile(source, filename, mode, flags,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 2
touch main.py
^^^^
SyntaxError: invalid syntax

### Expected behavior

Not to error. Or, start things like,

_Let's start with the first step of the plan: "Create a new folder called 'My Project'"._

Without instruction.

### Open Interpreter version

v0.1.4

### Python version

3.11.3

### Operating System name and version

Microsoft Windows 11 Pro [Version 10.0.22621.2134]

### Additional context

**Computer Specs:**

Specs below
Machine Type: AMD64
Processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel, 11th Gen Intel(R) Core(TM) i911950H @2.60GHz
GPU: Nvidia RTX A5000 16GB GDDR6
Python Compiler: MSC v.1934 64 bit (AMD64)
Python Build: v3.11.3:f3909b8
OS Name Microsoft Windows 11 Pro
Version 10.0.22621 Build 22621
System Manufacturer Dell Inc.
System Model Precision 7760
System Type x64-based PC
Processor 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz, 2611 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date Dell Inc. 1.18.0, 11/15/2022
SMBIOS Version 3.2
Embedded Controller Version 255.255
BIOS Mode UEFI
BaseBoard Manufacturer Dell Inc.
BaseBoard Product 0H3D01
BaseBoard Version A01
Platform Role Mobile
Secure Boot State On
PCR7 Configuration Elevation Required to View
Windows Directory C:\WINDOWS
System Directory C:\WINDOWS\system32
Boot Device \Device\HarddiskVolume1
Locale United States
Hardware Abstraction Layer Version = "10.0.22621.1413"
Installed Physical Memory (RAM) 128 GB
Total Physical Memory 127 GB
Available Physical Memory 108 GB
Total Virtual Memory 135 GB
Available Virtual Memory 114 GB
Page File Space 8.00 GB
Page File C:\pagefile.sys
Kernel DMA Protection On
Virtualization-based security Not enabled
Windows Defender Application Control policy Enforced
Windows Defender Application Control user mode policy Off
Device Encryption Support Elevation Required to View
Hyper-V - VM Monitor Mode Extensions Yes
Hyper-V - Second Level Address Translation Extensions Yes
Hyper-V - Virtualization Enabled in Firmware Yes
Hyper-V - Data Execution Protection Yes

-----------------

**pip list below**
aiobotocore 2.4.2
aiofiles 22.1.0
aiohttp 3.8.3
aioitertools 0.7.1
aiosignal 1.2.0
aiosqlite 0.18.0
alabaster 0.7.12
anaconda-catalogs 0.2.0
anaconda-client 1.12.0
anaconda-navigator 2.4.2
anaconda-project 0.11.1
ansicon 1.89.0
anyio 3.5.0
appdirs 1.4.4
argon2-cffi 21.3.0
argon2-cffi-bindings 21.2.0
arrow 1.2.3
asgiref 3.7.2
astor 0.8.1
astroid 2.14.2
astropy 5.1
asttokens 2.2.1
async-timeout 4.0.2
atomicwrites 1.4.0
attrs 22.1.0
Automat 20.2.0
autopep8 1.6.0
Babel 2.11.0
backcall 0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile 1.0
backports.weakref 1.0.post1
bcrypt 3.2.0
beautifulsoup4 4.12.2
binaryornot 0.4.4
black 0.0
bleach 4.1.0
blessed 1.20.0
blosc2 2.0.0
bokeh 3.2.1
boltons 23.0.0
boto3 1.24.28
botocore 1.27.59
Bottleneck 1.3.5
brotlipy 0.7.0
certifi 2023.7.22
cffi 1.15.1
chardet 4.0.0
charset-normalizer 2.0.4
click 8.0.4
cloudpickle 2.2.1
clyent 1.2.2
colorama 0.4.6
colorcet 3.0.1
comm 0.1.3
conda 23.7.2
conda-build 3.26.0
conda-content-trust 0+unknown
conda_index 0.2.3
conda-libmamba-solver 23.5.0
conda-pack 0.6.0
conda-package-handling 2.2.0
conda_package_streaming 0.9.0
conda-repo-cli 1.0.41
conda-token 0.4.0
conda-verify 3.4.2
constantly 15.1.0
contourpy 1.0.5
cookiecutter 1.7.3
cryptography 41.0.2
cssselect 1.1.0
cycler 0.11.0
Cython 3.0.2
cytoolz 0.12.0
daal4py 2023.1.1
dask 2023.6.0
datashader 0.15.1
datashape 0.5.4
debugpy 1.6.7
decorator 5.1.1
defusedxml 0.7.1
diff-match-patch 20200713
dill 0.3.6
diskcache 5.6.3
distributed 2023.6.0
Django 4.2.5
docstring-to-markdown 0.11
docutils 0.18.1
entrypoints 0.4
et-xmlfile 1.1.0
executing 1.2.0
fastjsonschema 2.16.2
filelock 3.9.0
flake8 6.0.0
Flask 2.2.2
fonttools 4.25.0
frozenlist 1.3.3
fsspec 2023.3.0
fst-pso 1.8.1
future 0.18.3
FuzzyTM 2.0.5
gensim 4.3.0
git-python 1.0.3
gitdb 4.0.10
GitPython 3.1.36
glob2 0.7
greenlet 2.0.1
h5py 3.7.0
HeapDict 1.0.1
holoviews 1.17.0
huggingface-hub 0.16.4
hvplot 0.8.4
hyperlink 21.0.0
idna 3.4
imagecodecs 2021.8.26
imageio 2.26.0
imagesize 1.4.1
imbalanced-learn 0.10.1
importlib-metadata 6.8.0
incremental 21.3.0
inflection 0.5.1
iniconfig 1.1.1
inquirer 3.1.3
intake 0.6.8
intervaltree 3.1.0
ipykernel 6.22.0
ipython 8.12.0
ipython-genutils 0.2.0
ipywidgets 8.0.4
isort 5.9.3
itemadapter 0.3.0
itemloaders 1.0.4
itsdangerous 2.0.1
jaraco.classes 3.2.1
jedi 0.18.2
jellyfish 0.9.0
Jinja2 3.1.2
jinja2-time 0.2.0
jinxed 1.2.0
jmespath 0.10.0
joblib 1.2.0
json5 0.9.6
jsonpatch 1.32
jsonpointer 2.1
jsonschema 4.17.3
jupyter 1.0.0
jupyter_client 8.1.0
jupyter-console 6.6.3
jupyter_core 5.3.0
jupyter-events 0.6.3
jupyter-server 1.23.4
jupyter_server_fileid 0.9.0
jupyter_server_ydoc 0.8.0
jupyter-ydoc 0.2.4
jupyterlab 3.6.3
jupyterlab-pygments 0.1.2
jupyterlab_server 2.22.0
jupyterlab-widgets 3.0.5
keyring 23.13.1
kiwisolver 1.4.4
lazy_loader 0.2
lazy-object-proxy 1.6.0
libarchive-c 2.9
libmambapy 1.4.1
linkify-it-py 2.0.0
litellm 0.1.693
llama_cpp_python 0.2.6
llvmlite 0.40.0
lmdb 1.4.1
locket 1.0.0
lxml 4.9.2
lz4 4.3.2
Markdown 3.4.1
markdown-it-py 2.2.0
MarkupSafe 2.1.1
matplotlib 3.7.1
matplotlib-inline 0.1.6
mccabe 0.7.0
mdit-py-plugins 0.3.0
mdurl 0.1.0
menuinst 1.4.19
miniful 0.0.6
mistune 0.8.4
mkl-fft 1.3.6
mkl-random 1.2.2
mkl-service 2.4.0
more-itertools 8.12.0
mpmath 1.3.0
msgpack 1.0.3
multidict 6.0.2
multipledispatch 0.6.0
munkres 1.1.4
mypy-extensions 0.4.3
navigator-updater 0.4.0
nbclassic 0.5.5
nbclient 0.5.13
nbconvert 6.5.4
nbformat 5.7.0
nest-asyncio 1.5.6
networkx 3.1
nltk 3.8.1
notebook 6.5.4
notebook_shim 0.2.2
numba 0.57.0
numexpr 2.8.4
numpy 1.26.0
numpydoc 1.5.0
open-interpreter 0.1.4
openai 0.27.10
openpyxl 3.0.10
packaging 23.0
pandas 1.5.3
pandocfilters 1.5.0
panel 1.2.1
param 1.13.0
paramiko 2.8.1
parsel 1.6.0
parso 0.8.3
partd 1.2.0
pathlib 1.0.1
pathspec 0.10.3
patsy 0.5.3
pep8 1.7.1
pexpect 4.8.0
pickleshare 0.7.5
Pillow 9.4.0
pip 23.2.1
pkginfo 1.9.6
platformdirs 3.2.0
plotly 5.9.0
pluggy 1.0.0
ply 3.11
pooch 1.4.0
poyo 0.5.0
prometheus-client 0.14.1
prompt-toolkit 3.0.38
Protego 0.1.16
psutil 5.9.4
ptyprocess 0.7.0
pure-eval 0.2.2
py-cpuinfo 8.0.0
pyarrow 11.0.0
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycodestyle 2.10.0
pycosat 0.6.4
pycparser 2.21
pyct 0.5.0
pycurl 7.45.2
PyDispatcher 2.0.5
pydocstyle 6.3.0
pyerfa 2.0.0
pyflakes 3.0.1
pyFUME 0.2.25
Pygments 2.14.0
PyJWT 2.4.0
pylint 2.16.2
pylint-venv 2.3.0
pyls-spyder 0.4.0
PyNaCl 1.5.0
pyodbc 4.0.34
pyOpenSSL 23.2.0
pyparsing 3.0.9
PyQt5 5.15.7
PyQt5-sip 12.11.0
PyQtWebEngine 5.15.4
pyreadline3 3.4.1
pyrsistent 0.18.0
PySocks 1.7.1
pytest 7.4.0
python-dateutil 2.8.2
python-dotenv 1.0.0
python-editor 1.0.4
python-json-logger 2.0.7
python-lsp-black 1.2.1
python-lsp-jsonrpc 1.0.0
python-lsp-server 1.7.2
python-slugify 5.0.2
python-snappy 0.6.1
pytoolconfig 1.2.5
pytz 2022.7
pyviz-comms 2.3.0
PyWavelets 1.4.1
pywin32 306
pywin32-ctypes 0.2.0
pywinpty 2.0.10
PyYAML 6.0
pyzmq 25.0.2
QDarkStyle 3.0.2
qstylizer 0.2.2
QtAwesome 1.2.2
qtconsole 5.4.2
QtPy 2.2.0
queuelib 1.5.0
readchar 4.0.5
regex 2022.7.9
requests 2.31.0
requests-file 1.5.1
requests-toolbelt 1.0.0
rfc3339-validator 0.1.4
rfc3986-validator 0.1.1
rich 13.5.3
rope 1.7.0
Rtree 1.0.1
ruamel.yaml 0.17.21
ruamel-yaml-conda 0.17.21
s3fs 2023.3.0
s3transfer 0.6.0
sacremoses 0.0.43
scikit-image 0.20.0
scikit-learn 1.3.0
scikit-learn-intelex 20230426.121932
scipy 1.10.1
Scrapy 2.8.0
seaborn 0.12.2
Send2Trash 1.8.0
sentencepiece 0.1.99
service-identity 18.1.0
setuptools 68.0.0
simpful 2.11.0
sip 6.6.2
six 1.16.0
smart-open 5.2.1
smmap 5.0.1
sniffio 1.2.0
snowballstemmer 2.2.0
sortedcontainers 2.4.0
soupsieve 2.4
Sphinx 5.0.2
sphinxcontrib-applehelp 1.0.2
sphinxcontrib-devhelp 1.0.2
sphinxcontrib-htmlhelp 2.0.0
sphinxcontrib-jsmath 1.0.1
sphinxcontrib-qthelp 1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder 5.4.3
spyder-kernels 2.4.3
SQLAlchemy 1.4.39
sqlparse 0.4.4
stack-data 0.6.2
statsmodels 0.14.0
sympy 1.11.1
tables 3.8.0
tabulate 0.8.10
TBB 0.2
tblib 1.7.0
tenacity 8.2.2
terminado 0.17.1
text-unidecode 1.3
textdistance 4.2.1
threadpoolctl 2.2.0
three-merge 0.1.1
tifffile 2021.7.2
tiktoken 0.4.0
tinycss2 1.2.1
tldextract 3.2.0
tokentrim 0.1.10
toml 0.10.2
tomlkit 0.11.1
toolz 0.12.0
tornado 6.2
tqdm 4.65.0
traitlets 5.9.0
transformers 2.1.1
Twisted 22.10.0
twisted-iocpsupport 1.0.2
typing_extensions 4.8.0
tzdata 2023.3
uc-micro-py 1.0.1
ujson 5.4.0
Unidecode 1.2.0
urllib3 1.26.16
w3lib 1.21.0
watchdog 2.1.6
wcwidth 0.2.6
webencodings 0.5.1
websocket-client 0.58.0
Werkzeug 2.2.3
wget 3.2
whatthepatch 1.0.2
wheel 0.38.4
widgetsnbextension 4.0.5
win-inet-pton 1.1.0
wrapt 1.14.1
xarray 2023.6.0
xlwings 0.29.1
xyzservices 2022.9.0
y-py 0.5.9
yapf 0.31.0
yarl 1.8.1
ypy-websocket 0.8.2
zict 2.2.0
zipp 3.11.0
zope.interface 5.4.0
zstandard 0.19.0

**Comment by ericrallen** [comment]
I'm going to close this one as `readline` support was temporarily removed several versions ago and I don't think this is an issue with the latest version of Open Intepreter.

Please feel encouraged to reopen the issue if I'm wrong.
