### ISSUE TITLE
How to completely remove items from the computer?

### ISSUE THREAD

**Issue by lipppchen** [KillianLucas/open-interpreter#436]
### Is your feature request related to a problem? Please describe.

All I can say is that at this stage interpre-local doesn't work at all.

### Describe the solution you'd like

I downloaded the 34G package, did I delete the package and remove it completely?

**Comment by Dix01** [comment]
C:\Users\USERNAME\AppData\Local\Open Interpreter\Open Interpreter\models is where youll find the downloaded models. delete them from there.

**Comment by okhach** [comment]
> C:\Users\USERNAME\AppData\Local\Open Interpreter\Open Interpreter\models is where youll find the downloaded models. delete them from there.

Hi Dix01, How about on Mac? I used miniconda to install Open Interpreter.
