### ISSUE TITLE
Editing .env on a Mac

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#438]
Can you tell me howto edit the .env file so I can have more control on the (possible) settings like prompt etc (looked into the location of the pip install but it wasn't there). Also can't set the API key by default. Doesn't accept the ones I set via export.

Thanks!

**Comment by markstrom** [comment]
I had the same issue with the API key. Just asked Interpreter to do it for me.

**Comment by stevenbaert** [comment]
How would you do that? I tried several ways to ask, but didn't want to answer.

**Comment by markstrom** [comment]
> How would you do that? I tried several ways to ask, but didn't want to answer.

I wrote "Add my OpenAI API Key, so it's available every time a start a new shell."

**Comment by stevenbaert** [comment]
show me my OpenAI API key
                                                                                
  I'm sorry, but as an AI, I don't have access to personal data unless it has   
  been shared with me in the course of our conversation. ...

Whatever I try: show, give, adapt. Always same answer. Same goes for any other option I want to change, like using gpt-4-32k or change system prompt etc. Things you could do using the github repo. I did look for the install location of Open Interpeter but no config files found there.

**Comment by markstrom** [comment]
You obviously have to know your OpenAI API Key.

**Comment by stevenbaert** [comment]
Of course, that's not the point. If I didn't know it, the Interpreter wouldn't work.

**Comment by ericrallen** [comment]
Hey there, @stevenbaert!

You can use [config files](https://github.com/KillianLucas/open-interpreter#configuration) for this.

Just as a note, in your example of asking for your API key, the LLM doesn’t “know” what your API key is.

You could ask something like “echo my OPENAI_API_KEY” to have Open Interpreter execute an `echo` with the environment variable.

I’m going to close this one as the `-config` and `-config_file` ages should cover it, but feel free to reopen if there’s an an Issue to discuss.
