### ISSUE TITLE
how do u implant code interpreter in your environment? & hugging face

### ISSUE THREAD

**Issue by guruk** [KillianLucas/open-interpreter#441]
### Is your feature request related to a problem? Please describe.

i have code interpreter running on my local machine and on my aws ec2 system.
so far so good.

still i think whats the best way to create an app that connects with ai and is for public access.

- on my local machine, nice to develop, also not accessible from outside. (i dont like to let it run 24/7)
- on my aws, ok, i got my domain connected, my python app is running.
- now whats about hugging face, i like them a lot, also i still dont understand them in all.
   is there a way to run my whole project that is by now on aws on huggingface, or is this all through this yupiter notebook (what i still dont understand)
   
   so just as a brainstorm, to build a scaleable app that uses databases, python and the nlp of ai's to understand the user input, how would u set it up. fast scaleable, easy to maintain. :) just the best. lol.
   
   

### Describe the solution you'd like

no solution so far, more questions.

**Comment by guruk** [comment]
btw i think there is huge potential in this group here. code interpreter , awesome job killianlucas btw, became my favorite tool to work with ai. its back to command line, and directly in the system. i think a few versions in the future it will be one of the most useful tools.

**Comment by ericrallen** [comment]
Hey there, @guruk!

I’m going to close this one as it’s not really an Issue.

You might want to take this discussion to the [Discord](https://discord.gg/6p3fD6rBVm), though.
