### ISSUE TITLE
Parser error due unterminated string literal

### ISSUE THREAD

**Issue by ElCuboNegro** [KillianLucas/open-interpreter#443]
### Describe the bug

Lots of errors of this kind: Parser error due unterminated string literal

───────────────────────────────────────────────────────────────────────────────
> please generate a jupyter notebook that allows and explains all the flow process behind Stripe, from the moment a user adds a creadit card, when the system asks for a payment, to the moment when a user cancells or asks for a refund

  Sure, I can help with that. Here's a high-level plan of what we're going to do:

   1 Install necessary Python packages (if not already installed): nbformat for creating Jupyter notebooks
     programmatically, and stripe for interacting with the Stripe API.
   2 Create a new Jupyter notebook using nbformat.
   3 Add sections to the notebook explaining and demonstrating each step of the Stripe flow process:
      • Adding a credit card
      • Making a payment
      • Cancelling a payment
      • Requesting a refund
   4 Save the notebook to a file.

  Let's start with step 1: installing the necessary Python packages. If you already have these packages installed, you
  can skip this step.

  import pkg_resources

  REQUIRED_PACKAGES = ['nbformat', 'stripe']

  for package in REQUIRED_PACKAGES:
      try:
          dist = pkg_resources.get_distribution(package)
          print('{} ({}) is installed'.format(dist.key, dist.version))
      except pkg_resources.DistributionNotFound:
          print('{} is NOT installed'.format(package))

  nbformat (5.7.0) is installed
  stripe (6.5.0) is installed

  Great, both nbformat and stripe Python packages are already installed on your system.

  Now, let's move to step 2: creating a new Jupyter notebook using nbformat. We'll start by creating a new notebook
  and adding a title and an introductory section.

  import nbformat as nbf

  # Create a new notebook
  nb = nbf.v4.new_notebook()

  # Add a title
  nb['cells'].append(nbf.v4.new_markdown_cell('# Stripe Flow Process'))

  # Add an introductory section
  intro = (
      'This notebook explains and demonstrates the flow process in Stripe, '
      'from the moment a user adds a credit card, when the system asks for a payment, '
      'to the moment when a user cancels or asks for a refund.'
  )
  nb['cells'].append(nbf.v4.new_markdown_cell(intro))

  nb

  {'nbformat': 4, 'nbformat_minor': 5, 'metadata': {}, 'cells': [{'id': '638d19e4', 'cell_type': 'markdown', 'source':
  '# Stripe Flow Process', 'metadata': {}}, {'id': '78ffb8db', 'cell_type': 'markdown', 'source': 'This notebook
  explains and demonstrates the flow process in Stripe, from the moment a user adds a credit card, when the system
  asks for a payment, to the moment when a user cancels or asks for a refund.', 'metadata': {}}]}

  The Jupyter notebook has been successfully created with a title and an introductory section.

  Next, we'll add sections to the notebook explaining and demonstrating each step of the Stripe flow process. We'll
  start with the section on adding a credit card.

  Please note that for security reasons, we won't be able to run actual transactions using Stripe in this notebook.
  We'll just show the code and explain what it does.

  add_card_section = (
      '## Adding a Credit Card\n'
      '\n'
      'To add a credit card in Stripe, you would typically create a new customer or use an existing one, '
      'then attach a new payment method to the customer. Here is an example of how you might do this in Python:\n'
      '\n'
      '```python\n'
      'import stripe\n'
      '\n'
      '# Set your secret key. Remember to switch to your live secret key in production!\n'
      'stripe.api_key =

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jalba\anaconda3\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 938, in respond
    self.respond()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 938, in respond
    self.respond()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jalba\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\jalba\anaconda3\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 12
    'stripe.api_key =
    ^
SyntaxError: unterminated string literal (detected at line 12)

### Reproduce

Go to terminal.
- Install Open Interpreter
- Ask for any run that interoperates between python and the file system.
- Eventually it will explode

### Expected behavior

the process continue without crash

### Open Interpreter version

0.14

### Python version

3.11

### Operating System name and version

Windows 11

### Additional context

No other provided, entire trace already given.

**Comment by AncalagonX** [comment]
Similar `unterminated string literal` errors that completely crash open-interpreter. It's the most frustrating bug right now.

**Comment by ericrallen** [comment]
Hey there, @ElCuboNegro and @AncalagonX!

can you confirm if this is still an issue with the latest version of Open Interpreter

**Comment by ElCuboNegro** [comment]
I'll verify and add the test

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if you experience the issue with the latest version of Open Interpreter.
