### ISSUE TITLE
'gbk' codec can't decode byte 0x80 in position 30: illegal multibyte sequence

### ISSUE THREAD

**Issue by Roych13** [KillianLucas/open-interpreter#446]
### Describe the bug

when read the file, the programm cannot decode for chinese charaters.

### Reproduce

interpreter -f
interpreter.chat('please read the file test.xlsx and tell me the first 5 rows data')

### Expected behavior

I want to fix the bug so that it can read file with chinese charater column names.

### Screenshots

![屏幕截图 2023-09-19 213806](https://github.com/KillianLucas/open-interpreter/assets/39145668/eb9d879d-b934-4b62-9c86-92601e746681)

### Open Interpreter version

latest

### Python version

3.11.3

### Operating System name and version

win11

**Comment by ericrallen** [comment]
Hey there, @Roych13!

Can you confirm if this is still an issue with the most recent of Open Interpreter?

**Comment by Roych13** [comment]
> Hey there, @Roych13!
> 
> Can you confirm if this is still an issue with the most recent of Open Interpreter?

I will check it for someday recently, because now it shows  the error i "The server is overloaded" about OpenAI.

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if you experience the issue with the latest version of Open Interpreter.
