### ISSUE TITLE
Cannot print files containing [/USER]

### ISSUE THREAD

**Issue by mathiasrw** [KillianLucas/open-interpreter#448]
### Describe the bug

Markdown is being affected by the content of files being printed to the user. 

Any file containing `[/xyz]` (xyz = any string) will halt the printing of the file and panic the program.

```
object refcount : 2
object type     : 0x102e04810
object type name: MarkupError
object repr     : MarkupError("closing tag '[/USER]' at position 609 doesn't match any open tag")
lost sys.stderr
```

### Reproduce

1. Make a file with [/BBB]
	- `>  echo "A\n[/BBB]\nC" > test.js`
3. Ask the interpreter to read the content for some reason. 
	- `> please run `cat test.js`

### Expected behavior

The content of the file is printed

### Screenshots

<img width="551" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/1063454/0ac887e0-864f-489c-82cc-725ab7335690">

<img width="556" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/1063454/aa7efa5a-b80f-41ea-8f46-378a506008c0">

### Open Interpreter version

0.1.4

### Python version

3.11.5

### Operating System name and version

MacOS 12.6

**Comment by ericrallen** [comment]
Hey there, @mathiasrw!

Can you give us some info about what model you were using and if you still experience this issue with the latest version of Open Interpreter?

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
