### ISSUE TITLE
interpreter.reset() throws an error

### ISSUE THREAD

**Issue by DaliborBoldis** [KillianLucas/open-interpreter#449]
### Describe the bug

When using an interpreter.reset() command in the Powershell terminal, I get following error:

At line:1 char:19
+ interpreter.reset()
+                   ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpressionthe 

I am unable to clear the conversation history, and has to do that manually every time.

### Reproduce

Normal installation on Windows 11.

### Expected behavior

Should clear interpreter conversation history.

### Screenshots

https://prnt.sc/Q1sfb09vfwsS

### Open Interpreter version

0.1.1

### Python version

3.11.4

### Operating System name and version

Windows 11

**Comment by ericrallen** [comment]
Going to close this one as it’s for an older version of Open Interpreter.

Feel free to reopen if you upgrade and still experience this issue.
