### ISSUE TITLE
[Feature Request] Raycast Extension

### ISSUE THREAD

**Issue by jag-k** [KillianLucas/open-interpreter#45]
This project looks wonderful! And I think it will be a great addition to be able as an extension for [Raycast](https://raycast.com).

I want to try (re-)impement using the new Raycast AI feature, and it would be great if you could help me out with this.

**Comment by galligan** [comment]
Yes! Would love to see this. Subscribe.

**Comment by Binary-Bytes** [comment]
Yeah that would be cool.

**Comment by alifanov** [comment]
+1

**Comment by wowdd1** [comment]
+1

**Comment by MikeBirdTech** [comment]
This has been started here: https://github.com/Cobular/raycast-openinterpreter
