### ISSUE TITLE
Resume complex tasks after interrupt

### ISSUE THREAD

**Issue by mikeda100** [KillianLucas/open-interpreter#450]
### Describe the bug

HI all,

I am reproducing the sample in the demo Colab: "YouTube Link -> Animation".

It listed out 10 steps to do. 

But it hangs after 3 steps, due to the downloading gave a lot of troubles and it spent a lot of retries in downloading the video from YouTube until finally it successfully downloaded the video. 

After it hangs, I interrupt the kernel (I am using Jupyter Lab) and then use "interpreter.chat("continue") "  to ask it to continue. 

But it hangs again shortly.

And then I interrupt the kernel a few times and then use  "interpreter.chat("continue") " a few times. But it doesn't go anywhere and keeps freezing forever.

Please help! What can I do?

My questions:

1. Is there a way to save all the "state-map", so if I kill the whole Jupyter Lab and restart everything from scratch, it should resume from the "broken-point", without retrying the downloading stuff again and again.

2. Why didn't my approach work? i.e. "interrupt the kernel and then use "interpreter.chat("continue")" ...
It just keeps freezing without going anywhere....

### Reproduce

please run the sample in demo Colab:  "YouTube Link -> Animation".

### Expected behavior

it should get results like in the demo Colab ... 
it should be able to fulfill the task in a few steps.

### Open Interpreter version

0.1.4

### Python version

3.11.4

### Operating System name and version

Win 10

**Comment by ericrallen** [comment]
Hey there, @mikeda100!

Have you tried this with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if you experience the issue with the latest version of Open Interpreter.
