### ISSUE TITLE
Is it possible to retrieve input and output of gpt api ?

### ISSUE THREAD

**Issue by pezou45** [KillianLucas/open-interpreter#451]
### Is your feature request related to a problem? Please describe.

I search but i couldn't find where is the api call. Is it possible to retrieve the input that is sent to gpt4 api and the output that gpt sends back to the user ?

### Describe the solution you'd like

A simple way to retrieve what open interpreter sends to gpt api and what gpt api sends back to open interpreter.

**Comment by ericrallen** [comment]
Can you be more specific about what you're looking for here?

Does `debug_mode`, the `%debug` magic command, or the `messages` array not provide what you need?

**Note**: In the future, opening a [duplicate issue](https://github.com/KillianLucas/open-interpreter/issues/696) will de-prioritize your existing issues from triage.

**Comment by pezou45** [comment]
Thank you
Debug mode is close to what i need, but i would like to be able to run the programme without llm at all. For example, i would put my request, then it will show the input like in debug mode but it will wait for me to send it back the output myself. Is there a way to do that ?

**Comment by ericrallen** [comment]
I’m not sure I understand what you’re asking for here.

Can you provide an example exchange that illustrates what you are asking about?

This part

> without LLM at all 

is a bit confusing as Open Interpreter is a way to interface with an LLM.

**Comment by pezou45** [comment]
For example i would like to replace openai api with my own api. So i would type my request in the programm, then instead of sending the complete input (request + open interpreter instructions) to openai api or local llm, it would send the request to my own api and it will wait for the ouptut sended back by my api. This would be the best, or someway to have a manual mode where the programm don't send the request to openai and instead, it would just show the input (like in debug mode) but without sending anything and i would wait for me or another program to retrieve the output

**Comment by ericrallen** [comment]
Using your own API is supported by LiteLLM, which Open Interpreter uses under the hood.

There is information about it in [this issue](https://github.com/KillianLucas/open-interpreter/issues/398#issuecomment-1779175123) and the LiteLLM docs if you search for `api_base`.

**Comment by pezou45** [comment]
Thank you so much, it worked!
