### ISSUE TITLE
How to show Latex in output?

### ISSUE THREAD

**Issue by mikeda100** [KillianLucas/open-interpreter#454]
### Is your feature request related to a problem? Please describe.

Hi all,

I am following one example and ask GPT-4 to do math:

![image](https://github.com/KillianLucas/open-interpreter/assets/128166104/e1dc5f63-3805-41b6-9dfc-ba920e07e7f4)

But it doesn't show outputeed equations in Latex.

Even though I prompted specifically to GPT-4: "make sure you show equations in Latex on screen", it still doesn't show Latex equations.

What might be wrong?

Thanks!

### Describe the solution you'd like

Show math visually and graphically in the output.

**Comment by mikeda100** [comment]
If I separately try the above Python code snippet in Jupyter Notebook, it actaully can show math equations visually and graphically.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
