### ISSUE TITLE
Configurable Multi-line Input with SHIFT-ENTER

### ISSUE THREAD

**Issue by leotulipan** [KillianLucas/open-interpreter#455]
### Is your feature request related to a problem? Please describe.

When pasting in Windows to a terminal window the pasted text gets submitted right after the first line. This also interferese e.g. with y/n asking for execution as the next line will be pastes as answer there

### Describe the solution you'd like

**Background:**  
When interacting with the OpenInterpreter script via the Windows Terminal, pasting multi-line inputs using CTRL-V submits the command immediately after the first line. This behavior disrupts workflows that rely on multi-line input pasting.

**Feature Request:**

1. **SHIFT-ENTER for Multi-line Inputs**: 
   - When the user presses SHIFT-ENTER, the input should not be submitted, but rather a new line should be added for continued input.
   - The regular ENTER key should not submit multi-line input unless SHIFT is also pressed.

2. **CTRL-V Pasting Behavior**:
   - When pasting multi-line text with CTRL-V, the input should not be auto-submitted after the first line.

3. **Configurable Via argparse**:
   - Implement an argparse switch to configure this behavior, allowing users to toggle between the standard behavior and the new SHIFT-ENTER behavior.

**Reasoning:**  
The current behavior makes it cumbersome to work with multi-line inputs, especially when pasting. Offering a configurable option to control the submission behavior can significantly enhance user experience and flexibility.

**Comment by cschubiner** [comment]
this would be soooo nice to have

**Comment by dagelf** [comment]
Another suggestion: continue input for next lines if there is a quote that is not closed eg. if you add \' or \" and paste

**Comment by Swiffers** [comment]
current hack: paste your multi-line prompts inside a file, start the open interpreter, ask it "your commands on inside this file: file.txt"

**Comment by ericrallen** [comment]
Hey there, folks!

Input handling is on the radar, but I’d like to consolidate the conversation into a single thread.

I’m going to close this one in favor of the first issue that mentioned input challenges: #117 

Please feel encouraged to continue discussing this issue  in that thread.

**Comment by pinggit** [comment]
hi what's the solution today?
seems like I can only input one line questions.

**Comment by cschubiner** [comment]
yeah, this is still broken to this day (8/25/24)

**Comment by LucasMatuszewski** [comment]
It looks like it was finally fixed, at least on Ubuntu 24.
Try to use `"""` in REPL mode and then just hit enter for a new line, or paste.

Works for me fine. THX! OI is great :)
