### ISSUE TITLE
How do i replace the gpt4 key

### ISSUE THREAD

**Issue by TONGlong520** [KillianLucas/open-interpreter#456]
### Is your feature request related to a problem? Please describe.

How do i replace the gpt4 key

### Describe the solution you'd like

How do i replace the gpt4 key

### Describe alternatives you've considered

How do i replace the gpt4 key

### Additional context

How do i replace the gpt4 key

**Comment by Hackdwerg** [comment]
Run "man export" in your terminal, read it, how hard is it and how is this an issue. 

Just in case you stay lazy:
https://www.javatpoint.com/linux-export-command

**Comment by blue-ethan** [comment]
> Run "man export" in your terminal, read it, how hard is it and how is this an issue.在你的终端中运行“man export”，阅读它，它有多难，这是一个问题。
> 
> Just in case you stay lazy:以防万一你偷懒：

Lmao，You're so adorable, I like you.

**Comment by TONGlong520** [comment]
这是什么，看不明白，但谢谢你回复我

HD ***@***.***> 于 2023年9月24日周日 00:44写道：

**Comment by TONGlong520** [comment]
谢谢你回复

blue-ethan ***@***.***> 于 2023年9月29日周五 09:27写道：
