### ISSUE TITLE
Is anyone else finding that this is just not usable ATM?

### ISSUE THREAD

**Issue by ryangdar** [KillianLucas/open-interpreter#460]
### Describe the bug

I like the theory behind it, but I see two concerns:

1. The costs are insane due to the fact that it keeps failing and trying something new (poor iterative querying). Within 10 minutes of usage, it had racked up about $5 on GPT4. 
2. Most open source LLM's at the moment are not runnable by the average consumer. I have 64GB RAM on my computer (way better than the average consumer), and it takes like 2 hours to perform simple tasks using a 30GB LLAMA model. For the smaller models, they're so poor performing that even if they run quicker they're not able to figure out the problem. 

I feel like this would be so much better if there existed an auto-GPT API. Basically like GPT, but with historical evidence about what works and what doesn't that way it finds the least amount of API queries to solve a problem. 

I feel like someday this will be great, but for now it's out of reach of most people due to prohibitive costs or too large of language models. 

### Reproduce

Trying to download LLAMA and running on your computer or really running any task with the GPT4 API. 

### Expected behavior

I expected that it would have performed better with local models on my computer. Quicker and better responses.

### Screenshots

No screenshots.

### Open Interpreter version

Current 

### Python version

Current 

### Operating System name and version

MacOSX

### Additional context

Just an open discussion

**Comment by iwaduarte** [comment]
There has also been a poor lack of improvements;/features/bug fixes since its launch.  I believe the devs are more interested in the desktop application than anything else because I keep seeing an increase in issues and PR and the pace of integration is slow for such a successful idea/product.

**Comment by AncalagonX** [comment]
> There has also been a poor lack of improvements;/features/bug fixes since its launch. I believe the devs are more interested in the desktop application than anything else because I keep seeing an increase in issues and PR and the pace of integration is slow for such a successful idea/product.

This is a fantastic initial implementation! Sadly, it keeps crashing when writing scripts due to what seems to be poorly handled strings-within-strings and other exceptions.

**Comment by winterdelta** [comment]
The associated costs should be mentioned in the README - there could be a hazard warning, as an example.

**Comment by ericrallen** [comment]
Going to close this one as it’s really just more of a discussion, which could be continued on [Discord](https://discord.gg/6p3fD6rBVm) rather than adding noise to the Issues.

Feel free to reopen if you feel like there’s still an Issue to address here and we can work on rephrasing the Issue and dig into it.
