### ISSUE TITLE
Interpreter should use the python version defined in the present virtual environment

### ISSUE THREAD

**Issue by ahmetax** [KillianLucas/open-interpreter#466]
### Is your feature request related to a problem? Please describe.

I'm using Ubuntu 22.04 and I have many versions of python. Mostly I use venv virtual environment. When I use interpreter --local with Llama 7B, it tries to run python scripts using system defined python which is Python2 by default. Is it possible to use interpreter to use venv python in order to execute python scripts. 
Also interpreter can not run its shell commands if I don't say it to use bash. That might be automatically used.

### Describe the solution you'd like

It will be useful if it can use virtual environmant.
Also it might check the shell system and use it in order to execute its suggested shell commands.

### Describe alternatives you've considered

I couldn't succeed how to define venv python.
But for the shell system, "use bash" prompt is useful in my conditions.

**Comment by ericrallen** [comment]
Hey there, @ahmetax!

Can you confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now, but feel encouraged to reopen it if the issue still happens.

We made some adjustments to how the subprocess interpreter is executed, so I _think_ it might be resolved.
