### ISSUE TITLE
Question- i can't seem to get it working pls help

### ISSUE THREAD

**Issue by ewswlw** [KillianLucas/open-interpreter#474]
### Describe the bug

First time playing around with it, but can't get it to write any code. Error msg below in the screenshot.

### Reproduce

have it downloaded but can't get it to write any code, look at screenshot. 

### Expected behavior

Supposed to write code. 

### Screenshots

![Capture](https://github.com/KillianLucas/open-interpreter/assets/93443727/9e33d612-01a3-4f27-b750-27d05d3db160)

### Open Interpreter version

newest

### Python version

Python 3.11.4

### Operating System name and version

Windows

**Comment by ihgalis** [comment]
First, can make sure that the API key you provided in the screenshot is not valid anymore because it will be misused otherwise by other people.

It seems your request to the OpenAI API was somehow malformed or OpenAIs backend just didn't understood what open-interpreter sent. Can you try again with "write me a python hello world", while using GPT4? And did you also try to use the locally running Code-LLama?

**Comment by samluise** [comment]
I have the same issue, and my API is valid.I tried a lot of times but got the same error.

**Comment by ihgalis** [comment]
@samluise in that case please provide more technical details. I don't find this issue on my Mac but I suppose you use Windos, too? "pip freeze" would be nice so that we know which packages you use.

**Comment by mayank-malhotra** [comment]
Your key doesnt have access to gpt-4 because you must not be the premium subscriber. 
Try using interpreter --fast (which will use the gpt3.5 which is free for all users)

**Comment by mocy** [comment]
I had the same issue with one of my openai account (which was created a long time ago). I had to cancel my payment method, and resubmit it. On resubmit, I got the option to pre-pay for the API, and got access to gpt-4 API.

It would be good to catch those kind of exceptions and return a user friendly message - or even better try to default to gpt-3.5, or a free option.

**Comment by ewswlw** [comment]
I had to cancel my payment method, and resubmit it. On resubmit, I got the option to pre-pay for the API, and got access to gpt-4 API.

thank you for your help
