### ISSUE TITLE
The open-interpreter change it own environment dependency when installing new python package by GPT model

### ISSUE THREAD

**Issue by alexxchen** [KillianLucas/open-interpreter#475]
### Describe the bug

After running serval analysis on the data, the open-interpreter break its own dependency, thus itself can not start to run anymore.

### Reproduce

unstable

### Expected behavior

Run the GPT-generated code with a sandbox, and maybe reset the sandbox every time the task is finished.

### Open Interpreter version

0.1.4

### Python version

3.10.9

### Operating System name and version

Ubuntu 16.04

**Comment by ihgalis** [comment]
I don't get how you produced the error. What was the exact path you went? Send us some screenshots what you tried. GPT4 will never run locally, at least not within our homes. Did you have issues with Code-LLama?

**Comment by alexxchen** [comment]
> I don't get how you produced the error. What was the exact path you went? Send us some screenshots what you tried. GPT4 will never run locally, at least not within our homes. Did you have issues with Code-LLama?

I mean open-interpreter pip intall the new packages into its own python environment when running tasks, the new package may have different dependency, which will  make open-interpreter unable to run in the next time. 

Sorry, I have already reinstalled the package, and the error message is unavailable. It is just a suggestion to run GPT-generated code in another separated python environment.

**Comment by alexxchen** [comment]
I will open an new issue of feature request.
