### ISSUE TITLE
Run the LLM-generated code in a sandbox

### ISSUE THREAD

**Issue by alexxchen** [KillianLucas/open-interpreter#477]
### Is your feature request related to a problem? Please describe.

The GPT-generated command on pip install new package can break open-interpreter dependency.

### Describe the solution you'd like

Run GPT-generated code in another separated python environment.

**Comment by alexxchen** [comment]
I made mofification to the system message by writing "For python, you should run python code after source the venv named sandbox in the directory you're currently in (run_code executes on the user's machine)."

Sometime it remember to source, but in most situation it fails.

**Comment by salvinoto** [comment]
This would be a very useful feature to have

**Comment by jakubno** [comment]
There's PR which would solve this #591
