### ISSUE TITLE
Node does not work when default shell is fish

### ISSUE THREAD

**Issue by rohanrajpal** [KillianLucas/open-interpreter#478]
### Describe the bug

Thanks a lot for working on this awesome project! It's an exponential productivity boooster.
I'm just facing a small issue. If i give a simple prompt like "get current node version", it just hangs forever. This only happens when the default shell is fish

### Reproduce

1. Change the default shell to fish `chsh -s $(which fish)`
2. Start open interpreter and give prompt "print node version"
3. Hangs forever

### Expected behavior

Node version should be printed

### Open Interpreter version

0.1.4

### Python version

3.11.4

### Operating System name and version

Macos Venture 13.5.2

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!

**Comment by endolith** [comment]
I think this is still unresolved.  Whenever open interpreter tries to run a plain command, it hangs indefinitely.  My shell is fish.
