### ISSUE TITLE
Interpreter errors out while printing css

### ISSUE THREAD

**Issue by rohanrajpal** [KillianLucas/open-interpreter#479]
### Describe the bug

<img width="1624" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/7023147/e180ddc0-23bd-4c5a-a0b3-c3e3020fd4ce">

### Reproduce

1. Rune code interpreter `interpreter -y`
2. Give it the prompt `create a pricing calculator based on spur-new-pricing.json, create the html, js for it and save it, html should have all the form elements necessary`
3. Here is the [file](https://pastebin.com/ut167hM0)
4. Interpreter works great but errors at the css part (ss attached)

### Expected behavior

Should not error out while printing css

### Open Interpreter version

0.1.4

### Python version

3.11.4

### Operating System name and version

Macos Venture 13.5.2

**Comment by ericrallen** [comment]
Hey there, @rohanrajpal!

I think this might have been resolved by #680.

If you have a chance to test it with the `main` branch before we do, please let us know if it’s fixed.

**Comment by ericrallen** [comment]
Going to close this one as stale (and possibly resolved) for now, but please feel encouraged to reopen it if the latest version of Open Interpreter still experiences this issue.
