### ISSUE TITLE
Unable to support Chinese correctly

### ISSUE THREAD

**Issue by nufeng1999** [KillianLucas/open-interpreter#486]
### Describe the bug

![WFq5ylpRG3](https://github.com/KillianLucas/open-interpreter/assets/28748029/8e808340-9604-48c6-a043-59a2e8532937)

### Reproduce

1.
where /R C:\Users\Administrator\Desktop "电梯.txt"

2.error
 C:\Users\Administrator>where /R C:\Users\Administrator\Desktop "������.txt"
  INFO: Could not find files for the given pattern(s).
  C:\Users\Administrator>

### Expected behavior

Perfect support for Chinese

### Screenshots

![Pyi8pb3vOR](https://github.com/KillianLucas/open-interpreter/assets/28748029/ecfd48e4-89dd-4ce2-a853-8a553706eba6)

### Open Interpreter version

0.1.4

### Python version

3.10.7

### Operating System name and version

Windows 11

**Comment by Emasoft** [comment]
I have the same issue. I have epubs with chinese names and it gives error.

**Comment by erayyym** [comment]
Is this bug fixed now?

**Comment by Notnaton** [comment]
Will be fixed the next update:
https://github.com/KillianLucas/open-interpreter/pull/799

**Comment by erayyym** [comment]
Thank you so much! When I saw this bug, I wanted to help! Good to know that it is already solved!
