### ISSUE TITLE
Add a flag to disable calls to https://open-procedures.replit.app/

### ISSUE THREAD

**Issue by medvedev1088** [KillianLucas/open-interpreter#487]
### Is your feature request related to a problem? Please describe.

The tool is sending user's messages to the Open Procedures API https://open-procedures.replit.app/ as can be seen here https://github.com/KillianLucas/open-interpreter/blob/c71078027fb6331adf9080c337802af73654c28d/interpreter/interpreter.py#L158

It's a privacy/security concern for some users.

### Describe the solution you'd like

Add a flag to disable this feature

**Comment by ericrallen** [comment]
Hey there, @medvedev1088!

I'm going to close this one as the `https://open-procedures.replit.app/` request has been removed in more recent versions of Open Interpreter.
