### ISSUE TITLE
I am not seeing any options to load model weights from disk.

### ISSUE THREAD

**Issue by phalexo** [KillianLucas/open-interpreter#489]
### Is your feature request related to a problem? Please describe.

I have several models installed already locally that I can use with other UIs. llama-cpp-python can load all the models with GGUF extensions.

Is there a way to prevent Open Interpreter from downloading model weights, and instead just take a path like llama-cpp does?

### Describe the solution you'd like

--model parameter itself should detect if something is a path or on the local system or an URL on HuggingFace and if a local path, just load a model from disk, or

--model_path parameter can be added for take a path.

**Comment by Notnaton** [comment]
@ericrallen We can close this one too, this is handled by LM Studio
