### ISSUE TITLE
Integrate a wake up word for use with speechgpt

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#490]
### Describe the solution you'd like

See https://github.com/Jdka1/SpeechGPT
Looks pretty straight forward to integrate this with the Interpreter.
The only thing is that Interpreter should limit the output like listing all the steps because they would be read all a loud.

F. e' "put screen in light modus", sure then only success or fail and if fail ask if it should try again or different thing.
Therefore Interpreter should have config in how output is, verbose/minimal etc.

**Comment by ericrallen** [comment]
Hey there, @stevenbaert!

While voice is super cool, I don’t know if we’re in a place where it makes sense to integrate it into the core project yet.

You should already be able to wrap Open Interpreter in your own Python script that can utilize voice as an input if this functionality is important to your workflows.

I’m going to close this one for now, but that doesn’t mean it won’t end up on the roadmap at some point.
