### ISSUE TITLE
Limit token usage by settings open interpreter 

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#491]
### Describe the solution you'd like

I used Open Interpreter, I pretty intensivelyfor a day and directly hit the OpenAI limit of 120 Dollar.
There has to be some optimization in settings or advise in way of use to limit the token size.
F. e. make use of cheaper engine gpt-3.5 or even Llama /code Llama in cases, where gpt-4 isn't needed like summarization of text. Also the steps in between and/or verbose output could be limited(?)
The tool is great but has to stay affordable....

**Comment by krrishdholakia** [comment]
I believe there is already a budget manager implemented in openinterpreter. Did that not work for you?

**Comment by ericrallen** [comment]
There is a `max_budget` setting, local models are available, and you can check out the new `%tokens` magic command to estimate your toke usage.

Closing as there are many options to try to help this.

Feel free to reopen if none of these are helpful and there’s more to discuss.
