### ISSUE TITLE
`import` interpreter error w/ new 0.1.5

### ISSUE THREAD

**Issue by jjfantini** [KillianLucas/open-interpreter#494]
### Describe the bug

It seems I can only access open-interpreter functions using an instantiated class of interpreter. 

### Reproduce

1. poetry add open-interpreter 
2. import interpreter
3. interpreter.chat() ... Error!

### Expected behavior

interpreter.chat() to run their functions.

### Screenshots

![interpreter](https://github.com/KillianLucas/open-interpreter/assets/63276164/ef72ac22-5ddf-4047-a5d2-121e1e081784)

### Open Interpreter version

0.1.5

### Python version

3.11.5

### Operating System name and version

Windows 11

**Comment by jjfantini** [comment]
Code:
```
import interpreter

messages = interpreter.chat("Hello", return_messages=True)
```

Error:
Traceback (most recent call last):
  File "c:\Users\jjfan\Cursor_WD\open-orghi\src\open-orghi\open_chat\test.py", line 3, in <module>
    messages = interpreter.chat("Hello", return_messages=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Interpreter.chat() got an unexpected keyword argument 'return_messages'

**Comment by ericrallen** [comment]
Closing as I believe this is fixed in the current version.

This is how we’re running our pytest tests.

Please reopen if you experience the issue with the latest version.
