### ISSUE TITLE
Trying to run open-interpreter. 

### ISSUE THREAD

**Issue by Dangasa98** [KillianLucas/open-interpreter#495]
### Describe the bug

Basically, the more technical people here can review what I wrote on cmd, and review the other information as context. if there is something in excess or missing, I will try to refine (it) and find out what (that) is.

So here it is, and I don't know if I should have interpreter file.py or not. Do not. downloaded codellama 34B 5km via powershell because of some error messages etc. had some issues with python 3.10 so basically tried running the poetry lock --no-update and edited a bunch of things in pyproject.toml to comply although a fresh install would have probably been quicker. even tried to set up anthropic but ran into some errors. anyways, you can find the python version and the error codes (or the absence of) in the following cmd instance.... ---> but before that let me mention that I don't have SIM for API-key, not interested in paid service nor in any attempts to acquire and use it. cmd... (tried running from Powershell without success and testing with python---)

C:\Users\peter\open-interpreter>poetry shell
Spawning shell within C:\Users\peter\AppData\Local\pypoetry\Cache\virtualenvs\open-interpreter-aMbMYQXW-py3.9

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>interpreter codellama-34b-instruct.Q5_K_M
usage: interpreter [-h] [-s SYSTEM_MESSAGE] [-l] [-y] [-d] [-m MODEL] [-t TEMPERATURE] [-c CONTEXT_WINDOW]
                   [-x MAX_TOKENS] [-b MAX_BUDGET] [-ab API_BASE] [-ak API_KEY] [--config] [--models]
                   [--conversations] [-f]
interpreter: error: unrecognized arguments: codellama-34b-instruct.Q5_K_M
(open-interpreter-py3.9) C:\Users\peter\open-interpreter>interpreter codellama-34b-instruct.Q5_K_M.gguf
usage: interpreter [-h] [-s SYSTEM_MESSAGE] [-l] [-y] [-d] [-m MODEL] [-t TEMPERATURE] [-c CONTEXT_WINDOW]
                   [-x MAX_TOKENS] [-b MAX_BUDGET] [-ab API_BASE] [-ak API_KEY] [--config] [--models]
                   [--conversations] [-f]
interpreter: error: unrecognized arguments: codellama-34b-instruct.Q5_K_M.gguf
(open-interpreter-py3.9) C:\Users\peter\open-interpreter>poetry show open-interpreter

Package open-interpreter not found

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: open-interpreter (0.1.5)

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: open-interpreter (0.1.5)

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>poetry show open-interpreter

Package open-interpreter not found

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>pip install open-interpreter==0.1.5
Requirement already satisfied: open-interpreter==0.1.5 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (0.1.5)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (1.4.4)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.8.1)
Requirement already satisfied: git-python<2.0.0,>=1.0.3 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (1.0.3)
Requirement already satisfied: huggingface-hub<0.17.0,>=0.16.4 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.16.4)
Requirement already satisfied: inquirer<4.0.0,>=3.1.3 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (3.1.3)
Requirement already satisfied: litellm<0.2.0,>=0.1.590 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.1.736)
Requirement already satisfied: openai<0.29.0,>=0.28.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.28.0)
Requirement already satisfied: pyreadline3<4.0.0,>=3.4.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (3.4.1)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (1.0.0)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (6.0.1)
Requirement already satisfied: rich<14.0.0,>=13.4.2 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (13.5.3)
Requirement already satisfied: six<2.0.0,>=1.16.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (1.16.0)
Requirement already satisfied: tiktoken<0.5.0,>=0.4.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.4.0)
Requirement already satisfied: tokentrim<0.2.0,>=0.1.9 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (0.1.10)
Requirement already satisfied: wget<4.0,>=3.2 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from open-interpreter==0.1.5) (3.2)
Requirement already satisfied: gitpython in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from git-python<2.0.0,>=1.0.3->open-interpreter==0.1.5) (3.1.37)
Requirement already satisfied: filelock in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (3.12.4)
Requirement already satisfied: fsspec in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (2023.9.2)
Requirement already satisfied: requests in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (4.66.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (4.8.0)
Requirement already satisfied: packaging>=20.9 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (23.1)
Requirement already satisfied: blessed>=1.19.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (1.20.0)
Requirement already satisfied: python-editor>=1.0.4 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (1.0.4)
Requirement already satisfied: readchar>=3.0.6 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (4.0.5)
Requirement already satisfied: importlib-metadata<7.0.0,>=6.8.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter==0.1.5) (6.8.0)
Requirement already satisfied: tokenizers<0.15.0,>=0.14.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter==0.1.5) (0.14.0)
Requirement already satisfied: aiohttp in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (3.8.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from rich<14.0.0,>=13.4.2->open-interpreter==0.1.5) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from rich<14.0.0,>=13.4.2->open-interpreter==0.1.5) (2.16.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from tiktoken<0.5.0,>=0.4.0->open-interpreter==0.1.5) (2023.8.8)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (0.2.6)
Requirement already satisfied: jinxed>=1.1.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (1.2.0)
Requirement already satisfied: zipp>=0.5 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from importlib-metadata<7.0.0,>=6.8.0->litellm<0.2.0,>=0.1.590->open-interpreter==0.1.5) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.4.2->open-interpreter==0.1.5) (0.1.2)
Requirement already satisfied: setuptools>=41.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from readchar>=3.0.6->inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (68.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (2023.7.22)
Requirement already satisfied: colorama in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from tqdm>=4.42.1->huggingface-hub<0.17.0,>=0.16.4->open-interpreter==0.1.5) (0.4.6)
Requirement already satisfied: attrs>=17.3.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter==0.1.5) (1.3.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from gitpython->git-python<2.0.0,>=1.0.3->open-interpreter==0.1.5) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from gitdb<5,>=4.0.1->gitpython->git-python<2.0.0,>=1.0.3->open-interpreter==0.1.5) (5.0.1)
Requirement already satisfied: ansicon in c:\users\peter\appdata\local\pypoetry\cache\virtualenvs\open-interpreter-ambmyqxw-py3.9\lib\site-packages (from jinxed>=1.1.0->blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter==0.1.5) (1.89.0)

(open-interpreter-py3.9) C:\Users\peter\open-interpreter>interpreter codellama-34b-instruct.Q5_K_M.gguf
usage: interpreter [-h] [-s SYSTEM_MESSAGE] [-l] [-y] [-d] [-m MODEL] [-t TEMPERATURE] [-c CONTEXT_WINDOW]
                   [-x MAX_TOKENS] [-b MAX_BUDGET] [-ab API_BASE] [-ak API_KEY] [--config] [--models]
                   [--conversations] [-f]
interpreter: error: unrecognized arguments: codellama-34b-instruct.Q5_K_M.gguf
(open-interpreter-py3.9) C:\Users\peter\open-interpreter>interpreter.model = "codellama-34b-instruct.Q5_K_M.gguf"
'interpreter.model' is not recognized as an internal or external command,
operable program or batch file.

If my internet was faster I would certainly download via cmd, but if there is anything special about the instructions you use for cmd vs just downloading via link on powershell then let me know because maybe part of the issue is there. I am running on w11home.

I hope someone can help here. I have tried admin-mode also. restarting. running on p310 and p39, tried pip3/pip install, and many more things. I am quite new to this so please have patience. And the objective is to run the open interpreter with LLM such as the one showcased here.

### Reproduce

Review the cmd code.  I have been fighting this thing for perhaps eight hours so as an intermediate resort I am posting here. I cannot recollect all the things I have tried out but perhaps the solution is very simple here, at least I suspect it.

### Expected behavior

I expected to run the LLM.

### Open Interpreter version

0.1.5

### Python version

3.9

### Operating System name and version

windows 11

### Additional context

a

**Comment by ericrallen** [comment]
Hey there, @Dangasa98!

Could you try to explain what you’re asking for here with a brief and concise question?

**Comment by ericrallen** [comment]
Going to close this one as stale.

Feel free to reopen if you’d like to rephrase the Issue and discuss it further.
