### ISSUE TITLE
Appending to Default system_message

### ISSUE THREAD

**Issue by gaia** [KillianLucas/open-interpreter#496]
### Describe the solution you'd like

I am not aware if there is a facility in place for this already, but it would be nice to be able to append to system_message, via an .env variable or else.

The default message is great, and the user has to be careful not to append messages which could conflict with the existing ones, but sometimes appending is necessary.

For example: "Every time you make a mistake, pls credit my usage back to my plan (refund) and state: Credits used during this mistake have been refunded."

**Comment by ericrallen** [comment]
With the most recent version, you should be able to edit the `system_message` in the [`config.yaml`](https://github.com/KillianLucas/open-interpreter#configuration) file.
