### ISSUE TITLE
INSTALLING Interpreter on MACOS 

### ISSUE THREAD

**Issue by SamWise1987** [KillianLucas/open-interpreter#513]
### Describe the bug

**After i've used the command: pip3 install open-interpreter to install intrepreter on my Mac the Terminal give me this set if information.

As i understand this mean that the "installation" as being successful but when i try to call th command "open Intepreter" the Termina gives me this error: zsh: command not found: interpreter**

And if i run: sudo apt install python3-pip
gives to me an error that says that i've ti install JAVA but is already installed 

And if eventually mycode run because i've created a temporary path for the pip in my computer i can launch Interpreter but after giving the API KEY i have a new error.

Could someone help? I'm new and i'm learning:)

Requirement already satisfied: open-interpreter in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.1.5)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.4.4)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.8.1)
Requirement already satisfied: git-python<2.0.0,>=1.0.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.0.3)
Requirement already satisfied: huggingface-hub<0.17.0,>=0.16.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.16.4)
Requirement already satisfied: inquirer<4.0.0,>=3.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (3.1.3)
Requirement already satisfied: litellm<0.2.0,>=0.1.590 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.1.743)
Requirement already satisfied: openai<0.29.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.28.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.0.0)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (6.0.1)
Requirement already satisfied: rich<14.0.0,>=13.4.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (13.5.3)
Requirement already satisfied: six<2.0.0,>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.16.0)
Requirement already satisfied: tiktoken<0.5.0,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.4.0)
Requirement already satisfied: tokentrim<0.2.0,>=0.1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.1.10)
Requirement already satisfied: wget<4.0,>=3.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (3.2)
Requirement already satisfied: gitpython in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from git-python<2.0.0,>=1.0.3->open-interpreter) (3.1.37)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.12.4)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2023.9.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (4.66.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (4.8.0)
Requirement already satisfied: packaging>=20.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (23.1)
Requirement already satisfied: blessed>=1.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.20.0)
Requirement already satisfied: python-editor>=1.0.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.0.4)
Requirement already satisfied: readchar>=3.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (4.0.5)
Requirement already satisfied: importlib-metadata<7.0.0,>=6.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter) (6.8.0)
Requirement already satisfied: tokenizers<0.15.0,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter) (0.14.0)
Requirement already satisfied: aiohttp in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<0.29.0,>=0.28.0->open-interpreter) (3.8.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (2.16.1)
Requirement already satisfied: regex>=2022.1.18 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tiktoken<0.5.0,>=0.4.0->open-interpreter) (2023.8.8)
Requirement already satisfied: wcwidth>=0.1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter) (0.2.6)
Requirement already satisfied: zipp>=0.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from importlib-metadata<7.0.0,>=6.8.0->litellm<0.2.0,>=0.1.590->open-interpreter) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.4.2->open-interpreter) (0.1.2)
Requirement already satisfied: setuptools>=41.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from readchar>=3.0.6->inquirer<4.0.0,>=3.1.3->open-interpreter) (65.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.3.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (5.0.1) 

### Reproduce

% pip3 install open-interpreter

Requirement already satisfied: open-interpreter in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.1.5)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.4.4)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.8.1)
Requirement already satisfied: git-python<2.0.0,>=1.0.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.0.3)
Requirement already satisfied: huggingface-hub<0.17.0,>=0.16.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.16.4)
Requirement already satisfied: inquirer<4.0.0,>=3.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (3.1.3)
Requirement already satisfied: litellm<0.2.0,>=0.1.590 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.1.743)
Requirement already satisfied: openai<0.29.0,>=0.28.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.28.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.0.0)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (6.0.1)
Requirement already satisfied: rich<14.0.0,>=13.4.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (13.5.3)
Requirement already satisfied: six<2.0.0,>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (1.16.0)
Requirement already satisfied: tiktoken<0.5.0,>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.4.0)
Requirement already satisfied: tokentrim<0.2.0,>=0.1.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (0.1.10)
Requirement already satisfied: wget<4.0,>=3.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from open-interpreter) (3.2)
Requirement already satisfied: gitpython in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from git-python<2.0.0,>=1.0.3->open-interpreter) (3.1.37)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.12.4)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2023.9.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (4.66.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (4.8.0)
Requirement already satisfied: packaging>=20.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (23.1)
Requirement already satisfied: blessed>=1.19.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.20.0)
Requirement already satisfied: python-editor>=1.0.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.0.4)
Requirement already satisfied: readchar>=3.0.6 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (4.0.5)
Requirement already satisfied: importlib-metadata<7.0.0,>=6.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter) (6.8.0)
Requirement already satisfied: tokenizers<0.15.0,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from litellm<0.2.0,>=0.1.590->open-interpreter) (0.14.0)
Requirement already satisfied: aiohttp in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from openai<0.29.0,>=0.28.0->open-interpreter) (3.8.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (2.16.1)
Requirement already satisfied: regex>=2022.1.18 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from tiktoken<0.5.0,>=0.4.0->open-interpreter) (2023.8.8)
Requirement already satisfied: wcwidth>=0.1.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter) (0.2.6)
Requirement already satisfied: zipp>=0.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from importlib-metadata<7.0.0,>=6.8.0->litellm<0.2.0,>=0.1.590->open-interpreter) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.4.2->open-interpreter) (0.1.2)
Requirement already satisfied: setuptools>=41.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from readchar>=3.0.6->inquirer<4.0.0,>=3.1.3->open-interpreter) (65.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub<0.17.0,>=0.16.4->open-interpreter) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->openai<0.29.0,>=0.28.0->open-interpreter) (1.3.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (5.0.1)
samuelerea@MacBook-Pro-di-Samuele ~ % interpeter
zsh: command not found: interpeter
samuelerea@MacBook-Pro-di-Samuele ~ % interpreter
zsh: command not found: interpreter
samuelerea@MacBook-Pro-di-Samuele ~ % open interpreter
The file /Users/samuelerea/interpreter does not exist.
samuelerea@MacBook-Pro-di-Samuele ~ % import interpreter

interpreter.chat()                                       
function> Apri cartella applicazioni 
zsh: command not found: import
samuelerea@MacBook-Pro-di-Samuele ~ % 

### Expected behavior

I was expecting tu run the code and see interpreter works.

### Open Interpreter version

nopn

### Python version
[Uploading installing interpreter.pdf…]()

Python 3.11.3

### Operating System name and version

13.5.2 (22G91)

**Comment by gavinmclelland** [comment]
You tried using `import interpreter` in the shell. Shell commands don't work like Python code; you can't import a Python library directly into the shell. You would need to enter a Python interpreter first by typing `python` or `python3`.

If you want to stay with the custom install path, check the installation to see if this is a path issue. 

### Check Installation

Use `pip3 show open-interpreter` to confirm where the package is installed. 

### Run Python Code in Python Interpreter

2. start a Python session and import `interpreter`:
```bash 
python 3
```

3. Once inside the Python interpreter:
``` python
import interpreter
# then you can use it
```

### Follow `MACOS.md` to get started quickly

If you just want to get up and running, I've created an updated version of the [MACOS.md](https://github.com/gavinmclelland/open-interpreter/blob/main/docs/MACOS.md) to solve my own install issues for running `interpreter` on MacOS (Apple Silicon) with ARM64 (CPU) Metal (GPU) support. 

Give these steps a try, let me know if the guide solves your issues.

**Comment by SamWise1987** [comment]
[Output di Terminal_gavinhelp.txt](https://github.com/KillianLucas/open-interpreter/files/12747331/Output.di.Terminal_gavinhelp.txt)


this what happened At least is a step forward for me. 
Thanks for helping me

**Comment by ericrallen** [comment]
It looks like you’re trying to mix Python (running inside of your Python REPL after invoking `python3`) and Shell commands (like `pip install`).

You need to run `pip` commands in the shell and Python commands in the REPL or, more ideally, create a Python script and execute them.

Maybe if you explain what you’re trying to do, someone can help guide you towards how to do it.

You might want to consider just starting by running `interpreter` and playing around with it first.

**Comment by ericrallen** [comment]
I’m going to close this one for now, as it’s not really an Issue in the codebase.

Please feel encouraged to open up another Issue for any other problems you experience.
