### ISSUE TITLE
Give “Segment error (core has been dumped)”

### ISSUE THREAD

**Issue by heyuwei1018** [KillianLucas/open-interpreter#514]
### Describe the bug

It gives "Segment error (core has been dumped)”.

### Reproduce

1.Input "interpreter".
2.choose Code-Llama
3.choose 7B.
4.choose Small.
5.choose use GPU.

### Expected behavior

It should appear where I need to input text, and then I get the answer。

### Open Interpreter version

0.1.4

### Python version

3.10.9

### Operating System name and version

Ubuntu 20.04.6

**Comment by ericrallen** [comment]
Hey there, @heyuwei1018!

Can you confirm if this is still an issue with the latest version of Open Interpreter?

If it is, can you provide a little more context around this issue, provide a more full sample of the output and error trace from the Terminal, what GPU you're using, if you can use the GPU with other models/model runners?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Please reopen it if the issue still exists in the latest version of Open Interpreter or you feel like there’s more to discuss.
