### ISSUE TITLE
Local CUDA Toolkit Support

### ISSUE THREAD

**Issue by hjnnjh** [KillianLucas/open-interpreter#515]
### Is your feature request related to a problem? Please describe.

I have read the [GPU setup guide](https://github.com/KillianLucas/open-interpreter/blob/main/docs/GPU.md), which implies that the global CUDA Toolkit is required. However, there is another python environment that contains `JAX` components  in my Linux server,  in which the global CUDA Toolkit may cause some unexpected troubles.

### Describe the solution you'd like

Is there an alternative that use local CUDA Toolkit(which means installing CUDA Toolkit in a `conda` virtual environment) instead of a global one?

**Comment by Notnaton** [comment]
@ericrallen Ooba question I believe, we can close this one
