### ISSUE TITLE
Up-Arrow does not work

### ISSUE THREAD

**Issue by johntday** [KillianLucas/open-interpreter#518]
### Describe the bug

Using <up-arrow> on cls does not work

### Reproduce

1. type on cls prompt
2. up-arrow

### Expected behavior

<up-arrow≥ shows history

### Screenshots

![up-arrow](https://github.com/KillianLucas/open-interpreter/assets/4418325/e795ef8e-4846-4b62-9d2f-a18dc057090f)

### Open Interpreter version

0.1.5

### Python version

3.11.3

### Operating System name and version

macOS 13.5.2

**Comment by jonny7737** [comment]
This is the same as issue #502.

**Comment by ericrallen** [comment]
Hey there, folks!

I’d like to consolidate the discussion around input and keyboard controls into one thread, #117 

Please feel encouraged to continue the discussion in that thread.
