### ISSUE TITLE
Feature Request: Full integration with Jupyter

### ISSUE THREAD

**Issue by valerie-makes** [KillianLucas/open-interpreter#52]
## Summary

I'm using Open Interpreter in a Jupyter Notebook with the Python API. Here is a simple example:

```python
import interpreter
interpreter.chat("Plot a simple graph using matplotlib")
```

## Expected result

1. A visible plot is rendered in the notebook
2. Imports and variables created by Open Interpreter are available in code cells

## Actual result

1. A visible plot is not rendered:
   ![image](https://github.com/KillianLucas/open-interpreter/assets/4248177/0c19abc9-693a-40f0-9061-bc290f8bb965)

2. Imports and variables created by Open Interpreter are unavailable in code cells:
   ![image](https://github.com/KillianLucas/open-interpreter/assets/4248177/36ed5059-6b9f-47bd-a5ca-652b4fbab8f5)

## Proposed solution

Full integration with Jupyter would be amazing for complex use cases and data science!

Ideally Open Interpreter would be able to create and run cells directly in the notebook.

This could be achieved with a Jupyter extension, or by writing outputs to a notebook file.

**Comment by ericrallen** [comment]
There's some work on this in-progress in #553 and @blujus is making some awesome progress.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please try OI in Jupyter Notebook to see if there are any new tickets to create. Thanks!
