### ISSUE TITLE
Hangs on code execution

### ISSUE THREAD

**Issue by amiame** [KillianLucas/open-interpreter#520]
### Describe the bug

I'm running interpreter on MacOS running on M2.
After entering my prompt, and having interpreter lay down its plan, when I type y to allow plan execution, it hangs.

For instance:
```bash
❯ interpreter -y
> Where are we?

  pwd  <-- It hangs here
```

### Reproduce

1. interpreter -y
2. Prompt "Where are we?"
3. This issue happens

### Expected behavior

Plan gets executed

### Screenshots

<img width="1331" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/19357632/1f496dae-d9fc-4201-820a-bb547ca5f7ec">

### Open Interpreter version

0.1.5

### Python version

3.10.13

### Operating System name and version

macOS Venture 13.4.1

**Comment by moshejs** [comment]
Sometimes it hangs for me too. CTRL+C stops the execution and it doesn't understand to try again or another approach.

**Comment by ericrallen** [comment]
I’m going to close this as it’s for an older version number.

Please reopen the issue if you experience the same thing after upgrading.
