### ISSUE TITLE
Running locally with Cpu doesn't produce any output

### ISSUE THREAD

**Issue by WonkySoft** [KillianLucas/open-interpreter#529]
### Describe the bug

I followed the installation instructions and as far as I can tell I'm not getting any errors. I am attempting to run local only using the cpu (newb mistake of buying radeon). I initially tried HUGGINGFACE/THEBLOKE/CODELLAMA-34B-INSTRUCT-GGUF and after inputting any prompt it would consume about 70% of my 16 cores for a few minutes and then return nothing. So then I switched to HUGGINGFACE/THEBLOKE/CODELLAMA-7B-INSTRUCT-GGUF with the smallest ram usage: codellama-7b-instruct.Q2_K.gguf | Size: 2.6 GB, Estimated RAM usage: 5.1 GB. I have 32GB of ram but this model too ran my cpu hard for a shorter time and produced no output. I then turned on %debug and tried a simple prompt "where am I" and after an initial blurb it just repeatedly returns new lines until it stops:

> 
> <</SYS>>
> where am i? [/INST] Let's explore this. By the way, I can run code on your machine by writing the code in a markdown code block. This works if I put a newline after ```shell, ```javascript, ```python, ```R, and ```applescript then write code. I'm going to try to do this for your task, and I'll put the *correct* language after the "```" now. Anyway,
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> Chunk in `terminal_interface`: {'message': '\n'}
> ....

### Reproduce

Run local, input any prompt. 

### Expected behavior

Output text related to my prompt.

### Open Interpreter version

0.1.5

### Python version

3.11.5

### Operating System name and version

Windows 11

**Comment by suyvv** [comment]
same here, will it ever be fixed...?

**Comment by ericrallen** [comment]
Hey there, @WonkySoft and @suyvv!

Can you confirm if you still experience this issue with the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if you experience the issue with the latest version of Open Interpreter.
