### ISSUE TITLE
error on mac m1 pro

### ISSUE THREAD

**Issue by JohnnWi** [KillianLucas/open-interpreter#531]
### Describe the bug

I have this error, why? with any comand 

### Reproduce

any comand

### Expected behavior

<img width="713" alt="SCR-20230926-sgzx" src="https://github.com/KillianLucas/open-interpreter/assets/129292024/852c0b3a-a72c-42a9-9b2c-9a39093d36c8">
 This is the error: "I can run any code on your machine by writing it in a markdown code block.
This works if I put a newline after"

### Open Interpreter version

0.1.1

### Python version

3.11

### Operating System name and version

MacOS 14

**Comment by borjonx** [comment]
I stopped using the smallest model & parm# because I was having this & several issues with it.  Can you try the medium llama model?  I am on M1 Mac w/16GB.

**Comment by primemp** [comment]
Using the large CODELLAMA-13B-INSTRUCT-GGUF q8_0
Same result.

**Comment by JohnnWi** [comment]
> Using the large CODELLAMA-13B-INSTRUCT-GGUF q8_0 Same result.

same result

**Comment by maimorto** [comment]
Same result using HUGGINGFACE/THEBLOKE/CODELLAMA-7B-INSTRUCT-GGUF small one

**Comment by Swallow74** [comment]
Same issue on a macbook air m1  with 16GB of ram. Some solution?

**Comment by ericrallen** [comment]
Closing for now because this is for an older version of Open Interpreter.

Please reopen this Issue if you experience it with an updated version.
