### ISSUE TITLE
Cannot execute bash command in Ubuntu anymore

### ISSUE THREAD

**Issue by ahmetax** [KillianLucas/open-interpreter#532]
### Describe the bug

I am using "codellama-7b-instruct.Q2_K.gguf" model on Ubuntu 22.04.
When I give the command "list files in the current folder" it works and list the files in the current folder.
There is a file "resim1.jpg" in the current folder.
I give a new command as delete resim1.jpg on the current folder.
Interpreter responds saying "  I can run code on your machine by writing the code in a markdown code block.  
  This works if I put a newline after"

### Reproduce

1. give the command  delete file abc.jpg
2. see the response : I can run code on your machine by writing the code in a markdown code block.  
  This works if I put a newline after.

### Expected behavior

Gives the response : I can run code on your machine by writing the code in a markdown code block.  
  This works if I put a newline after.

### Screenshots

![Screenshot from 2023-09-26 23-07-17](https://github.com/KillianLucas/open-interpreter/assets/16287915/ae6b2e57-1933-4286-ae93-ef402f99aaf0)

### Open Interpreter version

0.1.5

### Python version

3.10.12

### Operating System name and version

Ubuntu 22.04

### Additional context

In a few days ago, the same command were running.

**Comment by PotzTausend** [comment]
Same here. Could this have been caused by the update?

**Comment by primemp** [comment]
Same here

**Comment by maimorto** [comment]
Same here

**Comment by Swallow74** [comment]
Same here with mac os x sonoma

**Comment by ericrallen** [comment]
Hey there, folks!

Is this still an issue in the latest version of Open Interpreter?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

Feel free to reopen it if you experience the issue with the latest version of Open Interpreter.
