### ISSUE TITLE
When using the command prompt pip is an error

### ISSUE THREAD

**Issue by LeiYihan01** [KillianLucas/open-interpreter#534]
### Describe the bug

Windows installs with pip install errors of type "Warninig" and "error".
![image](https://github.com/KillianLucas/open-interpreter/assets/140927739/ceb9fa0a-cbd7-43b9-86f0-c680d2ce791c)

### Reproduce

1. First open the command prompt with the shortcut key "Win+r"
2. Enter the pip install command to install
3. Press Enter to start reporting an error

### Expected behavior

None

### Open Interpreter version

None

### Python version

3.8

### Operating System name and version

Windows 10 21H2 64bit

**Comment by ericrallen** [comment]
It looks like the issue might be related to the PyPI mirror that you're using.

Have you tried installing without the mirror?

**Comment by LeiYihan01** [comment]
Not yet, I don't know how to install without an image.

**Comment by osjimene** [comment]
@LeiYihan01 
Looks like you are also using Python 3.8 instead of the Python 3.10. I got errors when I tried to pip install it on my machine earlier this morning but my errors were a long list of "You dont have Python 3.10 installed"

**Comment by LeiYihan01** [comment]
Is it? Is there a possibility that this project does not support Python 3.8 or only 10.0. However, due to the lack of space on my computer, I can no longer toss, I hope to push the client to me as soon as possible, I have applied

**Comment by ericrallen** [comment]
Is this a separate issue from #586?

Can we close one of them instead of having multiple issues open?
