### ISSUE TITLE
Python: calling interpreter with a message causes an infinite loop

### ISSUE THREAD

**Issue by jonny7737** [KillianLucas/open-interpreter#536]
### Describe the bug

In python, executing this code: 

`interpreter.chat(message)`

Tested with message 'ls', 'pwd' and others.

The chat is started and the request is executed: forever with a bit of attitude: 

`The current working directory is...`
`The current working directory is still...`
`The current working directory is...`
`The current working directory is still...`
`The current working directory is...`
`The current working directory is still...`

^C does not work regardless of how interpreter is initialized (with or without a chat message).
Auto_run is enabled and model is 'gpt-3.5-turbo-0613'

### Reproduce

1. execute: `interpreter.chat(message)` where message is 'pwd'

### Expected behavior

output the directory

### Open Interpreter version

0.1.6

### Python version

3.10.11

### Operating System name and version

macOS 14

### Additional context

The ^C issue remains regardless of the auto_run value.

With auto_run=False
`> ^C
▌ Model set to GPT-3.5-TURBO-0613

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.`

**Comment by KillianLucas** [comment]
Hi @jonny7737, thanks for opening an issue! I'm unable to reproduce this bug, could you send a screenshot of what's happening? Please also send a screenshot with `interpreter.debug_mode = True` on, set that before you run `interpreter.chat(message)`.

This is what I got:

<img width="994" alt="Screen Shot 2023-09-27 at 11 23 13 AM" src="https://github.com/KillianLucas/open-interpreter/assets/63927363/ea7d5aa2-05c0-4073-93c5-e114ac4c8490">

**Comment by KillianLucas** [comment]
Same for `gpt-3.5-turbo`:

<img width="918" alt="Screen Shot 2023-09-27 at 11 25 57 AM" src="https://github.com/KillianLucas/open-interpreter/assets/63927363/a2b54b9d-7c76-46bd-abbf-9d8685b279dd">

**Comment by jonny7737** [comment]
Thank you for looking at this issue. Unfortunately, I was called away for business and will not get back to these efforts for some time.  I will close this issue and open a new one when I can focus on this effort.

Thanks again for you time.
