### ISSUE TITLE
Edit code before running

### ISSUE THREAD

**Issue by JustMrMendez** [KillianLucas/open-interpreter#537]
### Is your feature request related to a problem? Please describe.

sometimes the code that is going to run is incorrect, rather than wasting more tokens, I am wasting a lot of tokens for a misplaced brackets.

this issue keeps happening:
```py
f.write('Bootstrap also has advanced ...\n\n')}
```

### Describe the solution you'd like

Any code that is going to run should be saved in a cache file, and the options should be y/n/e
when you type  `e`dit, it should open the file on any default editor and watch for changes, then ask again.

**Comment by KillianLucas** [comment]
This is an amazing idea. I really wish we could edit it right in the terminal like `vim` or something... let's think about this. I think it's important.

**Comment by JustMrMendez** [comment]
If my hands weren't tied by work, I would try to implement it myself. I wasted $3+ in tokens because of a }, when I caught the error (a single `}`,  it was an instant facepalm 🤦

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
