### ISSUE TITLE
please suport use gpt4 for free

### ISSUE THREAD

**Issue by wowdd1** [KillianLucas/open-interpreter#54]
please use [gpt4free](https://github.com/xtekky/gpt4free),  so do not need chatgpt api key anymore

**Comment by mak448a** [comment]
Any progress on this? Should I try to make a pull request for this

**Comment by leifktaylor** [comment]
From what I can see, gpt4free abstracts LLM access by giving a limited subset of conversations endpoints to different models through their **provider** functionality.
The vercel provider seems to be the only true provider for GPT4 access, the other providers are all abstractions of GPT-4 and are actually services like Bing, and Bard.

Support for gpt4free would be a massive undertaking, as we would need to keep an up to date list of compatible providers, and we would need to account for the lack of endpoints such as embeddings, functions, messages, temperature and more.

I would don't think that adding gpt4free support to open-interpreter is within the scope of the project, as gpt4free isn't a model per se, but rather a provider driven abstraction layer.

@KillianLucas @jordanbtucker 
**I would recommend closing this issue.**

**Comment by mak448a** [comment]
Maybe you should support vercel-llm-api instead since it's more stable: #462

**Comment by dataaug** [comment]
@wowdd1  Considering that author has no intention of accessing gpt4free. I forked the repository to support gpt4free. 
[open-interpreter-free](https://github.com/dataaug/open-interpreter-free)
If author changes his mind, I'll be happy to provide a PR.

**Comment by mak448a** [comment]
@dataaug Looks good!

**Comment by mak448a** [comment]
> @wowdd1 Considering that author has no intention of accessing gpt4free. I forked the repository to support gpt4free. [open-interpreter-free](https://github.com/dataaug/open-interpreter-free) If author changes his mind, I'll be happy to provide a PR.

There's an error though, you need to import g4f from the gpt4free package. The way it is right now is that it throws an error. Thanks!

**Comment by mak448a** [comment]
It throws an error: cannot import g4f @dataaug

**Comment by ericrallen** [comment]
Hey there, @mak448a!

Let’s keep issues and discussions about issues in other repos in the Issues section of that repo and not keep using a closed thread here.

**Comment by dataaug** [comment]
@mak448a `pip install -U g4f`
