### ISSUE TITLE
Error "Model meta-llama/Llama-2-7b is currently loading","estimated_time":20.0}

### ISSUE THREAD

**Issue by RohitNansen** [KillianLucas/open-interpreter#540]
### Describe the bug

I performed 

$ interpreter --model huggingface/meta-llama/Llama-2-7b

I get this error

Traceback (most recent call last):
  File "C:\Users\Rohit\anaconda3\envs\virt_env\Lib\site-packages\litellm\utils.py", line 3029, in __next__
    response_obj = self.handle_huggingface_chunk(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rohit\anaconda3\envs\virt_env\Lib\site-packages\litellm\utils.py", line 2870, in handle_huggingface_chunk
    raise ValueError(chunk)
ValueError: {"error":"Model meta-llama/Llama-2-7b is currently loading","estimated_time":20.0}

Note: chunk has b'{"error":"Model meta-llama/Llama-2-7b is currently loading","estimated_time":20.0}'

### Reproduce

interpreter --model huggingface/meta-llama/Llama-2-7b

### Expected behavior

responds to the chat

### Open Interpreter version

0.1.6

### Python version

3.11.5

### Operating System name and version

windows 11

**Comment by djakabubu** [comment]
Start app, wait some minutes before state the question and it should work. Else tray again. I did with Phind 34b from HuggingFace and it worked

**Comment by RohitNansen** [comment]
> Start app, wait some minutes before state the question and it should work. Else tray again. I did with Phind 34b from HuggingFace and it worked

Hallo @djakabubu, I appreciate the reply. I started cmd prompt and ran the code "interpreter --model huggingface/meta-llama/Llama-2-7b" after few minutes. 

There is the same issue that comes.

Could you kindly share the code that worked for Phind 34b model?

**Comment by ericrallen** [comment]
Hey there, folks!

Now that LM Studio is the underlying local model provider, I _think_ we can close this one.

Please reopen it if you still experience the issue in the latest version of Open Interpreter.

**Comment by saifpashaTrigent** [comment]
Im using lteLLM  and I'm getting an error of having the Estimated time of 20.0
HF_TOKEN = os.getenv("HF_TOKEN")
def selectLLM(query: str):
    message_text = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": query},
    ]
    try:
        llm_response = completion(
            model="huggingface/meta-llama/Llama-2-7b",
            messages=message_text,
            # api_base=base,
        )
        llmResult = llm_response.choices[0].message.content
        pprint("RESULT: ", llmResult)
    except Exception as e:
        return f"Error in OneLite: {str(e)}"
