### ISSUE TITLE
Please support the third-party OpenAI API Key, thank you.

### ISSUE THREAD

**Issue by G-LJDS2022** [KillianLucas/open-interpreter#541]
### Is your feature request related to a problem? Please describe.

Please support the third-party OpenAI API Key, thank you.
Please support the third-party OpenAI API Key, thank you.
Please support the third-party OpenAI API Key, thank you.

### Describe the solution you'd like

Please support the third-party OpenAI API Key, thank you.

### Describe alternatives you've considered

Please support the third-party OpenAI API Key, thank you.

### Additional context

Please support the third-party OpenAI API Key, thank you.

**Comment by dagelf** [comment]
Which one? Azure?

**Comment by ericrallen** [comment]
Closing this one.

Please provide a clear description of your issue and how it might be resolved in the future rather than just entering the same string numtipke times with no context.
