### ISSUE TITLE
Please support Mistral 7B model

### ISSUE THREAD

**Issue by velteyn** [KillianLucas/open-interpreter#550]
### Describe the solution you'd like

I read that Mistral 7B is more capable than LLAMA and it is free and open source as well.
Are you planning to support it ?
Thank you

https://mistral.ai/news/announcing-mistral-7b/

**Comment by haseeb-heaven** [comment]
I have tested it on Perplexity its blazing fast but its also not accurate in terms of logic and codig, so i wont recommend

**Comment by tcinhoff** [comment]
When evaluating the coding benchmarks, Mistral 7B clearly surpasses both Llama and Code Llama in terms of coding performance.

**Comment by haseeb-heaven** [comment]
> When evaluating the coding benchmarks, Mistral 7B clearly surpasses both Llama and Code Llama in terms of coding performance. I would greatly appreciate it if support for Mistral 7B could be considered.

We dont totaly rely on benchmarks, you have to test yourself to give recommendation. 
Where you have tested this.

**Comment by LawOff** [comment]
Stats doesnt lies

![image](https://github.com/KillianLucas/open-interpreter/assets/95545719/7ed183cc-ea9d-4689-92af-2f8bb408b6e4)

**Comment by haseeb-heaven** [comment]
I have tested this myself its no good for coding tasks man, stats are always exaggerated btw, try the demo yourself and don’t rely on stats please.

**Comment by ericrallen** [comment]
You can try Mistral already via Open Interpreter’s LiteLLM integration and the `--model` argument.

Fair warning, Open Interpreter is based on function calling, so Language Models that aren’t tuned for function calling are not going to perform quite as well when acting as Open Interpreter.

https://docs.litellm.ai/docs/providers/huggingface

https://docs.litellm.ai/docs/providers/huggingface

**Comment by haseeb-heaven** [comment]
I guess Gpt Palm and LLamA models are only good for coding assistants. These new models we have to test them for a while before using them for coding assistants

**Comment by ericrallen** [comment]
I believe there might be some exciting news coming soon regarding Open Interpreter and better support for the Mistral model.

There's a bit of a teaser in the [Open Interpreter Discord](https://discord.gg/6p3fD6rBVm).

**Comment by ericrallen** [comment]
Closing as LiteLLM already supports this and the new default local model is Mistral.

**Comment by mrahjoo** [comment]
I'm trying to use perplexity APIs with the open-interpreter, but I'm encountering an error. Can anyone provide guidance on how to correctly set the perplexity using the open-interpreter?

https://github.com/BerriAI/litellm/issues/602#issue-1942996061
