### ISSUE TITLE
Add OpenAI Proxy url

### ISSUE THREAD

**Issue by OmiiiDev** [KillianLucas/open-interpreter#551]
### Is your feature request related to a problem? Please describe.

the problem is that not everyone can afford to have an open ai api key so it could be better to make a proxy url to make it easier to use

### Describe the solution you'd like

be able to add the open ai proxy url to the env

**Comment by ericrallen** [comment]
I think LiteLLM, which Open Interpreter leverages, provides this functionality.

https://github.com/KillianLucas/open-interpreter/issues/261#issuecomment-1713989808

https://docs.litellm.ai/docs/providers/openai#using-openai-proxy-with-litellm

**Comment by OmiiiDev** [comment]
how do i use it if i want to run it?

**Comment by OmiiiDev** [comment]
@ericrallen Can you please show me how to do it?

**Comment by CiaranYoung** [comment]
(●'◡'●)

**Comment by OmiiiDev** [comment]
> (●'◡'●)

?

**Comment by OmiiiDev** [comment]
Ok so what the problem is that not many people have or can afford an OpenAI api key. And using the models that you can download by skipping the OpenAI key option is a little buggy, the ai is slow and doesn't respond well. So to fix this it could be possible in the options when you run the interpreter to add an OpenAI proxy url with its own api key and make it work

**Comment by ericrallen** [comment]
What proxy URL have you tried? Did the `api_base` functionality not work?

**Comment by OmiiiDev** [comment]
> What proxy URL have you tried? Did the `api_base` functionality not work?

What do you mean by proxy url have I tried? Because I haven't tried any proxy urls on this program. And I do not know how to use the api base can you tell me or show me?

**Comment by ericrallen** [comment]
Here are the docs for arguments like `api_base`.

Try one of your URLs and see what happens.

**Comment by OmiiiDev** [comment]
So can I do this?: interpreter --api_base "https://api.example.com" --api_key "your_api_key_here"

**Comment by OmiiiDev** [comment]
> Try one of your URLs and see what happens.

If you want I can to tell you the free OpenAI proxy urls and their api keys and how they work

**Comment by ericrallen** [comment]
I think the command you showed should work, but you might need to add `—-model openai/gpt-3.5-turbo` to get LiteLLM to invoke it correctly.

**Comment by OmiiiDev** [comment]
ok, i will try it out and give you feedback
