### ISSUE TITLE
Hangs after update

### ISSUE THREAD

**Issue by JustMrMendez** [KillianLucas/open-interpreter#557]
### Describe the bug

No matter the command it tries to run, it hangs with no feedback, CTRl-C outputs this:

```bash
Traceback (most recent call last):
  File "/path/to/python3.11/site-packages/interpreter/core/respond.py", line 118, in respond
    for line in code_interpreter.run(code):
  File "/path/to/python3.11/site-packages/interpreter/code_interpreters/subprocess_code_interpreter.py", line 103, in run
    output = self.output_queue.get(timeout=0.3)  # Waits for 0.3 seconds
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/queue.py", line 180, in get
      self.not_empty.wait(remaining)
    File "/usr/lib64/python3.11/threading.py", line 324, in wait
      gotit = waiter.acquire(True, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  KeyboardInterrupt
```

### Reproduce

Reproduce
1. `pip install open-interpreter`
2. `pip install --upgrade open-interpreter`
3. `interpreter`
4. type `run hello world in bash` (or anything that runs a command)
5. type `y` and press enter to run the code, then it just hangs...

### Expected behavior

It should run the code and show its output

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/56850299/32978137-19d7-4234-93be-8dd5afcb8a76)

### Open Interpreter version

0.1.7

### Python version

3.11.5

### Operating System name and version

Fedora Linux 38 (Workstation Edition) x86_64

**Comment by JustMrMendez** [comment]
the problem is the **`fish`** shell, if i use bash, it works

**Comment by neilbGH** [comment]
I have the same problem and it's happening for me if I use bash in Ubuntu 22.04.3 LTS

**Comment by vedran-** [comment]
Same problem, using Windows 10.

**Comment by appenz** [comment]
Symptoms look identical to #880.

**Comment by MikeBirdTech** [comment]
Closing this stale issue as address in a newer ticket. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
