### ISSUE TITLE
More apis to implement LLMs.

### ISSUE THREAD

**Issue by Pxys-io** [KillianLucas/open-interpreter#558]
### Is your feature request related to a problem? Please describe.

Currently, Open-Interpreter can be accessed exclusively via OpenAI's API or by local execution.
This setup restricts many potential users:
Those hesitant about OpenAI API dependency.
Users without adequate local hardware for LLMs.
Individuals wanting to integrate with other proprietary APIs.

### Describe the solution you'd like

I am seeking a solution involving an open-interpreter Python API. This API would provide the text to be processed, which I would then process through my preferred LLM. Subsequently, I would invoke another Python function with the API's response. Essentially, I aim to act as an intermediary, managing external API requests. This approach would enable other API providers to develop their own libraries based on the open-interpreter.

**Comment by krrishdholakia** [comment]
you can access more than just openai's api @Pxys-io  - https://docs.litellm.ai/docs/providers

openinterpreter uses litellm which lets you call anthropic, togetherai, huggingface tgi, bedrock, sagemaker, cohere, ai21, etc.

**Comment by krrishdholakia** [comment]
if you think there's any providers missing let me know! (i'm the co-maintainer of litellm)

**Comment by CosmicNu** [comment]
Are API keys needed to run Open-Interpreter? Are they free if that's the case?

**Comment by krrishdholakia** [comment]
oh - to be clear you can set the api key for any of the providers you want to call. 

If you're looking for a unified key - check out: https://openrouter.ai/
