### ISSUE TITLE
Azure option is no longer accessible

### ISSUE THREAD

**Issue by othmanelhoufi** [KillianLucas/open-interpreter#559]
### Describe the bug

Previously I could've just use `interpreter -use-azure` but it no longer works.
Thanks for this incredible tool :)

### Reproduce

1. Type `interpreter -h'
2. In the options list you won't see `--use-azure` option anymore

### Expected behavior

This option allows to enter Azure OpenAI credentials to use GPT models.

### Screenshots

<img width="860" alt="Screenshot 2023-09-29 at 16 28 57" src="https://github.com/KillianLucas/open-interpreter/assets/40344016/42df8cc5-9914-44b0-b8df-6823df904bca">

### Open Interpreter version

0.1.7

### Python version

3.11.5

### Operating System name and version

MacOS 13.6

**Comment by krrishdholakia** [comment]
i believe you can call azure by just appending it to model name `interpreter --model azure/gpt-4`

**Comment by blue-ethan** [comment]
> i believe you can call azure by just appending it to model name `interpreter --model azure/gpt-4`我相信您只需将其附加到模型名称 `interpreter --model azure/gpt-4` 即可调用 azure

NO， its not work。its say that
❯ interpreter --model azure/gpt-4

▌ Model set to AZURE/GPT-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.
> hi

We were unable to determine the context window of this model. Defaulting to 3000.
If your model can handle more, run interpreter --context_window {token limit} or interpreter.context_window = {token limit}.

**Comment by knightwave** [comment]
try with this `interpreter --model azure/gpt-4-32k` it worked for me

**Comment by krrishdholakia** [comment]
its' `azure/<your-deployment-id>`

**Comment by blue-ethan** [comment]
its working NOW！
The real process is like this：

export AZURE_API_KEY="your_api_key"
export AZURE_API_BASE="your_api_base"
export AZURE_API_VERSION="your_api_version"

interpreter --model azure/<your-deployment-id> -c 3000

**Comment by othmanelhoufi** [comment]
Works like a charm. Thanks to all of you!

**Comment by othmanelhoufi** [comment]
Solution: `interpreter -y --model azure/<your-deployment-id>`

**Comment by SushmitaSahuAI** [comment]
Same here : interpreter --model azure/<your-deployment-id> -c 3000 , not working
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/litellm/utils.py", line 2722, in exception_type
    raise e
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/litellm/utils.py", line 2141, in exception_type
    raise original_exception
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/litellm/main.py", line 328, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/opt/conda/envs/oi11/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

**Comment by stevenbaert** [comment]
??? So each time I have to start interpreter with azure I have type my deployment id (which I have to go and search for, no clue). Just a interpreter -azure is to simple? Sorry, quite frustrated that it suddenly changed and then also in a way that's not straight-forward at tall. I'd have to type the deployment id each time I start interpreter or remember it/copy it from somehwere. Don't get that "improvement".

**Comment by krrishdholakia** [comment]
how were you passing the deployment id to open interpreter previously @stevenbaert?

**Comment by stevenbaert** [comment]
What is the deployment ID, the openai engine, that's not an idea, but that's the engine name.
Please give an example.

**Comment by krrishdholakia** [comment]
<img width="460" alt="Screenshot 2023-10-03 at 2 37 58 PM" src="https://github.com/KillianLucas/open-interpreter/assets/17561003/02a18b79-deb0-46f9-ba82-0497b7286289">
In this example - chatgpt-v-2 is a deployment id/name

**Comment by stevenbaert** [comment]
Ok, so you mean the name, the ID would be a number, at least that's how interprete an ID. Thanks, I ll try again, though last attempt with name failed.
