### ISSUE TITLE
export COHERE_API_KEY does not work 

### ISSUE THREAD

**Issue by text2sql** [KillianLucas/open-interpreter#565]
### Describe the bug

export COHERE_API_KEY says bad assignment 

### Reproduce

terminal, export COHERE_API_KEY = "api_key" -> zsh: bad assignment

### Expected behavior

should have assigned the key to the command-nightly model

### Open Interpreter version

0.1.7

### Python version

3.11

### Operating System name and version

MacOS

**Comment by HeMuling** [comment]
You should do `export COHERE_API_KEY="api_key"` instead of `export COHERE_API_KEY = "api_key"`
