### ISSUE TITLE
Unused return from "get_relevant_procedures" unnecessary call

### ISSUE THREAD

**Issue by mersu898** [KillianLucas/open-interpreter#567]
### Describe the bug

Please see image below, from the file `interpreter\core\respond.py`.

When running OI from a network that blocks Open Procedures website, the call at line 24 might throw an SSL error. This call is duplicate, since there's another one at line 27, but this one is wrapped in a `try/except` block.

<img width="603" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/36384950/ee8e8a00-7c67-4b0e-a4db-7b4ef0a8a3f7">

The code at line 24 should be removed, because:
- its return is not being used
- it's probably wrong, since there's another call at line 27, correctly wrapped for exception handling

### Reproduce

1 Connect to a corporate network that blocks Open Procedures website
2 Try to use OI normally, in OpenAI mode (not local)
3 OI will fail with a weird error, like:
```
...
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

### Expected behavior

Expected result is that OI would work normally, without throwing the error to the user.

### Open Interpreter version

0.1.7

### Python version

3.10.8

### Operating System name and version

Windows 10

**Comment by ericrallen** [comment]
Hey there, @mersu898!

I'm going to close this one for now as the call to `https://open-procedures.replit.app/` was removed in more recent versions of Open Interpreter.
