### ISSUE TITLE
RAG for Source Code and/or Docs

### ISSUE THREAD

**Issue by slavakurilyak** [KillianLucas/open-interpreter#568]
### Is your feature request related to a problem? Please describe.

It would be great to see Open Interpreter use retrieval-augmented generation (RAG) to answer questions about source code, docs, or both.

### Describe the solution you'd like

I would like Open Interpreter to perform retrieval on existing codebases and/or docs so that code generations are more grounded and the models are hallucinating less.

### Describe alternatives you've considered

autogen's [Auto Generated Agent Chat](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_RetrieveChat.ipynb)

Meta's [Retrieval-Augmented Generation (RAG) for Knowledge-Intensive NLP Tasks](https://browse.arxiv.org/pdf/2005.11401.pdf)

### Additional context

Related notebook on [how to change what OI knows](https://colab.research.google.com/drive/1DUVYLAstnXs22Ov4YuHMngjvNB4Mfx0Y?usp=sharing#scrollTo=lE2GSFLJoOtI) which lets you use RAG to teach OI new things

**Comment by ericrallen** [comment]
Hey there, @slavakurilyak!

I'm going to close this one as a `duplicate` so we can consolidate all of the Vector, Memory, RAG, storage, etc. discussions into the first issue that brought them up (#144) and reduce the overall noise in the projects' Issues.
