### ISSUE TITLE
Connect to vector store for long term memory

### ISSUE THREAD

**Issue by williamp0044** [KillianLucas/open-interpreter#569]
### Is your feature request related to a problem? Please describe.

OpenAI code interpreter's memory is very short-lived. This has no memory or recollection at all.

### Describe the solution you'd like

The ability to store info in a vector store would be an exceptional improvement. 

### Describe alternatives you've considered

Maybe saving and recalling from a pickle or numpy array? that way the user won't have to install a separate DB? 
or maybe use faiss?

**Comment by ericrallen** [comment]
Hey there, @williamp0044!

I'm going to close this one as a `duplicate` so we can consolidate all of the Vector, Memory, RAG, storage, etc. discussions into the first issue that brought them up (#144) and reduce the overall noise in the projects' Issues.
