### ISSUE TITLE
Where is the Code-Llama model downloaded to?

### ISSUE THREAD

**Issue by XInTheDark** [KillianLucas/open-interpreter#57]
1. I was prompted to enter an openAI key, but I do not have one, so I switched to code-llama mode.
2. The instance of code-llama was not found on my Mac. So I was prompted to download it instead:
<img width="561" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/61100393/e70f79ed-343a-421f-8756-3ab600a7b715">

However after the download completed, I'm not able to locate where the file is on my Mac. 
<img width="569" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/61100393/2073c3cf-2549-419c-a97a-b70e2e0818b0">

I'm using completely default settings with the latest build of open-interpreter. Can someone help me locate the file? Thanks!

**Comment by coderj001** [comment]
@XInTheDark possibly here `~/.local/share/Open Interpreter`

**Comment by XInTheDark** [comment]
> I tried printing the directories which it look for loading the model
> 
> ```
> [
>     '/Users/username/Library/Application Support/Open Interpreter/models',
>     'llama.cpp/models/',
>     '/Users/username/llama.cpp/models/',
>     '/'
> ]
> ```
> 
> by the way I am using Mac m1

thanks, found it!
