### ISSUE TITLE
Feed Open Interpreter documentation like Azure OpenAI API and Langchain 

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#570]
### Is your feature request related to a problem? Please describe.

Open interpreter is great for coding, but it doesn't know about Azure OpenAI, GPT-4 and or Langchain. It would be great to feed that data to it, maybe via a Chromadb Vector db?

### Describe the solution you'd like

Open interpreter is great for coding, but it doesn't know about Azure OpenAI, GPT-4 and or Langchain. It would be great to feed that data to it, maybe via a Chromadb Vector db?

**Comment by ericrallen** [comment]
Hey there, @stevenbaert!

I'm going to close this one as a `duplicate` so we can consolidate all of the Vector, Memory, RAG, storage, etc. discussions into the first issue that brought them up (#144) and reduce the overall noise in the projects' Issues.
