### ISSUE TITLE
Azure open AI support gone again 😕

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#573]
### Describe the bug

Azure open AI support gone again 😕
Reported it a while ago, it was back now gone again. 
Love the tool, I use interpreter on daily basis, how can I make sure updates don't break basic features? 

### Reproduce

Interpreter - - use-azure

### Expected behavior

Working 😁

### Open Interpreter version

Latest

### Python version

Latest

### Operating System name and version

Latest

**Comment by krrishdholakia** [comment]
I believe this is what you're looking for - https://github.com/KillianLucas/open-interpreter/issues/559#event-10526782804

tldr; 
```
interpreter -y --model azure/<your-deployment-id>
```

**Comment by krrishdholakia** [comment]
@stevenbaert
