### ISSUE TITLE
data persistence/opening programs

### ISSUE THREAD

**Issue by Conorjames98** [KillianLucas/open-interpreter#576]
### Describe the bug

Really needs data persistence for one but I appreciate it may be difficult right now but the second issue is when asking to open vscode for example it does it but believes it hasn't.

could this maybe due to the fact when opening vscode through terminal it doesn't give a response so the ai then just waits until human intervention and assumes an error occurred. 

### Reproduce

be running interpreter using turbo3.5 and -y 

ask to open a file in vscode and study it's code 

it opens vs code but stays on the code execution box until human intervention so then it doesn't actually study the code only opens vs code and then cancels,

### Expected behavior

Expected to open the flle using vs code at the same time opening a terminal in the background and using "ls" to study the code and output the results this is at the very least automation wise.

### Open Interpreter version

1.0

### Python version

3.11.5

### Operating System name and version

debian

**Comment by Conorjames98** [comment]
got it to work by asking it to find the the PID of vscode nd once it had been found asked it to open a file from my desktop with vs code and it did it

**Comment by Conorjames98** [comment]
Mainly an issue with how it handles terminal commands that do not give an output.

**Comment by ericrallen** [comment]
As you mentioned, I think the `code` command doesn't have an appropriate exit code, so you do need to use `CTRL + C` and provide a keyboard interrupt, but in my brief tests, Open Interpreter seemed to think that VS Code had been successfully opened after the keyboard interrupt. It would then proceed with ingesting the file contents and analyzing them.

Until there's something in place to handle the case of executed code that doesn't provide a clear exit/return signal, it might help to modify your instructions when you ask Open Interpreter to help with this. Something like the following example worked for me in a few different tests:

> Let's open up /path/to/file and analyze it. Can you ingest the file and provide suggestions, and also open it up in VSCode for me so I can take a look, too?

In some cases, these instructions would open the file for me first, and in others, Open Interpreter would ingest the code first and then open it for me in VS Code after.

I wonder if we should consider adding some kind of timeout on waiting for a response from code execution and asking the user if the code executed successfully.

**Comment by ericrallen** [comment]
Going to close this one as a stale issue. Feel free to reopen if you think there’s more to discuss.
