### ISSUE TITLE
editing config while in > OI 

### ISSUE THREAD

**Issue by text2sql** [KillianLucas/open-interpreter#578]
### Is your feature request related to a problem? Please describe.

would be great to change config / model / prompt on the fly while in OI 

### Describe the solution you'd like

access --config while in OI

**Comment by ericrallen** [comment]
Hey there, @text2sql!

If #609 gets merged, I believe we could leverage the `interpreter.extend_config()` functionality in a magic command like `%config` to achieve this.

We could introduce a few magic commands like `%config edit` (or `%config open`), `%config load`, and maybe `%config_file` to mimic the `--config_file` argument proposed in #609.

We could also consider something similar to the proposal in #612 for handling opening and editing files and having Open Interpreter wait for changes to them, but I think the basic magic commands are probably the better approach for this one.

I'm not sure if any potential issues could arise from things like hot-swapping models in Open Interpreter, though.

**Comment by TanmayDoesAI** [comment]
Implemented in #609 closing as resolved
