### ISSUE TITLE
Please support Azure OpenAI

### ISSUE THREAD

**Issue by Wannabeasmartguy** [KillianLucas/open-interpreter#58]

**Comment by SimplyJuanjo** [comment]
Yeh, this one would be amazing, since some could have access to 32k API via Azure easily than with OpenAI.

**Comment by gianpaj** [comment]
closed by https://github.com/KillianLucas/open-interpreter/pull/62

**Comment by hiirooooo** [comment]
interpreter.use_azure = True
interpreter.api_key = "your_openai_api_key"
interpreter.azure_api_base = "your_azure_api_base"
interpreter.azure_api_version = "your_azure_api_version"
interpreter.azure_deployment_name = "your_azure_deployment_name"

these code are not working.
when "use_azure" is True, connect to ,it connects to openai (not azure open ai

**Comment by KillianLucas** [comment]
Happy to report that **Azure is now fully supported in Open Interpreter** thanks to the incredible @ifsheldon. [Read the docs here.](https://github.com/KillianLucas/open-interpreter/#azure-support)

Run the following commands to get the fix:

```
pip install --upgrade open-interpreter
interpreter --use-azure
```

@hiirooooo -- let me know if that's still the case in Python after this upgrade, but it should be fixed now.

**Comment by Wannabeasmartguy** [comment]
Thanks for your amazing efforts!
