### ISSUE TITLE
Allow use of text-generation-webui api calls

### ISSUE THREAD

**Issue by iplayfast** [KillianLucas/open-interpreter#580]
### Is your feature request related to a problem? Please describe.

I would like to run open-interpreter using a local llm. I think there are better models available then codellama. 

### Describe the solution you'd like

text-generation-webui allows api calls which makes all the difficulties of downloading/loading models etc be handled by text-geneation-webui and open-interpreter can concentrate on what it does best.

**Comment by iplayfast** [comment]
It turns out that [text-generation-webui](https://github.com/oobabooga/text-generation-webui/blob/main/docs/Extensions.md )has  an extension that "Creates an API that mimics the OpenAI API and can be used as a drop-in replacement."  How do I access that when using open-interpreter?

**Comment by TanmayDoesAI** [comment]
@iplayfast Kindly have a look at #625 that should be similar, and it just got merged.

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Feel free to reopen it if there’s new information or something more to discuss.
