### ISSUE TITLE
How can I use an OpenAI proxy url? I need help

### ISSUE THREAD

**Issue by OmiiiDev** [KillianLucas/open-interpreter#583]
### Is your feature request related to a problem? Please describe.

I need help adding the proxy url

### Describe the solution you'd like

I would like it if you would add OpenAI proxy url as an option

**Comment by ericrallen** [comment]
It’s super not cool to open a second issue after you haven’t provided any context on what you tried, if the docs helped or what questions you still have in the original issue.

Please close this and provide some more context on what you tried, what didn’t work, etc. in #551
