### ISSUE TITLE
Make Docker as default and warn user if not running under sandboxes, backup data when drag-n-drop

### ISSUE THREAD

**Issue by James4Ever0** [KillianLucas/open-interpreter#585]
### Is your feature request related to a problem? Please describe.

Many people have reported that this software brings loss of data and unwanted code execution. I do not want to talk about familiarity with coding experience. Nobody has control or observation over mindless AIs when sleeping.

Even though ChatGPT-like LLMs are proficient in programming, they are not error-free. Securities shall be put into first place, if anyone wants to make it stable, user friendly, production ready and even self-learning.

Security is a prerequisite, not something optional or custom.

### Describe the solution you'd like

I want the containerized application run as default, share as few interfaces as possible with the physical machine, copy by default when doing drag-n-drop, execute code only inside the container.

### Describe alternatives you've considered

Virtualbox images, UTM or QEMU. You name it.

### Additional context

I have also posted a similar issue at [AutoGPT](https://github.com/Significant-Gravitas/AutoGPT/issues/5526).

**Comment by ericrallen** [comment]
Hey there!

> Many people have reported that this software brings loss of data and unwanted code execution.

I’m doing some research into this topic and would love some sources for this, if you have them.

There is at least one [currently in-progress Pull Request exploring fist-class containerization](https://github.com/KillianLucas/open-interpreter/pull/459) for the project, but until that’s ready, anyone is free to set up a Dockerfile that runs `pip install open-interpreter` and whatever dependencies they want to give it access to, and interact with it via the container.

In that case, you might want to adjust the `system_message` in the `config.yaml` to mention something like:

> You are inside of a Docker Container and have limited system access.

**Comment by ericrallen** [comment]
@James4Ever0 Is there anything else this Issue is trying to address or can we close it as executing Open Interpreter code in a container is work that's already in-progress?

**Comment by ericrallen** [comment]
I’m going to close this one as stale.

Feel free to reopen it if there is more to discuss.
