### ISSUE TITLE
When using pip to install, pip reports an error, which is solved after error checking, but still reports an error.

### ISSUE THREAD

**Issue by LeiYihan01** [KillianLucas/open-interpreter#586]
### Describe the bug

When I use CMD's pip command, he has a lot of errors, but I checked these errors, solved them, and ran them again, still reporting errors. It's puzzling, I guess I'm mistaken. But still want to ask.

In fact, this is my release with [issue #534,](https://github.com/KillianLucas/open-interpreter/issues/534) I tried osjimene's answer and reinstalled Python 3.10, but I never expected that Python did not have its own pip,😂 and I would not install it myself, so I had to install it back.

The screenshot of the interface is as follows
<img width="1069" alt="1" src="https://github.com/KillianLucas/open-interpreter/assets/140927739/c6e849b3-04a6-4e00-9850-1c00689ce660">

### Reproduce

1. Open CMD directly
2. Follow the steps to install
3. The error begins

### Expected behavior

None

### Open Interpreter version

None

### Python version

3.8.5

### Operating System name and version

Windows 10 21H2 64bit

**Comment by LeiYihan01** [comment]
Can you send me the desktop test version? Please 🤞. I have applied and the email address is leiyihan01@gmail.com

**Comment by AshishJaimon** [comment]
@LeiYihan01 

To create a virtual environment using Python and install it, follow these steps:

1. Create a virtual environment using the command: `conda create -n oi python==3.11.4`
2. Activate the environment using the command: `conda activate oi`
3. Install the open-interpreter using the command: `pip install open-interpreter`

After following these steps, it should work properly.

**Comment by LeiYihan01** [comment]
Oh, thank you very much, but why does it say "'conda' is not an internal or external command, nor is it a runnable program" when I use the conda command
or batch files. ”

**Comment by AshishJaimon** [comment]
@LeiYihan01 that means conda is not installed in your System

**Comment by AshishJaimon** [comment]
@LeiYihan01 you can use other ways also to create an environment rather than using conda.

**Comment by LeiYihan01** [comment]
I have returned to python3.10. I found that I don’t even know how to install python (I should be, I am stupid). In the end, I have to download it from the Microsoft store (I didn’t find it before). Thank you very much for your help.
