### ISSUE TITLE
We were unable to determine the context window of this model. Defaulting to      3000. 

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#590]
### Describe the bug

I get this all the time, but there is nowhere I can set it, at least didn't find it?

We were unable to determine the context window of this model. Defaulting to  3000

Using Azure Open AI GPT-4

### Reproduce

We were unable to determine the context window of this model. Defaulting to     
3000. 

### Expected behavior

Not this message, but just the output

### Open Interpreter version

 0.1.6

### Python version

3.11.5

### Operating System name and version

Mac OS

**Comment by stevenbaert** [comment]
Note: I can run interpreter --model azure/gpt-4 --context_window 3000 but I'd have to run this each time(?)
Can't I just set default to azure and default context_window to 3000?

**Comment by ericrallen** [comment]
@stevenbaert Have you tried setting these in your `config.yaml`?

**Comment by ericrallen** [comment]
Going to close this one as stale.

Feel encouraged to reopen it if you still want to dig into this Issue.
