### ISSUE TITLE
Specify organization for openai

### ISSUE THREAD

**Issue by Sigurd-git** [KillianLucas/open-interpreter#592]
### Is your feature request related to a problem? Please describe.

For users who belong to multiple organizations, OpenAI allows them to specify which organization's quota should be counted. See [Openai Authentication](https://platform.openai.com/docs/api-reference/authentication).
<img width="838" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/52092818/e26a462c-9a16-402d-afe6-089e120d5e16">

### Describe the solution you'd like

Add a parameter to pass organization id or read it from environment.

**Comment by ericrallen** [comment]
Hey there, @Sigurd-git!

I don't have more than one OpenAI Organization to test this with, but if you want to pull down this branch of my Open Interpreter fork and test it, I'd be happy to put up a Pull Request to the core repo here if it works as you would expect.

https://github.com/InterwebAlchemy/open-interpreter/tree/feature/openai-org

It adds a `--organization` or `-org` argument that you can pass when invoking the CLI or you can set `organization` in your `config.yaml`.

## Steps to Test

1. `git clone git@github.com:InterwebAlchemy/open-interpreter.git`
2. `cd open-interpreter`
3. `git checkout feature/openai-org`
4. `poetry run interpreter --organization $OPENAI_ORGANIZATION`

**Note**: Replace `$OPENAI_ORGANIZATION` with your Organization ID, or add it to your `config.yaml` with the key `organization`.

**Comment by krrishdholakia** [comment]
fix pushed - 689371949c120ff6bb748e5736683e091a6e610f

litellm now checks env for `OPENAI_ORGANIZATION`

**Comment by ericrallen** [comment]
@Sigurd-git Do either of these approaches help solve your Issue?

**Comment by Sigurd-git** [comment]
@ericrallen The second worked for me. All I need is to export OPENAI_ORGANIZATION=<my org id>. Thanks!

**Comment by Sigurd-git** [comment]
>export OPENAI_ORGANIZATION=org-xxxxxxx
