### ISSUE TITLE
 pip install open-interpreter

### ISSUE THREAD

**Issue by kouroshshafi** [KillianLucas/open-interpreter#6]
On trying to install using pip, I receive:

ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

**Comment by KillianLucas** [comment]
Hi @kouroshshafi! First I think try to upgrade `pip`, hopefully that fixes it:

```bash
python -m pip install --upgrade pip
```

If not, let me know what python vers you're using with `python --version` then let's work from there 👍
