### ISSUE TITLE
[QUESTION] How can I help with the desktop version?

### ISSUE THREAD

**Issue by quicoli** [KillianLucas/open-interpreter#60]
Hi,

I'd like to help with the desktop version....

**Comment by jordanbtucker** [comment]
Thank you for your interest in contributing! We welcome involvement from the community.

Please see our [Contributing Guidelines](https://github.com/KillianLucas/open-interpreter/blob/main/contributing.md) for more details on how to get involved.

**Comment by quicoli** [comment]
@jordanbtucker I know it might not be in the roadmap.... but how could we discuss (who should I contact) ideas/expectations/features regarding a desktop front-end? 

See, I'm interested in helping and to be fair/honest I have experience with desktop applications and regulated sectors.
So, before I start developing something unwanted could we have a chat? (e-mail works for me)

👍🏻

**Comment by quicoli** [comment]
Oh, sorry... I just saw it now... you are actively using Discord for discussing ideas...  my mistake. I'm going there...  :)
