### ISSUE TITLE
Possible to bypass curses - or document how to make debugging easier?

### ISSUE THREAD

**Issue by dagelf** [KillianLucas/open-interpreter#600]
### Is your feature request related to a problem? Please describe.

The curses interface makes debugging quite hard - as print statements don't work.  Grepping for `debug` doesn't give any obvious hints either, and the default `--debug` flag absolutely spams the screen so as to be virtually useless - just sending that to debug.log would be much more useful - at least you could tail it in a different window. (Which is what I've resorted to, for now)

### Describe the solution you'd like

A command line option to skip using curses and just print to the terminal. 

I'm still trying to wrap my head around the choice of architecture... it's a lot to take in, before you can really start contributing. Is there a discussion or review of why the architecture is the way it is? Is there any part that can be simplified? Or can we at least draft a good contributor guide to help people direct their efforts to the right places? 

### Describe alternatives you've considered

```
import logging
from pprint import pformat

logging.basicConfig(filename='debug.log', level=logging.DEBUG)
logging.debug(pformat(vars(code)))
```

**Comment by ericrallen** [comment]
Hey there!

> print statements don't work

Could you expand on this part? I've contributed a little bit to the project and find myself constantly `print()`ing stuff while I'm working through my implementations, and it seems to work.

I will agree that `debug_mode` is a bit too noisy at the moment, though. Allowing for some alternate logging configuration could be a good PR if you feel strongly about it.

**Comment by ericrallen** [comment]
Going to close this one as stale.

Feel encouraged to reopen it if you want to expand on what you’re experiencing and we can dig into this.
