### ISSUE TITLE
Using OpenAI API proxy breaks the interpreter

### ISSUE THREAD

**Issue by OmiiiDev** [KillianLucas/open-interpreter#601]
### Describe the bug

Wh

### Reproduce

Open cmd
type command: interpreter --api_base "url" --api_key "key" --model openai/gpt-3.5-turbo  --context_window 100000 --max_tokens 10000  

### Expected behavior

I expected it to know the name of my computer

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/103533638/7ff596ab-c8ce-43c5-8923-0a1599ceeb51)

### Open Interpreter version

0.1.7

### Python version

3.10

### Operating System name and version

Windows 10

**Comment by OmiiiDev** [comment]
also, when I say yes to running the code, the Windows terminal starts to stutter and always give out the same error:

![image (1)](https://github.com/KillianLucas/open-interpreter/assets/103533638/3b459911-ce80-43d4-a73f-8dc135de2e9b)
![image (2)](https://github.com/KillianLucas/open-interpreter/assets/103533638/c64d7876-d1e6-47cd-90fa-01efd299772e)
![image](https://github.com/KillianLucas/open-interpreter/assets/103533638/e1feed5c-40ea-428c-8019-4fbff18b3511)

**Comment by ericrallen** [comment]
Just wanted to clarify:

> I expected it to know the name of my computer

There's nothing that tells Open Interpreter the name of your computer. It could run some code, like the `hostname` command to get the name of your computer, but Open Interpreter doesn't "know" anything about your system other than the type of Operating System (Windows vs Mac vs Linux) and your username on your machine.

As far as the issue with running the code, it could be something about how whatever proxy you are using is handling the request to the model?

Have you tried similar requests without the proxy?

Have you tried similar requests with `gpt-4` instead of `gpt-3.5-turbo`?

**Comment by OmiiiDev** [comment]
I see the issue now, when ChatGPT writes code it does it with the  **``** little things on the top and bottom of the text, which triggers the Windows machine to not realize the command because of the  ``

**Example of AI response:**
  ``
  import request
  ``
  
  **What it should be:**
  
  import request

**Comment by ericrallen** [comment]
Open Interpreter's terminal interface is supposed to render markdown and markdown code blocks use three backticks (`\`\`\``) to designate a codeblock.

It seems like something might be strange with the terminal itself.

Is this Command Prompt, Terminal, or some other program?

**Comment by OmiiiDev** [comment]
It is the Windows command prompt

**Comment by OmiiiDev** [comment]
@ericrallen Any fix on this?

**Comment by ericrallen** [comment]
@OmiiiDev Unfortunately, I don't have Open Interpreter running on a Windows machine, so I think someone else is going to have to help debug this one.

**Comment by OmiiiDev** [comment]
What OS are you running it on?

**Comment by OmiiiDev** [comment]
@ericrallen Can you tell me what os you are using to run open interpreter? And what the settings are (in case there are some settings that need to be changed)?

**Comment by ericrallen** [comment]
Going to close this one as stale for now.

I believe this should work with the underlying LiteLLM integration.
