### ISSUE TITLE
Cant install it, like at all

### ISSUE THREAD

**Issue by idk73248** [KillianLucas/open-interpreter#602]
### Describe the bug

I cannot install it, it just shows this
![Screenshot 2023-10-07 232424](https://github.com/KillianLucas/open-interpreter/assets/86132722/373eae3f-7f29-4ee7-8306-a84a52ad9bd9)

### Reproduce

Just open python and type pip install open-interpreter

### Expected behavior

I expect it to well... install

### Open Interpreter version

None

### Python version

3.12

### Operating System name and version

Windows eleven, latest stable update

**Comment by KillianLucas** [comment]
Hi @idk73248. It looks like you're running a shell command in Python! You can simply open Terminal/CMD and run the command, no need to open Python.
