### ISSUE TITLE
So, now it wont run

### ISSUE THREAD

**Issue by idk73248** [KillianLucas/open-interpreter#603]
### Describe the bug

When i type intrepreter, it says this
![image](https://github.com/KillianLucas/open-interpreter/assets/86132722/f1c02d44-183a-4561-8639-7a62f7b789db)
In terminal (specifically powershell) its just 
![image](https://github.com/KillianLucas/open-interpreter/assets/86132722/2a596a32-1107-4f5f-93a8-db52b3ea6a42)

### Reproduce

Just try to run it in terminal, python 3.11, 3.12 or anything really

### Expected behavior

For it to run

### Open Interpreter version

0.1.7

### Python version

3.12

### Operating System name and version

WIndows 11, latest stable update

**Comment by ibharathboga** [comment]
hey there, 
maybe see [#issue169](https://github.com/KillianLucas/open-interpreter/issues/169)

**Comment by idk73248** [comment]
> hey there, maybe see [#issue169](https://github.com/KillianLucas/open-interpreter/issues/169)

I dont know how to use path

**Comment by TanmayDoesAI** [comment]
@idk73248 this maybe of help [add python to path](https://www.mygreatlearning.com/blog/add-python-to-path/)

**Comment by ericrallen** [comment]
Hey there, @idk73248!

Have you tried making sure that your `PATH` is correct?

I’m going to close this one as stale for now, but please reopen if you configure your path, update to the latest version, and still experience this issue.
