### ISSUE TITLE
'interpreter' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by vinusmiles** [KillianLucas/open-interpreter#604]
### Describe the bug

Please help in fixing this

![image](https://github.com/KillianLucas/open-interpreter/assets/24727104/01c96315-028a-4ded-8f25-adc8defe6789)

### Reproduce

pip install open-interpreter ---> success

but on executing cmd "interpreter" after the above I am getting error

### Expected behavior

should run

### Open Interpreter version

0.1.4

### Python version

3.10.1

### Operating System name and version

Windows 10 Home Single Language

**Comment by ibharathboga** [comment]
hey there,
maybe see https://github.com/KillianLucas/open-interpreter/issues/169
