### ISSUE TITLE
Azure openai not working

### ISSUE THREAD

**Issue by amazingvince** [KillianLucas/open-interpreter#608]
### Describe the bug

I have followed the suggested steps in the issues tab. I have set --model azure/<model id>. The error looks like it fails to make the openai model on line 100 of setup_openai_coding_llm with "NoneType" object is not iteraable.

It then says it failed to make a litellm object.

### Reproduce

interpreter --model azure/gpt-4 

### Expected behavior

It should make an azure model object 

### Open Interpreter version

tried on main and latest on pip

### Python version

3.10

### Operating System name and version

windows

**Comment by ericrallen** [comment]
Hey there!

I'm not an expert on the Azure integration, but just wanted to double-check that you've got your [`AZURE_API_*` Environment Variables](https://docs.openinterpreter.com/language-model-setup/hosted-models/azure#required-environment-variables) set up and that you're using the Deployment ID as described in the [comments](https://github.com/KillianLucas/open-interpreter/issues/559#issuecomment-1742355858) of #559?

**Comment by amazingvince** [comment]
yes is set env vars though dont see here in the code where they are refrenced. The debug does not show them. I am using the model name from the azure portal which I think was the guidance in 559.

**Comment by amazingvince** [comment]
I updated to the latest version of litellm which fixed the probblem

**Comment by krrishdholakia** [comment]
glad it got fixed @amazingvince
