### ISSUE TITLE
Unsupported Language: powershell , Win11

### ISSUE THREAD

**Issue by DaveChini** [KillianLucas/open-interpreter#610]
### Describe the bug

get this error whenever any of the models output powershell script.

```
Traceback (most recent call last):
    File
  "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreters\create_code_i
  nterpreter.py", line 8, in create_code_interpreter
      CodeInterpreter = language_map
  KeyError: 'powershell'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\respond.py", line
  105, in respond
      interpreter._code_interpreters = create_code_interpreter(language)
    File
  "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreters\create_code_i
  nterpreter.py", line 11, in create_code_interpreter
      raise ValueError(f"Unknown or unsupported language: {language}")
  ValueError: Unknown or unsupported language: powershell
```

### Reproduce

On windows 11 using latest release of intepreter 0.1.7
ask the model to output a powershell script, even simple things like "list the files in the current working directory"

### Expected behavior

can execute powershell script and continues.

### Screenshots

![Screenshot 2023-10-09 154320](https://github.com/KillianLucas/open-interpreter/assets/65976856/ab30dc04-afbe-44b8-ba59-bb0949afd343)

### Open Interpreter version

0.1.7

### Python version

3.10

### Operating System name and version

Windows 11

**Comment by ericrallen** [comment]
Hey there!

PowerShell isn't currently one of the supported [languages](https://github.com/KillianLucas/open-interpreter/tree/main/interpreter/code_interpreters/languages) that has been implemented in Open Interpreter.

If you're a frequent PowerShell user, please consider contributing PowerShell language support to [`interpreter/languages`](https://github.com/KillianLucas/open-interpreter/tree/main/interpreter/code_interpreters/languages).

**Comment by DaveChini** [comment]
ok thank you, i had it in my head it was supported. Ill work on it in my free time.
