### ISSUE TITLE
download language model

### ISSUE THREAD

**Issue by While941** [KillianLucas/open-interpreter#611]
### Is your feature request related to a problem? Please describe.

i need to download language model when use local. but disk space available
How to change the download path ?

Download to `C:\Users\z\AppData\Local\Open Interpreter\Open Interpreter\models`?
[?]  (Y/n): y

You do not have enough disk space available to download this model.
Open Interpreter will require approval before running code.

### Describe the solution you'd like

How to change the download path ?

**Comment by ericrallen** [comment]
I don't believe there is currently a way to change the path for the models directory.

**Comment by While941** [comment]
> I don't believe there is currently a way to change the path for the models directory.

alright

**Comment by ericrallen** [comment]
@While941 You might find some helpful info in the comments from #294 about using symlinks to try to manage this issue.

Alternatively, you could submit a Pull Request allowing the user to specify where to store downloaded models.
