### ISSUE TITLE
Issues with Azure setting

### ISSUE THREAD

**Issue by nsvbhat** [KillianLucas/open-interpreter#615]
### Describe the bug

I am trying to point to my azure keys in the application, but each time I get the issue

`There might be an issue with your API key(s).
 To reset your API key (we'll use OPENAI_API_KEY for this example, but you may need to reset your ANTHROPIC_API_KEY, HUGGINGFACE_API_KEY, etc):
        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',
        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.`

Have done everything mentioned in the documentation to setup interpreter with azure but it does not work for me. :(

Any help will be appreciated. I am trying to build a simple streamlit application as a frontend invoking interpreter..

I even went and set the model in the code to reflect azure.. 

### Reproduce

1. Configure the interpreter to use azure:

```
interpreter.azure_api_type = "azure" 
interpreter.use_azure = True
interpreter.azure_api_base = "https://something.openai.azure.com/"
interpreter.azure_api_version = "2023-05-15"
interpreter.azure_api_key = "my-azure-key"
interpreter.azure_deployment_name="GPT-4"
interpreter.auto_run = True
interpreter.conversation_history = True
```

```
async def get_response(prompt: str, files: Optional[list] = None):
    if files is None:
        files = []
    with st.chat_message("user"):
        st.write(prompt)
    with st.spinner():
        response=''
        for chunk in interpreter.chat(f'content={input_text}, files={file_path}', stream=True):
            if 'message' in chunk:
                response += chunk['message']
        st.write(response)
```

and sometimes i get an issue as below abotu SSL... 
<img width="839" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/40305398/801bb045-3677-416f-b348-ab91ec584761">

### Expected behavior

The azure specific configurations must be picked up and the interpreter must work as expected.

### Screenshots

<img width="1264" alt="Screenshot 2023-10-10 at 12 16 58" src="https://github.com/KillianLucas/open-interpreter/assets/40305398/c6519d1d-55d6-41bf-80a8-95b7cc6df300">

### Open Interpreter version

0.1.7

### Python version

3.11.3

### Operating System name and version

Windows 11

**Comment by ericrallen** [comment]
Hey there, @nsvbhat!

I think the way that Azure models are referenced was changed.

You should be able to get them working by following the updated [Azure Docs](https://docs.openinterpreter.com/language-model-setup/hosted-models/azure).

I'm going to close this one for now, but please reopen it and let us know if you run into issues after following the docs.
