### ISSUE TITLE
azure openai api version support in yaml config file

### ISSUE THREAD

**Issue by rasmusstrong** [KillianLucas/open-interpreter#616]
### Is your feature request related to a problem? Please describe.

Currently using open-interpreter version 0.1.7 together with azure openai, I need to specify the api_version as an environment 
variable in my shell configuration file, e.g: 

export: AZURE_API_VERSION=2023-08-01-preview

### Describe the solution you'd like

I would like to be able to specify the api version in open-interpreter's config.yaml just like the api_key and api_base.
An argument like api_version would be appreciated.

**Comment by ericrallen** [comment]
If anyone wants to tackle this one before someone can get to it, we need to add some handling for setting the `api_version` property on the `params` object, similarly to how we handle `api_base` and `api_key`:

- [interpreter/llm/setup_text_llm.py](https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/llm/setup_text_llm.py#L98)
- [interpreter/llm/setup_openai_coding_llm](https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/llm/setup_openai_coding_llm.py#L75)

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
