### ISSUE TITLE
Open Interpreter does not work with Azure OpenAI

### ISSUE THREAD

**Issue by pav-les** [KillianLucas/open-interpreter#618]
### Describe the bug

I am trying to point to my azure keys in the application, but I get the issue
_Unrecognized request argument supplied: functions_

### Reproduce

Configure the interpreter to use azure:
```
import interpreter
import litellm
interpreter.use_azure = True
interpreter.model = "azure/gpt-4-large"
interpreter.api_key = "..."
interpreter.azure_api_base = "https://...openai.azure.com/"
interpreter.azure_api_version = "2023-05-15"
interpreter.azure_deployment_name = "gpt-4-large"
interpreter.azure_api_type = "azure"
os.environ["AZURE_API_KEY"]=interpreter.api_key 
os.environ["AZURE_API_BASE"]= interpreter.azure_api_base
os.environ["AZURE_API_VERSION"] = interpreter.azure_api_version
interpreter.chat()
```
**Error:**
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
Cell In[39], line 1
----> 1 interpreter.chat()

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/core/core.py:66, in Interpreter.chat(self, message, display, stream)
     63     return self._streaming_chat(message=message, display=display)
     65 # If stream=False, *pull* from the stream.
---> 66 for _ in self._streaming_chat(message=message, display=display):
     67     pass
     69 return self.messages

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/core/core.py:87, in Interpreter._streaming_chat(self, message, display)
     82 # Sometimes a little more code -> a much better experience!
     83 # Display mode actually runs interpreter.chat(display=False, stream=True) from within the terminal_interface.
     84 # wraps the vanilla .chat(display=False) generator in a display.
     85 # Quite different from the plain generator stuff. So redirect to that
     86 if display:
---> 87     yield from terminal_interface(self, message)
     88     return
     90 # One-off message

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/terminal_interface/terminal_interface.py:62, in terminal_interface(interpreter, message)
     59 render_cursor = False
     61 try:
---> 62     for chunk in interpreter.chat(message, display=False, stream=True):
     63         if interpreter.debug_mode:
     64             print("Chunk in `terminal_interface`:", chunk)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/core/core.py:95, in Interpreter._streaming_chat(self, message, display)
     93     message = "No entry from user - please suggest something to enter"
     94 self.messages.append({"role": "user", "message": message})
---> 95 yield from self._respond()
     97 # Save conversation if we've turned conversation_history on
     98 if self.conversation_history:
     99 
    100     # If it's the first message, set the conversation name

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/core/core.py:121, in Interpreter._respond(self)
    120 def _respond(self):
--> 121     yield from respond(self)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/core/respond.py:57, in respond(interpreter)
     54 # Start putting chunks into the new message
     55 # + yielding chunks to the user
     56 try:
---> 57     for chunk in interpreter._llm(messages_for_llm):
     58 
     59         # Add chunk to the last message
     60         interpreter.messages[-1] = merge_deltas(interpreter.messages[-1], chunk)
     62         # This is a coding llm
     63         # It will yield dict with either a message, language, or code (or language AND code)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/interpreter/llm/setup_openai_coding_llm.py:94, in setup_openai_coding_llm.<locals>.coding_llm(messages)
     91 if interpreter.debug_mode:
     92     print("Sending this to LiteLLM:", params)
---> 94 response = litellm.completion(**params)
     96 accumulated_deltas = {}
     97 language = None

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/utils.py:718, in client.<locals>.wrapper(*args, **kwargs)
    714     if (
    715         liteDebuggerClient and liteDebuggerClient.dashboard_url != None
    716     ):  # make it easy to get to the debugger logs if you've initialized it
    717         e.message += f"\n Check the log in your dashboard - {liteDebuggerClient.dashboard_url}"
--> 718 raise e

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/utils.py:677, in client.<locals>.wrapper(*args, **kwargs)
    674             return cached_result
    676 # MODEL CALL
--> 677 result = original_function(*args, **kwargs)
    678 end_time = datetime.datetime.now()
    679 if "stream" in kwargs and kwargs["stream"] == True:
    680     # TODO: Add to cache for streaming

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/timeout.py:53, in timeout.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
     51     local_timeout_duration = kwargs["request_timeout"]
     52 try:
---> 53     result = future.result(timeout=local_timeout_duration)
     54 except futures.TimeoutError:
     55     thread.stop_loop()

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/concurrent/futures/_base.py:458, in Future.result(self, timeout)
    456     raise CancelledError()
    457 elif self._state == FINISHED:
--> 458     return self.__get_result()
    459 else:
    460     raise TimeoutError()

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/timeout.py:42, in timeout.<locals>.decorator.<locals>.wrapper.<locals>.async_func()
     41 async def async_func():
---> 42     return func(*args, **kwargs)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/main.py:1213, in completion(model, messages, functions, function_call, temperature, top_p, n, stream, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, deployment_id, request_timeout, **kwargs)
   1210     return response
   1211 except Exception as e:
   1212     ## Map to OpenAI Exception
-> 1213     raise exception_type(
   1214         model=model, custom_llm_provider=custom_llm_provider, original_exception=e, completion_kwargs=args,
   1215     )

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/utils.py:2851, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   2849 # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   2850 if exception_mapping_worked:
-> 2851     raise e
   2852 else:
   2853     raise original_exception

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/utils.py:2270, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   2264     if "This model's maximum context length is" in original_exception._message:
   2265         raise ContextWindowExceededError(
   2266             message=str(original_exception),
   2267             model=model,
   2268             llm_provider=original_exception.llm_provider
   2269         )
-> 2270     raise original_exception
   2271 elif model:
   2272     error_str = str(original_exception)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/litellm/main.py:320, in completion(model, messages, functions, function_call, temperature, top_p, n, stream, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, deployment_id, request_timeout, **kwargs)
    310 logging.pre_call(
    311     input=messages,
    312     api_key=api_key,
   (...)
    317     },
    318 )
    319 ## COMPLETION CALL
--> 320 response = openai.ChatCompletion.create(
    321     engine=model,
    322     messages=messages,
    323     headers=litellm.headers,
    324     api_key=api_key,
    325     api_base=api_base,
    326     api_version=api_version,
    327     api_type=api_type,
    328     **optional_params,
    329 )
    330 if "stream" in optional_params and optional_params["stream"] == True:
    331     response = CustomStreamWrapper(response, model, custom_llm_provider="openai", logging_obj=logging)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/openai/api_resources/chat_completion.py:25, in ChatCompletion.create(cls, *args, **kwargs)
     23 while True:
     24     try:
---> 25         return super().create(*args, **kwargs)
     26     except TryAgain as e:
     27         if timeout is not None and time.time() > start + timeout:

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py:155, in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    129 @classmethod
    130 def create(
    131     cls,
   (...)
    138     **params,
    139 ):
    140     (
    141         deployment_id,
    142         engine,
   (...)
    152         api_key, api_base, api_type, api_version, organization, **params
    153     )
--> 155     response, _, api_key = requestor.request(
    156         "post",
    157         url,
    158         params=params,
    159         headers=headers,
    160         stream=stream,
    161         request_id=request_id,
    162         request_timeout=request_timeout,
    163     )
    165     if stream:
    166         # must be an iterator
    167         assert not isinstance(response, OpenAIResponse)

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/openai/api_requestor.py:299, in APIRequestor.request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    278 def request(
    279     self,
    280     method,
   (...)
    287     request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    288 ) -> Tuple[Union[OpenAIResponse, Iterator[OpenAIResponse]], bool, str]:
    289     result = self.request_raw(
    290         method.lower(),
    291         url,
   (...)
    297         request_timeout=request_timeout,
    298     )
--> 299     resp, got_stream = self._interpret_response(result, stream)
    300     return resp, got_stream, self.api_key

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/openai/api_requestor.py:710, in APIRequestor._interpret_response(self, result, stream)
    702     return (
    703         self._interpret_response_line(
    704             line, result.status_code, result.headers, stream=True
    705         )
    706         for line in parse_stream(result.iter_lines())
    707     ), True
    708 else:
    709     return (
--> 710         self._interpret_response_line(
    711             result.content.decode("utf-8"),
    712             result.status_code,
    713             result.headers,
    714             stream=False,
    715         ),
    716         False,
    717     )

File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/openai/api_requestor.py:775, in APIRequestor._interpret_response_line(self, rbody, rcode, rheaders, stream)
    773 stream_error = stream and "error" in resp.data
    774 if stream_error or not 200 <= rcode < 300:
--> 775     raise self.handle_error_response(
    776         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    777     )
    778 return resp

InvalidRequestError: Unrecognized request argument supplied: functions

Just with litellm it works:
```
import os
from litellm import completion

use_azure = True
model = "azure/gpt-4-large"
api_key = "..."
azure_api_base = "https://....openai.azure.com/"
azure_api_version = "2023-05-15"
azure_deployment_name = "gpt-4-large"
azure_api_type = "azure"
os.environ["AZURE_API_KEY"]=api_key 
os.environ["AZURE_API_BASE"]= azure_api_base
os.environ["AZURE_API_VERSION"] = azure_api_version

messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion("azure/gpt-4-large", messages)
print(response)
```
"message": {
        "role": "assistant",
        "content": "Hello! As an AI, I do not have feelings or emotions, but I'm here to help you. How can I assist you today?"
}

### Expected behavior

The open interpreter should work as expected.

### Open Interpreter version

0.1.7

### Python version

3.10

### Operating System name and version

  Operating System: Ubuntu 20.04.6 LTS             Kernel: Linux 5.15.0-1040-azure

**Comment by amazingvince** [comment]
the api version you are using is too old. This app seems to require function calling. Make sure you are using a newer version of gpt4 with a later api version.

**Comment by pav-les** [comment]
@amazingvince, thank you for the advice. Unfortunately, it is not what I can easily change. I wonder why using only the same version of "litellm" does not result in an error. Is it possible to use an older version of open interpreter to make everything work?

**Comment by pav-les** [comment]
By the way "2023-05-15" is the most recent version of API that is not in preview mode is:
Azure OpenAI Supported versions
:
2022-12-01 [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2022-12-01/inference.json)
2023-03-15-preview [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json)
2023-05-15 [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/inference.json)
2023-06-01-preview [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-06-01-preview/inference.json)
2023-07-01-preview [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-07-01-preview/inference.json)
2023-08-01-preview [Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-08-01-preview/inference.json)

**Comment by pav-les** [comment]
Hello everyone, the solution was  indeed to choose the model and versions that are the most recent. In my case:
![image](https://github.com/KillianLucas/open-interpreter/assets/141645071/e70eccec-5ad9-476d-96d5-2a7be4418acd)
and  azure_api_version = "2023-07-01-preview"
