### ISSUE TITLE
Unable to execute code

### ISSUE THREAD

**Issue by usathyan** [KillianLucas/open-interpreter#619]
### Describe the bug

Here is the response from open-interpreter to create a scatter plot based on an uploaded excel csv file:

------------------------
"Let's break the task down into steps:

Step 1. Read the data file using pandas and check its first few rows to see its structure.

Step 2. Plot the required scatterplot using any visualization library such as matplotlib, seaborn, or plotly. For interactive options (including hover features), we'll use plotly.

Package requirements for this task:

pandas
plotly
Since Python is the language of choice for this task, let's proceed by first reading the data and exploring it.The Amazon products data has been successfully loaded and contains 17 columns. The columns include 'Unnamed: 0', 'actual_price (USD)', 'category', 'product_name', 'rating', 'product_link' and others.

For the scatterplot, we need the following columns: 'actual_price (USD)', 'category', 'product_name', and 'rating'.

Let's proceed to Step 2, which creates the scatterplot with the mentioned features. We will use the plotly.express library for this because it makes it straightforward to add the required color variation and hover features.The error arose because the column name 'actual_price (USD)' does not exist in the dataframe. The error message states that actual_price (USD) is not a column in the data frame.

The 'expected' columns according to the error message are: 'Unnamed: 0', 'product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', and 'product_link'.

It seems that there is a misunderstanding regarding the actual price's column name. From the provided columns, 'actual_price' appears to be the column we may be interested in as it's most likely to represent the product's actual price.

Let's create the scatterplot again, this time referring to 'actual_price' instead of 'actual_price (USD)'.It seems we're facing an issue with exporting the plot created with plotly as a .png image.

The error message suggests that we need to install the kaleido package which is required for image export with the plotly engine.

Here's what we can do:

Install the required kaleido package.
Once the package is installed, we try to execute the code again to create and save the scatterplot.
Let's proceed with the first option and try to install kaleido package on your machine.Unfortunately, the installation of the kaleido package failed due to a connection timeout to pypi.org.

This could occur for a few reasons:

An unstable internet connection that's preventing the connection to the Python package index.
There might be issues with the Python package index service, though this is quite rare.
Here's what we can do to proceed:

We could try the installation again, which might work if the problem was temporary.
If it continues to fail, we could attempt to install kaleido from a different index server.
As a last resort, if it's okay with you, we could use a different plotting library that doesn't require any additional installations. Matplotlib can help us in creating scatter plots, which is an alternative strategy (though this might slightly change the appearance of your plot).
Would it be okay for you if we try an alternative method? Or, do you prefer to retry the installation of kaleido package?
-----------------------------

As you can see - it looks like there is some issue in instantiating the sandbox to execute this. I am suspecting this to be related to  network proxy, but need some hints as to where in the code this happening so i can fix/add the proxy details.

Much appreciated!

### Reproduce

open interepter works; but not completely - it is unable to execute code in sandbox.

### Expected behavior

I would expect to see an executed scatter plot in PNG  in the response, not just text.

### Screenshots

none available.

### Open Interpreter version

0.1.7

### Python version

3.11.5

### Operating System name and version

Windows 11

### Additional context

Thanks for a great program!

**Comment by usathyan** [comment]
Hi, thanks!
If I understand the code correctly, I think you are asking for code
snippets from https://open-procedures.replit.app/search/, compile them into
an executable package; and execute it on a terminal simulation (magic
commands). Unfortunately, sometimes the recommendations may include
non-python - for example I am seeing R code. and if my computer has no R
installed, it will fail. Is there a way to address this?
Thanks

**Comment by ericrallen** [comment]
@usathyan I think you can close the Issue yourself if it's resolved on your end.

**Comment by TanmayDoesAI** [comment]
Closing as resolved!
