### ISSUE TITLE
I have a error when run the code"pip3 install open-interpreter"

### ISSUE THREAD

**Issue by Zcc1234567890** [KillianLucas/open-interpreter#624]
### Describe the bug

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build tiktoken aiohttp
ERROR: Could not build wheels for tiktoken, aiohttp, which is required to install pyproject.toml-based projects

### Reproduce

run the code'pip3 install open-interpreter'
and then after some download going
shows a line of red sentences
“note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build tiktoken aiohttp
ERROR: Could not build wheels for tiktoken, aiohttp, which is required to install pyproject.toml-based projects”

### Expected behavior

I want to run it with out error

### Open Interpreter version

Package(s) not found: open-interpreter

### Python version

3.12.0

### Operating System name and version

MACOS 14.0

**Comment by ericrallen** [comment]
I don't think a lot of the dependencies that Open Interpreter relies are have added support for Python `3.12` yet.

Can you try with `3.11`?

**Comment by leifktaylor** [comment]
@ericrallen is correct; 

In the poetry lock you can see we are locked at `aiohttp-3.8.6`.

Unfortunately, aiohttp currently does not support python 3.12

This is a post from aiohttp dev from yesterday stating such:
https://github.com/DevilXD/TwitchDropsMiner/issues/318#issuecomment-1763233448

**We will need to wait for the latest aiohttp release to support python 3.12, until that time use 3.11**

@KillianLucas @jordanbtucker I suggest closing this issue, and perhaps updating docs to reference that we do not support 3.12 until aiohttp release supports it.
```

**Comment by ericrallen** [comment]
Going to close this one for now.

We’ll update support for 3.12 once our dependencies are ready.
