### ISSUE TITLE
Compatibility Issue with Python 3.12 - Temporary Solution

### ISSUE THREAD

**Issue by TanmayDoesAI** [KillianLucas/open-interpreter#627]
## Known Issue: Compatibility with Python 3.12

**Issue Description:**
As of the latest release, Open-Interpreter is facing compatibility issues with Python 3.12 due to certain dependencies, I believe `aiohttp`, not yet supporting this version. This may result in errors when attempting to run/install Open-Interpreter on Python 3.12.

**Temporary Solution:**
To work around this issue, it is recommended to create a separate Conda environment with a Python version lower than 3.12. You can use the following command to achieve this:

```bash
conda create -n open-interpreter-env python=3.11
conda activate open-interpreter-env
```

You can then proceed to use Open-Interpreter within this environment.

Dependency Update:
It's worth noting that the [aiohttp](https://github.com/aio-libs/aiohttp/) have released a beta version with the fix [here](https://github.com/aio-libs/aiohttp/issues/7685).

We appreciate your patience and understanding in this matter. If you encounter any further issues or have additional questions, please feel free to reach out to us on [Discord](https://discord.gg/6p3fD6rBVm) or by opening a new issue, providing all relevant details for expedited assistance.

Thank you for your continued support for Open-Interpreter!

**Comment by bmwhite1611** [comment]
I tried downgrading to 3.11... but I have the new open-interpreter version... how do I downgrade to the last interpreter so at least it works?

**Comment by MikeBirdTech** [comment]
3.12 does not play nice with tiktoken yet, and OI is dependent on it. Hopefully this changes soon! Will upgrade as soon as possible

**Comment by JamesClarke7283** [comment]
> 3.12 does not play nice with tiktoken yet, and OI is dependent on it. Hopefully this changes soon! Will upgrade as soon as possible

Just some added context, i am sure everyone knows as it's closed.

I ran the unit test's today, and they seem to be fine for 3.12, with tiktoken 0.9.0.
https://github.com/openai/tiktoken/issues/264#issuecomment-2993468948
