### ISSUE TITLE
Rate Limit Usage in stream

### ISSUE THREAD

**Issue by brettstark73** [KillianLucas/open-interpreter#628]
### Describe the bug

Tried a few basic commands - 

> Plot AAPL and META's normalized stock prices

See what seems an error and then app crashes.

### Reproduce

> Plot AAPL and META's normalized stock prices

Run

line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 200 from API ("{\"rate_limit_usage\": {\)

Crash

### Expected behavior

Do something :).

### Open Interpreter version

0.1.8

### Python version

3.11.6

### Operating System name and version

Mac OS 14.0

**Comment by tyfiero** [comment]
I'm getting the same bug too

**Comment by tyfiero** [comment]
This seems to be happening when I use --fast (gpt-3.5-turbo).  Almost every request I send with 3.5 fails with the `openai.error.APIError: HTTP code 200 from API ("{\"rate_limit_usage\": {\)` error before it tries to execute the code.

**Comment by sanyarajan** [comment]
I get the same error when using the GPT4 model

**Comment by ericrallen** [comment]
Hey there, folks!

I’d like to consolidate discussions around rate limit errors to #408

Please feel encouraged to continue the discussion in that thread.

**Comment by Gera001** [comment]
请问有人解决了吗？感谢！
