### ISSUE TITLE
`Code-Llama` interface package not found. Install `llama-cpp-python`?

### ISSUE THREAD

**Issue by 451983910** [KillianLucas/open-interpreter#63]
When performing this step“When performing this step”，terminal error shows"error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [116 lines of output]"
"  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects"

The log records are as follows“[?] `Code-Llama` interface package not found. Install `llama-cpp-python`? (...: 
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.83.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (4.7.1)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/site-packages (from llama-cpp-python) (1.24.3)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Obtaining dependency information for diskcache>=5.6.1 from https://files.pythonhosted.org/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl.metadata
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [116 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      -- The C compiler identification is AppleClang 11.0.0.11000033
      sh: ps: command not found
      -- Detecting C compiler ABI info
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /usr/bin/cc
      sh: ps: command not found
      sh: ps: command not found
      sh: ps: command not found
      -- Check for working C compiler: /usr/bin/cc - broken
      CMake Error at /tmp/pip-build-env-d3oo_3ih/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler
      
          "/usr/bin/cc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/tmp/pip-install-p2qsitk1/llama-cpp-python_c3e8e2f322cc4821955fb6d001cb3564/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-3eEGeq'
      
          Run Build Command(s): /private/tmp/pip-build-env-d3oo_3ih/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -v cmTC_ac853
          [1/2] /usr/bin/cc   -arch x86_64 -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o -c /tmp/pip-install-p2qsitk1/llama-cpp-python_c3e8e2f322cc4821955fb6d001cb3564/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-3eEGeq/testCCompiler.c
          FAILED: CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o
          /usr/bin/cc   -arch x86_64 -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_ac853.dir/testCCompiler.c.o -c /tmp/pip-install-p2qsitk1/llama-cpp-python_c3e8e2f322cc4821955fb6d001cb3564/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-3eEGeq/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=13.0'
          ninja: build stopped: subcommand failed.
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      sh: ps: command not found
      CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------
      
                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.
      
                      Building MacOSX wheels for Python 3.11 requires XCode.
      Get it here:
      
        https://developer.apple.com/xcode/
      
                      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
Error during installation with Metal: Command 
'['/usr/local/opt/python@3.11/bin/python3.11', '-m', 'pip', 'install', 
'llama-cpp-python']' returned non-zero exit status 1.

▌ Failed to install Code-LLama.                                               

We have likely not built the proper Code-Llama support for your system.         

( Running language models locally is a difficult task! If you have insight into 
the best way to implement this across platforms/architectures, please join the  
Open Interpreter community Discord and consider contributing the project's      
development. )                                                                  

Please press enter to switch to GPT-4 (recommended).                            

”

please help🙏

**Comment by TanmayDoesAI** [comment]
try installing `llama-cpp-python` separately and then try running this command again, that may help with this.

**Comment by andrescueva** [comment]
Hi, make sure to install gcc. Also, if you are getting this note at the end of the message:

 ` ********************************************************************************
      [end of output] 
note: This error originates from a subprocess, and is likely not a problem with pip.` 

Install the pacakge at CLI:
`pip install llama-cpp-python`
Then it works.

**Comment by gerickt** [comment]
in Windows 11 environment:
- install Visual Studio 2019/2022
- start a Developer Command Prompt
- (optional) conda activate env
- `pip install llama-cpp-python`

works like a charm

**Comment by Silversith** [comment]
Well, that took a second to figure out. You need to use Python x64 not x86

**Comment by GuyBarel26** [comment]
i did everything you guys mentioned but im still getting the same problem pls help

**Comment by bradsterling** [comment]
I ran this command to verify I was running x64:

import platform

if platform.architecture()[0] == "64bit":
  print("You are running Python x64")
else:
  print("You are running Python x86")
  
  Running Python x64 did not fix this error. I have tried all the above. I'm running Windows 10 Enterprise

**Comment by jordanbtucker** [comment]
@bradsterling On Windows, follow the steps in [Code-Llama on Windows](https://github.com/jordanbtucker/open-interpreter/blob/windows/WINDOWS.md).

For MacOS, you need CMake and possibly other development tools like XCode.

**Comment by 451983910** [comment]
> try installing `llama-cpp-python` separately and then try running this command again, that may help with this.

I tried  installing llamma separately ,it still shows"[end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
"
log are as follows" pip3 install llama-cpp-python
Collecting llama-cpp-python
  Using cached llama_cpp_python-0.1.83.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.5.0 (from llama-cpp-python)
  Obtaining dependency information for typing-extensions>=4.5.0 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting numpy>=1.20.0 (from llama-cpp-python)
  Obtaining dependency information for numpy>=1.20.0 from https://files.pythonhosted.org/packages/c9/57/3cb8131a0e6d559501e088d3e685f4122e9ff9104c4b63e4dfd3a577b491/numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (5.6 kB)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Obtaining dependency information for diskcache>=5.6.1 from https://files.pythonhosted.org/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl.metadata
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Using cached diskcache-5.6.3-py3-none-any.whl (45 kB)
Using cached numpy-1.25.2-cp311-cp311-macosx_10_9_x86_64.whl (20.8 MB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [136 lines of output]
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Ninja' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 11.0.0.11000033
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-build-env-xcidj7nk/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler
      
          "/Library/Developer/CommandLineTools/usr/bin/cc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-install-8_ru_40f/llama-cpp-python_55b0b2b093ce4f10ad14fd145de112ee/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zEhhNz'
      
          Run Build Command(s): /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-build-env-xcidj7nk/overlay/lib/python3.11/site-packages/ninja/data/bin/ninja -v cmTC_6e0ce
          [1/2] /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o -c /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-install-8_ru_40f/llama-cpp-python_55b0b2b093ce4f10ad14fd145de112ee/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zEhhNz/testCCompiler.c
          FAILED: CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_6e0ce.dir/testCCompiler.c.o -c /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-install-8_ru_40f/llama-cpp-python_55b0b2b093ce4f10ad14fd145de112ee/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-zEhhNz/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=13.0'
          ninja: build stopped: subcommand failed.
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja' generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying 'Unix Makefiles' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      Not searching for unused variables given on the command line.
      
      -- The C compiler identification is AppleClang 11.0.0.11000033
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
      CMake Error at /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-build-env-xcidj7nk/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler
      
          "/Library/Developer/CommandLineTools/usr/bin/cc"
      
        is not able to compile a simple test program.
      
        It fails with the following output:
      
          Change Dir: '/private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-install-8_ru_40f/llama-cpp-python_55b0b2b093ce4f10ad14fd145de112ee/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-3bKYan'
      
          Run Build Command(s): /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-build-env-xcidj7nk/overlay/lib/python3.11/site-packages/cmake/data/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_72ce0/fast
          /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_72ce0.dir/build.make CMakeFiles/cmTC_72ce0.dir/build
          Building C object CMakeFiles/cmTC_72ce0.dir/testCCompiler.c.o
          /Library/Developer/CommandLineTools/usr/bin/cc   -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_72ce0.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_72ce0.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_72ce0.dir/testCCompiler.c.o -c /private/var/folders/nn/6dg92q5n5vgd_0bbpw4lj0cm0000gn/T/pip-install-8_ru_40f/llama-cpp-python_55b0b2b093ce4f10ad14fd145de112ee/_cmake_test_compile/build/CMakeFiles/CMakeScratch/TryCompile-3bKYan/testCCompiler.c
          clang: error: invalid version number in '-mmacosx-version-min=13.0'
          make[1]: *** [CMakeFiles/cmTC_72ce0.dir/testCCompiler.c.o] Error 1
          make: *** [cmTC_72ce0/fast] Error 2
      
      
      
      
      
        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (ENABLE_LANGUAGE)
      
      
      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Unix Makefiles' generator - failure
      --------------------------------------------------------------------------------
      
                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.
      
                      Building MacOSX wheels for Python 3.11 requires XCode.
      Get it here:
      
        https://developer.apple.com/xcode/
      
                      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects"

**Comment by jordanbtucker** [comment]
@451983910 It looks like you might have an unsupported version of macOS. What version do you have?

```
clang: error: invalid version number in '-mmacosx-version-min=13.0'
```

**Comment by skynet1113** [comment]
I have the same problem. Windows 11

**Comment by alevant1905** [comment]
i think he figured it out in this video: https://www.youtube.com/watch?v=7KFbG_3dKKs&t=204s

**Comment by bladeolson** [comment]
Mac OS : 

I am having this issue on my Mac as well. 

pip install llama-cpp-python 

installs ok but then when I run 

interpreter -y --local 

it says it can't find  llama-cpp-python

and then asks me to Y or N install . If I say Yes it tries and gets the Error. 

does anyone have step by step for Mac OS?

**Comment by terfani** [comment]
the same issue on macOS.

**Comment by gsahinpi** [comment]
i have the same issue on ubuntu
