### ISSUE TITLE
Not able to run --local after downloaded the model gguf.

### ISSUE THREAD

**Issue by jackfood** [KillianLucas/open-interpreter#630]
### Describe the bug

![image](https://github.com/KillianLucas/open-interpreter/assets/11504716/2fab7f26-b552-4d58-9e52-770586795968)
![image](https://github.com/KillianLucas/open-interpreter/assets/11504716/0dc5b63b-d11f-43ae-99f9-1183decc2059)

### Reproduce

1. pip install open-interpreter
2. interpreter
3. skip API
4. downloaded gguf model
5. Error.

### Expected behavior

Hope to run

### Open Interpreter version

0.1.9

### Python version

3.10

### Operating System name and version

Windows 11

**Comment by ericrallen** [comment]
Hey there, @jackfood!

Now that LM Studio is the underlying local model provider, I _think_ we can close this one.

Please reopen it if you still experience the issue in the latest version of Open Interpreter.
