### ISSUE TITLE
Architecture not yet supported for local LLM inference via `Oobabooga`

### ISSUE THREAD

**Issue by ashakiro** [KillianLucas/open-interpreter#636]
### Describe the bug

windows 11
i'm trying to run local model
interpreter --local --model /TheBloke/CodeLlama-34B-Instruct-GGUF
After model has been downloaded it stucked on:
Getting started...
Ctrl+C
setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.
How can be fixed?

### Reproduce

interpreter --local --model /TheBloke/CodeLlama-34B-Instruct-GGUF

### Expected behavior

open interpreter

### Screenshots

![b6245fe9d6ffa90b](https://github.com/KillianLucas/open-interpreter/assets/14361753/cbf5d133-1b7e-4be1-b43e-344f1d2ae7b8)

### Open Interpreter version

0.1.9

### Python version

3.11.5

### Operating System name and version

windows 11

**Comment by WonkySoft** [comment]
I hit this issue after updating today. From what I can tell Oobabooga is a webui. I don't want a UI, sigh.

**Comment by Kwalladee** [comment]
I am having the same issue starting interpreter with --local but on the default Mistral 7b for the newest commit

**Comment by sebvannistel** [comment]
exactly the same for me too

**Comment by Notnaton** [comment]
Hi, I have the same problem.

OS: Windows 10
CPU: AMD Ryzen 7 3700X 8-Core Processor
RAM: 64,0 GB
GPU: AMD Radeon RX 5700 XT

Last working Open-interpreter version for me:  0.1.3

I ran `pip install --upgrade open-interpreter`

<details>
<summary>interpreter --local</summary>

> C:\Users\NAME>interpreter --local
> 
> Open Interpreter will use Mistral 7B for local execution.
> 
> ▌ Warning: Local LLM usage is an experimental, unstable feature.
> 
> Located 'C:\Users\NAME\AppData\Local\ooba\ooba\models\mistral-7b-instruct-v0.1.Q4_0.gguf', which has already been downloaded.
> 
> Getting started...

</details>

Hitting ctrl + c because it is not doing anything

<details>
<summary>Error: </summary>

> Traceback (most recent call last):
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 45, in setup_text_llm
>     return setup_local_text_llm(interpreter)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_local_text_llm.py", line 40, in setup_local_text_llm
>     ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ooba\llm.py", line 51, in __init__
>     open_ports = get_open_ports(2000, 10000)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ooba\utils\get_open_ports.py", line 8, in get_open_ports
>     result = s.connect_ex((host, port))  # returns 0 if the connection was successful
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyboardInterrupt
> 
> 
> ▌ Failed to install huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF.
> 
> 
> We have likely not built the proper huggingface/TheBloke/Mistral-7B-Instruct-v0.1-GGUF support for your system.
> 
> 
> (Running language models locally is a difficult task! If you have insight into the best way to implement this across platforms/architectures, please join the Open Interpreter community Discord, or the Oobabooga community Discord, and
> consider contributing the development of these projects.)
> 
> Traceback (most recent call last):
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 45, in setup_text_llm
>     return setup_local_text_llm(interpreter)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_local_text_llm.py", line 40, in setup_local_text_llm
>     ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ooba\llm.py", line 51, in __init__
>     open_ports = get_open_ports(2000, 10000)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\ooba\utils\get_open_ports.py", line 8, in get_open_ports
>     result = s.connect_ex((host, port))  # returns 0 if the connection was successful
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyboardInterrupt
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 26, in cli
>     cli(self)
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 254, in cli
>     interpreter.chat()
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 88, in chat
>     for _ in self._streaming_chat(message=message, display=display):
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 102, in _streaming_chat
>     self._llm = setup_llm(self)
>                 ^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_llm.py", line 20, in setup_llm
>     text_llm = setup_text_llm(interpreter)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 56, in setup_text_llm
>     raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
> Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.
> 

</details>

**Comment by grabani** [comment]
I am getting the same error.

I am running on:
 Windows 11
i5 12th Gen
16GB RAM

![image](https://github.com/KillianLucas/open-interpreter/assets/25469154/5ac4021b-82e7-4faf-94ad-4a614512c151)

**Comment by ZackBradshaw** [comment]
I'm also seeing this error 
```
Traceback (most recent call last):
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/utils.py", line 517, in async_iteration
    return await iterator.__anext__()
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/utils.py", line 510, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/zack/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zack/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/zack/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/utils.py", line 493, in run_sync_iterator_async
    return next(iterator)
  File "/home/zack/.local/lib/python3.10/site-packages/gradio/utils.py", line 647, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/zack/code/Open-Sourcerer/jarvis.py", line 84, in bot
    for chunk in interpreter.chat(user_message, stream=True, display=False):
  File "/home/zack/.local/lib/python3.10/site-packages/interpreter/core/core.py", line 102, in _streaming_chat
    self._llm = setup_llm(self)
  File "/home/zack/.local/lib/python3.10/site-packages/interpreter/llm/setup_llm.py", line 20, in setup_llm
    text_llm = setup_text_llm(interpreter)
  File "/home/zack/.local/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 56, in setup_text_llm
    raise Exception("Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.")
Exception: Architecture not yet supported for local LLM inference via `Oobabooga`. Please run `interpreter` to connect to a cloud model.
```

**Comment by hyyh619** [comment]
I also have the same bug with windows11, python 3.11.

**Comment by RedemptionC** [comment]
using M1 Pro MacBook, had this issue

**Comment by gregoryca** [comment]
Same here ! strange thing is, i run it from a venv. On a pure Linux (22.04) install it works flawless (albeit slow because the server runs on old hardware). I created the same setup from within WSL2 (Ubuntu 22.04) and now receive the message: "**_Architecture not yet supported for local LLM inference via `Oobabooga`._**"

**Comment by Sunwood-ai-labs** [comment]
I also have the same bug with windows11, Python 3.10.12 on Docker.
![image](https://github.com/KillianLucas/open-interpreter/assets/108736814/428d8945-9f95-4a6c-ac45-e5f3635d4bdc)

**Comment by reeyarn** [comment]
Same here. I run it on Windows 10 + WSL; and again with native Ubuntu. Got the same exception.

**Comment by frsykml** [comment]
Same here, is there a solution?:(

**Comment by kigenstore** [comment]
Same issue, Windows 11 python 3.11

**Comment by chirayu-2001** [comment]
Same issue, Macbook M1 pro, python 3.11

**Comment by gerwinvis** [comment]
is there an issue with cpu vs gpu?

**Comment by Notnaton** [comment]
@ericrallen I cant request review in Ooba, I believe those pull requests will fix many of the: "Getting Started", "Server took too long" and "System not supported" issues on windows

**Comment by Usuario800** [comment]
Same error

**Comment by mweichert** [comment]
I'm seeing this too. I know that I can run the model locally with ollama, so I find this odd.

**Comment by Notnaton** [comment]
I have a fork of Ooba that fixes this:
https://github.com/Notnaton/ooba

you can install it by running:
`pip install git+https://github.com/Notnaton/ooba.git --force-reinstall`

**Comment by mweichert** [comment]
Thanks. I installed via the above command then launched open-interpreter
again but getting the same error.

**Comment by ericrallen** [comment]
I _think_ we can close this one now that LM Studio is powering Open Interpreter’s local models.

Please reopen it or ping me if I’m wrong.

**Comment by mweichert** [comment]
LM Studio isn't available on Linux, so many of us are using Ollama instead.

**Comment by ericrallen** [comment]
Ollama is great!

I think there’s also a Linux beta of LM Studio, too.
