### ISSUE TITLE
Custom Prompt in Generator

### ISSUE THREAD

**Issue by NatanAmado** [KillianLucas/open-interpreter#638]
### Describe the solution you'd like

For those using OI in their own apps, we should be able to personalize the prompt (through an argument) in the same way we can personalize the model being used. 

### Describe alternatives you've considered

Of course, we can add a custom prompt into the `interpreter.chat("Prompt")` already, but this is just added to OI's prompt + all the previous messages, creating a ball of text that dramatically affects the performance of the models.

**Comment by ericrallen** [comment]
Hey there, @NatanAmado!

I’m closing this one as this functionality already exists.

You can set  [`interpreter.system_prompt`](https://github.com/KillianLucas/open-interpreter#customize-system-message) or create a `config.yaml` with a `system_prompt` property and use the [`interpreter.extend_config()`](https://github.com/KillianLucas/open-interpreter#python-example) method.

Feel free to reopen if neither of those methods suits your needs.
