### ISSUE TITLE
chatview

### ISSUE THREAD

**Issue by AdelElo13** [KillianLucas/open-interpreter#639]
### Describe the bug

i reinstalled interpreter a few times since I started getting allot of output and not only the answer 

### Reproduce

terminal type interpreter put in key and ask it something I tried changing the gpt4 to get 3.5 but same behavior 

### Expected behavior

simple chatvieuw with only the answer provided

### Screenshots

> hi
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": ""
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "Hello"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "!"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " How"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " can"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " I"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " assist"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " you"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " today"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "?"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-89WKMtmM28zQUi9YdMnqillFVWwkD",
  "object": "chat.completion.chunk",
  "created": 1697279910,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "delta": {},
      "finish_reason": "stop"
    }
  ]
}

  Hello! How can I assist you today?

>

### Open Interpreter version

0.1.9

### Python version

3.11.5

### Operating System name and version

Mac OS 13

### Additional context

first it ruined good after a reinstall not anymore

**Comment by ridhanya-intain** [comment]
Try using older version v0.1.4

**Comment by teeaarbee** [comment]
https://github.com/KillianLucas/open-interpreter/issues/645
