### ISSUE TITLE
Failed to install open-interpreter

### ISSUE THREAD

**Issue by Alan-W-L-Z** [KillianLucas/open-interpreter#644]
### Describe the bug

Thanks for providing such a convenient project! But I'm so sorry that I received an error while simply running "pip install open-interpreter" in my cmd T_T. The screenshot is attached. Please help me solve it and I will appreciate it a lot~ thank you for your precious time!

### Reproduce

1. Go to cmd
2. run "pip install open-interpreter"

### Expected behavior

I want it to be successfully installed without this warning

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/72439385/5df79f33-6562-44ea-8208-d895816a3056)

### Open Interpreter version

WARNING: Package(s) not found: open-interpreter

### Python version

3.12.0

### Operating System name and version

Windows 11

**Comment by mingxing0769** [comment]
把代理关了

**Comment by ericrallen** [comment]
Hey there, @Alan-W-L-Z!

Part of that error message mentions not being able to connect to a proxy.

Is your connection behind a proxy? If so, are you sure `pip` is configured to use it?

Here's some info about using `pip` with a proxy: https://www.activestate.com/resources/quick-reads/pip-install-proxy/

**Comment by ericrallen** [comment]
Open Interpreter also only supports Pytbon 3.10 and 3.11 currently.

Going to close this one as stale for now.

Please reopen it if the issue still exists in the latest version of Open Interpreter or you feel like there’s more to discuss.
