### ISSUE TITLE
Streaming outputs raw JSON instead of text

### ISSUE THREAD

**Issue by teeaarbee** [KillianLucas/open-interpreter#645]
### Describe the bug

open-interpreter is printing unnecessary json data when streaming results in terminal on widows machine, resulting in too much text 

### Reproduce

Simply running it is causing it

### Expected behavior

It is supposed to output only text

### Screenshots

![image_6418](https://github.com/KillianLucas/open-interpreter/assets/65780147/4d9b1328-b08e-479b-8aee-591a84264f5e)

### Open Interpreter version

v0.1.9

### Python version

3.11.6

### Operating System name and version

Windows 11

**Comment by theposch** [comment]
same here!

**Comment by Audun97** [comment]
me too :(

**Comment by hjhjbmy** [comment]
same problem!

**Comment by Audun97** [comment]
Duplicate https://github.com/KillianLucas/open-interpreter/issues/637#issue-1941470260

Fix is

pip install --upgrade litellm

**Comment by krrishdholakia** [comment]
@ericrallen
