### ISSUE TITLE
Showing stream result

### ISSUE THREAD

**Issue by lityrdef** [KillianLucas/open-interpreter#646]
### Describe the bug

▌ Model set to GPT-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> hi
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "role": "assistant",
        "content": ""
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "Hello"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "!"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " How"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " can"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " I"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " assist"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " you"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": " today"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {
        "content": "?"
      },
      "finish_reason": null
    }
  ]
}
stream result: {
  "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
  "object": "chat.completion.chunk",
  "created": 1697477236,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "delta": {},
      "finish_reason": "stop"
    }
  ]
}

  Hello! How can I assist you today?

### Reproduce

just installed the interpreter and save the apikey on windows. 
It downloads a chatglm 79mb model. 

Then it happens. 

### Expected behavior

no stream results

### Open Interpreter version

Version: 0.1.9

### Python version

Python 3.11.6

### Operating System name and version

win 11 latest

**Comment by EsoCoding** [comment]
Same for linux fedora 38, so it probably does the same with other distro's. i'm not sure about this, but could the module openai play a part in this? I'm not sure, but i think a external module update causes it. I installed older version of interpreter and see the same response result.

``` stream result: {
    "id": "chatcmpl-8ALf2WLpXIpf10HBFQabx6oSymm0l",
    "object": "chat.completion.chunk",
    "created": 1697477236,
    "model": "gpt-4-0613",
    "choices": [
        {
             "index": 0,
             "delta": {
                  "content": " you"
             },
             "finish_reason": null
        }
    ]
} ```

**Comment by Kwalladee** [comment]
I found the solution to this.

Type in 'pip show open-interpreter' to find the location of your open-interpreter installation.

Next locate the package called "liteLLM" and open up the 'utils.py' file.

On line 427 you will see "print(f"stream result: {result}")"

That is the offending line. Simply comment it out and it will stop printing all that stream completion info.

**Comment by alita-moore** [comment]
that's a less than ideal solution :(

**Comment by EsoCoding** [comment]
I just did update the LiteLLM, then problem was solved also.

**Comment by moymoussan** [comment]
> I found the solution to this.
> 
> Type in 'pip show open-interpreter' to find the location of your open-interpreter installation.
> 
> Next locate the package called "liteLLM" and open up the 'utils.py' file.
> 
> On line 427 you will see 'print(f"stream result: {result}")'
> 
> That is the offending line. Simply comment it out and it will stop printing all that stream completion info.

It worked, thanks

**Comment by lityrdef** [comment]
> that's a less than ideal solution :(

it works. why not ideal?

**Comment by alita-moore** [comment]
Not ideal because editing source code directly means it gets wiped when you update / reinstall packages.

**Comment by KillianLucas** [comment]
An OI update is coming out today which pins the LiteLLM version (by not pinning it, some folks got a version of LiteLLM that printed everything it streamed).The best fix until then is `pip install --upgrade litellm`.After today it will simply be `pip install --upgrade open-interpreter`.On Oct 18, 2023, at 9:22 AM, Cryptohash ***@***.***> wrote:﻿
Any long term fixes for this?
