### ISSUE TITLE
can't install open-interpreter. Error for rustc!

### ISSUE THREAD

**Issue by alifhossainbits** [KillianLucas/open-interpreter#647]
### Describe the bug

I have tried to install open interpreter but I always get this error: [Click for error details](https://cdn.discordapp.com/attachments/1128589450692280490/1163185769335234570/image.png)
but then again, I try to install rustup-init.exe and I get this: [Click for  details](https://cdn.discordapp.com/attachments/1128589450692280490/1163186156645658744/image.png)

when I open rustup-init.exe it gives me this

```
"The Cargo home directory is located at:

  C:\Users\alifh\.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  C:\Users\alifh\.cargo\bin
                                                                                                                        
The Cargo home directory is located at:

  C:\Users\alifh\.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  C:\Users\alifh\.cargo\bin

This path will then be added to your PATH environment variable by
modifying the HKEY_CURRENT_USER/Environment/PATH registry key.

You can uninstall at any time with rustup self uninstall and
these changes will be reverted."
```

but if I try to find rust by manually going to C:\Users\alifh here .cargo folder doesn't exists. when I do echo $env:path it shows this path "C:\Users\alifh\.cargo\bin" but when I check user or system path from environment variables I don't see "C:\Users\alifh\.cargo\bin" this there. and no rustc --version or anything related to rust dosesn't work. including rustup self uninstall this command. So I can't even uninstall and install or reinstall it. 

### Reproduce

1. I type the command "pip install open-interpreter"
2. I get this error: [Click for error details](https://cdn.discordapp.com/attachments/1128589450692280490/1163185769335234570/image.png)
3. I try to install rust by opening rustup-init.exe but it just gives me a window directly saying where my cargo is located. but the cargo file isn't really there. I can't find it in C:\Users\alifh [Click for  details](https://cdn.discordapp.com/attachments/1128589450692280490/1163186156645658744/image.png)
4. Since I can't use rust commands in command prompt/powershell I don't know how to reinstall it since `rustup self uninstall ` command also don't get recognized. 

### Expected behavior

I expected to use rustc --version and cargo --version to work in powershell. and then proceed to smoothly install open-interpreter.

### Screenshots

https://cdn.discordapp.com/attachments/1128589450692280490/1163185769335234570/image.png
https://cdn.discordapp.com/attachments/1128589450692280490/1163186156645658744/image.png

### Open Interpreter version

probably latest! since I only input "pip install open-interpreter"

### Python version

Python 3.12.0

### Operating System name and version

Windows 11

**Comment by RexHuang** [comment]
same issue!

**Comment by Usuario800** [comment]
I had the problem that told me that Cargo was not installed, so I installed rust and the installation of open interpreter continue, what you could do is search on Google how to uninstall and reinstall rust

**Comment by alifhossainbits** [comment]
> I had the problem that told me that Cargo was not installed, so I installed rust and the installation of open interpreter continue, what you could do is search on Google how to uninstall and reinstall rust

as you can see from the post I have tried everythng I could find in the internet. I couldn't get my rustc working.. so I reinstalled my windows. but even after doing everything, installing visual studio 2022 and rustc I am still getting another error. am I just unlucky? I am so tired of it that I don't feel the energy to go on.. this is where I say goodbye. 

..
....
......
stX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
 $alifh: ~ ❯                                                                                               76% 13/17GB

**Comment by ericrallen** [comment]
> ERROR: Failed building wheel for aiohttp
> Failed to build aiohttp
> ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

This error is generally related to using an incorrect Python version.

Because aiohttp doesn’t support 3.12 yet, Open Interpreter can only support 3.10 and 3.11 currently.

**Comment by Usuario800** [comment]
> > ERROR: Failed building wheel for aiohttp
> > Failed to build aiohttp
> > ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
> 
> This error is generally related to using an incorrect Python version.
> 
> Because aiohttp doesn’t support 3.12 yet, Open Interpreter can only support 3.10 and 3.11 currently.

I have a similar problem o the same problem, don´t remember, what I did was to change python from 3.12 to 3.10 or 3.11 don´t remember the version, and I the installation continue.

**Comment by ericrallen** [comment]
Hey there, folks!

Just in case you're installing via `pipx` you might want to pass in the correct python version via the `--python` flag: https://stackoverflow.com/a/69828751/656011

Just ran into this issue on a new machine and thought it might help.

I'm going to close this one as stale for now, but please reopen it if you're still experiencing the issue after using the proper Python version, too.

**Comment by vogler** [comment]
`pipx install` failed due to missing rustc, but `poetry install` worked fine since it's installing a newer tiktoken which comes with wheels (see [comment](https://github.com/openai/tiktoken/issues/205#issuecomment-1837414989)).
Why is the version constraint for pip `tiktoken<0.5.0,>=0.4.0` when `pyproject.toml` says `tiktoken = "^0.5.2"`?
Shouldn't the constraints on https://libraries.io/pypi/open-interpreter ideally match the ones used for poetry (or at least not disallow the newer version)?
(I don't know much about the chaos that is python tooling, maybe that is still an unsolved problem 🙈)

```
❯ pipx install open-interpreter
Fatal error from pip prevented installation. Full pip output in file:
    /Users/voglerr/Library/Logs/pipx/cmd_2024-01-16_23.20.36_pip_errors.log

pip failed to build package:
    tiktoken

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: can't find Rust compiler

Error installing open-interpreter.

❯ cat /Users/voglerr/Library/Logs/pipx/cmd_2024-01-16_23.20.36_pip_errors.log | grep tiktoken
Collecting tiktoken<0.5.0,>=0.4.0 (from open-interpreter)
  Using cached tiktoken-0.4.0.tar.gz (25 kB)
Collecting regex>=2022.1.18 (from tiktoken<0.5.0,>=0.4.0->open-interpreter)
Building wheels for collected packages: tiktoken
  Building wheel for tiktoken (pyproject.toml): started
  Building wheel for tiktoken (pyproject.toml): finished with status 'error'
Failed to build tiktoken
  × Building wheel for tiktoken (pyproject.toml) did not run successfully.
      creating build/lib.macosx-14-arm64-cpython-312/tiktoken
      copying tiktoken/registry.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken
      copying tiktoken/__init__.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken
      copying tiktoken/core.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken
      copying tiktoken/model.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken
      copying tiktoken/load.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken
      creating build/lib.macosx-14-arm64-cpython-312/tiktoken_ext
      copying tiktoken_ext/openai_public.py -> build/lib.macosx-14-arm64-cpython-312/tiktoken_ext
      writing tiktoken.egg-info/PKG-INFO
      writing dependency_links to tiktoken.egg-info/dependency_links.txt
      writing requirements to tiktoken.egg-info/requires.txt
      writing top-level names to tiktoken.egg-info/top_level.txt
      reading manifest file 'tiktoken.egg-info/SOURCES.txt'
      writing manifest file 'tiktoken.egg-info/SOURCES.txt'
      copying tiktoken/py.typed -> build/lib.macosx-14-arm64-cpython-312/tiktoken
  ERROR: Failed building wheel for tiktoken
ERROR: Could not build wheels for tiktoken, which is required to install pyproject.toml-based projects
```
