### ISSUE TITLE
Model selection problem when upgrade from 0.1.17 to 0.1.19

### ISSUE THREAD

**Issue by dwang48** [KillianLucas/open-interpreter#649]
### Describe the bug

I upgraded to 0.1.19 today and the default model is mistral 7b. I tried to switch to the old llama 34b medium size (Q4_K_M) I was using by using --model "TheBloke/CodeLlama-34B-Instruct-GGUF" but cannot find the right model. It seems that I have to download another model again. 

### Reproduce

interpreter --local --model "TheBloke/CodeLlama-34B-Instruct-GGUF"
This gives me extra small, small and other three options but all of them are the same Q4_0 model file

### Expected behavior

Anyway to set model path directly?

### Open Interpreter version

0.1.19

### Python version

3.11.3

### Operating System name and version

macOS 14

**Comment by hvacking** [comment]
what's your mac type? M1, M2?

**Comment by dwang48** [comment]
> what's your mac type? M1, M2?

M1 max.

**Comment by hvacking** [comment]
M1 max can run local 34b model?

**Comment by dwang48** [comment]
> hvacking

Yes. With 34b Q4 model, it will take about 20GB RAM. My laptop has 32 GB and the inference speed is about 18 tokens/sec

**Comment by hvacking** [comment]
▌ Warning: Local LLM usage is an experimental, unstable feature.                                                                                     

Located '/Users/liulan/.ooba/models/mistral-7b-instruct-v0.1.Q4_0.gguf', which has already been downloaded.

Getting started...
Server took too long to start
Traceback (most recent call last):
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm
    return setup_local_text_llm(interpreter)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm
    ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode)
  File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/ooba/llm.py", line 105, in __init__
    raise Exception("Server took too long to start")
Exception: Server took too long to start .My M1 can't load the model ,and always show 'Server took too long to start' . So i wonder if M1 can run the Mistral.

**Comment by dwang48** [comment]
> ▌ Warning: Local LLM usage is an experimental, unstable feature.
> 
> Located '/Users/liulan/.ooba/models/mistral-7b-instruct-v0.1.Q4_0.gguf', which has already been downloaded.
> 
> Getting started... Server took too long to start Traceback (most recent call last): File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_text_llm.py", line 45, in setup_text_llm return setup_local_text_llm(interpreter) File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/interpreter/llm/setup_local_text_llm.py", line 40, in setup_local_text_llm ooba_llm = ooba.llm(path, verbose=interpreter.debug_mode) File "/Users/liulan/opt/anaconda3/envs/oi/lib/python3.10/site-packages/ooba/llm.py", line 105, in **init** raise Exception("Server took too long to start") Exception: Server took too long to start .My M1 can't load the model ,and always show 'Server took too long to start' . So i wonder if M1 can run the Mistral.

You can definitely run mistral-7b gguf q4 as long as your ram is above like 5GB, which I believe almost all macbook satisfy this requirement. Try run the most simple case: from langchain.llms import LlamaCpp llm = LlamaCpp(
    # model_path="models/codellama-34b-instruct.Q4_K_M.gguf",
    model_path="models/mistral-7b-instruct-v0.1.Q5_K_M.gguf",
    n_ctx=5000,
    n_gpu_layers=1,
    n_batch=512,
    max_tokens=4096,
    f16_kv=True,
    callback_manager=callback_manager,
    verbose=False,
)template = """<s>[INST] {prompt} [/INST]"""

class Question(BaseModel):
    text: str

def get_response_from_bot(question: str):
    formatted_prompt = template.format(prompt=question)
    os.system('clear')
    response = llm(formatted_prompt)
    return response

@app.post("/chat")
async def chat_endpoint(question: Question):
    response = get_response_from_bot(question.text)
    return {"answer": response} 
This is how I run it using fastapi and langchain. You can try modify this code to use it in your terminal. The server issue could be network issue

**Comment by hvacking** [comment]
yes, it works when i run ' ollama run mistral' in terminal, the mistral works. But when i run ' interpreter --local' in terminal, it shows 'raise Exception("Server took too long to start")' error.

**Comment by bmwhite1611** [comment]
I don't know how to do this on my Windows. I noticed the option for Llama wasn't available with the new upgrade, but I wanted the 30B Llama and I can't find a way to get it and no support. Plus, it won't even run Minstral-7B

**Comment by ericrallen** [comment]
Hey there, folks!

Now that local model support is powered LM Studio, I _think_ we can close this one.

Feel free to reopen it if I’m wrong.
