### ISSUE TITLE
interpreter stuck on data load or task execution

### ISSUE THREAD

**Issue by ilvolodel** [KillianLucas/open-interpreter#652]
### Describe the bug

Most of the times I try to perform an action, the interpreter freezes and doesn't return any error. This happens both when analyzing a dataset and when installing a package. I have no way of understanding the error.
<img width="1597" alt="Screenshot 2023-10-17 alle 19 41 34" src="https://github.com/KillianLucas/open-interpreter/assets/7567219/279af870-cd46-4618-b378-79181b3fe082">

### Reproduce

Ask interpreter to analyze excel file.
Wait for response

### Expected behavior

the task was completed

### Open Interpreter version

Open Interpreter 0.1.9

### Python version

Python 3.11.6

### Operating System name and version

MacOS SONOMA  14.0

**Comment by Astlvk** [comment]
I've encountered the same issue as well. I am running on win11. I suspect that it might have been terminated during program execution due to an infinite loop or an unhandled error code.

**Comment by Donovoi** [comment]
same here even ctrl+c doesnt help

**Comment by ericrallen** [comment]
Hey there, folks!

Could anyone confirm if this issue still exists in the most recent version of Open Interpreter?

We shipped some fixes to an underlying token management library that I _think_ might have helped with this issue.

**Comment by ilvolodel** [comment]
Last night I tried for about half an hour using the GPT-4 Turbo model and did not encounter any problems, it seems to work well. Today I will try more, in the meantime thanks and great job, I would say!

**Comment by ericrallen** [comment]
Awesome!

I’m going to close this one for now, but please reopen it or ping me if you still experience the issue.
