### ISSUE TITLE
not running Python scripts

### ISSUE THREAD

**Issue by marciovictoria** [KillianLucas/open-interpreter#656]
### Describe the bug

A bug happened! When try to run any python script

### Reproduce

when ask anything is given error

### Expected behavior

not error on interpreter

### Screenshots

Traceback (most recent call last):
    File
  "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreters\subprocess_c
  ode_interpreter.py", line 65, in run
      self.start_process()
    File
  "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreters\subprocess_c
  ode_interpreter.py", line 43, in start_process
      self.process = subprocess.Popen(self.start_cmd.split(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified

### Open Interpreter version

0.1.5

### Python version

3.10

### Operating System name and version

windows 11

**Comment by pmiddlet72** [comment]
I don't know exactly what you're doing to get this error, but you might check issue #635, which has a fix to a class for open interpreter.  Give that a try and see if it works. I'm assuming since there was a PR for this issue that it will be integrated into a future release of OI.

**Comment by marciovictoria** [comment]
The new version, released today, has correct the error.
