### ISSUE TITLE
Using model gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by habbler** [KillianLucas/open-interpreter#662]
### Describe the bug

Has anyone had any luck using model gpt-3.5-turbo-instruct?

I have not yet figured out why it doesn't work.

### Reproduce

interpreter --model gpt-3.5-turbo-instruct

> What is sum 1..10 ?

We were unable to determine the context window of this model. Defaulting to 3000.                                                                                      
If your model can handle more, run interpreter --context_window {token limit} or interpreter.context_window = {token limit}.                                           
Also, please set max_tokens: interpreter --max_tokens {max tokens per response} or interpreter.max_tokens = {max tokens per response} 

I find this strange since the context length is defined for model gpt-3.5-turbo-instruct .

### Expected behavior

Works the same as gpt-3.5-turbo

### Open Interpreter version

1.10

### Python version

3.10

### Operating System name and version

Ubuntu

**Comment by ericrallen** [comment]
Hey there, @habbler!

The context length is defined in the world, but the token trimming package that Open Interpreter uses did not have that information for the `gpt-3.5-turbo-instruct` model.

I've submitted a Pull Request to add some more models and hopefully help reduce the prevalence of this warning message for this use case and many others.

**Comment by ericrallen** [comment]
I'm going to close this one as I think it has been shipped and should be working.

Please reopen this issue if you experience issues with the this model and the latest version of Open Interpreter.
