### ISSUE TITLE
The official open-interpreter Discord server has a problem..

### ISSUE THREAD

**Issue by TomExMachina** [KillianLucas/open-interpreter#663]
### Is your feature request related to a problem? Please describe.

It doesn't exist.

### Describe the solution you'd like

Discord

### Describe alternatives you've considered

Discord

### Additional context

BetterDiscord

**Comment by chirayu-2001** [comment]
Can someone give the current active link of discord community?

**Comment by ericrallen** [comment]
The [Discord](https://discord.gg/6p3fD6rBVm) is linked in the Contributing Guide.
