### ISSUE TITLE
MacOS & conda env did not run interpreter.

### ISSUE THREAD

**Issue by yoyoyo-yo** [KillianLucas/open-interpreter#669]
### Describe the bug

I tried following environment

- Mac OS  v14.0 Sonoma
- conda environment : python=3.11    (created by 'conda create python=3.11')

```bash
$ pip install open-interpreter
```
could be done.

When I tried 'interpreter' command on terminal, following error occured.

```bash
...
  File "/Users/xxx/miniconda3/lib/python3.9/site-packages/ooba/llm.py", line 195
    match incoming_data['event']:
          ^
SyntaxError: invalid syntax
```

How do I fix this?

### Reproduce

1. conda create python=3.11 -n py311
2. conda activate py311
3. pip install open-interpreter

### Expected behavior

Starting interpreter

### Open Interpreter version

0.1.10

### Python version

3.11.5

### Operating System name and version

 Mac OS  v14.0 Sonoma

**Comment by ericrallen** [comment]
Hey there, @yoyoyo-yo!

The path in that error message indicates you are running Python 3.9, which is not currently a supported Python version for Open Interpreter.

Please upgrade to 3.10 or 3.11 (support for 3.12 is coming soon, just waiting on some dependencies to support it first).

I’m going to close this one, but please reopen it if you upgrade your Python version and still experience the issue.
