### ISSUE TITLE
Infrastructure intelligence 

### ISSUE THREAD

**Issue by ngoiyaeric** [KillianLucas/open-interpreter#670]
### Is your feature request related to a problem? Please describe.

<img width="569" alt="Screen Shot 2023-10-21 at 10 43 45 AM" src="https://github.com/KillianLucas/open-interpreter/assets/115367894/c1b53e8d-07b3-4637-9d57-1cb5e514ea6e">

### Describe the solution you'd like

I'd like for open interpreter to keep track of its intelligence resource and even be able to replenish its credits from within open interpreter itself. 
Perhaps interface methods generic to language models for resource maintenance.

### Additional context

Generalize to multiple language models.

**Comment by ericrallen** [comment]
I don’t believe OpenAI provides an API for this kind of thing.

You could probably ask Open Interpreter to create a Puppeteer of Playwright script that does this for you.

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now, but feel free to reopen it if there’s more to discuss.

**Comment by ngoiyaeric** [comment]
@ericrallen I've found this solution, https://labs.perplexity.ai. 
if we can connect their API's to open interpreter we can move closer towards having an intelligence infrastructure for the terminal intelligence.

**Comment by ngoiyaeric** [comment]
This would help with model variety, its also highly optimized inference with real time information.
