### ISSUE TITLE
Please add integration with Poe API

### ISSUE THREAD

**Issue by legaltextai** [KillianLucas/open-interpreter#671]
### Is your feature request related to a problem? Please describe.

https://developer.poe.com/ 

### Describe the solution you'd like

A good way to minimize costs

**Comment by krrishdholakia** [comment]
Hey @legaltextai  tracking this here - https://github.com/BerriAI/litellm/issues/113

**Comment by ericrallen** [comment]
Going to close this one as it looks like it will be handled at the LiteLLM later.
