### ISSUE TITLE
Repetitive/monotonous tasks automation

### ISSUE THREAD

**Issue by vasnt** [KillianLucas/open-interpreter#672]
### Is your feature request related to a problem? Please describe.

Many times, without consciousness, users do Repetitive/monotonous tasks

### Describe the solution you'd like

Without prompting by users, it would be great if tool observes users' behaviour/pattern/actions & automatically creates code/script/rules.
e.g. if user does A followed by B followed by C followed by D regularly. Then tool will create a rule/script to do D directly by omitting/automating A,B&C steps.

### Additional context

https://github.com/InfrHQ/server/issues/2

**Comment by ericrallen** [comment]
Hey there, @vasnt!

This is definitely an interesting idea, but I don’t think Open Interpreter is in a place to put this on the roadmap at the moment.

You could try to build this functionality into a Python application built on top of Open Interpreter, though.

I’m going to close this one for now, but feel encouraged to discuss this idea or any attempts you make at implementing it with the community in [Discord](https://discord.gg/6p3fD6rBVm).
