### ISSUE TITLE
Not work on termux. chroma-hnswlib

### ISSUE THREAD

**Issue by bropines** [KillianLucas/open-interpreter#673]
### Describe the bug

During installation on termux cannot build the library

### Reproduce

1. Open termux
2. `pip install open-interpreter`
3. Error. read more in this question
4. https://github.com/sm18lr88/Open-Interpreter-Termux/issues/2#issue-1951383882

### Expected behavior

Successful install

### Screenshots

![Screenshot_2023-10-22-06-33-19-427_com termux](https://github.com/KillianLucas/open-interpreter/assets/57861007/02e24379-82d7-48f3-b24e-3f42f44035b6)

### Open Interpreter version

0.1.9

### Python version

3.11.6

### Operating System name and version

Android 13, MIUI 14, Termux-monet 0.118

**Comment by ericrallen** [comment]
Hey there, @bropines!

I’m not familiar with termux, but have you taken a look at #77?

**Comment by bropines** [comment]
> Hey there, @bropines!
> 
> I’m not familiar with termux, but have you taken a look at #77?

Yes. This can be solved by installing rust. We have the chroma-hnswlib library and it does not compile for some reason.

**Comment by ericrallen** [comment]
I'm going to close this one as ChromaDB has been removed from the project, so this error shouldn't happen anymore.

Please reopen the issue if you still experience it with the latest version of Open Interpreter.

**Comment by nickfixit** [comment]
> ### Describe the bug
> 
> During installation on termux cannot build the library
> 
> ### Reproduce
> 
> 1. Open termux
> 2. `pip install open-interpreter`
> 3. Error. read more in this question
> 4. https://github.com/sm18lr88/Open-Interpreter-Termux/issues/2#issue-1951383882
> 
> ### Expected behavior
> 
> Successful install
> 
> ### Screenshots
> 
> ![Screenshot_2023-10-22-06-33-19-427_com termux](https://github.com/KillianLucas/open-interpreter/assets/57861007/02e24379-82d7-48f3-b24e-3f42f44035b6)
> 
> 
> ### Open Interpreter version
> 
> 0.1.9
> 
> ### Python version
> 
> 3.11.6
> 
> ### Operating System name and version
> 
> Android 13, MIUI 14, Termux-monet 0.118 
> 
> ### Additional context
> 
> _No response_

Happening to me now.

**Comment by MikeBirdTech** [comment]
@nickfixit have you followed the instructions on this repo: https://github.com/MikeBirdTech/open-interpreter-termux

If you still have issues, please open a ticket there with a detailed explanation of the issue. Thanks!
