### ISSUE TITLE
openai.error.RateLimiterror

### ISSUE THREAD

**Issue by buiaka99** [KillianLucas/open-interpreter#679]
### Describe the bug

when i input command : "xxxxx" ,is call back this:
File "C:\Users\XY\AppData\Roaming\Python\Python311\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

### Reproduce

....

### Expected behavior

help.please!

### Open Interpreter version

0.1.1

### Python version

3.11.5

### Operating System name and version

window11

**Comment by ericrallen** [comment]
Are you actually running the `0.1.1` version of Open Interpreter or is that a typo?

Have you confirmed that you aren’t exceeding your [account’s rate limits](https://platform.openai.com/account/rate-limits)?

If you’re using a `gpt-4` model, have you confirmed that you have access to it and haven’t exceeded any quotas?

**Comment by ericrallen** [comment]
I’m going to close this one for now, but please feel encouraged to continue discussion about rate limit issues in #408
