### ISSUE TITLE
could not find a version that satisfies the requirment open-interpreter(from version:)

### ISSUE THREAD

**Issue by lzesyr** [KillianLucas/open-interpreter#684]
### Describe the bug

I use 'pip install open-interpreter' but it does not work, and show the error like title

### Reproduce

pip install open-interpreter

### Expected behavior

I hope i can install it

### Open Interpreter version

0.1.1

### Python version

3.6.5

### Operating System name and version

Windows11

**Comment by Notnaton** [comment]
Upgrade python to 3.10 or 3.11

**Comment by ericrallen** [comment]
I’ve added this to the Common Issues thread: https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1777305850

I’m going to close this one, but please reopen it if upgrading your Python version doesn’t resolve the issue.
