### ISSUE TITLE
raise error.APIConnectionError

### ISSUE THREAD

**Issue by lzesyr** [KillianLucas/open-interpreter#685]
### Describe the bug

when i input “interpreter -y”， it show “ raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247EAA78B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))”    

How can i solve this proble，thanks！

### Reproduce

when i input “interpreter -y”， it show “ raise error.APIConnectionError(openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247EAA78B80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))”    

### Expected behavior

start to use-

### Open Interpreter version

0.1.10

### Python version

3.10.0

### Operating System name and version

Windows11

**Comment by ericrallen** [comment]
That error message looks like you're trying to use an `api_base` of `localhost:1234`, which means this is possibly an issue with the proxy you're running.

Can you confirm that you can send a `curl` request to `http://localhost:1234/v1/chat/completions`?

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

Please reopen it if there is more to discuss or the issue still exists with the latest version.
