### ISSUE TITLE
sqlite3 version problem for chroma

### ISSUE THREAD

**Issue by shawnmittal** [KillianLucas/open-interpreter#686]
### Describe the bug

When trying to run the `interpreter` command from the terminal, the following error message pops up:
`Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0`.

There isn't a solution listed for any OS other than Mac OS in the "common problems" issue #164.

Here's the fix for Ubuntu 20.04:
1. `wget https://sqlite.org/2023/sqlite-autoconf-3430200.tar.gz`
2. `tar -xvf sqlite-autoconf-3430200.tar.gz`
3. `cd sqlite-autoconf-3430200`
4. `sudo apt-get install libreadline-dev`
5. `./configure`
6. `make`
7. `sudo apt-get purge sqlite3`
8. `sudo make install`
9. Add the following to your ~/.bashrc `export PATH="/usr/local/bin:$PATH"`
10. `source ~/.bashrc`
11. `sqlite3 --version` to verify the version

### Reproduce

1. `pip install open-interpreter`
2. run `interpreter` command

### Expected behavior

The interpreter command should launch a session

### Open Interpreter version

0.1.10

### Python version

3.10.1

### Operating System name and version

WSL 2 (Ubuntu 20.04.6 LTS)

**Comment by ericrallen** [comment]
Thanks for this solution for Ubuntu, @shawnmittal!

Would you mind adding it as a comment to the thread in #164?

There are a ton of Issues to triage and we'd love to start compiling solutions in that thread and cleaning up as many Issues as possible.

**Comment by shawnmittal** [comment]
Thread is locked currently.

**Comment by ericrallen** [comment]
Sorry about that, @shawnmittal.

I didn't realize that it was locked.

Do you mind if I move it there, tag you, and close this issue?

**Comment by shawnmittal** [comment]
@ericrallen fine by me!

**Comment by ericrallen** [comment]
Thanks for your help, @shawnmittal!

Moved to #164: [Direct Link to Comment](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1777613353)

**Comment by shawnmittal** [comment]
@ericrallen forgot to add a step after step 9 to make it work:
Add the following to your .bashrc `export LD_LIBRARY_PATH="/usr/local/lib"`

Apologies. I've tested the above and things are functioning as expected.

**Comment by ericrallen** [comment]
Thanks!

I updated the [comment](https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1777613353).
