### ISSUE TITLE
Getting stuck at "Setting up the language model..." / Windows / local model

### ISSUE THREAD

**Issue by Tom1827** [KillianLucas/open-interpreter#688]
### Describe the bug

On Windows, trying to get a local model to start, I'm getting stuck every time at the _"Setting up the language model..."_ stage.

I've tried several times, by removing open-interpreter, ooba, and the ooba folder in C:\Users\<user>\AppData\Local\ooba and then reinstalling and redownloading Mistral 7B.  It has got stuck each time at a different amount of progress.  The attempt shown in the screenshot has now been running for about two hours.

### Reproduce

- Install per the instructions
- Run interpreter (i.e. for the first time)
- Press enter to use local model
- Wait for the model to download

...then it grinds to a halt at some point as it is setting up the language model

### Expected behavior

To not get stuck, and finish setting up the language model? :)

### Screenshots

![Screenshot 2023-10-25 001421](https://github.com/KillianLucas/open-interpreter/assets/30773934/6bb61872-2941-4d6d-9ac9-7801827b4393)

### Open Interpreter version

0.1.10

### Python version

3.10.2

### Operating System name and version

Windows 11 Pro

### Additional context

Ryzen 7 5800X, 32GB RAM, NVidia 3060Ti 8GB

**Comment by bmwhite1611** [comment]
Yeah I waited like half a day and then closed the window. Now I run interpreter --local and it just says "Getting Started..." forever. I wish I could have gone back to Llama, but they turned it off for some reason, or else I just can't figure out how to go back to a larger model like that... should never have uninstalled it...

**Comment by sebvannistel** [comment]
yea same issue here. they still have not fixed it. been waiting for over 2 weeks for a fix #636

**Comment by thisdp** [comment]
It scans port from 2000 to 10000 at the speed of 1 port pre second, we need at least 8000 secs. And under llm.py, class llm, __init__ function, there are at least 3 scans....

**Comment by thisdp** [comment]
And even there's a bug in path management.
llm.py line 45, under windows, there should be "\\" not "/"

**Comment by Notnaton** [comment]
Hi, while the PRs are being merged, you can try my fork that fixes Ooba for windows: 
https://github.com/Notnaton/ooba
`pip install git+https://github.com/Notnaton/ooba.git@windows --force-reinstall`

**Comment by ericrallen** [comment]
Hey there, folks!

Now that LM Studio is the underlying local model provider, I _think_ we can close this one.

Please reopen it if you still experience the issue in the latest version of Open Interpreter.
