### ISSUE TITLE
使用GPT3.5模型无响应

### ISSUE THREAD

**Issue by wangqiao2019** [KillianLucas/open-interpreter#689]
### Describe the bug

当使用GPT3.5模型时，可以正常聊天，也可以就提出的问题给出解决问题的代码。但是当我要求它执行代码的时候就没有响应了。换成GPT4模型的时候就没有问题。其他的系统环境都一样仅仅是模型的不同就有这样的问题。

### Reproduce

出现“请确认是否希望继续执行以上代码”类似的提示，回答yes或者继续执行就没有然后了。

### Expected behavior

希望能像使用GPT4一样继续执行

### Open Interpreter version

0.1.10

### Python version

3.11.4

### Operating System name and version

windows11

**Comment by ericrallen** [comment]
Hey there, @wangqiao2019!

We've seen some other reports of `gpt-3.5-turbo` not responding or not executing code recently.

We're digging into it to try to understand if it's model-related or something in the codebase.

**Comment by wangqiao2019** [comment]
> Hey there, @wangqiao2019! 嘿， ！
> 
> We've seen some other reports of `gpt-3.5-turbo` not responding or not executing code recently.我们最近看到了一些关于 `gpt-3.5-turbo` 没有响应或没有执行代码的其他报告。
> 
> We're digging into it to try to understand if it's model-related or something in the codebase.我们正在深入研究它，试图了解它是否与模型相关或代码库中的某些内容。

Alright, I hope to resolve this issue as soon as possible, after all, 4.0 is too expensive.

**Comment by ericrallen** [comment]
I’m going to close this one in favor of #723 because it’s easier to search for that one, but please feel encouraged to continue the discussion in that thread.
