### ISSUE TITLE
Elevated token usage and Inaccuracy in Token Estimation with `%tokens` Command

### ISSUE THREAD

**Issue by moymoussan** [KillianLucas/open-interpreter#692]
#### Problem Description
I've noticed that the magic command `%tokens` appears to not provide an accurate estimate of the total tokens used in a complete conversation. According to the documentation, this command calculates the tokens used by the current conversation's messages to estimates their cost. However, it seems not to account for the tokens used to include all previous message history as context in each new message.

#### Questions
1. Is the `%tokens` command designed to include tokens from conversation history **of each message** in its calculation?
2. If not, are there plans to update this command to provide a more accurate estimate?
3. Is there any other recommended way to accurately estimate the total token usage in a conversation?

#### Implications
- Underestimation of the cost of API calls.
- Possibility of unexpectedly hitting rate limits.
- Challenges in efficiently managing resources.

#### Potential Solutions
1. Update the `%tokens` command to include tokens from conversation history.
2. Implement a warning system for users when they are nearing the token limit.
3. Clearly specify in the documentation that the `%tokens` command does not count tokens from conversation history (context) that was sent within each new message.

### Steps to Reproduce

1. Open the Open Interpreter terminal application.
2. Start a new conversation with a series of messages.
3. Use the `%tokens` command to estimate the token usage for the current conversation.
4. Observe the token count and cost estimation provided by the `%tokens` command.
5. Compare this with the actual token count and cost as seen in the OpenAI Dashboard or other monitoring tools.

The `%tokens` command seems to only account for the tokens used in the current conversation's messages and does not include tokens from the **conversation history sent as context with every message**, leading to an inaccurate estimate.

### Expected Behavior

The `%tokens` command should provide an accurate and comprehensive estimate of the total tokens consumed in an ongoing conversation. This estimate should account for:

1. Tokens used in the current message input.
2. Tokens used for the output generated by the OpenAI API.
3. Tokens consumed by including the entire conversation considering **history included as context for each new message** to maintain conversational state.

The command should ideally also provide a breakdown of these components for better transparency, allowing users to understand how the total token count is derived. This would aid in more effective token management and cost estimation.

### Screenshots

![IMG_2112](https://github.com/KillianLucas/open-interpreter/assets/66051741/0c603eca-ed11-4944-bca8-4f52e69eb79f)

### Open Interpreter version

0.1.10 and 0.1.9

### Python version

3.10 and 3.11

### Operating System name and version

macOS 14

### Additional Context

This issue is not based solely on personal observations but has also been discussed within the community. Multiple users have reported similar experiences, indicating that this is a broader concern that affects the overall usability of this great project.

**Comment by ericrallen** [comment]
Hey there, @moymoussan!

Thanks for the in-depth feedback.

I’ll get the language clarified and then we can start working on an aggregate calculator.

**Comment by ericrallen** [comment]
@moymoussan can you take a look at #694?

I tried to clarify what `%tokens` currently represents to alleviate confusion until we decide on the best approach for the aggregate token calculation.

**Comment by moymoussan** [comment]
Ok @ericrallen thanks for the agile response!

**Comment by ericrallen** [comment]
It's also worth noting that there is some [complexity around understanding how OpenAI tokenizes some things like functions](https://github.com/KillianLucas/tokentrim/issues/8) and how some of our input/ouput ends up getting included in the conversation, so `%tokens` should probably be considered experimental at the moment.

I'll update the language to make that more clear, too.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
