### ISSUE TITLE
code docs :)

### ISSUE THREAD

**Issue by scafati98** [KillianLucas/open-interpreter#693]
### Describe the solution you'd like

Hey! Hoping this finds you well
We are generating a product to automate the generation of docs. We want to contribute to the community, this is the first iteration of the product and would love to receive feedback as to what could be enhanced to make them valuable for the community.

I’ve generated this [docs](https://demo.autonoma.app/docs/0f45eccd-813d-467c-b982-f6178fa1f5c5/3a62b0e5-ca08-410b-9bb7-79bc107db1c7) for the open interpreter repo. 

They are generated with AI so it will always be up to date and a Changelog is fed with changes.

**Motivation**
contribute to the community!

We recently made a post in our LinkedIn page about this great repo [here](https://www.linkedin.com/posts/autonoma-ai_100daycodedocschallenge-day7-openai-activity-7122645065306390528-wizc) :)

**Comment by ericrallen** [comment]
Hey there!

Just taking a very brief look at the link you provided, it seems like there are pages that are totally irrelevant to the Open Interpreter project (like creating a router and controller, communicating with the database, creating a Pytest test, etc.), and the `Introduction` is unrelated to Open Interpreter and very verbose.

Pages like [this one](https://autonoma.app/docs/0f45eccd-813d-467c-b982-f6178fa1f5c5/dc83ea0b-71e6-4af1-902d-65a1abb40a52) also seem to create more confusion than they would resolve.

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now, but feel free to reopen it if you’d like to discuss this further.

**Comment by scafati98** [comment]
Great Eric! Thanks for the feedback, we will be working on improving the quality of docs. I'll let you know when V2 is out!

Thanks again for your comments!!!
