### ISSUE TITLE
interpreter: error: unrecognized arguments: --use -azure

### ISSUE THREAD

**Issue by HsinhungLin** [KillianLucas/open-interpreter#698]
### Describe the bug

Run interpreter --use -azure in Windows CLI
The response shows interpreter: error: unrecognized arguments: --use -azure
as screenshot

### Reproduce

1. Run interpreter --use -azure in Windows CLI
2. show error "interpreter: error: unrecognized arguments: --use -azure"

### Expected behavior

can use openai model deployed on azure

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/8468977/14dec616-fc1c-4e32-a26a-171dd26a0f9c)

### Open Interpreter version

0.1.10

### Python version

3.11.5

### Operating System name and version

Windows 10

**Comment by ericrallen** [comment]
I believe it's `--use-azure` without the space between `--use` and `-azure`.

**Comment by HsinhungLin** [comment]
Have tried both ways, the results are the same...
![image](https://github.com/KillianLucas/open-interpreter/assets/8468977/20d31602-5329-4d80-8b02-71ad3909d74d)

**Comment by ericrallen** [comment]
I forgot that with the LiteLLM integration there is a new way to use Azure models:

https://docs.openinterpreter.com/language-model-setup/hosted-models/azure

I believe `--use-azure` is the older, deprecated approach.

**Comment by HsinhungLin** [comment]
@ericrallen  Thanks a lot! 
It seems that interpreter can connect to Azure openai model, however, it appears openai error.
Since it's not the issue of open-interpreter, I'll close this issue.
