### ISSUE TITLE
problem when installing

### ISSUE THREAD

**Issue by dcityteg** [KillianLucas/open-interpreter#700]
### Describe the bug

![image](https://github.com/KillianLucas/open-interpreter/assets/132677224/ae8d46cc-4f75-409c-8479-e68122afaecf)
this is a photo of the problem.i run pip install open-interpreter to install.but after i run this code,it shows that.

### Reproduce

-

### Expected behavior

-

### Open Interpreter version

-

### Python version

-

### Operating System name and version

Windows11

**Comment by kelamg** [comment]
You just need to install [Rust ](https://www.rust-lang.org/tools/install) and try again

**Comment by KillianLucas** [comment]
Hey @dcityteg, we recently took out a bunch of packages. Can you try installing again and let us know if it still asks for Rust?

**Comment by alexmunteanu** [comment]
Hi, @KillianLucas! I can confirm it still asks for Rust.

**Comment by ericrallen** [comment]
Hey there, folks!

[`tiktoken`](https://github.com/openai/tiktoken) the OpenAI library for tokenization that our underlying [`tokentrim`](https://github.com/killianlucas/tokentrim) library uses to keep content within the context window requires Rust.

You can install the rust toolchain following the docs:

https://www.rust-lang.org/tools/install

Going to close this one for now, but if you have Rust and still experience this issue, please reopen it so we can dig into it.
