### ISSUE TITLE
Unexpected Open AI RateLimitError

### ISSUE THREAD

**Issue by xinranli0809** [KillianLucas/open-interpreter#706]
### Describe the bug

Hi!

I see a few similar issues have already been posted here before but I believe mine is a bit more strange. I am getting: 
```
openai.error.RateLimitError: Rate limit reached for gpt-4 in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at
help.openai.com if you continue to have issues.
``` 

I am using the python library to automate some data generation task using GPT 4 API. I have relatively lengthy instruction prompt, around 800 tokens based on OpenAI's tokenizer, this is the function I use to find token number of some string:
```python
def num_tokens_from_string(string: str, encoding_name: str) -> int:
    """Returns the number of tokens in a text string."""
    encoding = tiktoken.encoding_for_model(encoding_name)
    num_tokens = len(encoding.encode(string))
    return num_tokens
    
    print(num_tokens_from_string("hello world!","gpt-4"))
``` 

I send around 500~1000 tokens of text data into with every `interpreter.chat(),` I thought I might be inputting too many things too quickly.  So I have written some function that counts the total number of tokens in `interpreter.messages` and give me the total number of tokens that I input and got from API in the last 60 seconds. Before each time I send my next input with  `interpreter.chat()`, this check makes sure total tokens in the past 60 seconds does not exceed 9000. If it does exceed, I just `time.sleep` until it is lower that the threshold. But I keep getting this error, I have set the threshold to 3000 and I am still getting it!

Even more strangely, the time when the error occurs is not when I input a bunch of data (which I suspected was where the issue was), but when API is streaming the response tokens a long time after I sent my last input tokens. Considering how slow the tokens streams (maybe a few t/s? just eyeballing), there is no chance the average total token/minute is going beyond 10000 per minute.

So my question is, does anyone know how Open AI is actually calculating this token/minute thing? Also, am I missing something when calculating the number of tokens I send to the API? I feel like `interpreter.messages` already contains most of the chat history. I know it does not include the `system_message` in `config.yaml`, which is about 460 tokens. Are there anything else not included in `interpreter.messages`, but are actually sent to the API? 

Thanks!!!

### Reproduce

1. Send large but not too large amount of input prompt and wait for response.

### Expected behavior

Does not trigger the limit.

### Open Interpreter version

0.1.10

### Python version

3.11.6

### Operating System name and version

Windows 10

**Comment by ericrallen** [comment]
Hey there!

If your prompts are generating code, I could be wrong, but I believe you might need to look into the output for token counts as well, because the output is fed back into the model for context.

Also, since the error message mentions an organization ID, are you sure no one else or no other app is making requests to the `gpt-4` model with one of your API keys?

**Comment by xinranli0809** [comment]
> Hey there!
> 
> If your prompts are generating code, I could be wrong, but I believe you might need to look into the output for token counts as well, because the output is fed back into the model for context.
> 
> Also, since the error message mentions an organization ID, are you sure no one else or no other app is making requests to the `gpt-4` model with one of your API keys?

hello! I am the only one in the company using the API so all traffic should come from my program.

After enabling `debug_mode`, I indeed see there are a lot of traffic going on, I am still trying to understand the meaning of all of it. For example. printing a conversation that triggers the 10000 token/minute limit with `print(interpreter.messages)` gives me a list with total token count of around 2000. The debug log of the same conversation is about 25000 tokens long... I know only a small portion of this is actually API traffic and most are just program log, but there are indeed a few things I didn't take into account such as the procedures string. There also seems to be some kind of repetition of the code generated? still trying to understand what actually goes into the API, the log is a bit hard to read. But knowing this ratio now I guess I will lower my threshold to around 2000 tokens/minute just to get the program running.

Also, when running the terminal interface I can use %token command but it does not seem to exist for the python library just yet? Please let me know if I am wrong, interested to see it this give a more accurate token count.

**Comment by ericrallen** [comment]
The magic commands, like `%tokens` are currently part of the Terminal UI, but you should be able to import the underlying method that it calls:

https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/utils/count_tokens.py

It’s worth noting that `%tokens` is designed to estimate how many tokens would be sent with the next message, and is still a little experimental. If you notice any issues with it, feel encouraged to make suggestions or help us improve it by submitting a Pull Request.

**Comment by ericrallen** [comment]
It's worth noting that there are [some complexities around how functions are tokenized](https://github.com/KillianLucas/tokentrim/issues/8), and that can lead to some possible confusion regarding context and rate limits.

**Comment by ericrallen** [comment]
I'm going to close this one for now.

Optimizing and providing better tools for understanding token usage is definitely top of mind.
