### ISSUE TITLE
Need to pre-load a model somehow to avoid long start up times on Cloud Run

### ISSUE THREAD

**Issue by MarkEdmondson1234** [KillianLucas/open-interpreter#708]
### Describe the bug

When using a Cloud Run instance, the model is newly installed each time, but we have to download the start up files each time:

<img width="1047" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/3155884/94a46636-5fef-4049-bf44-5ce135eb3509">

Is it possible to load this at build time, so start up execution time can be reduced by ~20secs?

### Reproduce

On first start up on Cloud Run
```
    for chunk in interpreter.chat(user_input, stream=True, display=False):
          # do stuff


# /home/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz:   0%|          | 0.00/79.3M [00:00<?, ?iB/s]
#..
# /home/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz:   1%|          | 0.00/79.3M [00:00<?, ?iB/s]
```

etc. about 20 seconds

### Expected behavior

Download of onnx_models/all-MiniLM-L6-v2/onnx.tar.gz to be possible during the Dockerfile build somehow

### Screenshots

<img width="1047" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/3155884/94a46636-5fef-4049-bf44-5ce135eb3509">

### Open Interpreter version

0.1.10

### Python version

3.10

### Operating System name and version

Linux

### Additional context

To stop the HTTP timeout, I run a test query each time first, but it adds ~20+ seconds latency to first token back.

**Comment by MarkEdmondson1234** [comment]
I put the bug label on, as I have an OpenAI key in the environment, and it uses that for generating text, but it looks like it is downloading a local model?

**Comment by MarkEdmondson1234** [comment]
And this behavior started in 1.10 but wasn't present in 1.7

**Comment by RealityMoez** [comment]
> I have an OpenAI key in the environment, and it uses that for generating text, but it looks like it is downloading a local model?

Same here.

**Comment by MarkEdmondson1234** [comment]
I can help solve this if I can be pointed at where the code is that does this download is called from.

**Comment by MarkEdmondson1234** [comment]
It was Chroma, so adding this line in to fake a chroma call during build time has solved the issue:

```
#Dockerfile
...rest of your docker
RUN python -c "import chromadb;client = chromadb.Client();collection = client.create_collection('all-my-documents');collection.add(documents=['This is document1'], ids=['doc1']);results = collection.query(query_texts=['This is a query document'],n_results=1)"
...
```
