### ISSUE TITLE
open-interpreter UI

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [KillianLucas/open-interpreter#714]
### Is your feature request related to a problem? Please describe.

Is there any plan for open-interpreter web UI in the future?

### Describe the solution you'd like

 Such as：chainlit

**Comment by ericrallen** [comment]
There are currently plans to build a desktop app.

Several teams built UIs for a recent hackathon, and because Open Interpreter is just a Python package, anyone can import it and built things - like a UI - on top of it.

**Comment by ericrallen** [comment]
I'm going to go ahead and close this one as stale for now.

There will be announcements when the UI is ready to release.
