### ISSUE TITLE
Adding Contributors Section to readme.md 

### ISSUE THREAD

**Issue by mohitd404** [KillianLucas/open-interpreter#715]
### Describe the bug

Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

### Reproduce

..

### Expected behavior

![3](https://github.com/KillianLucas/open-interpreter/assets/146939900/582edaa4-913e-42fc-a8f2-39a615af9ab9)

### Open Interpreter version

0.1.1

### Python version

3.1.1.5

### Operating System name and version

windows 10

### Additional context

@ericrallen  kindly assign this issue to me !  Thank You !

**Comment by ericrallen** [comment]
Hey there!

Every repo has a [Contributors](https://github.com/KillianLucas/open-interpreter/graphs/contributors) list in it’s Insights and there is a contributor list in the project root-level UI, too.

![IMG_3130](https://github.com/KillianLucas/open-interpreter/assets/1667415/cc11a224-01e6-4c58-afac-94d9182ef87e)

I’m not sure if adding more noise to an already very dense README is the best approach, but will defer to @KillianLucas on this one.
