### ISSUE TITLE
Programmatic chat initial prompt

### ISSUE THREAD

**Issue by SuperMaximus1984** [KillianLucas/open-interpreter#717]
### Is your feature request related to a problem? Please describe.

My feature is related to an initial prompt that would set up Interpreter's behavior

### Describe the solution you'd like

Can `interpreter.chat()` have some kind of initial setup for "role", "content" (basic rules of communication)?
Just like for ChatGPT bot.
I need to limit it for a conversation regarding narrow topics.

**Comment by ericrallen** [comment]
Going to close this one for now as I believe this functionality already exists, but please feel encouraged to reopen it and provide more context if the current options don't work for you.
