### ISSUE TITLE
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

### ISSUE THREAD

**Issue by kiloppertry** [KillianLucas/open-interpreter#720]
### Is your feature request related to a problem? Please describe.

i am chatgpt4 user .what's wrong?

### Describe the solution you'd like

what's wrong?

**Comment by ericrallen** [comment]
Hey there, @kiloppertry!

This is a common issue for folks who may not have set up prepaid API billing.

https://github.com/KillianLucas/open-interpreter/issues/164#issuecomment-1711992453

Please reopen this issue if the suggestion from the common issue thread dies not work for you.
