### ISSUE TITLE
Cannot reproduce the sample FastAPI code

### ISSUE THREAD

**Issue by zhimin-z** [KillianLucas/open-interpreter#722]
### Describe the bug

I found I cannot reproduce the sample FastAPI code on the readme page whether I use Linux or MacOS using Python>3.10.

### Reproduce

I am trying to deploy using FastAPI on the provided sample code:
```
# server.py

from fastapi import FastAPI, Response
import interpreter

app = FastAPI()

@app.get("/chat")
def chat_endpoint(message):
    return Response(interpreter.chat(message, stream=True), media_type="text/event-stream")

@app.get("/history")
def history_endpoint():
    return interpreter.messages
```
and
```
pip install fastapi uvicorn
uvicorn server:app --reload
```
but each time I run the last line of code it gives me the following error:
```
INFO:     Will watch for changes in these directories: ['/Users/jimmy/Documents/GitHub/L-factor']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [35975] using WatchFiles
ERROR:    Error loading ASGI app. Could not import module "server".
```

### Expected behavior

It just runs.

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/8592144/5665eed8-6c8c-4d55-8443-719b10094a60)

### Open Interpreter version

0.1.10

### Python version

3.10.6 AND 3.11.1

### Operating System name and version

Ubuntu 20.04 AND MacOS 14.1

**Comment by ericrallen** [comment]
This is addressed by #727
