### ISSUE TITLE
No matching distribution found for open-interpreter

### ISSUE THREAD

**Issue by tranhoangnguyen03** [KillianLucas/open-interpreter#724]
### Describe the bug

https://github.com/KillianLucas/open-interpreter/issues/290#issuecomment-1788901214

I'm having the same issue when trying to deploy my streamlit app on streamlit cloud
![image](https://github.com/KillianLucas/open-interpreter/assets/31383641/ff6d66be-41c8-4a8f-8479-3875c4b534bb)

### Reproduce

.

### Expected behavior

.

### Open Interpreter version

0.1.10

### Python version

3.11

### Operating System name and version

Linux

**Comment by ericrallen** [comment]
Hey there, @tranhoangnguyen03!

Is your Streamlit app using a compatible Python version?

**Comment by tranhoangnguyen03** [comment]
You are right, I did not specify the Python version for my streamlit app. Issue resolved. Thanks for your help @ericrallen
