### ISSUE TITLE
cannot use anyscale api

### ISSUE THREAD

**Issue by OTA-Tech-AI** [KillianLucas/open-interpreter#731]
### Describe the bug

interpreter --api_base https://api.endpoints.anyscale.com/v1 -ak myscretkey -m anyscale/meta-llama/Llama-2-70b-chat-hf

this won't work

### Reproduce

interpreter --api_base https://api.endpoints.anyscale.com/v1 -ak  -m anyscale/meta-llama/Llama-2-70b-chat-hf

### Expected behavior

not working

### Open Interpreter version

0.1.10

### Python version

3.10.0

### Operating System name and version

win10

**Comment by ericrallen** [comment]
@OTA-Tech-AI I believe you need to follow the [LiteLLM docs for Anyacale AI](https://docs.litellm.ai/docs/providers/anyscale) and prefix the model name with `anyscale/`.

**Comment by OTA-Tech-AI** [comment]
The litellm version in current open interpreter is too low, which does not
support anyscale, could we update the litellm to be latest?

**Comment by ericrallen** [comment]
Until another update is ready to go out, I believe you _should_ be able to `pip install -upgrade litellm` in the same virtual environment where you installed Open Interpreter.

**Comment by OTA-Tech-AI** [comment]
Thanks, seems to work now!
