### ISSUE TITLE
intermittent response dict missing "message" attribute

### ISSUE THREAD

**Issue by Fuushi** [KillianLucas/open-interpreter#732]
### Describe the bug

intermittent empty response from interpreter when using python library and calling interpreter.chat(prompt),
returning a dict with only a role attribute

issue is suspected to be in respond.py on line 44
for chunk in interpreter._llm(messages_for_llm):

interpreter._llm(messages_for_llm) is intermittently returning an empty iterable

### Reproduce

use python library

use chatgpt3.5 turbo

prompt = "use python to find the directory of the interpreter library" #this prompt i found causes the issue most often (90% of the time)

interpreter.chat(prompt)

### Expected behavior

expected result is a dict with both role and message attributes, but only role is returned

### Screenshots

![ex1](https://github.com/KillianLucas/open-interpreter/assets/88691430/02082bf8-15c4-4adb-93b8-5f17ff6abc08)

### Open Interpreter version

0.1.10

### Python version

python 3.11.0

### Operating System name and version

Windows 10

**Comment by gstarwd** [comment]
您好 您的邮件我已经收到~
----
王迪

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
