### ISSUE TITLE
Readme.md is missing system requirements for local installation

### ISSUE THREAD

**Issue by Spaceman333** [KillianLucas/open-interpreter#733]
### Is your feature request related to a problem? Please describe.

My computer has 8GB of RAM, runs on Windows 7 and has an average graphics card. Will I be able to run this tool locally?

I don't know because readme.md doesn't tell me this.

### Describe the solution you'd like

How much RAM, disk space and processing power do I need to use this tool? Are there minimum OS requirements?

**Comment by ericrallen** [comment]
Hey there, @Spaceman333!

As long as you have Python 3.10 or 3.11, Open Interpreter should be capable of running on your system.

With older hardware, you’re going to have to research and test things if you want to find a local model that will work with your setup.

It will likely need to be a highly quantized model and responses will be slow. For reference, I’ve successfully run several models on a 2012 MacBook Pro.

That being said, you can still make use of any hosted models that the underlying [LiteLLM](https://docs.litellm.ai/) integration supports and not have to worry about hardware specs.

**Comment by Spaceman333** [comment]
Wow, that surprised me. I've been used to seeing some AI tools require huge requirements to run so to hear that a machine from 2012 can do it gives me the confidence to install this tool.

Thanks. I don't know if the readme.md got any updates to mention the requirements, but I'm happy with this inquiry. I'll close the issue.
