### ISSUE TITLE
can control own company's office systems？

### ISSUE THREAD

**Issue by yoyomule** [KillianLucas/open-interpreter#734]
### Is your feature request related to a problem? Please describe.

I would like to ask, if you want to control own company's office systems, these office systems have their own API and their own data, what should you do?

### Describe the solution you'd like

It is possible to communicate with the office system through natural language or even voice, and obtain the system's functional operations and data.

### Describe alternatives you've considered

https://openai.com/blog/function-calling-and-other-api-updates

**Comment by ericrallen** [comment]
Hey there, @yoyomule!

If it’s a well-known API you might be able to ask Interpreter to use the API.

If it’s something more proprietary you might need to feed the API docs in as context by having Open Interpreter read them from a URL or an API specification. Depending on how complex the documentation is, you might run up against the context window, but you could try asking Open Interpreter to create an API client from the spec if one doesn’t exist and save that client to a Python script that it can use in subsequent requests to interact with the API.

We would need more details to provide more guidance.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
