### ISSUE TITLE
Local model does not work on Linux

### ISSUE THREAD

**Issue by Xu99999** [KillianLucas/open-interpreter#736]
### Describe the bug

After the server deploys version 0.1.11, it crashes by pressing any key. How to run a multi-GPU machine with a specified GPU?

### Reproduce

interpreter  --local

### Expected behavior

Should not exit, Linux is minimized and there is no graphical interface. How to use LM STUDIO?

### Open Interpreter version

0.1.11

### Python version

3.10.0

### Operating System name and version

redhat 7.9

**Comment by Xu99999** [comment]
<img width="590" alt="截屏2023-11-07 13 02 50" src="https://github.com/KillianLucas/open-interpreter/assets/111261378/6f912557-fc84-4841-950e-51faa3819cc6">

**Comment by ericrallen** [comment]
Hey there, @Xu99999!

The latest version of Open Interpreter uses LM Studio for local inference, but LM Studio Linux support is currently in beta:

https://lmstudio.ai/

I believe you can request access to the beta, though.

You can request access to the beta or use an alternate method of running a local model and the underlying [LiteLLM integration](https://docs.litellm.ai/docs/providers).

**Comment by Notnaton** [comment]
When joining LM studios discord server you get access to the linux beta download.

**Comment by Xu99999** [comment]
> When joining LM studios discord server you get access to the linux beta download.

ths,but my Linux server is minimally installed and has no graphical interface. Does LM support command line interaction?

**Comment by Notnaton** [comment]
Im not sure, I don't think so. You can use other programs to serve LLMs. 
Llama.cpp
Ollama
Etc.

And then connect interpreter with the correct port:
`interpreter --api_base http://localhost:port/v1`

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
