### ISSUE TITLE
errors on long writting task

### ISSUE THREAD

**Issue by PaulLockett** [KillianLucas/open-interpreter#75]
<img width="1728" alt="Screenshot 2023-09-06 at 10 57 37 AM" src="https://github.com/KillianLucas/open-interpreter/assets/20708690/48d19528-c8cd-4ca0-a398-53748fb263ae">

initial prompt:  Make a pdf called aksum.pdf in the downloads folder that contains a history of the aksum empire and its influence on Rome. Provide at least 5 peer-reviewed and scholarly articles on the civilization and 2 interesting future research paths that would hook any person with a passing interest in African history. the pdf should contain information from the peer-reviewed article and reference them when it does.

**Comment by PaulLockett** [comment]
any keyboard interrupt will get it going again though

**Comment by PaulLockett** [comment]
<img width="1728" alt="Screenshot 2023-09-06 at 1 45 30 PM" src="https://github.com/KillianLucas/open-interpreter/assets/20708690/0930618b-aa26-454f-b725-2a8200595bd8">
It kept going and crashed

**Comment by TanmayDoesAI** [comment]
@PaulLockett Could I know what model are you using?

**Comment by ericrallen** [comment]
Closing as stale for now. Feel free to reopen with relevant info if you update and still experience the same Issue.
