### ISSUE TITLE
Discovered Issues and User Feedback

### ISSUE THREAD

**Issue by dongdongxiang** [KillianLucas/open-interpreter#751]
### Is your feature request related to a problem? Please describe.

I recently tried the 'open-interpreter' feature using GPT-4 to install some software. The terminal output an overwhelming amount of logs and just like that, $5 was gone.

Moreover, there are quite a few bugs, such as the lack of an automatic '-y' option for confirmations, which caused the process to hang.

I also ended up owing $2.

Still, the tool was handy. In total, I spent $7 to set up Nginx, write a file upload function, and install PDF dependencies, which amounts to roughly 35 Chinese Yuan.

With 35 Yuan, I could have two meals in China, so the cost-effectiveness is rather low.

### Describe the solution you'd like

I just used the 'open interpreter' and encountered several issues. Linux outputs a ton of logs, which quickly consumed my credit, and if the installation command is run without the '-y' flag, it causes the interface to freeze. It seems like any operation requiring interaction gets stuck.

**Comment by ericrallen** [comment]
Hey there, @1135004584!

It sounds like maybe you’re talking about passing input into underlying interactive commands that Open Interpreter has initiated?

In terms of the cost, there are still some ideas for us to explore for helping bring it down, but that’s also a fundamental issue with anything built on top of an LLM - especially the more capable OpenAI models.

**Comment by dongdongxiang** [comment]
I hope for a cheaper and more precise large-model solution.

**Comment by ericrallen** [comment]
@dongdongxiang I think we all do.

You can try out almost every current model offering thanks to the underlying [LiteLLM](https://github.com/BerriAI/litellm) integration.

**Comment by ericrallen** [comment]
Hey there!

I'm going to close this one as a duplicate for now because we are already tracking discussions for:

- **Cost**: #569 #409 #692
- **Sending Characters to Subprocess Shell**: #274 

Feel free to reopen it if you feel like there is more to discuss that isn't covered in any of these other Issues.
