### ISSUE TITLE
can't install open interpreter.

### ISSUE THREAD

**Issue by Domo326** [KillianLucas/open-interpreter#752]
### Describe the bug

I have updated python to version 3.9 and pip to version 23. I put in the command to install it, but it says:

"Error: Could not find a version that satisfies the requirement code-interpreter (from versions: non)
Error: No matching distribution found for code-interpreter"

anyone else getting this issue? 

### Reproduce

open command

type "pip install code-interpreter"

get error codes

### Expected behavior

i expected it to be installed but nothing happened

### Screenshots

![Screenshot 2023-11-13 184537](https://github.com/KillianLucas/open-interpreter/assets/11468227/d853879b-d266-43c8-8213-da32677d4b03)

### Open Interpreter version

none

### Python version

3.12.0

### Operating System name and version

window 10 home

**Comment by ericrallen** [comment]
Hey there, @Domo326!

Open Interpreter only supports Python 3.10 and 3.11 at the moment.

Going to close this one for now. Feel free to reopen if you experience the issue with a supported version of Python.

**Comment by Domo326** [comment]
Copy that. I think I noticed that in some videos I saw. I'll give it a try. Thx
