### ISSUE TITLE
Support for Linux without lm studio

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#754]
### Describe the solution you'd like

Is there a way to run this locally on Linux without LM Studio? Currently their download page says that you have to request a beta in their discord server, which I would not like to do. Can you do this with `--model`? If so, how? Thank you for this great project!

**Comment by ericrallen** [comment]
Hey again, @mak448a!

Anything that you can run with [LiteLLM](https://docs.litellm.ai/docs/providers) can be used as an Open Interpreter model. So you could try out [ollama](https://ollama.ai/) or any other way of running the model locally that can serve up an [endpoint](https://docs.litellm.ai/docs/providers/custom_openai_proxy).

**Comment by mak448a** [comment]
Thanks! Also I joined the discord server and got lm studio anyway
