### ISSUE TITLE
In depth documentation

### ISSUE THREAD

**Issue by ngoiyaeric** [KillianLucas/open-interpreter#756]
### Is your feature request related to a problem? Please describe.

I've been trying to go over every line of code for oi. So I started mapping out every directory -> file -> function graph. 
I've found an automated solution. 

### Describe the solution you'd like

Find solution at 
codesee.io 
 https://player.vimeo.com/video/735870471?h=93d5792bf6

### Additional context

Killian would have to authenticate with codesee. This is a new start up so maybe some due diligence is necessary.

**Comment by MikeBirdTech** [comment]
Not sure why authentication is needed on a public repo?

Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
