### ISSUE TITLE
long-lived sessions (python, shell, etc.)

### ISSUE THREAD

**Issue by nitsanavni** [KillianLucas/open-interpreter#758]
### Is your feature request related to a problem? Please describe.

On chatgpt when you define a python function, or you import a module, it is then available for subsequent commands.
This opens up a workflow where you build a tool in an early stage and then use it in a later stage, without the need to write the code to files (which is a valid workflow too).

### Describe the solution you'd like

Don't have a design in mind.
In other automation scripts I've created an ongoing `subprocess` for the the shell or repl and then continued feeding code into it and getting results out of it.

### Describe alternatives you've considered

To reuse code, you can instruct gpt to write it to files, but that is a less natural way for it to write code, it becomes an extra layer of complexity.

**Comment by MikeBirdTech** [comment]
Re-using code/tools is on the roadmap. Thanks!
