### ISSUE TITLE
Integration/Similarity to OpenAI's Assistans

### ISSUE THREAD

**Issue by h14turkiye** [KillianLucas/open-interpreter#759]
### Describe the solution you'd like

Need to rewrite the code for this...
By using assisstans's retrieval, we dont need to send the files, saving money by alot.
And rather than using openai's code interpreter we can use ours!

I liked the messages addition to assistants, Capturing whether message has a text or image is really great! (e1.)
```py
for content in msg.content:
  try: 
      content = content.image_file.file_id
      print(f"{role.capitalize()}: image_file")
      retrieve_file(content).show()
      # todo: Show it on the net! 
  except: 
      pass
  try:
      content = content.text.value
      print(f"{role.capitalize()}: {content}")
      # todo: show it on the net
  except: 
      pass
```

### Describe alternatives you've considered

Well it is not an addition to the code but it is great use to me so maybe another repo, getting the message and checking if it is a code and executing it, and adding the content to messages, removing code from the current message splitting it. By doing so it will work with normal assistants.

**Comment by ericrallen** [comment]
Hey there, @h14turkiye!

Can you take a step back and briefly explain what you’re asking for from Open Interpreter here?

**Comment by h14turkiye** [comment]
> Hey there, @h14turkiye!
> 
> Can you take a step back and briefly explain what you’re asking for from Open Interpreter here?

Yes, sorry for my ability to explain. 

Well, retrieval tool of OpenAI is quite useful, considering you simply need to upload a file once when you create the assistant.
I want open interpreter to have this ability. I am not skilled in reading python packages, but this repo seems to never send any file content(Correct me if I am wrong).

In my case, chatgpt needs to have the data, I want chatgpt to generate a similar content to a 50mb pdf file. I could use this file 5000 times.

And the second feature, adding the possibly generated image files to the messages. message.content.data.image_file.file_id, thats how OpenAI's assissants do.

**Comment by MikeBirdTech** [comment]
Check out the `computer` features to see if this is what you're looking for. Thanks!
