### ISSUE TITLE
discord channel link?

### ISSUE THREAD

**Issue by mberman84** [KillianLucas/open-interpreter#76]
hi sorry if i'm missing it but where is the discord channel link?

**Comment by gianpaj** [comment]
https://discord.com/invite/YG7APUyJ5

https://twitter.com/hellokillian/status/1699184049800249683

**Comment by ilteris** [comment]
This link doesn't work :( Can we get an updated invite if possible please

**Comment by Notnaton** [comment]
There is a link on the Readme file at the top. It's a discord icon and the text says "chat"
