### ISSUE TITLE
is it possible to store the api key in a config file?

### ISSUE THREAD

**Issue by bbigras** [KillianLucas/open-interpreter#766]
### Describe the solution you'd like

store the key in a config file or in the keyring

**Comment by ericrallen** [comment]
It’s not recommended, but should be possible via the api_key property.

I’m going to close this one for now, but feel free to reopen it or ping me if I’m wrong.

**Comment by bbigras** [comment]
The recommended way is setting the API key as an environment variable (possibly after disabling the shell history)?

**Comment by ericrallen** [comment]
The API key input uses a password input that hides it from your shell history.

We have integrating a keyring provider on our roadmap and hope to get it implemented soon.
