### ISSUE TITLE
Browser bookmarks and Chinese characters

### ISSUE THREAD

**Issue by ghosthree** [KillianLucas/open-interpreter#768]
### Describe the bug

1.Interaction in Chinese is prone to gbk errors
2.The permissions of open interpreter are too low. Even bookmarks cannot be accessed. How can I increase the permissions?

### Reproduce

1.What files are on my desktop?
2.Go to a website in my browser bookmarks

### Expected behavior

no error and get more permissions

### Screenshots

1.Exception in thread Thread-32 (handle_stream_output):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreters\subprocess_code_interpreter.py", line 127, in handle_stream_output
    for line in iter(stream.readline, ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8d in position 166: illegal multibyte sequence1

2.I currently don't have the capability to access your browser bookmarks       
  directly. However, if you can provide the URL or name of the website you'd   
  like to visit, I can create a button that, when clicked, will open that      
  website in your default web browser.   

### Open Interpreter version

0.1.15

### Python version

3.11

### Operating System name and version

win10

**Comment by ericrallen** [comment]
Hey there, @ghosthree!

I don’t know if there’s an API for your browser’s bookmarks, so I’m not sure how you expect Open Interpreter to react to your request.

On macOS it could try to run an AppleScript to interact with your browser, but I don’t think there is an equivalent on Windows.

Open Interpreter isn’t magic, it requires exposed APIs to interact with your machine directly.

In terms of the Chinese characters, feel encouraged to submit Pull Requests to help. There are two core maintainer and a small handful of very awesome contributors, but I’m not sure if any of them use Chines characters for their interactions with Open Interprwter.
