### ISSUE TITLE
How to use a different port than 1234 connecting to LM Studio?

### ISSUE THREAD

**Issue by caryknoop** [KillianLucas/open-interpreter#769]
### Is your feature request related to a problem? Please describe.

Port 1234, which is the default port for LM Studio, may be used by other applications.  LM Studio allows the use of any port. However, open-interpreter has no documented options to use another port and automatically assumes port 1234.

### Describe the solution you'd like

A config or command line option to use the port LM Studio uses.

**Comment by Notnaton** [comment]
Change PORT and MODEL to whatever you want
`
interpreter -ab http://localhost:PORT/v1 --model openai/MODEL
`
Further documentation is here: https://docs.openinterpreter.com/usage/terminal/arguments

**Comment by caryknoop** [comment]
> Change PORT and MODEL to whatever you want `interpreter -ab http://localhost:PORT/v1 --model openai/MODEL` Further documentation is here: https://docs.openinterpreter.com/usage/terminal/arguments

I checked the link you provided and could not see any documentation about the -ab option.  Could you point out where that is documented?

**Comment by Notnaton** [comment]
@caryknoop https://docs.openinterpreter.com/usage/terminal/arguments#api-base-or-ab

**Comment by ericrallen** [comment]
Hey there, @caryknoop!

Feel encouraged to submit a Pull Request to clear up any confusion you notice in the docs.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!

**Comment by DarthJahus** [comment]
@caryknoop 

`.lmstudio\.internal\http-server-config.json`


```json
{
  "autoStartOnLaunch": true,
  "port": 1234,
  "cors": false,
  "logSensitiveData": true,
  "logIncomingTokens": false,
  "verbose": true,
  "logLinesLimit": 500,
  "networkInterface": "0.0.0.0",
  "justInTimeModelLoading": true,
  "fileLoggingMode": "succinct"
}
```

You can change the port, activate CORS and change network interface (`127.0.0.1` is the default, so no server access). These options used to be in the UI, now they are not. I don't know why they've removed them.
