### ISSUE TITLE
problem when installing 

### ISSUE THREAD

**Issue by qianxinxuexi** [KillianLucas/open-interpreter#771]
### Describe the bug

![屏幕截图 2023-11-18 163933](https://github.com/KillianLucas/open-interpreter/assets/150140023/017e4354-6b3c-4230-befd-ef8a3192183f)
I have install rust,but when I  run pip install open-interpreter to install.but after i run this code,it shows that.

### Reproduce

Sorry,I don't what should to answer.

### Expected behavior

I want it can install smoothly.

### Open Interpreter version

 Package(s) not found: open-interpreter

### Python version

3.12.0

### Operating System name and version

Windows11

**Comment by Notnaton** [comment]
https://github.com/KillianLucas/open-interpreter/issues/627
Python 3.12 not supported yet

**Comment by ericrallen** [comment]
Hey there, @qianxinxuexi!

Going to close this one for now.

As is mentioned in the README and common issues thread, Open Interpreter can’t support Python 3.12 yet.
