### ISSUE TITLE
Encountered an unexpected function call when prompting for Javascript functions

### ISSUE THREAD

**Issue by JBlitzar** [KillianLucas/open-interpreter#774]
### Describe the bug

I asked Open Interpreter about how to create a Javascript function to return a string containing escaped unicode characters. The program produced the below output and instructed me to open an issue. 

`> all right. Make me a javascript function that returns zero width space + zero width non joiner as a string using unicode escapes
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": ""
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function get"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getIn"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisible"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString()"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n "
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\n"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisible"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString ="
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = get"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getIn"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisible"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\n"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log(in"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log(invisible"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log(invisibleString"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log(invisibleString);"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter
Encountered an unexpected function call:  {
  "name": "javascript",
  "arguments": "function getInvisibleString() {\n  return '\\u200B\\u200C';\n}\n\nconst invisibleString = getInvisibleString();\nconsole.log(invisibleString);"
} 
Please open an issue and provide the above info at: https://github.com/KillianLucas/open-interpreter`

### Reproduce

`interpreter -m gpt-3.5-turbo`
Prompt: `all right. Make me a javascript function that returns zero width space + zero width non joiner as a string using unicode escapes`

### Expected behavior

Expected behavior is to not produce an error and instead produce plaintext javascript code.

### Open Interpreter version

0.1.11

### Python version

3.10

### Operating System name and version

Macos Ventura 13.6.1

**Comment by Notnaton** [comment]
> Open Interpreter version
> 0.1.11
Please run `pip install --upgrade open-interpreter` current version is 0.1.15

**Comment by JBlitzar** [comment]
In updated version bug no longer persists.
