### ISSUE TITLE
open intrepreter

### ISSUE THREAD

**Issue by qianxinxuexi** [KillianLucas/open-interpreter#775]
### Describe the bug

![屏幕截图 2023-11-19 115344](https://github.com/KillianLucas/open-interpreter/assets/150140023/7481cd6e-f577-498e-b5bd-3fe60add0766)
I have installed open-interpreter and when installing no error was showed,however,when I want run it,it shows that.

### Reproduce

can't run

### Expected behavior

correctly run

### Open Interpreter version

0.1.15

### Python version

3.10.11

### Operating System name and version

Windows11

### Additional context

![屏幕截图 2023-11-19 115940](https://github.com/KillianLucas/open-interpreter/assets/150140023/6d892e0e-30e0-4a9c-810d-354fb9a11d3a)
it is my open-interpreter

**Comment by Notnaton** [comment]
@qianxinxuexi Can you show the output when you run `interpreter`

**Comment by Notnaton** [comment]
@qianxinxuexi Can you translate this?
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/3b9e90c0-e146-4d80-b768-431df7a829eb)

**Comment by qianxinxuexi** [comment]
The first photo is the result of installing.No errormessage was displayed during the installing process.
The second photo is the result of typing interpreter after I finished installing it.
I want to know if I installing successfully,because when I input "where open-interpreter",it shows like the third photo,and I can't find it in File Exporer.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KillianLucas/open-interpreter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KillianLucas/open-interpreter] open intrepreter (Issue #775)





 
@qianxinxuexi Can you show the output when you run interpreter—

**Comment by Notnaton** [comment]
@qianxinxuexi Please run:
```
pip install --upgrade pip
pip install --force-reinstall open-interpreter
interpreter
```

**Comment by qianxinxuexi** [comment]
Thanks for your reply.however,I run according to your command and still have the following problems.
When I input "pip install --force-reinstall open-interpreter",there are many warnings like the first photo.











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KillianLucas/open-interpreter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KillianLucas/open-interpreter] open intrepreter (Issue #775)





 
@qianxinxuexi Please run:
 pip install --upgrade pip pip install --force-reinstall open-interpreter interpreter

**Comment by qianxinxuexi** [comment]
OK,yestoday,I have added my python and scripts into adds.And I have get a openai API key and run"setx OPENAI _API_KEY my key".But&nbsp; it still shows like the first photo.

Today,I try to run it,but it has no responding like this.





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "KillianLucas/open-interpreter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月21日(星期二) 凌晨2:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KillianLucas/open-interpreter] open intrepreter (Issue #775)





 
@qianxinxuexi Is your python/Scrips folder in PATH?

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
