### ISSUE TITLE
extra option: or would you like me to regenerate this code?

### ISSUE THREAD

**Issue by Morriz** [KillianLucas/open-interpreter#776]
### Is your feature request related to a problem? Please describe.

The code is not good most of the times and devs can inspect it.

### Describe the solution you'd like

I would like to see another option provided like so:

```
Would you like to run this code, or generate other code? (y/n/o)
```
(In auto mode this is not possible obviously)

**Comment by Notnaton** [comment]
Related:
https://github.com/KillianLucas/open-interpreter/pull/612
https://github.com/KillianLucas/open-interpreter/issues/537

**Comment by Morriz** [comment]
Ah yes. Closing
