### ISSUE TITLE
linting errors and auto completion not working

### ISSUE THREAD

**Issue by Morriz** [KillianLucas/open-interpreter#778]
### Describe the bug

when I import interpreter and do`interpreter.extend_config(config_path=...)` I get the following:
```
Module 'interpreter' has no 'extend_config' memberPylint[E1101:no-member](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-member.html)
```

autocompletion also does not work

### Reproduce

1. import interpreter
2. run `interpreter.extend_config(config_path=...)`
3. observe the error

### Expected behavior

no linting errors

### Open Interpreter version

0.1.15

### Python version

3.11.2

### Operating System name and version

macOS 14

**Comment by Morriz** [comment]
If I do this it works:

```yaml
from interpreter import Interpreter

interpreter = Interpreter()
```

**Comment by MikeBirdTech** [comment]
@Morriz please user lower case `interpreter`

Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
