### ISSUE TITLE
Does the Open  interpreter support direct data transfer from the data generated by the interpreter to an external program?

### ISSUE THREAD

**Issue by hvacking** [KillianLucas/open-interpreter#781]
### Describe the solution you'd like

How we get the data generate by interpreter when run OI?

**Comment by Notnaton** [comment]
Using python you can read interpreter.messages
I believe it contains what you want

**Comment by hvacking** [comment]
let me make an example . If i use prompts for OI to generate a dataframe or an image， how we get this dataframe or image directly? Now i have to use prompts for OI to download this dataframe and image in a local folder, then use python program to load this dataframe or image file. It is not a good method.

**Comment by Manamama** [comment]
Simple items: in Markdown. Embedded images from local or Web work, so does some other nifty Markdown. 
Advanced? Api calls, Xterm, rendering server, Latex via PDF, PlantUML, Wolfram Alfa links, etc. Possibilities are endless, the LLM may gladly advise. 

E.g. Claude2 renders most fine: one just presses Y or "wakes her up" by encouragement.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
