### ISSUE TITLE
Interpreter fails to edit code?

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#783]
### Describe the bug

Plese see screenshot, it tries again and again to correct code, but it always does the same thing/doesn't correct it. ![image](https://github.com/KillianLucas/open-interpreter/assets/43472567/2e7ecc6e-f5be-4f10-a64b-e22e10f59e17)

### Open Interpreter version

2.0

### Python version

3.11.5

### Operating System name and version

Mac OS

**Comment by ericrallen** [comment]
Hey there, @stevenbaert!

Just as a note from both of your recent issues, it's not super helpful to just repeat the same thing over and over in your Issue description. I've edited both for clarity, but please keep that in mind in the future.

Could you provide some more details to help debugging, like:

- What was the prompt that lead to this?
- What's the full error output? The provided screenshot is cut off without the end of the stack trace.
- What model were you using?
- What version of Open Interpreter are you using? The issue says, `2.0`, but Open Interpreter is still in `0.1.x` versions.

**Comment by stevenbaert** [comment]
Sorry about that, will do.
I asked interpreter to adapt some python files of which one (main.py) is executing a "fetching mails from gmail (receivemail.py)", when it finds new with specific subject, it will grab the content and use it to execute it by Open Interpreter.
But there it gets into a loop as you can see in screenshot, new_content = ... it changes code but doesn't do that correctly and runs into that correction again and again.
I have the latest open interpreter running (if I wouldn't, it would ask me to upgrade which it does not). Using the GPT-4 model. I cannot reproduce the full output at this time since I meanwhile manually adapted the code.

Though thè reason for me to not use open interpreter is exactly what I describe here: it loops into correction of code, but doesn't do that correctly so at the end I just do things manually again.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
