### ISSUE TITLE
Always in debug_mode?

### ISSUE THREAD

**Issue by stevenbaert** [KillianLucas/open-interpreter#784]
### Is your feature request related to a problem? Please describe.

Maybe I'm missing something but missing config for default interpreter (installed via pip3 install open-interpreter), like setting it to azure openai, setting it to -y for auto continue or disable debug. Now interpreter is running continuously in debug :-(

**Comment by Notnaton** [comment]
@stevenbaert You can use `interpreter --config` to open the config file. You can see more arguments here: https://docs.openinterpreter.com/usage/terminal/arguments
