### ISSUE TITLE
Change default model to GPT4 Turbo

### ISSUE THREAD

**Issue by talkingtoaj** [KillianLucas/open-interpreter#785]
### Is your feature request related to a problem? Please describe.

OpenAI released GPT 4 turbo, it is cheaper and stronger

### Describe the solution you'd like

change default model loaded to `gpt-4-1106-preview`

**Comment by Notnaton** [comment]
You're in luck, just merged https://github.com/KillianLucas/open-interpreter/pull/770
Should be available next update.
For now use `interpreter --model gpt-4-1106-preview`

**Comment by doublecookie** [comment]
I've installed it just a day ago and the default model is still gpt4

**Comment by Notnaton** [comment]
It says gpt-4 but in the background it's using turbo

**Comment by Equirinya** [comment]
According to the usage dashboard at openai its using the base gpt4 without turbo
Im pretty sure i didnt change the model

**Comment by Notnaton** [comment]
Okay, I'll have a look later today. Might be because something has changed with the dependencies

**Comment by Notnaton** [comment]
> According to the usage dashboard at openai its using the base gpt4 without turbo Im pretty sure i didnt change the model

Seems like we are using gpt-4-0613 and not the turbo version. 
The reason being the quality is better.

if you want to use turbo use this:
```
interpreter -m openai/gpt-4-turbo-preview
```

**Comment by cschubiner** [comment]
there is one true way to run interpreter: 

```
interpreter --model openai/gpt-4-turbo-2024-04-09 --context_window 126000 -y
```

**Comment by IkonicR** [comment]
Is it possible to run GPT-4o ??
