### ISSUE TITLE
Generated program failed when use lambda/namess function

### ISSUE THREAD

**Issue by YutakaShimokawa** [KillianLucas/open-interpreter#787]
### Describe the bug

If I have the following data and generated program that uses a pandas dataframe and lambda expression to search for a person with the same skills and qualifications as UserA, the following error will always occur.
But when I copy the same code to .py file it works fine
----------Data----------
Name, skill, qualification
UserA,"Skill1,Skill2","qualification1,qualification2"
UserB,"Skill3,Skill4,Skill5","qualification1"
UserC,"Skill1,Skill2,Skill5","qualification3"
UserD,"Skill1,Skill7","qualification2,qualification3"
----------Data----------

----------Error----------
TypeError: unhashable type: 'list'
----------Error----------

### Reproduce

1. Throw analysis instructions such as using lambda expressions on the data frame

### Expected behavior

I want it to work properly even if I use a lambda expression.

### Open Interpreter version

0.1.14

### Python version

Python 3.11.0

### Operating System name and version

Windows 11

**Comment by soloaliens** [comment]
Also for me. Same issue

Mac OS 13.2.1 (22D68)
Python 3.10
Open-interpreter 0.1.17

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
