### ISSUE TITLE
Encountered an unexpected function call.  Please open an issue

### ISSUE THREAD

**Issue by MarkEdmondson1234** [KillianLucas/open-interpreter#789]
### Describe the bug

I asked it to use a script in a tools/ folder and it looks like it used it for OpenAI functions instead

<img width="494" alt="Screenshot 2023-11-24 at 15 40 22" src="https://github.com/KillianLucas/open-interpreter/assets/3155884/81737ef3-cdbd-4b9a-94e8-9c1ccb060369">

the file_modifier.py file is one I have told is available within the prompt.

### Reproduce

My prompt includes:

```
  When given a task, check if a script exists in /app/tools that does that task.  If none exists, make one.
  To modify files, use the /app/tools/file_modifier.py CLI and create temporary text files first you will use to modify existing files: an example of usage is ./file_modifier.py path/to/file.txt path/to/pattern_file.txt path/to/replacement_file.txt
  Do not use shell's 'echo' to change files, as there are other artifacts in stderr/stdout that pollute the stream.
  You can run the scripts in /app/tools with no commands to check the syntax needed e.g. "/app/tools/git_commit_and_push_to_branch.sh <commit-message> <branch-name>"
```

it doesn't do it every time

### Expected behavior

For it to use the function as defined.

### Open Interpreter version

0.1.15

### Python version

3.10

### Operating System name and version

Docker debian

**Comment by ericrallen** [comment]
Hey there, @MarkEdmondson1234!

You might want to try adding this as a user message at the beginning of your conversation rather than in the `system_message` and see if that improves things.

There is some logic that appends the functions available to the model to the `system_message` and it might be creating confusion with the model’s function calling.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
