### ISSUE TITLE
Support for Custom llama.cpp models

### ISSUE THREAD

**Issue by razorback16** [KillianLucas/open-interpreter#79]
It will be great if the repo provides custom model support with json file description of the model huggingface url and the prompt template. This will help using [Phind-CodeLlama](https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GGUF) or [WizardCoder](https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0) model

**Comment by RoversX** [comment]
Ye, that's would be so great

**Comment by TanmayDoesAI** [comment]
We are working towards implementing open source models, that is one of the priorities. Would be implemented soon.

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. I'm going to close this as a duplicate of #183 where it's announced that we're working on this!
