### ISSUE TITLE
If config is empty interpreter crashes

### ISSUE THREAD

**Issue by Notnaton** [KillianLucas/open-interpreter#794]
### Describe the bug

Deleting the contents of the config file crashes interpreter

If there is someone who wants to try to contribute to Open Source Software for the first time, here is a good issue to work on. 
@ me if you need assistance, I'll help you make your first PR :teacher: 
You'll need some basic understanding of python :snake: 

### Reproduce

```
interpreter --config
```
delete content, save and close.
```
interpreter --config
```

### Expected behavior

Open the config file

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/291d6e41-3a7a-45c2-ba74-3be6baf614c6)

### Open Interpreter version

0.1.16

### Python version

3.11.6

### Operating System name and version

Windows 11

**Comment by Vikk-17** [comment]
Hey @Notnaton ! I want to this. Please help me by providing details what to do and how to do. :)
