### ISSUE TITLE
Integrating Bard via Cookies 

### ISSUE THREAD

**Issue by Dilahk7** [KillianLucas/open-interpreter#798]
### Is your feature request related to a problem? Please describe.

GPT api keys are paid and the only alternative to that is hugging face models that run locally, which tbh are not that great. 
was wondering if there is a way we could integrate this implementation of accessing bard via a terminal to this project.

https://github.com/mosajjal/bard-cli 

### Describe the solution you'd like

https://github.com/mosajjal/bard-cli

**Comment by DhrubaDC1** [comment]
As far as I have experienced, Integrating Bard via cookies doesn't really stay longer. It gets revoked and needs to be added again and again in every 10 minutes or so

**Comment by Notnaton** [comment]
Does their terms of service allow this?

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Thanks!
