### ISSUE TITLE
update litellm dependency

### ISSUE THREAD

**Issue by happysalada** [KillianLucas/open-interpreter#805]
### Is your feature request related to a problem? Please describe.

the litellm dependency is quite old in the lockfile (0.13.x) compared to the latest release which is 1.7.x
on nixos, this prevents updating open-interpreter to the latest version.

### Describe the solution you'd like

it would be nice to update to the latest version of the dependency, that would enable updating this program for nixos.

### Describe alternatives you've considered

leaving open-interpreter to 0.1.11 which is the current version it's at.

### Additional context

nixos works a bit differently, it tries to package every dependency from source, that is why only a certain subset of dependency versions can be maintained.

**Comment by Notnaton** [comment]
https://github.com/KillianLucas/open-interpreter/pull/793
