### ISSUE TITLE
raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model) litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference e

### ISSUE THREAD

**Issue by NatanAmado** [KillianLucas/open-interpreter#809]
### Describe the bug

When trying to call interpreter I get this:

> raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference e

It worked yesterday for me. Is there a new way of passing the model?

### Reproduce
```

def run_interpreter(userPrompt, api_key=None, interpreter_model='gpt-4-turbo'):
    if api_key:
        Set_API_Key(api_key)
    try:
        messages = load_chat_history()
        interpreter.messages.extend(messages)
        interpreter.system_message = read_prompt()
        interpreter.model = interpreter_model
        interpreter.auto_run = True
        #interpreter.vision = True

        output = interpreter.chat(userPrompt, stream=True, display=False)
        for chunk in output:
            print(chunk, flush=True)

        interpreter.messages.extend(output)
        save_chat_history(interpreter.messages)
        
    except Exception as e:
        log_error(f"Error: {e}\n{traceback.format_exc()}")
```

### Expected behavior

Streamed token response. 

### Open Interpreter version

0.1.16

### Python version

3.10

### Operating System name and version

macOS 14.1.1

**Comment by Notnaton** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/0fb36ecc-a658-4349-bc5e-1660916a6334)
https://platform.openai.com/docs/models/overview
