### ISSUE TITLE
how to install on Windows?

### ISSUE THREAD

**Issue by veonua** [KillianLucas/open-interpreter#81]
python
> import interpreter

works ok, but

python -m interpreter
C:\Users\veon\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe: Error while finding module specification for 'interpreter.__main__' (ModuleNotFoundError: __path__ attribute not found on 'interpreter' while trying to find 'interpreter.__main__'); 'interpreter' is a package and cannot be directly executed

interpreter
'interpreter' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jordanbtucker** [comment]
The package name is `open-interpreter` but the cli command is `interpreter`.

**Comment by veonua** [comment]
as you can see the command line doesn't have
interpreter as a command after pip install

tor. 7. sep. 2023 kl. 02:48 skrev Jordan Tucker ***@***.***>:

**Comment by jordanbtucker** [comment]
Did you run `pip install open-interpreter`?

**Comment by veonua** [comment]
yes I did

tor. 7. sep. 2023 kl. 19:01 skrev Jordan Tucker ***@***.***>:

**Comment by hamoudydev** [comment]
Same issue here. `pip install open-interpreter` then `interpreter` and the error is:

`interpreter : The term 'interpreter' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1`

**Comment by ys112** [comment]
same issue here with "interpreter" not being recognised in window's command prompt, but managed to get it working with conda prompt.

**Comment by scrachatron** [comment]
hey i had the same problem managed to get it running in it's own python enviroment (was combersome though, it gave me these steps to fix it: 

<img width="600" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/10553482/ac80d4fb-c7eb-4db2-bd67-090258e74e60">

And plot twist it fixed it i can now run it directly from terminal rather than via 
> python
> install interpreter
> interpreter.chat()

The issue was tied to my python installation not including the path correctly it seems.

**Comment by jordanbtucker** [comment]
As @scrachatron, this is most likely an issue with your Python/pip `Scripts` directory not being in your `PATH` environment variable.

To find out what that path is, run the following command.

```
python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))'
```

Now [add that directory](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7#file-path-md) to your `PATH` environment variable and restart your terminal.

**Comment by scrachatron** [comment]
sorted with a reinstall was my easiest solution but adding it manually would be the right way to do it.

**Comment by scrachatron** [comment]
@jordanbtucker @KillianLucas 
This issue seems to pop up a lot worth adding to an FAQ, just ensure that path is correctly referenced?

**Comment by jordanbtucker** [comment]
@scrachatron Great idea! I'm going to begin working on organizing these issues, and pinning the common ones. Then work on getting some better docs written.

**Comment by jordanbtucker** [comment]
This is now a duplicate of #169. If you still need help, please leave a comment on that issue.

**Comment by nothingness6** [comment]
I just faced the same issue. No solution yet?
