### ISSUE TITLE
命令interpreter运行GTP4无法运行

### ISSUE THREAD

**Issue by af6464** [KillianLucas/open-interpreter#814]
### Describe the bug

C:\Users\16121\Desktop\open-interpreter-env_vars>interpreter

▌ Model set to gpt-4-1106-preview

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

> interpreter -y

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

  You do not have access to gpt-4-1106-preview. Would you like to try gpt-3.5-turbo instead? (y/n)

### Reproduce

![QQ截图20231204152243](https://github.com/KillianLucas/open-interpreter/assets/151594014/ba3f36f8-c0c8-4cd6-81e9-c26bcef1d24b)

### Expected behavior

![QQ截图20231204152243](https://github.com/KillianLucas/open-interpreter/assets/151594014/765a6e8a-a8d3-4ec1-8447-07d39578b529)

### Screenshots

> 

> 
![QQ截图20231204152243](https://github.com/KillianLucas/open-interpreter/assets/151594014/08f26198-0527-4aa1-96fb-a3f6676380d3)

### Open Interpreter version

0.1.1

### Python version

3.11

### Operating System name and version

win11

### Additional context

![QQ截图20231204152243](https://github.com/KillianLucas/open-interpreter/assets/151594014/49ef1dbd-d4c1-49b4-9ff9-8390c9417534)

**Comment by Notnaton** [comment]
What is the issue? 
You need to type "y" and hit enter to switch to gpt3.5 as you don't have access to gpt-4

**Comment by af6464** [comment]
显示无法访问是为啥

**Comment by Notnaton** [comment]
>"显示无法访问是为啥" translates to "Why does it show unable to access?" 
You need to set a working openai api_key. 
1. Get the key from openaihttps://platform.openai.com/api-keys 
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/4d4c7ad5-0fa3-49d0-8a4a-bfcd57d19731)
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/b1cf8a13-5075-4583-af8a-39792f1b5c08)
Copy the key from here:
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/1221905c-25e5-4ce1-b7d4-bb34ac00fbf0)

Now open CMD:
```
setx OPENAI_API_KEY <insert_key>
```
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/3b862688-c11a-437c-a5b9-dd8882d28bec)

run interpreter:
```
interpreter
```

**Comment by Notnaton** [comment]
Let me know if it is working @af6464

**Comment by af6464** [comment]
![Uploading QQ截图20231205004041.png…]()

**Comment by af6464** [comment]
![QQ截图20231205004041](https://github.com/KillianLucas/open-interpreter/assets/151594014/6af217ee-dccd-4600-8dad-1b850abb7ff5)

**Comment by Notnaton** [comment]
@af6464 Can you show the rest of the error message? This tell me nothing... Type what you want it to do, I'll translate

**Comment by af6464** [comment]
不好意思哈，是因为gtp-4无法访问 访问GTP-4也就会要求我访问GTP-3.5要这是为什么啊

**Comment by XHXiaoHuang** [comment]
> 不好意思哈，是因为gtp-4无法访问 访问GTP-4也就会要求我访问GTP-3.5要这是为什么啊

你没有GPT4权限，肯定只能用GPT3.5不，你说为啥？你这问的~

**Comment by Notnaton** [comment]
> 但是我开了GTP4.0啊

You need to pay $0.5 and after a while it will give you access

**Comment by af6464** [comment]
好的谢谢
