### ISSUE TITLE
 Assistants API connect

### ISSUE THREAD

**Issue by Blqd** [KillianLucas/open-interpreter#815]
### Describe the solution you'd like

Connect to OpenAI Assistants API

**Comment by tegnike** [comment]
I'm also very interested in this project.  

However, I think that the current specifications of the Assistants API are a little unsatisfactory.  
Particularly difficult is the inability to control the addition and subtraction of messages in a thread.  
Is it possible to switch threads for each task...?  

Please tell me what you think.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!

**Comment by tegnike** [comment]
Actually, Assistants API is beta version and it's unstable I think.  
So, it's not time to merge to OI yet.
