### ISSUE TITLE
Lack of proper escaping of ACTIVE_LINE and END_OF_EXECUTION

### ISSUE THREAD

**Issue by jchia** [KillianLucas/open-interpreter#82]
code_interpreter.py prints strings like `ACTIVE_LINE:` & `END_OF_EXECUTION` to inject special signals in the generated program's output.

If the program naturally prints these strings on its own, open-interpreter mistakes them for special signals resulting in all manner of confusion in the output handling and even detection of program termination.

In general, I don't think there is an easy way to escape properly, though.

**Comment by ericrallen** [comment]
Hey there, @jchia!

Can you provide an example use case that makes it easy to reproduce and test this one?
