### ISSUE TITLE
A flag to disable line pointer when running code or automatically stop the animation when the result is already available

### ISSUE THREAD

**Issue by refeed** [KillianLucas/open-interpreter#822]
### Is your feature request related to a problem? Please describe.

When interpreter is running a code that needs a lot of looping interation, it seems to be stuck on doing the animation, I'm pretty sure it already has the result in the background (it has been more than 15 minutes and it's still doing the animation) .

[Screencast from 2023-12-06 22-12-58.webm](https://github.com/KillianLucas/open-interpreter/assets/20320125/d3b965a3-711b-43fb-ae5e-64c1aa12092d)

### Describe the solution you'd like

In my opinion a flag that can disable this kind of animation shown OR automatically just skip the animation when the result is already computed would be nice

**Comment by MikeBirdTech** [comment]
Closing this stale issue. A new terminal interface is being developed that will address issues like these. Thanks!
