### ISSUE TITLE
How to configure the openai  API proxy endpoint? 

### ISSUE THREAD

**Issue by xjspace** [KillianLucas/open-interpreter#823]
### Is your feature request related to a problem? Please describe.

Hi, how to set the api proxy api instead of the official open api address?
could i place it into .env? what's the ENV name? 

### Describe the solution you'd like

How to configure the openai  API proxy endpoint?

**Comment by Notnaton** [comment]
You can use the `--api_base https://host.com/v1`

Or you can edit the config:
`interpreter --config`
Add `api_base: "https://host.com/v1"

**Comment by RisingVoicesBk** [comment]
Notnaton, strangely when I did this Openai still appears in the model name when running code. But I have been trying to run code llama through huggingface: this is the line I'm referring to: Model: openai/huggingface/codellama/CodeLlama-34b-Instruct-hf

# Interpreter Info

        Vision: False
        Model: openai/huggingface/codellama/CodeLlama-34b-Instruct-hf
        Function calling: None
        Context window: 3000
        Max tokens: 400

        Auto run: False
        API base: https://api-inference.huggingface.co/models/codellama/CodeLlama-34b-Instruct-hf
        Offline: False

**Comment by Notnaton** [comment]
This is because we add it, so litellm uses openai format to communicate with the endpoint.
There is a change coming up to not do this anymore, next update?

**Comment by Notnaton** [comment]
https://github.com/KillianLucas/open-interpreter/pull/955
