### ISSUE TITLE
Update broke functionality. 

### ISSUE THREAD

**Issue by TheMavel** [KillianLucas/open-interpreter#832]
### Describe the bug

I honestly don't know what and why. 
But I did 2 days ago pip --upgrade open-interpreter, nothing seems to work anymore. 
API key can't be put in manually since the keyboard won't recognize once the interpreter is initialized. Even if you start with safed api key, the most simple tasks get time-outs, and freeze the console. This wasn't happening the last 2 months and I was super happy hardcore user. How do I fix this, I already uninstalled and reinstalled but it did nothing. My laptop has still an old version and it works flawlessly.

### Reproduce

after the current pip --upgrade open-interpreter to version 0.1.17

### Expected behavior

I expected to use the open-interpreter as intended. 

### Open Interpreter version

0.1.17

### Python version

3.10

### Operating System name and version

Windows 10

**Comment by Notnaton** [comment]
Try `pip install open-interpreter --force-reinstall` and see if that fixes it

**Comment by Notnaton** [comment]
Can you also run `interpreter --version` on the old laptop?

**Comment by TheMavel** [comment]
My Laptop is running version 0.1.11 without any issues.

**Comment by TheMavel** [comment]
> pip install open-interpreter --force-reinstall

fixed it 👍
