### ISSUE TITLE
A flag to disable running code entirely and give replies only

### ISSUE THREAD

**Issue by JohnnyRacer** [KillianLucas/open-interpreter#835]
### Is your feature request related to a problem? Please describe.

Hello, it seems like there is no way to disable the running code by default when returning responses which can cause the response to freeze waiting in a infinite loop for a y/n.  Seems there was an oversight considering there is the option to default to execute code by default with `interpreter -y`.

### Describe the solution you'd like

Have a simple flag that can be toggled in the CLI and API, such as `interpreter -nr` and  `res = interpreter.chat("Explain what is Python?", disable_code_run=True)`.

### Describe alternatives you've considered

Telling the interpreter to not run code doesn't always work and sometimes will get stuck in the prompt.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
