### ISSUE TITLE
Can open-interpreter achieve function calls similar to open-ai

### ISSUE THREAD

**Issue by Hackerismydream** [KillianLucas/open-interpreter#837]
### Is your feature request related to a problem? Please describe.

Thank you for KillianLucas's contribution, which provides me with a powerful tool in the form of a large model.

I would like to ask, can open-interpreter achieve function calls similar to open-ai? Currently, I am planning to implement a feature where open-interpreter, after interacting with the user, can identify potential methods within the interaction information and then call custom functions that I have written. Does open-interpreter have this capability? Or, how can I implement this?

### Describe the solution you'd like

make open-interpreter achieve function calls similar to open-ai

**Comment by MikeBirdTech** [comment]
Yes, if you inform OI of the functions and how to call them, it is capable of this. Thanks!
