### ISSUE TITLE
answering "I'm an AI language model and cannot directly interact with files"

### ISSUE THREAD

**Issue by aziefp** [KillianLucas/open-interpreter#839]
### Describe the bug

Hello, I would like to ask how to make the interpreter work on my computer. Why does it answer "I'm an AI language model and cannot directly interact with files"? Thank you so much! (i used local model Mistral 7B Instruct v0.2)

### Reproduce

ask questions like "can you help me summary this doc"

### Expected behavior

Able to interact with the system

### Open Interpreter version

0.1.17

### Python version

3.11.7

### Operating System name and version

Windows 11

**Comment by Notnaton** [comment]
Modify your prompt:
> use python to read this file and summarize it

**Comment by aziefp** [comment]
> Modify your prompt:
> 
> > use python to read this file and summarize it

Thank you so much!

**Comment by aziefp** [comment]
@Notnaton Thank you so much!
