### ISSUE TITLE
Long code execution due to console updating

### ISSUE THREAD

**Issue by gagebt** [KillianLucas/open-interpreter#841]
### Describe the bug

On Windows and possibly others:
A code with lots of operations executes much slower than in normal Python(/node/...) because the console is updated many times per second to highlight the currently executed code line. Apparently this causes Python to wait until the console finishes updating, so compute-intensive code such as long loops may execute prohibitively slowly.

### Reproduce

"loop 1 milllon times"

### Expected behavior

Without the bug, it should complete in much less than a second.
Instead, it appears frozen with the "pass" line being executed.

### Screenshots

<img width="368" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/132444332/345928aa-f624-481d-b36a-6c37854c79d5">

### Open Interpreter version

0.1.15

### Python version

 3.11.6

### Operating System name and version

windows 11

**Comment by gagebt** [comment]
Possible fix: only update the console each 0.2 sec

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
