### ISSUE TITLE
Python implementation always doubles up

### ISSUE THREAD

**Issue by Maclean-D** [KillianLucas/open-interpreter#844]
### Describe the solution you'd like

Open-Interpreter streams the messages first, and then sends the full thing again after start_of_code which is fine because you can at least filter it out because it doesn't start with {"code": ""}. However, when it starts a message after, it spits out the code again and then the rest of the message. because the messages don't start with {"message": ""} there's no easy way to distinguish/filter out between messages and when it's giving you the code again. I propose we remove sending the code again, or put it in something like {"executed_code": ""}
![CleanShot 2023-12-20 at 12 01 23@2x](https://github.com/KillianLucas/open-interpreter/assets/65423362/b611dcd7-5329-418a-91ef-3d2a1cc89ecf)

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
