### ISSUE TITLE
Cannot stop it from prompting as it goes through a plan

### ISSUE THREAD

**Issue by tolidano-humane** [KillianLucas/open-interpreter#847]
### Describe the bug

At each step in a multi-step process, it wants to execute the code. The only choices are y or n. It would be great to add a (d)efer option so it will just queue up all the code and run it all at once at the end. Or some other way of getting it to stop asking me and just write out all the code first.

### Reproduce

install brew
install python with brew
install pipx with python
install openinterpreter with pipx
run openinterpreter with the ollama/llama2:13b model via Ollama
ask this:
```
> write some pulumi python code to create a resource group in azure with a blob storage container with an expiration policy of 60 days for all objects. prompt me only once run at the very end

  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Welcome, Shawn! I'm here to help you with your task. Based on your request, I understand that you want to create a resource group in Azure with a blob storage container and set an expiration policy of 60 days
  for all objects using Pulumi Python code.

  Here's the complete plan to achieve this goal in one go:

   1 First, we'll create a new resource group in Azure using theazure.resource_groups module. We'll use thecreate method to create a new resource group with a unique name.



  import azure.resource_groups as rg

  # Create a new resource group
  rg.ResourceGroup(name='my-resource-group').create()


  Would you like to run this code? (y/n)
```

### Expected behavior

it should not try to execute the code at each step.

### Open Interpreter version

0.1.17

### Python version

3.11.6

### Operating System name and version

MacOS Sonoma 14.2

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
