### ISSUE TITLE
ValueError: Invalid model: code-llama. Specify max_tokens instead

### ISSUE THREAD

**Issue by ChillarAnand** [KillianLucas/open-interpreter#85]
```
▌ Model set to Code-Llama

> convert txt files to pdf
Traceback (most recent call last):
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 91, in cli
    cli(self)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/cli.py", line 42, in cli
    interpreter.chat()
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 245, in chat
    self.respond()
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 302, in respond
    messages = tt.trim(self.messages, self.model, system_message=system_message)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/tokentrim/tokentrim.py", line 129, in trim
    raise ValueError(f"Invalid model: {model}. Specify max_tokens instead")
ValueError: Invalid model: code-llama. Specify max_tokens instead
```

**Comment by KKD4Soei** [comment]
I meet the same problem

**Comment by KillianLucas** [comment]
This is a known issue with `tokentrim` which has just been resolved! Run the following command to get the fix:

```
pip install --upgrade tokentrim
```

**Comment by KKD4Soei** [comment]
thansk for your advice!
My env:
win11 
after install tokentrim,new warn coming !
![image](https://github.com/KillianLucas/open-interpreter/assets/58964439/5b63b34f-19f6-4357-9778-195945919396)

**Comment by ChillarAnand** [comment]
```
Traceback (most recent call last):
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 91, in cli
    cli(self)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/cli.py", line 42, in cli
    interpreter.chat()
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 245, in chat
    self.respond()
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/interpreter/interpreter.py", line 302, in respond
    messages = tt.trim(self.messages, self.model, system_message=system_message)
  File "/Users/chillaranand/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/tokentrim/tokentrim.py", line 145, in trim
    raise ValueError("System message exceeds token limit")
ValueError: System message exceeds token limit
```

Yes. I am also facing the same error.

**Comment by roshanis** [comment]
same error. 
ValueError: System message exceeds token limit

I am using a Mac with Intel chip.

**Comment by yaoxingwei** [comment]
same error.
ValueError: System message exceeds token limit

In intel + ubuntu20.04 + GTX3090.

**Comment by tangxiangmin** [comment]
same error on mac M2  chip

**Comment by AshwinRamachandran2002** [comment]
The tokentrim repository has this particular code present in tokentrim.py that is raising the error
```
max_tokens -= system_message_tokens

if system_message_tokens > max_tokens:
      raise ValueError("System message exceeds token limit")
```
Might this be an error? Should the check be done before the modification to the max_tokens?

**Comment by KKD4Soei** [comment]
> The tokentrim repository has this particular code present in tokentrim.py that is raising the error
> 
> ```
> max_tokens -= system_message_tokens
> 
> if system_message_tokens > max_tokens:
>       raise ValueError("System message exceeds token limit")
> ```
> 
> Might this be an error? Should the check be done before the modification to the max_tokens?

yeah   Dir to ....lib/python3.10/site-packages/tokentrim/tokentrim.py , edit tokentrim.py,
search "system_message_tokens" ,and comment out the code：
    #if system_message_tokens > max_tokens:
     # raise ValueError("System message exceeds token limit")
     
     
     and It can work right now！！！！！

**Comment by jimjatt1999** [comment]
> > The tokentrim repository has this particular code present in tokentrim.py that is raising the error
> > ```
> > max_tokens -= system_message_tokens
> > 
> > if system_message_tokens > max_tokens:
> >       raise ValueError("System message exceeds token limit")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Might this be an error? Should the check be done before the modification to the max_tokens?
> 
> yeah Dir to ....lib/python3.10/site-packages/tokentrim/tokentrim.py , edit tokentrim.py, search "system_message_tokens" ,and comment out the code： #if system_message_tokens > max_tokens: # raise ValueError("System message exceeds token limit")
> 
> ```
>  and It can work right now！！！！！
> ```

Thanks alot it worked!

**Comment by wch1618** [comment]
> > > The tokentrim repository has this particular code present in tokentrim.py that is raising the error
> > > ```
> > > max_tokens -= system_message_tokens
> > > 
> > > if system_message_tokens > max_tokens:
> > >       raise ValueError("System message exceeds token limit")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Might this be an error? Should the check be done before the modification to the max_tokens?
> > 
> > 
> > yeah Dir to ....lib/python3.10/site-packages/tokentrim/tokentrim.py , edit tokentrim.py, search "system_message_tokens" ,and comment out the code： #if system_message_tokens > max_tokens: # raise ValueError("System message exceeds token limit")
> > ```
> >  and It can work right now！！！！！
> > ```
> 
> Thanks alot it worked!

>This is another way to solve it, change 
'MODEL_MAX_TOKENS ...''code-llama': 1048' , # I'm not sure this is correct' 
to
'MODEL_MAX_TOKENS ...''code-llama': 104800' , # I'm not sure this is correct' 
 in tokentrim.py.

**Comment by KKD4Soei** [comment]
> > > > The tokentrim repository has this particular code present in tokentrim.py that is raising the error
> > > > ```
> > > > max_tokens -= system_message_tokens
> > > > 
> > > > if system_message_tokens > max_tokens:
> > > >       raise ValueError("System message exceeds token limit")
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Might this be an error? Should the check be done before the modification to the max_tokens?
> > > 
> > > 
> > > yeah Dir to ....lib/python3.10/site-packages/tokentrim/tokentrim.py , edit tokentrim.py, search "system_message_tokens" ,and comment out the code： #if system_message_tokens > max_tokens: # raise ValueError("System message exceeds token limit")
> > > ```
> > >  and It can work right now！！！！！
> > > ```
> > 
> > 
> > Thanks alot it worked!
> 
> > This is another way to solve it, change
> > 'MODEL_MAX_TOKENS ...''code-llama': 1048' , # I'm not sure this is correct'
> > to
> > 'MODEL_MAX_TOKENS ...''code-llama': 104800' , # I'm not sure this is correct'
> > in tokentrim.py.

yes  ，Noted！  thanks

**Comment by KillianLucas** [comment]
Hey all, thanks for finding this one @KKD4Soei @ChillarAnand @roshanis @yaoxingwei @tangxiangmin, and thank you so much for finding the fix @AshwinRamachandran2002.
ㅤ
**Update:** The faulty package has now been updated to trim system messages instead of throwing this error. You can upgrade `tokentrim` or simply upgrade Open Interpreter, which now requires the fixed `tokentrim` package:
ㅤ
```
pip install --upgrade open-interpreter
```
ㅤ
Let me know if this works.

**Comment by ChillarAnand** [comment]
It works. Instead of using pip, I installed the latest master and it has been working for a few hours.

Thanks, @KillianLucas for the quick fix.

**Comment by yaoxingwei** [comment]
> Hey all, thanks for finding this one @KKD4Soei @ChillarAnand @roshanis @yaoxingwei @tangxiangmin, and thank you so much for finding the fix @AshwinRamachandran2002. ㅤ **Update:** The faulty package has now been updated to trim system messages instead of throwing this error. You can upgrade `tokentrim` or simply upgrade Open Interpreter, which now requires the fixed `tokentrim` package: ㅤ
> 
> ```
> pip install --upgrade open-interpreter
> ```
> 
> ㅤ Let me know if this works.

It works after updated. Thanks.
