### ISSUE TITLE
cant install it in ubuntu 

### ISSUE THREAD

**Issue by YoucefSennoun** [KillianLucas/open-interpreter#852]
### Describe the bug

when i run code "pip install open-interpreter "
i get this 
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

### Expected behavior

to just install 

### Open Interpreter version

cant install 

### Python version

last update

### Operating System name and version

ubuntu 20.04

**Comment by Notnaton** [comment]
Run ```
python3 --version
pip3 --version
```
If you are using python 3.12 you need to downgrade to 3.11 as one of the dependencies break on 3.12
