### ISSUE TITLE
Open interpreter access LM Studio remotely

### ISSUE THREAD

**Issue by TonyF666** [KillianLucas/open-interpreter#853]
### Is your feature request related to a problem? Please describe.

can I access this LM Studio API remotely over my LAN from my workstation?

### Describe the solution you'd like

I have LM Studio installed and running successfully on a virtual machine. I also installed Open Interpreter on this same VM and it successfully speaks to the currently (locally) running LM studio model.  My question is, can I access this LM Studio API remotely over my LAN from my workstation?
Any insight appreciated!

**Comment by Notnaton** [comment]
You can use api_base:
`interpreter --api_base http://ip_adress:port/v1`

**Comment by ImJohnDoe** [comment]
How do the results compare to gpt-4-v?

**Comment by cestort** [comment]
How you did to install Lm studio on a vmachine? I'm trying It and i'm sufferingna JavaScript error that isbrelated to a avx2 problem.

**Comment by rachosuar** [comment]
@cestort  Where you able to run LM Studio on the VM? Can you tell me more about it?

**Comment by cestort** [comment]
No. the problem is that a virtualizer level 1 is needed, and user virtualizers as vbox or hyperv are level 2. Is compulsory the AVX2 technology and level 2 doesn't add this into the virtualized cpu. Level 1 uses the hardware directly and it should work.
