### ISSUE TITLE
how to change the shell to a remote one?

### ISSUE THREAD

**Issue by Kreijstal** [KillianLucas/open-interpreter#862]
### Is your feature request related to a problem? Please describe.

like I have open-interpreter installed in 1 host but it executes code through ssh remotely without the LLM knowing, it is remote, as if it were home is it possible?

### Describe the solution you'd like

essentially when the llm runs code, first it goes through ssh, remote computer executes and it answers back?

### Describe alternatives you've considered

instead of working text based, the LLM could take any terminal action, think ncurses, but maybe that is way way harder :)

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
