### ISSUE TITLE
Colab does not work

### ISSUE THREAD

**Issue by Kreijstal** [KillianLucas/open-interpreter#865]
### Describe the bug

the example on google colab does not work anymore despite giving it a openai key, it seems it doesnt receive it?

### Reproduce

Go to colab example
give working openai key
it crashes when attempting to chat with it

### Expected behavior

It should not crash, or it should just chat

### Screenshots

![grafik](https://github.com/KillianLucas/open-interpreter/assets/2415206/2a9904cf-4518-4271-a498-8c8e363637fb)

### Open Interpreter version

0.1.18

### Python version

3.10.12

### Operating System name and version

Google Colab

### Additional context

Same exact key does work on terminal I double checked.

**Comment by Notnaton** [comment]
Could you launch interpreter with this flag, on both machines:
```
interpreter --api_key sk-your-key
```

**Comment by Kreijstal** [comment]
In my own machine it works, in  Google colab it doesn't work, also there is no terminal in colab only Python

**Comment by Notnaton** [comment]
> In my own machine it works, in  Google colab it doesn't work, also there is no terminal in colab only Python 

```
interpreter.api_key = sk-your-key

**Comment by Kreijstal** [comment]
> > In my own machine it works, in  Google colab it doesn't work, also there is no terminal in colab only Python
> 
> ```
> interpreter.api_key = sk-your-key
> ```
> 
> I don't really know how colab works, I have just tested it once. Can't you run commands using !command?
> 
> ```
> !export OPENAI_API_KEY sk-your-key 
> ```
no you can't, it is not interactive

**Comment by KillianLucas** [comment]
Oh wow, thank you so much for spotting this @Kreijstal. Just updated the Colab with the [changes](https://github.com/KillianLucas/open-interpreter/blob/main/docs/NCU_MIGRATION_GUIDE.md) from the latest update. Please try it again and let me know if it's working.
