### ISSUE TITLE
Character overlap occurs when streaming out blocks of code

### ISSUE THREAD

**Issue by Moonlight-YS** [KillianLucas/open-interpreter#869]
### Describe the bug

When streaming out a block of code, there is a lot of repetition of characters within the block.
When this rendering problem occurs, the cursor will also shake the window violently.

### Reproduce

During streaming output, use the mouse wheel to view previous information

### Expected behavior

Steady and gentle output of answers

### Screenshots

![屏幕截图 2024-01-04 183233](https://github.com/KillianLucas/open-interpreter/assets/94052635/2e7ac9c6-b600-48a5-9d54-38f557548c5c)
![屏幕截图 2024-01-04 183653](https://github.com/KillianLucas/open-interpreter/assets/94052635/b2e54dcc-1eaf-4df6-80a1-0eec3fd1d1ff)
![屏幕截图 2024-01-04 183704](https://github.com/KillianLucas/open-interpreter/assets/94052635/629f6446-8e20-4eb3-a476-869929fc7aaa)

https://github.com/KillianLucas/open-interpreter/assets/94052635/acf50e33-d23c-4648-8bee-e85210e39a12

### Open Interpreter version

0.1.18

### Python version

3.10.11

### Operating System name and version

Windows 11

**Comment by MikeBirdTech** [comment]
Closing this stale issue. A new terminal interface is being developed that will address issues like these. Thanks!

**Comment by dorianherle** [comment]
Same issue for me. Any update on that?
