### ISSUE TITLE
Empty prompt (Hitting ENTER) results in LLM request

### ISSUE THREAD

**Issue by grabani** [KillianLucas/open-interpreter#871]
### Describe the bug

When I use open-interpreter (OI) with a local LLM `interpreter --local` when I hit `ENTER ` it results in an LLM request.

I see the following instructions in the LM Studio 'Local Inference Server' logs:

```
{
      "role": "user",
      "content": "No entry from user - please suggest something to enter."
}
```

### Reproduce

Start a OI session using a local LLM:

1) 'interpreter --local'
2) Hit `ENTER` at the empty prompt

### Expected behavior

When you hit the enter key at an empty prompt it should just return the prompt (and not initiate an LLM request).

### Open Interpreter version

0.2.0

### Python version

3.11.3

### Operating System name and version

Windows 11

### Additional context

LM Studio = v0.2.10

I am using the `mistral-7b-instruct-v0.1.Q6_K.gguf` LLM model.

**Comment by Notnaton** [comment]
I think this is fine as it is...
Will reopen if there are some sound arguments for it to not prompt a response from the LLM
