### ISSUE TITLE
I can't input my API

### ISSUE THREAD

**Issue by Zkj07892** [KillianLucas/open-interpreter#872]
### Describe the bug

I can't input my API . 
The first issue is that I can't see what I'm typing when I input, but after pressing Enter, there's a display of abbreviations.
The second issue is that even when I input the correct OPENAIAPIKEY, it still shows an error.
like this :  error uploading: HTTPSConnectionPool(host='app.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

### Reproduce

 error uploading: HTTPSConnectionPool(host='app.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

### Expected behavior

I'm not a professional, and my English isn't great. I would like a manual for common installation and usage issues that I can consult to quickly resolve problems.

### Open Interpreter version

0.2.0

### Python version

3.10.6

### Operating System name and version

windows 10

**Comment by Notnaton** [comment]
What command do you use to lauch interpreter? Where do you put in the api url?

**Comment by Zkj07892** [comment]
After downloading the file and extracting it, when I enter "cmd" in the address bar to access the console, then "interpreter," and press Enter, I can't see what I'm typing after "OPENAI KEY:"; it seems like an issue.（Machine translation）

**Comment by Zkj07892** [comment]
i have got a new problem after input :" interpreter "
from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
ImportError: cannot import name 'BaseTransport' from 'httpx' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\__init__.py)
i cant understand this

**Comment by giannons46** [comment]
i have the same problem, i can't see anything when i'm trying to write my api key

**Comment by srv1n** [comment]
It looks like interpreter is now using posthog for analytics/ tracking. If you have a custom DNS or your network is blocking posthog.com network calls(possibly using adguard/ pihole etc),  you'll see this issue.  Whitelisting posthog.com solves the issue. 

Alternatively you can disable this by running `interpreter --disable_telemetry` or `interpreter.anonymized_telemetry = False` or setting the `ANONYMIZED_TELEMETRY` os var to `false`.

@KillianLucas - The posthog calls seems to be blocking. I had the same issue until i whitelisted posthog.com

**Comment by donymorph** [comment]
![image](https://github.com/KillianLucas/open-interpreter/assets/94922760/57d73575-d544-4288-b660-b4fe4b079c95)
this is how I am using with local llm with textgenerationwebui api endpoint

**Comment by dhax** [comment]
only the command line option seems to work though, the config setting and env var is ignored in my case...

**Comment by wee23rer** [comment]
我也无法输入apikey，多次回车后能进入下一步但依然会卡住
![QQ截图20240212195144](https://github.com/KillianLucas/open-interpreter/assets/155554178/af197825-bfd5-4902-9291-6ef8c6cf3bec)

**Comment by wee23rer** [comment]
I also cannot enter the API key, after pressing enter multiple times I can proceed to the next step but it still gets stuck.
![QQ截图20240212195144](https://github.com/KillianLucas/open-interpreter/assets/155554178/96e2d1b4-d63f-437b-bc15-c6a818e1fe66)

**Comment by Notnaton** [comment]
> I also cannot enter the API key, after pressing enter multiple times I can proceed to the next step but it still gets stuck.
> ![QQ截图20240212195144](https://github.com/KillianLucas/open-interpreter/assets/155554178/96e2d1b4-d63f-437b-bc15-c6a818e1fe66)
> 

You should make a new issue

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
