### ISSUE TITLE
Can not run open-interpreter 

### ISSUE THREAD

**Issue by ximalayashanjiao** [KillianLucas/open-interpreter#877]
### Describe the bug

Can not run open-interpreter 

### Reproduce

i don't know where is wrong

### Expected behavior

can't run 

### Screenshots

![111](https://github.com/KillianLucas/open-interpreter/assets/12340211/903c6962-9d27-408e-849e-c853433c9531)
![222](https://github.com/KillianLucas/open-interpreter/assets/12340211/7a9fd7ae-f401-4e28-8501-64df91632ae5)
![333](https://github.com/KillianLucas/open-interpreter/assets/12340211/700c0fa6-b5a8-4d83-9827-1aad7581d89a)

### Open Interpreter version

0.2.0

### Python version

3.11.5

### Operating System name and version

win10

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
