### ISSUE TITLE
0.2.0 Keeps Crashing Python Kernal

### ISSUE THREAD

**Issue by teereximus88** [KillianLucas/open-interpreter#879]
### Describe the bug

Since the upgrade, any request to take control of my computer (outside just chatting) is resulting in Python shutting down.

### Reproduce

1. Run interpreter OS
2. Request to open app

### Expected behavior

Should open app

### Open Interpreter version

0.2.0

### Python version

3.11.5

### Operating System name and version

macOS 14

### Additional context

Here's the error I get:

▌ OS Control enabled

To find items on the screen, Open Interpreter has been instructed to send screenshots to api.openinterpreter.com (we do
not store them). Add --offline to attempt this locally.

Make sure that screen recording permissions are enabled for your Terminal or Python environment.

Warning: In this mode, Open Interpreter will not require approval before performing actions. Be ready to close your
terminal.

> can you help me open a program made for intel chips even with my m1 mac?

  Yes, I can help you with that. Running Intel-based applications on an M1 Mac is typically handled by Rosetta 2, which
  is Apple's software that allows apps built for Intel processors to run on their newer ARM-based chips. First, we need
  to check if Rosetta 2 is installed on your machine.

  Let's follow these steps:

   1 Open Spotlight search usingCommand + Space`.
   2 TypeTerminal to open the Terminal app.
   3 In the Terminal, we'll check if Rosetta is installed by attempting to invoke it.

  Here is how to do step 2 and 3 programmatically:

  # This will open Spotlight and type Terminal to search for it.
  computer.keyboard.hotkey("command", "space")
  computer.keyboard.write("Terminal")

        Python Version: 3.11.5
        Pip Version: 23.3.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.2.0
        OS Version and Architecture: macOS-14.0-arm64-arm-64bit
        CPU Info: arm
        RAM Info: 16.00 GB, used: 6.12, free: 1.76

        # Interpreter Info

        Vision: True
        Model: gpt-4-vision-preview
        Function calling: False
        Context window: 110000
        Max tokens: 4096

        Auto run: True
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.

When you write code, it will be executed **on the user's machine**. The user has given you **full and complete
permission** to execute any code necessary to complete the task.

When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing
code in.

In general, try to make plans with as few steps as possible. As for actually executing code to carry out that plan,
**don't try to do everything in one code block.** You should try something, print information about it, then continue from
there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to
errors you cant see.

Manually summarize text.

Do not try to write code that attempts the entire task at once, and verify at each step whether or not you're on track.

# Computer

You may use the `computer` Python module to complete tasks:

```python
computer.display.view() # Shows you what's on the screen, returns a `pil_image` `in case you need it (rarely). **You
almost always want to do this first!**

computer.keyboard.hotkey(" ", "command") # Opens spotlight (very useful)
computer.keyboard.write("hello")

computer.mouse.click("text onscreen") # This clicks on the UI element with that text. Use this **frequently** and get
creative! To click a video, you could pass the *timestamp* (which is usually written on the thumbnail) into this.
computer.mouse.move("open recent >") # This moves the mouse over the UI element with that text. Many dropdowns will
disappear if you click them. You have to hover over items to reveal more.
computer.mouse.click(x=500, y=500) # Use this very, very rarely. It's highly inaccurate
computer.mouse.click(icon="gear icon") # Moves mouse to the icon with that description. Use this very often

computer.mouse.scroll(-10) # Scrolls down. If you don't find some text on screen that you expected to be there, you
probably want to do this
x, y = computer.display.center() # Get your bearings

computer.clipboard.view() # Returns contents of clipboard
computer.os.get_selected_text() # Use frequently. If editing text, the user often wants this
```

For rare and complex mouse actions, consider using computer vision libraries on the `computer.display.view()` `pil_image`
to produce a list of coordinates for the mouse to move/drag to.

If the user highlighted text in an editor, then asked you to modify it, they probably want you to `keyboard.write` over
their version of the text.

Tasks are 100% computer-based. DO NOT simply write long messages to the user to complete tasks. You MUST put your text
back into the program they're using to deliver your text!

Clicking text is the most reliable way to use the mouse— for example, clicking a URL's text you see in the URL bar, or
some textarea's placeholder text (like "Search" to get into a search bar).

Applescript might be best for some tasks.

If you use `plt.show()`, the resulting image will be sent to you. However, if you use `PIL.Image.show()`, the resulting
image will NOT be sent to you.

It is very important to make sure you are focused on the right application and window. Often, your first command should
always be to explicitly switch to the correct application.

When searching the web, use query parameters. For example, https://www.amazon.com/s?k=monitor

Try multiple methods before saying the task is impossible. **You can do it!**

# Critical Routine Procedure for Multi-Step Tasks

Include `computer.display.view()` after a 2 second delay at the end of _every_ code block to verify your progress, then
answer these questions in extreme detail:

1. Generally, what is happening on-screen?
2. What is the active app?
3. What hotkeys does this app support that might get be closer to my goal?
4. What text areas are active, if any?
5. What text is selected?
6. What options could you take next to get closer to your goal?

        {'role': 'user', 'type': 'message', 'content': 'can you help me open a program made for intel chips even with my
m1 mac?'}

{'role': 'assistant', 'type': 'message', 'content': "Yes, I can help you with that. Running Intel-based applications on an
M1 Mac is typically handled by Rosetta 2, which is Apple's software that allows apps built for Intel processors to run on
their newer ARM-based chips. First, we need to check if Rosetta 2 is installed on your machine. \n\nLet's follow these
steps:\n\n1. Open Spotlight search usingCommand + Space`.\n2. TypeTerminal to open the Terminal app.\n3. In the Terminal,
we'll check if Rosetta is installed by attempting to invoke it.\n\nHere is how to do step 2 and 3 programmatically:\n\n"}

{'role': 'assistant', 'type': 'code', 'format': 'python', 'content': '\n# This will open Spotlight and type Terminal to
search for it.\ncomputer.keyboard.hotkey("command", "space")\ncomputer.keyboard.write("Terminal")\n'}

{'role': 'computer', 'type': 'console', 'format': 'output', 'content': ''}

{'role': 'assistant', 'type': 'message', 'content': "Since there was no text output, we still need to verify what is
currently visible on your screen to ensure that the Terminal app has been opened and is ready for the next step. I'll
execute a command to view the current screen and summarize the situation for you. Let's do that now.\n\n"}

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/main.py", line 748, in
completion
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/main.py", line 723, in
completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 349,
in completion
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 344,
in completion
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 271,
in completion
    return self.streaming(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/llms/openai.py", line 437,
in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line
272, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File
"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/resources/chat/completions.py",
line 645, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_base_client.py", line
1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_base_client.py", line 853,
in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_base_client.py", line 930,
in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API
key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code':
'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line
221, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 2118, in
wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 2025, in
wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/main.py", line 1744, in
completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 6570, in
exception_type
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 5538, in
exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key
provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error',
'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line
25, in start_terminal_interface
    start_terminal_interface(self)
  File
"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/terminal_interface/start_term
inal_interface.py", line 684, in start_terminal_interface
    interpreter.chat()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line
86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line
113, in _streaming_chat
    yield from terminal_interface(self, message)
  File
"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_i
nterface.py", line 135, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line
148, in _streaming_chat
    yield from self._respond_and_store()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/core.py", line
194, in _respond_and_store
    for chunk in respond(self):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/respond.py", line
49, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line
193, in run
    yield from run_text_llm(self, params)
  File
"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/llm/run_text_llm.py",
line 19, in run_text_llm
    for chunk in llm.completions(**params):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line
224, in fixed_litellm_completions
    raise first_error
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter/core/llm/llm.py", line
205, in fixed_litellm_completions
    yield from litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 2118, in
wrapper
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 2025, in
wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/main.py", line 1744, in
completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 6570, in
exception_type
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/litellm/utils.py", line 5569, in
exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'Rate limit reached for
gpt-4-vision-preview in organization org-UClX0RiVUM6fvXJ4QkZtc9tj on tokens per min (TPM): Limit 10000, Used 6200,
Requested 5651. Please try again in 11.106s. Visit https://platform.openai.com/account/rate-limits to learn more.',
'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

  Since there was no text output, we still need to verify what is currently visible on your screen to ensure that the
  Terminal app has been opened and is ready for the next step. I'll execute a command to view the current screen and
  summarize the situation for you. Let's do that now.

  ●
                                                                                                                          
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

**Comment by slavakurilyak** [comment]
Looks like `RateLimitError` /w rate limit reached for `gpt-4-vision-preview`

**Comment by teereximus88** [comment]
Interesting. Only asked for a few small tasks. Thanks for the troubleshoot.
I’m not very technical so couldn’t parse that in my end. If you don’t mind
me asking, what’s the fix?

**Comment by slavakurilyak** [comment]
Check out the [rate limits](https://platform.openai.com/docs/guides/rate-limits) guide by @openai

**Comment by teereximus88** [comment]
Thank you! I guess my outstanding question is does this seem right? Could OI be running up rate limits in a way that's not intended? Or are most other folks just on higher rate limits due to their higher usage which puts them into the upper tiers with OAI? I only ran a few small tasks before hitting these limits, so it was surprising to me, but maybe that's expected.
