### ISSUE TITLE
Issue in Python Installation

### ISSUE THREAD

**Issue by shubhexists** [KillianLucas/open-interpreter#88]
OS - Ubuntu 20.04
`jerry@jerry:~$ pip install open-interpreter
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
`

**Comment by fatelei** [comment]
python should be >= 3.10

**Comment by shubhexists** [comment]
Got It Thanks for the help
