### ISSUE TITLE
Interperter close when reached limit

### ISSUE THREAD

**Issue by vost-armtek** [KillianLucas/open-interpreter#881]
### Describe the bug

When I'm using the interpreter, I started by giving some big contexte before start to work

Before been abble to start to work : I got this issue : 

    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4 in organization org-Lq0Qn7hM3JWbjcfdmgUBymkm on tokens_usage_based per min: Limit 10000, Used
7270, Requested 4854. Please try again in 12.744s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens_usage_based', 'param': None, 'code': 'rate_limit_exceeded'}}

The problem is that the interperter close when we reach the limit. 

I would like to wait otherwise I loose again the contexte since there is no way to reuse an existing conversation?
Can we export a conversation ID or something to restart it?
A way of using MyGPT?

### Reproduce

Open the interpretor, 

Load multiple files in memory of GPT

### Expected behavior

Catch the limit error, and ask the user if he want to wait

### Open Interpreter version

0.2.0

### Python version

3.11.6

### Operating System name and version

MacOs

**Comment by MikeBirdTech** [comment]
You can use `interpreter --conversations` to resume previous conversations
