### ISSUE TITLE
Can't sign up for access to the desktop app on your web site

### ISSUE THREAD

**Issue by tv21** [KillianLucas/open-interpreter#883]
### Describe the bug

At https://openinterpreter.com/ the is a button labelled "Get early access to the desktop app" but when I click it I either get just a blank white page, a "Sorry that didn't work" page, or a kind of progress bar icon that never goes anywhere.  This happens in both Firefox and Chrome.  If you want people to be able to sign up for this you may need to try a more accessible method.

### Reproduce

1.  Use a computer running MacOS
2.  In Firefox or Chrome go to https://openinterpreter.com/
3. Click on the button labelled "Get early access to the desktop app"

### Expected behavior

Something other than a blank white page, a "Sorry that didn't work" page, or a never ending progress bar

### Screenshots

![Sorry](https://github.com/KillianLucas/open-interpreter/assets/5983788/f11b3ab1-1d87-49f2-ba13-4f59a02487a6)

### Open Interpreter version

n/a

### Python version

n/a

### Operating System name and version

MacOS 12.7.2

**Comment by Arrendy** [comment]
It should open up a typeform. Trying going directly to it here: https://0ggfznkwh4j.typeform.com/to/G21i9lJ2?typeform-source=openinterpreter.com

**Comment by Notnaton** [comment]
Works for me...

**Comment by tv21** [comment]
> It should open up a typeform. Trying going directly to it here: https://0ggfznkwh4j.typeform.com/to/G21i9lJ2?typeform-source=openinterpreter.com

That flashes a progress bar and goes to a blank white page in Firefox, and to the same image I posted above in Chrome.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem, please alert me to re-open the issue. Thanks!
