### ISSUE TITLE
Does this program need to configure own key?

### ISSUE THREAD

**Issue by fzfz666** [KillianLucas/open-interpreter#89]
Does this program need to configure own key?

**Comment by Frank40790** [comment]
You will need an api key if you want to use OpenAI's models like GPT-4 or get-3.5-turbo. But you can also use codellama locally without an api key 
```bash
interpreter --local
```
Hope this helps 👍

**Comment by jordanbtucker** [comment]
Thanks for your interest. Can you please provide more information about what you're asking.

**Comment by fzfz666** [comment]
Thanks, I've solved the problem.
"You will need an api key if you want to use OpenAI's models like GPT-4 or get-3.5-turbo. But you can also use codellama locally without an api key"
