### ISSUE TITLE
Set-of-Mark Prompting

### ISSUE THREAD

**Issue by slavakurilyak** [KillianLucas/open-interpreter#898]
### Is your feature request related to a problem? Please describe.

Set-of-Mark Prompting unlocks better control of multi-modal models like GPT-4V. The authors present Set-of-Mark (SoM), a new visual prompting method, to enhance the visual grounding abilities of large multimodal models (LMMs), such as GPT-4V. This method involves partitioning an image into regions at different levels of granularity and overlaying these regions with marks like alphanumerics, masks, and boxes. This enables GPT-4V to answer questions requiring visual grounding more effectively. The authors' experiments show significant improvements in tasks like referring expression comprehension and segmentation.

### Describe the solution you'd like

I propose the integration of Set-of-Mark Prompting with the `OS` mode in Open Interpreter. This enhancement would enable more effective handling of multi-modal tasks and leverage the existing capabilities of Open Interpreter in a more versatile and powerful way.

### Additional context

- Research paper: [SoM Method](https://arxiv.org/abs/2310.11441)
- Source code by @microsoft: [SoM Repo](https://github.com/microsoft/SoM)
- Implementation example by @joshbickett: [GitHub PR](https://github.com/OthersideAI/self-operating-computer/pull/125)

**Comment by MikeBirdTech** [comment]
Hi @slavakurilyak 
Thanks for your suggestion. I think Set of Mark prompting is really cool! 

We are taking a different approach to improving the vision aspect of OI but we will keep SoM in mind for any future iterations. Thanks!
