### ISSUE TITLE
Copy/Paste not working within terminal since 0.2.0 NCU 

### ISSUE THREAD

**Issue by mychaylo** [KillianLucas/open-interpreter#900]
### Describe the bug

Copy/Paste (ctrl+c/ctrl+v) no longer working on Open Interpreter since clean installation. Couldn't paste in an API key, as an example had to add the system variable. It's most troublesome for copying file paths in. Drag & drop still works. Copy + paste does work in the terminal generally, just not once open-interpreter has started. 

### Reproduce

Clean install open-interpreter
try to copy and paste

### Expected behavior

I expect it to copy + paste, like in prior versions and experience w. OI

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows 11

**Comment by Notnaton** [comment]
I can't replicate this... 
Can you try: ctrl shift v

**Comment by MikeBirdTech** [comment]
Closing this stale issue. If this is still a problem with the latest version of Open Interpreter, please alert me to re-open the issue. Thanks!
