### ISSUE TITLE
Copyrighted Music Violation?

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#901]
### Describe the bug

The demo video includes this song: https://www.youtube.com/watch?v=LeIZ0J-QL4w.
Is this a violation of copyright?

### Reproduce

Just watch the video

### Expected behavior

n/a

### Open Interpreter version

n/a

### Python version

n/a

### Operating System name and version

n/a

**Comment by Notnaton** [comment]
@KillianLucas

**Comment by Siddharth1605** [comment]
Yes @mak448a, this demo video uses the song from that youtube video. It will be a copyright violation, if the maintainers uses this song without the permission of the owner.

**Comment by mak448a** [comment]
@MikeBirdTech Is this issue actually resolved, or are you just closing it? The music is still on the video. Thanks!

**Comment by MikeBirdTech** [comment]
@mak448a 
This issue isn't related to the code base, so I'm not sure why a GitHub issue was opened, rather than contacting Open Interpreter with any concerns. Thanks

**Comment by mak448a** [comment]
Is there an email address that I can send it to?

**Comment by MikeBirdTech** [comment]
help@openinterpreter.com
