### ISSUE TITLE
Could not build wheels for tiktoken

### ISSUE THREAD

**Issue by dandanbang** [KillianLucas/open-interpreter#903]
### Describe the bug

pip install open-interpreter, then ran into the error Could not build wheels for tiktoken

### Reproduce

1. In terminal (running macOS Python 3.12.1)
2. run pip install open-interpreter

### Expected behavior

Finish installing

### Screenshots

<img width="1499" alt="Screenshot 2024-01-11 at 9 15 14 PM" src="https://github.com/KillianLucas/open-interpreter/assets/6740544/a96d96fc-757c-4c59-8f91-61eeb7238a36">

### Open Interpreter version

latest (hasn't been installed)

### Python version

3.12.1

### Operating System name and version

macOS 14.1

**Comment by Notnaton** [comment]
Python version 3.12 is not supported, please downgrade to 3.11
https://docs.openinterpreter.com/getting-started/setup
