### ISSUE TITLE
use interpreter os in an application

### ISSUE THREAD

**Issue by bachittle** [KillianLucas/open-interpreter#911]
rather than using `interpreter --os` to run the new os mode, is it possible to use it in a python app? I tried setting `interpreter.os = True` but it is still claiming that I am unable to view what is on my screen.

**Comment by MikeBirdTech** [comment]
OS mode is only available through the terminal at this time

**Comment by bachittle** [comment]
if that is the case, why did you close this issue as completed? or is it just not planned? I think it would be useful for scripting and using open interpreter as a library, which is my use case.

**Comment by MikeBirdTech** [comment]
Hi @bachittle 

It's not planned. What is the use case you're thinking of?
