### ISSUE TITLE
--local on windows lmstudio via interpreter ran via wsl

### ISSUE THREAD

**Issue by fxmbsw7** [KillianLucas/open-interpreter#914]
### Is your feature request related to a problem? Please describe.

i tried to run ur interpreter with --local via wsl windows linux ( debian python 3.12 venv pip )
before , run lmstudio windows version , and start there <->
but the linux part didnt make it to the windows one
so it aborted

### Describe the solution you'd like

i suppose some general windows style forward firewalling rule anywhere .. or use some special localhost notation that actually makes a connection ..
in both the the windows parts i dunno much of , as i dunno many windows cmds

### Additional context

thers simply windows localhost not accessable ( or the like ) via wsl .. so finding out and making such a rule seems my solution

**Comment by fxmbsw7** [comment]
i mean it can be in form of a brief information , like the windows cmd to run , on ur page , or anywhere , not included in binary ..

**Comment by ppamment** [comment]
You can use 
```
interpreter --local --api_base http://{windows_lan_ip}/v1
```

**Comment by fxmbsw7** [comment]
On Sun, Jan 14, 2024, 11:44 Paul Pamment ***@***.***> wrote:

> You can use
>
> interpreter --local --api_base http://{windows_lan_ip}/v1
>
>
ah cool .. i used the wsl lan ip via ipconfig ..
the {win..} part i need to sub with an ip / host right ? or is it ur apps
keyword .. ?

thanks for great ware ..

**Comment by fxmbsw7** [comment]
i got it on win pip compiled , closing herewith , thanks ..
