### ISSUE TITLE
--context_window & --max_tokens issue

### ISSUE THREAD

**Issue by chuangzhidan** [KillianLucas/open-interpreter#915]
### Describe the bug

**run into this problem after "interpreter --model openai/gpt-4-1106-preview --api_key sk-j5axpBIXNNHI3WTSXXXXXXXXXXX016B046"**
▌ Model set to openai/gpt-4-1106-preview
Open Interpreter will require approval before running code.
Use interpreter -y to bypass this.
Press CTRL-C to exit.
**> hi**
We were unable to determine the context window of this model. Defaulting to 3000.
If your model can handle more, run interpreter --context_window {token limit} --max_tokens {max tokens per response}.
Continuing...
·····

**so i set the value as suggested ,and i got this .do not know the right format and value ,if you know  what i mean**

usage: interpreter [-h] [-ci CUSTOM_INSTRUCTIONS] [-s SYSTEM_MESSAGE] [-y] [-v] [-m MODEL] [-t TEMPERATURE] [-lsv] [-lsf] [-c CONTEXT_WINDOW] [-x MAX_TOKENS] [-b MAX_BUDGET] [-ab API_BASE] [-ak API_KEY] [-av API_VERSION]
                   [-xo MAX_OUTPUT] [-fc] [-dt] [-o] [-sm] [-safe {off,ask,auto}] [-cf CONFIG_FILE] [-f] [-l] [-vi] [-os] [--config] [--reset_config] [--conversations] [--version]
interpreter: error: argument -c/--context_window: invalid int value: '{10000}'

**by the way  , i do not need to input api-key every time i open up a terminal ,yes? tried the stex too ,did not do do the trick ,still have to set api-key every time**

much appreciated if you can help me with this!

### Reproduce

interpreter --model openai/gpt-4-1106-preview --api_key sk-j5axpBIXNNHI3WTSXXXXXXXXXXX016B046
interpreter --model openai/gpt-4-1106-preview --context_window {10000} --max_tokens {5000} --api_key   sk-j5axpBIXNNHI3WTSXXXXXXXXXXX016B046
interpreter --m/gpt-4-1106-preview --c {10000} --x {5000} --ak sk-j5axpBIXNNHI3WTSXXXXXXXXXXX016B046

### Expected behavior

expect no reporting error  like max token and context widow issue

### Screenshots

![Uploading $2SJXQJZ9MDVVD6MI$CF{(K.png…]()

### Open Interpreter version

0.2.0

### Python version

3.9

### Operating System name and version

windows11

**Comment by chuangzhidan** [comment]
![$2SJXQJZ9MDVVD6MI$CF{(K](https://github.com/KillianLucas/open-interpreter/assets/62476420/01260b06-453c-4213-aaed-40f4b03fba45)

screenshot

**Comment by Arrendy** [comment]
Do not put the curly brackets around the value - [docs](https://docs.openinterpreter.com/usage/terminal/arguments#context-window-or-c)

**Comment by chuangzhidan** [comment]
thank you

**Comment by chuangzhidan** [comment]
thank you

**Comment by chuangzhidan** [comment]
> Do not put the curly brackets around the value - [docs](https://docs.openinterpreter.com/usage/terminal/arguments#context-window-or-c)

**thank u ,and it works ,so excited! your team is awesome!

its just  I noticed that after the 'hello word'(a typo) output, there's a significant amount of whitespace before the program continues. is this mormal?**
![$2SJXQJZ9MDVVD6MI$CF{(K](https://github.com/KillianLucas/open-interpreter/assets/62476420/0467b561-fe5e-4818-a888-7fe128d636bf)
![7(OQAY9XSUL~{I 5BGXB0YF](https://github.com/KillianLucas/open-interpreter/assets/62476420/76945518-b0a9-40ca-a6b7-c863afd5e180)

Could you help me understand why this is happening and how to remove these extra blank lines?" ,

**Comment by chuangzhidan** [comment]
![Uploading E9%2O~4W~HRZJKTPZH$UM(K.png…]()

**Comment by chuangzhidan** [comment]
![E9%2O~4W~HRZJKTPZH$UM(K](https://github.com/KillianLucas/open-interpreter/assets/62476420/05cb021b-8d1d-438e-8c17-e4618cf7b769)

**Comment by Arrendy** [comment]
I recommend you explore the documentation, Github issues, and other online resources first. Sharing the steps you've done to try to fix the issue yourself helps expedite a resolution.

**Comment by Notnaton** [comment]
@chuangzhidan Can you run interpreter with
```
interpreter -v 
```
This will output a lot, but it will let us see the raw output
