### ISSUE TITLE
AttributeError: module 'interpreter' has no attribute 'chat'

### ISSUE THREAD

**Issue by NatanAmado** [KillianLucas/open-interpreter#916]
### Describe the bug

When trying to run `interpreter.chat()` I get:

> AttributeError: module 'interpreter' has no attribute 'chat'

This same function worked just a few weeks ago, so I thought something in the definitions had changed, so I checked the library, but there was still a definition for chat in the OpenInterpreter class.

I also tried it on another computer with Python 3.10.9, but I got the same results.

### Reproduce

```
import interpreter

def run (prompt, key):
    interpreter.api_key = key
    output = interpreter.chat(prompt, stream=True)
    for chunk in output:
    print(chunk)

run("hello", "sk-3j9...")
```

### Expected behavior

Output being returned in chunks.

### Open Interpreter version

0.2.0

### Python version

Python 3.11.4

### Operating System name and version

MacOS 14.1.2 (23B92)

**Comment by Arrendy** [comment]
Your import statement should be 

`from interpreter import interpreter`

[docs](https://docs.openinterpreter.com/getting-started/setup#python-usage)

**Comment by Charlz91108112** [comment]
> Your import statement should be
> 
> `from interpreter import interpreter` - [docs](https://docs.openinterpreter.com/getting-started/setup#python-usage)
> 
> You will also need to update to `interpreter.llm.api_key` [docs](https://docs.openinterpreter.com/usage/python/arguments#api-key)

It worked for me
