### ISSUE TITLE
Inquiry about Your Project's Promotional Video Creation

### ISSUE THREAD

**Issue by xhacker5000** [KillianLucas/open-interpreter#920]
### Describe the solution you'd like

I'm really impressed with your project and the promotional video - it's both informative and cool ! Could you share some insights on how you made it? Any tips on how to make effect like yours such a video would be greatly appreciated.

**Comment by MikeBirdTech** [comment]
Please join our Discord to discuss topics like this

https://discord.gg/Hvz9Axh84z
