### ISSUE TITLE
Please add how to properly delete Open-interpreter. Previous Request Closed with no solution 

### ISSUE THREAD

**Issue by block178** [KillianLucas/open-interpreter#938]
### Describe the bug

Tried removing pyenv, Rust, Python, open-interpreter with no result. Using mac and brew. Need to free up space it took. 

### Reproduce

No way to uninstall properly 

### Expected behavior

"Error: No available formula"

No uninstallation script 

### Open Interpreter version

"zzh: command not found: pip"

### Python version

latest python 

### Operating System name and version

macOS 13

### Additional context

Previously request but closed as stale

**Comment by deeplook** [comment]
It would be helpful to say how you've installed it in the first place? If you used `pip install open-interpreter` then `pip uninstall open-interpreter` would be your friend. You might also want to remove local models downloaded by LM Studio, which should be saved to `~/.cache/lm-studio/models` which take much more space, if not used otherwise.

**Comment by Notnaton** [comment]
Go to
`~/Library/Application Support/open-interpreter`
Delete it

**Comment by gokulcoder7** [comment]
> ```
> # Install pip-autoremove package
> pip install pip-autoremove
> 
> # Uninstall open-interpreter
> pip-autoremove open-interpreter -y
> ```





(myenv) F:\for open interpreter>pip install pip-autoremove
Collecting pip-autoremove
  Downloading pip_autoremove-0.10.0-py2.py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pip in f:\for open interpreter\myenv\lib\site-packages (from pip-autoremove) (24.3.1)
Collecting setuptools (from pip-autoremove)
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Downloading pip_autoremove-0.10.0-py2.py3-none-any.whl (5.0 kB)
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, pip-autoremove
Successfully installed pip-autoremove-0.10.0 setuptools-75.6.0

(myenv) F:\for open interpreter>pip-autoremove open-interpreter -y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\for open interpreter\myenv\Scripts\pip-autoremove.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip_autoremove'
