### ISSUE TITLE
Perplexity API - Looking for Open AI API Key?

### ISSUE THREAD

**Issue by DaithiW** [KillianLucas/open-interpreter#939]
### Describe the bug

Open Interpreter 0.2.0
Python 3.11.7

Set PERPLEXITY_API_KEY as environmental variable.
RUN OI AND Set Model to "▌ Model set to perplexity/pplx-70b-chat" (have also tried 70b-online).
Enter Prompt
Returns exception, ending with "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"

### Reproduce

conda create -n oi python=3.11
pip install open-interpreter
set PERPLEXITY_API_KEY=pplx-xxxxxx
interpreter --model perplexity/pplx-70b-chat
enter prompt

### Expected behavior

Given that the model is set and the PPLX API key is set.
I would have thought it should not hang on a missing OPEN AI API KEY.

### Screenshots

![Snag_22e581a9](https://github.com/KillianLucas/open-interpreter/assets/151879348/23577622-a6b8-4ccc-9979-de355fba67c6)

### Open Interpreter version

0.2.0

### Python version

3.11.7

### Operating System name and version

Windows 11

**Comment by Arrendy** [comment]
Hi @DaithiW 

Can you please try `interpreter --model perplexity/pplx-70b-chat --api_key .`

**Comment by DaithiW** [comment]
> Hi @DaithiW
> 
> Can you please try `interpreter --model perplexity/pplx-70b-chat --api_key .`

Working nicely.

Thanks.
