### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by BluesKidd87** [KillianLucas/open-interpreter#944]
### Describe the bug

Every time i try to install, this is all i get..

### Reproduce

1. Open CMD (admin)
2. pip install open-interpreter 

### Expected behavior

install open-interpreter with all dependencies and offer to run open-interpreter.

### Screenshots

![Untitled](https://github.com/KillianLucas/open-interpreter/assets/143832790/cffbade4-946c-4bf0-b24f-bab7903826a6)

### Open Interpreter version

your newest version on GitHub

### Python version

3.12

### Operating System name and version

windows 10

**Comment by Notnaton** [comment]
Use python version 3.11
3.12 doesn't work yet

**Comment by BluesKidd87** [comment]
Cheers my dude!!
