### ISSUE TITLE
Continuous Chat

### ISSUE THREAD

**Issue by JamesClarke7283** [KillianLucas/open-interpreter#951]
### Is your feature request related to a problem? Please describe.

When i hit the context window limit, i get an error, saying ive gone over the token limit.

### Describe the solution you'd like

I would like to see different modes for continuing the chat, without having to restart, one could be, summarizing the chat into 4096 (or whatever the input max is(or user configurable)) tokens, so that the AI still has some idea about what the conversation is about.

### Describe alternatives you've considered

You could have it remember in its knowledge base, the files you have uploaded so far for this session. this will help it understand what the chat was about better, but i think combining it with chat summerization or at least getting the first 1-3 prompts and feeding it back into it, would be nice.

### Additional context

[ChatGPT Web](https://github.com/Niek/chatgpt-web) does something similar where it summarizes the prompts into one prompt. you might want to take inspiration from that/

**Comment by MikeBirdTech** [comment]
Hi @JamesClarke7283 

Are you hitting the maximum tokens of the model? Have you tried setting the `max_token` setting to align with the model? OI should handle trimming the messages so you can continue you conversations. Please try again on the latest model. Feel free to let me know if that doesn't work and I should re-open this issue. Thanks!
