### ISSUE TITLE
Cannot run OpenInterpreter using the command line

### ISSUE THREAD

**Issue by vidalnuneza** [KillianLucas/open-interpreter#966]
### Describe the bug

I cannot run OpenInterpreter using the command line. When I try to run the command `interpreter` in PowerShell or CMD, I get an error that says:
```
interpreter : El término 'interpreter' no se reconoce como nombre de un cmdlet, función, archivo de script o programa
ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta
es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ interpreter
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (interpreter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Then I try to run it through `python -m interpreter` and still, I can't manage to run it now, it says that it cannot be executed:
`C:\Users\####\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe: No module named interpreter.__main__; 'interpreter' is a package and cannot be directly executed`

But, it still runs when using python code.

### Reproduce

1.Open CMD or PowerShell
2.Type `interpreter` or `python -m interpreter`
3.Get the error

### Expected behavior

For what I understand by the documentation, it should run the open interpreter.

### Screenshots

![imatge](https://github.com/KillianLucas/open-interpreter/assets/80704162/ca65aac4-4616-47b7-903c-b0d5eb0a87c0)
![imatge](https://github.com/KillianLucas/open-interpreter/assets/80704162/1aae22e2-265a-4e5b-83a7-864333b4c5cd)

### Open Interpreter version

0.2.0

### Python version

Python 3.11.7

### Operating System name and version

Windows 11

**Comment by Notnaton** [comment]
Make sure Python and python/Scripts is in PATH

**Comment by AFng** [comment]
俺也一样。。
