### ISSUE TITLE
Need an instruction

### ISSUE THREAD

**Issue by Masterlovsky** [KillianLucas/open-interpreter#97]
What can I do with open-interpreter?
I'm not sure if the project works for me. I just set the env and  use GPT to ask questions, everything seems going well.
But when I try to create somthing, nothing happened... 
I'm useing windows11 with python 3.10

**Comment by alfredo-f** [comment]
Have you tried reading the README in the homepage?

**Comment by jordanbtucker** [comment]
Thanks for reporting. Please provide more information about what you are trying to accomplish, what prompt you are giving interpreter, and what output you are receiving. Running interpreter with the `--debug` flag will also provide useful information for us.
