### ISSUE TITLE
[Feature Request] OPENAI_API_BASE support on interpreter

### ISSUE THREAD

**Issue by skspark** [KillianLucas/open-interpreter#98]
Thank you for making this tool, it is really useful and elegant.
Currently I am using my own endpoint on openai call, 
and I thought it would be good to support OPENAI_API_BASE setup in interpreter.py, [in here](https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/interpreter.py#L314-L317).
Please take into consideration, or I can make a pr for this as well :)

**Comment by jordanbtucker** [comment]
Fixed by #62
