### ISSUE TITLE
Show The Code Before Run it.

### ISSUE THREAD

**Issue by pydaxing** [KillianLucas/open-interpreter#983]
### Is your feature request related to a problem? Please describe.

I want to show the code that generated by LLMs before run it. In OpenAI's Code Interpreter, the function show_code() is provided. Does Open Interpreter provides?

### Describe the solution you'd like

I want to show the code that generated by LLMs before run it. In OpenAI's Code Interpreter, the function show_code() is provided. Does Open Interpreter provides?

### Describe alternatives you've considered

I want to show the code that generated by LLMs before run it. In OpenAI's Code Interpreter, the function show_code() is provided. Does Open Interpreter provides?

### Additional context

I want to show the code that generated by LLMs before run it. In OpenAI's Code Interpreter, the function show_code() is provided. Does Open Interpreter provides?

**Comment by MikeBirdTech** [comment]
Yes, this is default behaviour for Open Interpreter. If you run `interpreter -y` it will automatically run code, but the default is to always wait until the user prompts OI to run the code. Thanks!
