### ISSUE TITLE
pip Installation failed

### ISSUE THREAD

**Issue by DawnMelody** [KillianLucas/open-interpreter#99]
Python 3.11.4
MAC OS
Failed to install using PIP, reason for failure：
ERROR: Cannot install open-interpreter==0.0.1, open-interpreter==0.0.2, open-interpreter==0.0.21, open-interpreter==0.0.22, open-interpreter==0.0.221, open-interpreter==0.0.222....
because these package versions have conflicting dependencies.

**Comment by clashai** [comment]
> Python 3.11.4 MAC OS Failed to install using PIP, reason for failure： ERROR: Cannot install open-interpreter==0.0.1, open-interpreter==0.0.2, open-interpreter==0.0.21, open-interpreter==0.0.22, open-interpreter==0.0.221, open-interpreter==0.0.222.... because these package versions have conflicting dependencies.

use python version 3.10.6

**Comment by OneHoopyFrood** [comment]
Succeeded with 3.11.4 here, for what it's worth.

**Comment by nishantkumar1292** [comment]
I was able to install it with Python 3.11.3 on Mac.

**Comment by syed-sz1708606** [comment]
@DawnMelody 
Had the same issue. 
I checked which pip was being used using in the terminal.
It was using the python3.9 which was causing the error.
You could update the path to prioritise the directory containing the desired Python interpreter or use the explicit Python version with pip

**Comment by jordanbtucker** [comment]
@DawnMelody Are you still having this issue? If so, can you please post the entire error message?

**Comment by ivanberry** [comment]
after create a new venv, which python version is 3.11.4. ERROR happens like below:

<img width="725" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/13112910/091bce6c-0e9b-404c-9a28-8b0b1d144e7f">

OS: MacOS
Python Version: 3.11.4
