### ISSUE TITLE
Control with alexa

### ISSUE THREAD

**Issue by vital121** [KillianLucas/open-interpreter#992]
### Is your feature request related to a problem? Please describe.

Control open interpreter with alexa

### Describe the solution you'd like

control open interpreter controlled with Alexa skill ll https://github.com/alexa-samples/skill-sample-nodejs-fact

**Comment by MikeBirdTech** [comment]
Hi @vital121 
Thanks for the enhancement idea.

A python script can be written to accomplish this. This will not be a part of the codebase.
